### ISSUE TITLE
Loading track files failed

### ISSUE THREAD

**Issue by ralphdt** [lidarr/Lidarr#1000]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15196927/65635851-0964a980-dfd9-11e9-842f-1970f13e873d.png)

**To Reproduce**
1. Go to Artist
2. See error

**Expected behavior**
To see the list of albums

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Synology 6.1.7
 - mono (macOS/Linux) Version: 5.18.0.240

**Additional context**
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/3654565/Lidarr.txt)

**Comment by Qstick** [comment]
The paths for your trackfiles don't give with the artist root folder path, in other words the tracks are not children of the artist folder. This is causing the API to bomb out when loading tracks

**Comment by ralphdt** [comment]
Thanks

**Comment by jdratcliffe** [comment]
hey I'm still getting this issue in the latest version

I have a drive fail ( my music one) i moved the Root folder to a new drive and hoping Lidarr would redownload my collection.

but I'm getting this issue of missing files/location

**Comment by bakerboy448** [comment]
@jdratcliffe there was no issue here and this was closed 1.5 years ago

Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.
