### ISSUE TITLE
Delay profiles insist on a tag

### ISSUE THREAD

**Issue by apcrcom** [lidarr/Lidarr#1001]
Hey, thanks for all your work on Lidarr. 

I encountered something that I cant make sense of. dont know if its a 'bug' so much as a quirk. 

Settings -> Quality Profiles -> Enter Delay Profile

I want to prefer usenet in delay profiles for all music. 

When I try to enter the delay profile, it insists I have to enter a tag: "tags should not be empty"

By contrast, same page, 'release profiles' has the option 'leave blank for all'. 

It seems like delay profile should also have the option 'leave blank for all'. 

I guess Im just a bit butt-sore about having to tag all my music just to enter a delay profile. Is this really necessary? 

Sorry if I am being that annoying user who doesnt understand the logic of the interface. 

Thanks

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by Qstick** [comment]
This is what the default profile is for, if you want it to apply to all music, use the default delay profile (which does not need a tag), adding additional delay profiles means there must be someway to identify which artists they should be used on, thus the tag requirement.
