### ISSUE TITLE
Can't get Lidarr to recognize Album + Compilation + DJ-Mix

### ISSUE THREAD

**Issue by ProjectMoon** [lidarr/Lidarr#1004]
**Describe the bug**
I cannot get Lidarr to recognize a an album that is filed as Album + Compilation + DJ Mix on Musicbrainz (Specifically: https://musicbrainz.org/release-group/089ab823-4aa8-311f-a7d7-ff048f4daf8c). I have a metadata profile set up as detailed in the image below, and assigned to DJ Ham. The album is also by a bunch of other artists. I don't really see anything relevant in the debug or info logs, except that it cannot find any albums for DJ Ham. Not sure if I have some config option wrong?

**To Reproduce**
1. Create a metadata profile as shown in the image.
2. Have the album spread across multiple artists (folder structure is, for example, `ham/Hardcore Euphoria/Track X.mp3` and `Gammer/Hardcore Euphoria/Track Y.mp3`)
3. Set the metadata profile for the artist, and refresh.
4. No albums found.

**Expected behavior**
The album to show up in the artist's listing. However, it does not show up. All of the Hardcore Euphoria tracks are unmapped files.

**Screenshots**
https://imgur.com/a/zeKvUHB

**Logs**
```
19-9-30 15:43:51.9|Debug|Api|[POST] /api/v1/command: 201.Created (119 ms)
19-9-30 15:43:51.9|Info|RefreshArtistService|Updating Info for DJ Ham
19-9-30 15:43:51.9|Debug|SkyHookProxy|Getting Artist with LidarrAPI.MetadataID of 73b90c12-c049-489b-addd-f33eeacd86cd
19-9-30 15:43:52.4|Debug|ArtistMetadataRepository|1 artist metadata up to date; Updating 0, Adding 0 artist metadata entries.
19-9-30 15:43:52.4|Debug|RefreshArtistService|[73b90c12-c049-489b-addd-f33eeacd86cd][DJ Ham] 0 albums up to date. Adding 0, Updating 0, Merging 0, Deleting 0.
19-9-30 15:43:52.6|Debug|AlbumAddedService|No new albums, skipping search
19-9-30 15:43:52.6|Debug|RefreshArtistService|Finished Artist refresh for [73b90c12-c049-489b-addd-f33eeacd86cd][DJ Ham]
19-9-30 15:43:52.7|Info|DiskScanService|Scanning DJ Ham
19-9-30 15:43:52.7|Debug|DiskScanService|Scanning '/music/ham' for music files
19-9-30 15:43:52.7|Debug|TrackService|Getting Tracks for ArtistId 104
19-9-30 15:43:52.7|Debug|DiskScanService|4 audio files were found in /music/ham
19-9-30 15:43:52.7|Debug|DiskScanService|[73b90c12-c049-489b-addd-f33eeacd86cd][DJ Ham] Cleaning up media files in DB
19-9-30 15:43:52.9|Debug|CleanExtraFileService|Cleaning missing metadata files for artist: DJ Ham
19-9-30 15:43:53.0|Debug|XbmcMetadata|Generating artist.nfo for: DJ Ham
19-9-30 15:43:53.0|Debug|XbmcMetadata|Saving artist.nfo for DJ Ham
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: [linuxserver.io Docker Container](https://hub.docker.com/r/linuxserver/lidarr)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.20.1.34

**Comment by ta264** [comment]
Lidarr only recognises the first artist listed on musicbrainz. It cannot currently pick up albums spread across artist folders, though this is a work in progress.

**Comment by ProjectMoon** [comment]
Is there an issue tracking that progress that I can follow?

**Comment by ta264** [comment]
#884

**Comment by Ryonez** [comment]
This is a pretty bad limitation. I'm unable to add a good chunk of music I want to because it's not strictly just an album.

**Comment by ta264** [comment]
@Ryonez see metadata profiles, or search under primary album. It'll be there :)

**Comment by Ryonez** [comment]
@ta264 Sweet, that seems to have been the pointer I needed, thank you.

**Comment by ta264** [comment]
The discord channel is the best place to get this sort of support next time :)
