### ISSUE TITLE
Track naming

### ISSUE THREAD

**Issue by vKnmnn** [lidarr/Lidarr#1007]
Since i have certain Artists with the same name e.g. Aes Dana brought me to setting {Artist NameThe} ({Artist Disambiguation}) as Track naming scheme. The problem here is, that in some cases, where there is no Artist Disambiguation set, a folder ```Artist NameThe ()``` gets created

i think there should be an option available to put the field in the filename only if it's set; or a mechanism that checks that itself.
{Artist NameThe} {ifSet{({Artist Disambiguation})}

As a bonus, i'm missing the ability to put the Qualitylevel e.g. flac or mp3-320 in the album-folder name

Let me know what you think

**Comment by Qstick** [comment]
Put the parentheses inside the brackets and it should work

**Comment by RandomNinjaAtk** [comment]
You need to set it this way:

{Artist NameThe}{ (Artist Disambiguation)}

That should fix your issue... This works in all of the available tags for all settings.

Heres an example I use for Album name:

{Artist Name}{ - Album Type}{ - Release Year} - {Album Title}{ (Album Disambiguation)}

**Comment by vKnmnn** [comment]
oh i didn't know that was possible! thank you
