### ISSUE TITLE
Wikipedia and Wikidata links on musicbrainz

### ISSUE THREAD

**Issue by JohanPotgieter** [lidarr/Lidarr#1014]
**Describe the bug**
I read on another bug report that images are extracted from the Wikipedia page (the link is on musicbrainz.org). I have noticed on a few bands that they get no art despite the fact that they are huge band and have Wikipedia entries. I did notice with the 2 examples I have "Twenty One Pilots" and "Trapt" that they have all they Wikipedia pages (many languages) listed on wikidata.org. On this site, they will have the normal English Wikipedia URL. I believe you should also look for this page (link) from MusicBrainz and then find the Wikipedia page from there.

**To Reproduce**
Find any well-known band that have no artwork and check the MusicBrainz website if they indeed have a Wikidata link that leads to a valid Wikipedia Page.

**Expected behaviour**
Gather the Wikidata information and proceed to the Wikipedia page to extract the required images.

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Debian
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.18 (I downgraded as Radarr/Sonarr/Lidarr had issues copying files to linked netword drives)

**Additional context**

**Comment by ta264** [comment]
Art comes from fanart.tv and theaudiodb.com, not Wikipedia. We use Wikipedia for overviews and parse the wikidata links as you suggest.
