### ISSUE TITLE
"Move" or "Hardlink/Copy" setting in Media Management

### ISSUE THREAD

**Issue by tommyalatalo** [Lidarr/Lidarr#1015]
**Is your feature request related to a problem? Please describe.**
The logic with which Lidarr decides whether to move or hardlink/copy an import is unclear, it seems to differ based on if its an automatic or manual import, and if its an interactive import or "quick import".

**Describe the solution you'd like**
A setting in the "Importing" section of "Media Management" where you would set the default behavior to "Move" or "Hardlink/Copy". It's likely very unusual for a user to do a little bit of both, so setting this would make it very clear what Lidarr is expected to do, and the manual import dialog would still offer an override if needed.

[AB#315](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/315)

**Comment by bakerboy448** [comment]
https://github.com/Lidarr/Lidarr/commit/e2cd4d69e0defe3c5480cdecd8b5794a0deb091a

Clarified that manual import is either Move Automatically or Interactive Import.  Thus making this request moot.
