### ISSUE TITLE
Changing profile does not reset monitored

### ISSUE THREAD

**Issue by wpmccormick** [Lidarr/Lidarr#1017]
When changing an artist metadata profile to a profile that includes less primary types, the monitored state for a title does not reset, effectively orphaning the title in the wanted list. 

This becomes a problem when there are a large number monitored titles that should no longer me monitored.

[AB#398](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/398)

**Comment by Qstick** [comment]
Please provide all the template bug report info (version, logs, etc) as well as a specific reproduction example
