### ISSUE TITLE
Use Beets as the library management backend

### ISSUE THREAD

**Issue by HerHde** [lidarr/Lidarr#1022]
First of all I haven't seen an issue related to this request, so I'll create one.

> Use [beets](http://beets.io/) for library management instead of reinventing the wheel. It supports all formats you may want to support, it has extensive tagging capabilities, it relies on MusicBrainz and potentially Discogs for tagging, etc, and its autotagger does similarity measurement to match the best "release", including the use of audio fingerprinting.
-- @retrography on [FeatHub](https://feathub.com/lidarr/Lidarr/+64)

beets and Lidarr are both *music collection/library managing* tools, but as Lidarr's focus is all the downloading stuff, beets clearly stands out with the management of files which are already on your disk, so why not let it handle it that stuff and focus on the missing tracks?

> This is the Unix philosophy: Write programs that do one thing and do it well. Write programs to work together.
-- [Doug McIlroy](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html)

Many of the problems in this issue tracker are already solved over at beets, as for example these guys (#925, #889, #390), things with paths (#176, #590, #544, #350) and some requests from FeatHub ([Automatically save album art to folder or embed in files](https://feathub.com/lidarr/Lidarr/+43), [Select default Release County and Medium](https://feathub.com/lidarr/Lidarr/+18), well, some at least for the lib like [Discogs as a Datasource](https://feathub.com/lidarr/Lidarr/+35) and [Ability to add an artist not currently on musicbrainz or other metadata providers](https://feathub.com/lidarr/Lidarr/+9))

So, how about a serious consideration?

*(Sorry for not sticking to the template. Thanks for everything so far. Love the calendar feature ;-)*

**Comment by ta264** [comment]
Not going to happen I'm afraid, not least because lidarr is csharp and beets python.

You can integrate with beets by using the custom script option.

https://github.com/lidarr/Lidarr/wiki/Custom-Post-Processing-Scripts#beets

**Comment by HerHde** [comment]
Well, too bad. I hoped that at least working with piped would suffice.
My personal advise would be to handle the MBID tags (maybe instead of the directory names when importing, if available) to create some more consistency.

**Comment by ta264** [comment]
That's what we do everywhere but the initial artist import; it's coming to artist import too soon

**Comment by HerHde** [comment]
Alright, good to know. Thanks mate!
