### ISSUE TITLE
Artist page subsections for Secondary Types (like Musicbrainz)

### ISSUE THREAD

**Issue by orsomething1030** [lidarr/Lidarr#1023]
**Is your feature request related to a problem? Please describe.**

Artists with a large number of releases have Lidarr Artist pages are a big mess due to only have sections for release Primary Types (Album, EP, Single).  All the release Secondary Types (Compilation, Live, Remix, etc) are thrown together with the normal releases and you can have an "Album" section with 100+ albums all jumbled together, which is very difficult to parse just by looking at it.
   
**Describe the solution you'd like**

Add the ability to have subsections based on Primary Type + Secondary Type + (Additional Secondary Types if applicable).  In other words, make it look exactly like Musicbrainz.  An artist page on Musicbrainz is MUCH more informative and easy to read than the same artist page on Lidarr.  As was referred to in #323, yes I'm also ok with having a whole bunch of sub-sections.

Each section/subsection should have it's own Monitor flag as well.

Yes, I am aware of the Edit > Metadata Profile setting.  I think all that should do is set up the default monitoring state for each section.  All sections/sub-sections should be displayed by default, just like musicbrainz.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Qstick** [comment]
Closing in lieu of #323, Renamed that issues to be general. Thanks for the feature request!
