### ISSUE TITLE
Search for certain artists leads to HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by jmooo** [lidarr/Lidarr#1028]
Using the latest Lidarr certain searches return HTTP 500 errors, for ex:

https://api.lidarr.audio/api/v0.4/search?type=artist&query=the%20ventures

while other artists return no errors:

https://api.lidarr.audio/api/v0.4/search?type=artist&query=the%20beatles

**Comment by ta264** [comment]
Try now?

**Comment by jmooo** [comment]
bango that fixed it! What was up?

**Comment by ta264** [comment]
Turn it off and turn it back on again...
