### ISSUE TITLE
Using Downloadstation for NZB instead SABnzbd client

### ISSUE THREAD

**Issue by MatthK** [lidarr/Lidarr#1033]
I have both the Synology Downloadstation as well as SABnzbd configured as download clients. Both show green ticks when testing.

When Lidarr found an album with NZB it passed it to the Downloadstation instead of SABnzbd. Downloadstation is setup only for torrents.

The nzb downloads should be passed on to SABnzbd.

Version    0.7.1.1381
Mono Version    5.18.0.240
DB Migration    35
On a Synology NAS

**Comment by ta264** [comment]
There are two download station clients in lidarr, one torrent and one nzb. Sounds like you added the usenet download station one by mistake. Delete it and add the torrent one.

**Comment by MatthK** [comment]
Yes, just realized that. Thanks.
