### ISSUE TITLE
Using a URL Base causes Lidarr not to start or start a dangling application

### ISSUE THREAD

**Issue by larivierec** [lidarr/Lidarr#1039]
**Describe the bug**
After doing a clean install (on both linux and windows) if you start the application using the service or the Lidarr.Console.exe it will attempt to create to socket listens on the same port. (in my example port 8686)

**To Reproduce**
1. Download the latest pre-release on linux or windows
2. Click on 'Settings -> General"
3. Change base url to anything
4. Restart the server.
5. Open the browser at the specified port with / or /{baseUrl}

**Expected behavior**
The application should only listen on 1 port and map all the underlying URL's
On ubuntu, the server starts and redirects traffic from / to the baseUrl (which is bad for reverse proxies). 
and since one application was properly started left running you must do **netstat -anp | grep 8686**  + kill the process id of the running instance.

On windows, the application simply does not start. 

**Logs**
Here's an output of the log.
https://pastebin.com/xya595wd

**System info (please complete the following information):**
 - Lidarr Version: latest -> 0.7.1.1381
 - Operating System (Windows and Linux) (Ubuntu 19.10)
 - .net Core 3.0.0 (should work fine) Linux

**Comment by ta264** [comment]
I'm afraid your issue isn't clear to me from your description but the port Lidarr listens on has nothing to do with the URL base.  I currently run lidarr myself with a URL base and a reverse proxy so this will just be a config issue on your end I believe.  Jump on the discord for support.
