### ISSUE TITLE
Choosing album release during manual import is not scrollable

### ISSUE THREAD

**Issue by Cantello** [lidarr/Lidarr#1040]
**Describe the bug**
During manual import of releases that were already sorted into folders, when I choose 'Album Release', a long list of albums and the respective available releases is shown but without any possibility to scroll. 
**To Reproduce**
1. Have a an artist with at lots of albums already in the artist's folder.
2. Select 'Manual Import' on the artist's main page
3. Select some files and try to choose an album release below the releases shown (there is *no* scroll bar on the right).

**Expected behavior**
A scrollable list of album releases even if the window is not tall enough to fit all releases.

**Screenshots**
![image](https://user-images.githubusercontent.com/594700/69867227-8268d180-12a6-11ea-809d-d015a8f57091.png)

**System info (please complete the following information):**
Version 0.7.1.1381
Mono Version 5.20.1.34
Docker True
DB Migration 35
AppData directory /config
Startup directory /app/lidarr
Mode Console

Running on Ubuntu 18.04 as linuxserver/lidarr docker. Tried with Vivaldi, Firefox & Chrome (most recent versions) on Windows 10. It is working if I enlarge the browser window but I had to put my display into vertical position for this.

**Comment by sirKitKat** [comment]
+1 - Can confirm same behaviour.

**Comment by addisonbabcock** [comment]
Can confirm the same behaviour on Chredge Dev 80.0.361.9 (latest as of this writing).
