### ISSUE TITLE
Search Monitored not finding results

### ISSUE THREAD

**Issue by dippynark** [Lidarr/Lidarr#1041]
**Describe the bug**
The full artist search 'Search Monitored' does not work and requires searching for each album individually

**To Reproduce**
1. Go to Library
2. Click on any artist for which an indexer has results you have not yet grabbed
3. Click 'Search Monitored' towards the top of the page
4. Observe following logs
```
[Info] NzbSearchService: Searching 1 indexers for [Solomun]
[Info] DownloadDecisionMaker: Processing 77 releases
[Info] ArtistSearchService: Artist search completed. 0 reports downloaded.
```
5. Search for an album individually that has a result
6. Observe Lidarr grabbing a result

**Expected behavior**
'Search Monitored' performs a search on every album/ep

**System info (please complete the following information):**
 - Lidarr Versio: `0.7.1.1381`
 - Operating System: `Linux`
 - mono Version: `5.20.1.34`

**Additional information**
- I am using REDacted through Jackett
- both 'Solomun' albums and EPs do not work
- 'The Pharcyde' albums work, but EPs do not

[AB#406](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/406)

**Comment by Qstick** [comment]
Need trace logs of the search if possible

**Comment by dippynark** [comment]
@Qstick I enabled trace logs in the settings but none seem to be showing for this action. This is what I am seeing.
```
[Info] NzbSearchService: Searching 1 indexers for [Bill Withers - Watching You Watching Me (1985)]
[Info] DownloadDecisionMaker: Processing 3 releases
[Info] NzbSearchService: Searching 1 indexers for [Bill Withers]
[Info] DownloadDecisionMaker: Processing 91 releases
[Info] DownloadService: Report sent to Whatbox. Bill Withers - Watching You Watching Me [1985] [Album] FLAC / Lossless / Log (100%) / CD
[Info] ArtistSearchService: Artist search completed. 1 reports downloaded.
[Info] NzbSearchService: Searching 1 indexers for [Bill Withers - 'Bout Love (1978)]
[Info] DownloadDecisionMaker: Processing 5 releases
[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.
[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0
[Info] NzbSearchService: Searching 1 indexers for [Bill Withers - 'Bout Love (1978)]
[Info] DownloadDecisionMaker: Processing 5 releases
[Info] NzbSearchService: Searching 1 indexers for [Bill Withers - 'Bout Love (1978)]
[Info] DownloadDecisionMaker: Processing 5 releases
[Info] DownloadService: Report sent to Whatbox. Bill Withers - 'Bout Love [1978] [Album] FLAC / 24bit Lossless / WEB / 2009
[Info] AlbumSearchService: Album search completed. 1 reports downloaded.
```

**Comment by ta264** [comment]
That's not a trace log! It should say trace not info on the left

**Comment by dippynark** [comment]
Yeah I know, that's why I said none seem to be showing - is there something else I should except from selecting Trace in the log settings

**Comment by ta264** [comment]
You need to open up the trace log file it produces, called something like lidarr.trace.txt

**Comment by dippynark** [comment]
@Qstick It seems to have produced a huge amount of content due to printing the full artist list over and over - I hope this is what you wanted

[Lidarr.zip](https://github.com/lidarr/Lidarr/files/3984555/Lidarr.zip)

**Comment by dasb00ter** [comment]
Version
0.7.1.1612 (tried latest and preview in docker)

I think I am seeing similiar behaviour. I am using Ombi to add but I'm pretty sure I cant get it to work when I add myself with add new. Albums are listed in the wanted section and interactive search(the little dude) finds acceptable releases. Nothing seems to download automatically. The trace log is a little too much for me but hope that it helps
[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/4150844/Lidarr.trace.txt)

[https://gist.github.com/dasb00ter/7866fae75a98bacbbb2f4ed6ebc75e87](url)

**Comment by mperez02** [comment]
Any update on this issue? I'm seeing it in Ombi as well.

> @Qstick It seems to have produced a huge amount of content due to printing the full artist list over and over - I hope this is what you wanted
> 
> [Lidarr.zip](https://github.com/lidarr/Lidarr/files/3984555/Lidarr.zip)

**Comment by rajah9** [comment]
I'm seeing the same issue and would like to see an update as well.

**Comment by bakerboy448** [comment]
Closing; can reopen if the appropriate logs are provided for Lidarr v1 and if this is a bug

given that users find results just fine, any issue is most likely simply trying to use trackers or indexers that are not good for music and don't have releases named appropriately or cannot internally search themselves appropriately
