### ISSUE TITLE
API queue delete is in source but not in documentation

### ISSUE THREAD

**Issue by esticle** [lidarr/Lidarr#1042]
**Describe the bug**
I would like to remove, remove & blacklist, etc items from the queue using the API v1

**To Reproduce**
n/a

**Expected behavior**
Documentation should give some hints - [unfortunately it does not](https://github.com/lidarr/Lidarr/wiki/Queue)

The [source however](https://github.com/lidarr/Lidarr/blob/develop/src/Lidarr.Api.V1/Queue/QueueActionModule.cs), mentions items such as Remove, skipReDownload, etc but unfortunately I cannot deduce from that how to call it (sonarr-style /api/v1/queue/%s?apikey=%s does not appear to work).

Rough hints appreciated!

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System:  Ubuntu 18.04.3 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

Thanks!

**Comment by Qstick** [comment]
Send a delete request in this format `/queue/${id}?blacklist=${blacklist}&skipredownload=${skipredownload}` and fill in the values for Id, blacklist (Boolean) and skipredownload (Boolean)

**Comment by esticle** [comment]
Just perfect, thanks!

**Comment by Qstick** [comment]
Added to WIKI, Thanks
