### ISSUE TITLE
Search for certain artists leads to HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by davewantsmoore** [lidarr/Lidarr#1045]
Using the latest Lidarr certain searches return HTTP 500 errors

19-12-11 15:18:01.6|Trace|Http|Req: 109 [GET] /api/v1/artist/lookup?term=a
19-12-11 15:18:01.6|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
19-12-11 15:18:01.6|Trace|HttpClient|Req: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=a
19-12-11 15:18:01.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-12-11 15:18:01.8|Trace|HttpClient|Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=a: 200.OK (131 ms)
19-12-11 15:18:01.8|Trace|Http|Res: 109 [GET] /api/v1/artist/lookup?term=a: 200.OK (158 ms)
19-12-11 15:18:01.8|Debug|Api|[GET] /api/v1/artist/lookup?term=a: 200.OK (158 ms)

19-12-11 15:18:04.4|Trace|Http|Req: 110 [GET] /api/v1/artist/lookup?term=dep
19-12-11 15:18:04.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
19-12-11 15:18:04.4|Trace|HttpClient|Req: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=dep
19-12-11 15:18:04.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-12-11 15:18:10.8|Trace|HttpClient|Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=dep: 500.InternalServerError
Internal Server Error (6349 ms)
19-12-11 15:18:10.8|Warn|HttpClient|HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=dep: 500.InternalServerError
Internal Server Error

**Comment by ta264** [comment]
Restarted the search server and it's working now.
