### ISSUE TITLE
500 error on some artist searches

### ISSUE THREAD

**Issue by robearlam** [lidarr/Lidarr#1046]
I'm getting a 500 error being returned from the services on some artist searches. Some examples that error:

https://api.lidarr.audio/api/v0.4/search?type=artist&query=611c226a-6eda-486a-ab1c-cd8573e68c00
https://api.lidarr.audio/api/v0.4/search?type=artist&query=pigs%20pigs%20pigs%20pigs%20pigs%20pigs%20pigs
https://api.lidarr.audio/api/v0.4/search?type=artist&query=7f89e20f-46f3-4571-9ae0-b29dcdb4bbe9
https://api.lidarr.audio/api/v0.4/search?type=artist&query=kikagaku%20moyo

**Comment by ta264** [comment]
Fixed
