### ISSUE TITLE
Error adding individual Album

### ISSUE THREAD

**Issue by tobsen987** [lidarr/Lidarr#1049]
Adding an individiual album is not working. Pressing the "add" button does nothing.

**To Reproduce**
1. Add new
2. search for album
3. try adding it
4. See error in log

**Expected behavior**
Album should be added

**Logs**
Note: nothing more as the following is showing in the logs:
```
19-12-17 17:45:52.4|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- Artist.QualityProfileId: Quality Profile does not exist
```
Changing the quality profile for the artist does nothing. Metadata profile is set to "none".

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1588
 - Operating System ubuntu/docker

**Comment by tobsen987** [comment]
The above is true, when the artist was already added before the update. After deleting the artist and adding individual albums it works.

**Comment by ta264** [comment]
Can you reproduce this for any other artists?

**Comment by tobsen987** [comment]
No, I can't.. Weird.. I guess I can close this then.
