### ISSUE TITLE
Completed Download Handling Missing Remove Button

### ISSUE THREAD

**Issue by goku-son** [lidarr/Lidarr#1051]
**Describe the bug**
Lidarr not removing downloads after import from utorrent. 

**To Reproduce**
Go to settings download client and there is no remove button for under Completed Download Handling like there is in Sonarr. 

**Expected behavior**
Remove option under Completed Download Handling like Sonarr. 

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. Windows 7]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by Qstick** [comment]
You mean this one? Turn on show advanced settings.
![17FFB821-2713-45BF-93AF-4E65ED97DB8C](https://user-images.githubusercontent.com/376117/71302972-1991e800-2380-11ea-92de-1c2b8e0873e9.jpeg)

**Comment by goku-son** [comment]
Thanks!
