### ISSUE TITLE
Track Title Error

### ISSUE THREAD

**Issue by aaronth07** [lidarr/Lidarr#1052]
I'm getting the error "Must contain Track Title and Track numbers OR Original Title". My current naming setup is "{Artist Name} - {Track Title}". Why must I have the track numbers with the name? This is very annoying, and every one of my songs in my music library is named like that. The main reason I want to use Lidarr is to have it quickly download and rename music, using a batch renaming tool (which is what i'll have to do if I use Lidarr) will defeat the purpose.

**Comment by ta264** [comment]
Because there are plenty of albums that have the same track an twice and your naming scheme won't uniquely identify them.

**Comment by aaronth07** [comment]
Leaving a "(1)" and "(2)" like Windows does as will identify them if they are ever in the same folder (which is rare), without ruining any already existing naming scheme. It's what Windows does by default, as well as most other batch renamers.
