### ISSUE TITLE
Remote Path not able to handle Docker container

### ISSUE THREAD

**Issue by Stuntaneous** [lidarr/Lidarr#1059]
**Describe the bug**
System page: "Local download client qBittorrent places downloads in /downloads/Finished/ but this is not a valid Windows path. Review your download client settings."

"/downloads/Finished/" is what qBittorrent in a local Docker container sees.

The same configuration works fine in Radarr and Sonarr (v3).

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Win10 Pro 64bit (host, Lidarr) + Docker (Linux, qBittorrent)
 - .net Framework (Windows): Probably latest.

**Comment by ta264** [comment]
Have you added a remote path mapping?

**Comment by Stuntaneous** [comment]
Yes, that's the source of the issue.

**Comment by ta264** [comment]
Fairly sure this will just be an issue with the path mapping not being correct. Please join the discord channel and someone will be able to help you. If it turns out there is a bug after that we can reopen.
