### ISSUE TITLE
Adding to musicbrainz? + request

### ISSUE THREAD

**Issue by Chris230291** [lidarr/Lidarr#1061]
Hello. I added some releases to musicbrainz website. When will they show up in lidarr?

I used a tampermonkey script I found that will let you add to musicbrainz from discogs...
https://github.com/murdos/musicbrainz-userscripts/blob/master/discogs_importer.user.js

I was wondering if this is something lidarr could potentially do for us? I see people asking for discogs support. What if lidarr checked for releases in discogs that are missing in musicbrainz, then did what that tampermonkey script does automatically? The script includes an option to check if the release already exists and an option to add. The way I would imagine it working from a client perspective is for us to enable the feature and add our musicbrainz credentials in lidarr. When artists are updated it checks for missing releases (discogs vs musicbrainz) and then adds any missing.

Chris

**Comment by ta264** [comment]
Musicbrainz doesn't allow automatic edits I'm afraid, certainly not at that level
