### ISSUE TITLE
Albums not populated in Library>Album Studio

### ISSUE THREAD

**Issue by mad-tunes** [lidarr/Lidarr#1064]
**Describe the bug**
If I click Library>Album Studio, Artists are populated and listed, I see CPU activity for approx 20 seconds which then stops - and no albums are listed.
This is when using 0.7.1.1381 (latest stable) and 0.7.1.1604 (latest nightly)

**To Reproduce**
1. Go to Library>Album Studio
2. Wait 20+ seconds
4. See no albums listed

**Expected behavior**
All albums should be listed

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6985934/72739549-bc19d280-3b9b-11ea-8686-b4d21dd05223.PNG)

**Logs**
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/4086898/Lidarr.debug.txt)
(Relevant bit starts at 20-1-20 15:13:20.2, pls ignore not connecting to transmission earlier in the log. That was my fault restarting Lidarr while Transmission wasnt running)

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1604
 - Operating System: Windows Server 2019
 - .net Framework (Windows): 4.7 (with any updates)

**Additional context**

**Comment by Qstick** [comment]
I would venture to say that you are not waiting long enough.... this works fine for me, though it does take some time to pull
