### ISSUE TITLE
svg Honeycomb broken

### ISSUE THREAD

**Issue by Fish2** [lidarr/Lidarr#107]
lidarr.svg Honeycomb is broken 

Provide a description of the feature request or bug, the more details the better.
Please use http://lidarr.audio for support or other questions. (When in doubt, use the forums)

**Comment by Qstick** [comment]
I pulled it until it could be fixed as it was rendering weird in UI. Feel free to fix if you want

**Comment by Fish2** [comment]
I did give it a go but very new to SVG Files and couldn't get it any better i did see that sonarr have change there style in this comment c32b2ac638e4dc52b5a89bdf745060cbb141a297

**Comment by Fish2** [comment]
https://github.com/lidarr/Lidarr/pull/117 has the fix for this issue
