### ISSUE TITLE
Transmission Default Path Ignores Mappings - Can't Choose Custom Path that are Valid

### ISSUE THREAD

**Issue by moogoos** [lidarr/Lidarr#1071]
**Describe the bug**
Lidarr keeps saying that the default dir that transmission is using doesn't exist locally. This is wrong as I have a "remote" dir that is mapped locally. The remote dir is valid in transmission and links to mucic locally.  sonarr and radarr do this correctly with custom folders that are valid on transmissions side.

**To Reproduce**
Just set a default dir on transmission, set it as a client and see that lidarr will ignore any mappings that are valid on transmission, and will use the default dir, even if you map legitimate folders and then you get annoying messages like this:

You are using docker; download client transmission places downloads in /data/video but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

It doesn't because I don't want it to use the default dir. I want it to use the mapped dir in lidarr which is a valid dir on transmission that manages music.

**Expected behavior**
Allow legitimate folders to be mapped other than the default.

This makes this software pretty much unusable as it chooses where it thinks it should put things based off the default path.

**Comment by ta264** [comment]
I don't understand the bug, you mentioned it's appending /music but don't see that in the example.

Remote path mapping are applied in that check if they are set up correctly. Bear in mind that sonarr and radarr don't have this check, so the lack of a warning there doesn't mean it's set up correctly. Please use the discord for support, if it does turn out there is a bug and not a config error we can reopen and fix

**Comment by moogoos** [comment]
radarr and sonarr work as it's supposed too. They write to the mapped directory. Lidarr doesn't. It writes to the default defined in transmission, as mentioned.

**Comment by ta264** [comment]
Lidarr doesn't do any writing when downloading, just sends torrents to transmission which is why I'm confused. Join the discord channel and someone will hopefully be able to sort you out - much easier with real time response

**Comment by moogoos** [comment]
Kk. I understand that’s how it works but why it picks up the default dir I don’t understand. The others use the correct mapped paths. I’ll jump on discord.
