### ISSUE TITLE
Feature Request: Manually Add Album Outside of Metadata Profile

### ISSUE THREAD

**Issue by Haze028** [lidarr/Lidarr#1072]
Issue: 
    1. Some artists, like Pearl Jam, have a large number of Live albums. I, personally, only want one of them (MTV Unplugged). If I manually download the one Live album I want, outside of Lidarr,  I cannot import it into my collection without having all Live albums selected in my Metadata Profile, causing my library to include all other live albums, which I have no intention of downloading. 
    2. Similarly Nirvana - Incesticide is a 'Compliation' album. I would like to add this to my library without having all compilation albums from all artists displayed in my library. 

Solution: 
    Have all possible releases listed when trying to manually import an album, regardless of Metadata profile. 

Alternative: 
    Local re-classification of Metadata, so I can manually identify Pearl Jam - MTV Unplugged or Nirvana - Incesticide as Studio Albums for my Library (Local Only)

**Comment by ta264** [comment]
This is already done in nightly

**Comment by Haze028** [comment]
Perfect, many thanks!
