### ISSUE TITLE
Missing album listing

### ISSUE THREAD

**Issue by Viceman256** [lidarr/Lidarr#1078]
**Describe the bug**
Not sure the source of this, but the Weeknd is missing his album: Trilogy

This does show in Musicbrainz:
https://beta.musicbrainz.org/release-group/d0ae475d-ee3b-4934-a442-631468867384

The confusion may be due to the fact Trilogy is a remake of older songs, so there are the originals under their original albums:
Echoes of Silence
House of Balloons
Thursday

Then there are songs from those albums remade for the Trilogy album.

**Comment by ta264** [comment]
Its there, enable compilation in your metadata profile

**Comment by Viceman256** [comment]
That did it, thanks!
