### ISSUE TITLE
Allow RSS sync periods greater than 120mins

### ISSUE THREAD

**Issue by elementalest** [lidarr/Lidarr#1080]
**Is your feature request related to a problem? Please describe.**
Currently unable to have longer RSS sync times than 120mins.

**Describe the solution you'd like**
Allow the RSS sync times to be extended to up to 24hrs

**Describe alternatives you've considered**
There are no alternatives, this is a hard limitation.

**Additional context**
Radarr has this functionality. Music releases (like movies) are generally less frequent/numerous than TV shows. Sometimes there are no changes in 2hrs between RSS syncs.

**Comment by ta264** [comment]
And what's the issue with just letting it run every two hours even if there are no changes? I don't see what this option would but you...

**Comment by elementalest** [comment]
Its nice to have the option for flexibility and I guess it can reduce unnecessary load on indexers.

**Comment by ta264** [comment]
It seems to me the answer is there isn't any benefit :)

**Comment by elementalest** [comment]
Respectfully I disagree. What is the downside of adding this functionality? It seems like it would be relatively easy to change. The fact that it gives greater flexibility for very small effort I think is a net benefit. Furthermore there is precedent given Radarr has it.
