### ISSUE TITLE
APi to add torznab indexers

### ISSUE THREAD

**Issue by dorel14** [Lidarr/Lidarr#1081]
**Is your feature request related to a problem? Please describe.**
My problem is adding all jackett indexers is a bit long to do

**Describe the solution you'd like**
It would be great having an API endpoint to add indexers in bulk import, Jackett offers an api to export 

**Describe alternatives you've considered**
To wourld be a bulk import directly from jackett

**Additional context**
There is an api endpoint on sonnar for indexers

[AB#416](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/416)

**Comment by supersnellehenk** [comment]
Don't know if this is still a current issue, but this can simply be fixed by actually using the endpoint Jackett provides. `/torznab/all`

I use this including NZBHydra2 and a usenet indexer. Hope this helps.

**Comment by Qstick** [comment]
Prowlarr

**Comment by dorel14** [comment]
Hello this endpoint "/torznab/all" is not anymore supported by Liddar  , it will be nice to send indexers in liddar such as prowlar .

**Comment by Qstick** [comment]
Lidarr has an API to setup Indexers, that's what Prowlarr uses
