### ISSUE TITLE
Run As Service - Network Drives

### ISSUE THREAD

**Issue by sokratz** [lidarr/Lidarr#1083]
Both Radarr and Sonarr run fine as a windows service with network mapped drive access (as long as that service runs as a network account).  Is there code checking if running as a service and disabling features?  Can we get a toggle on that in advanced if so?

Thanks

**Comment by ta264** [comment]
So does lidarr

**Comment by sokratz** [comment]
well that's weird.  i run it as a service and give it the perms it needs (identical to radarr and sonarr) but it still says it can't use network drives.  if you've got it to work then something must be goofy on my end.
