### ISSUE TITLE
Feature Request: Keep replaygain tags when tag scrubbing enabled

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Lidarr/Lidarr#1086]
**Is your feature request related to a problem? Please describe.**
Not entirely, tag scrubbing does exactly as it says, but it removes replaygain tags and makes me sad. All other tags should be scrubbed, but I feel like an exception should be made for those specific tags...

**Describe the solution you'd like**
Scrub all tags except for replaygain tags

**Describe alternatives you've considered**
Disable scrubbing

[AB#418](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/418)

**Comment by alucryd** [comment]
Would also be awesome if replaygain could be computed from within lidarr, removing the need for an external tool like beets.
