### ISSUE TITLE
Unable to connect outside of localhost

### ISSUE THREAD

**Issue by bsollenb54** [lidarr/Lidarr#1092]
**Describe the bug**
Using Lidarr 0.7.1.1381 on Ubuntu 16.04 LTS, I am unable to connect to Lidarr outside of localhost (neither on the network or remotely). Port forward for 8686 is enabled on the Netgear RAX80 router and other services (radarr, sonarr, ombi, plex, nzbget) are all connecting both when on the network using internal IP:port, or external using dyndns.com:port.

**To Reproduce**
1. sudo systemctl start lidarr
2. used firefox browser to enter localhost:8686 (worked)
3. checked network router for internal/external port forwarding set to 8686 for the internal IP of the server the service is actively running on.
4. Used seperate laptop and mobile phone to access internal ip:port while on the same wifi (didnt work).
5. Used seperate laptop and mobile phone to access external ip:port and mydyndns.com:port while not on same wifi (didnt work)
6. Changed port to 8688 randomly and restarted Lidarr + opened port forward for 8688, still didnt work

**Expected behavior**
UI displays for internalip:port and mydnswebsite.com:port from other devices just as it does for localhost:port on the server

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Ubuntu 16.04 LTS

**Additional context**
Recreating these steps for Radarr, Sonarr, Plex, Ombi, Headphones and NZBget all work...the issue seems to be exlusive to Lidarr.

**Comment by ta264** [comment]
This is an issue with your local network setup, not lidarr. Please use the discord channel for support
