### ISSUE TITLE
Megaboon or generic web store integration

### ISSUE THREAD

**Issue by monotok** [lidarr/Lidarr#1095]
Torrents are not the best when it comes to music and something like megaboon (website) has a lot of content, can download an album as a zip but obviously quite a manual process.

**Describe the solution you'd like**
It would be great if Lidarr could use it as an alternative to torrents. There isn't an API so I reckon it would rely on scrapping the web page. Then download the zip, extract it and sort. 

**Additional context**
Have thought how useful it would be for a while but thought I'd ask to see if it has been discussed before. 

Thanks!

**Comment by Qstick** [comment]
We have no plans to implement scraping or direct downloading at this time from Lidarr.
