### ISSUE TITLE
Import with spotify add all artists albums even if specific albums is selected

### ISSUE THREAD

**Issue by Mrpink200** [lidarr/Lidarr#1097]
Hello

Im using the latest nightly build (first time user)  and i see that whatever Spotify import list option i choose , lidarr imports all artists album even if only one is saved in spotify albums

Version 0.7.1.1641
Mono Version 5.18.0.240

Anyone ?

**Comment by ta264** [comment]
Set metadata profile for list to none.

Please use discord for support requests
