### ISSUE TITLE
Feature Request: Add an option menu to the tag process

### ISSUE THREAD

**Issue by calm3285** [Lidarr/Lidarr#1103]
**Is your feature request related to a problem? Please describe.**
I have a large collection and the storage is getting tight.
I prefer to put the album art in the files folder, that write it in every track (x10)

**Describe the solution you'd like**
I would like to add a menu where you can choose what fields to write, like album art, genre,etc

**Describe alternatives you've considered**
I'm trying to use beets; but with file permissions, metadata scrub, and other; I have a lot to learn

**Additional context**
With Feature request like this https://github.com/lidarr/Lidarr/issues/925 and issues like this https://github.com/lidarr/Lidarr/issues/979 it would be great to give the user the chance to choose what put in our music collection.

[AB#217](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/217)

**Comment by Qstick** [comment]
Setting added to allow album art embed to be disabled. No plans to tweak every field for tagging.
