### ISSUE TITLE
Import Lists / Spotify Albums : All albums artists are added even if specific is choosen

### ISSUE THREAD

**Issue by Mrpink200** [lidarr/Lidarr#1108]
**Describe the bug**

**To Reproduce**
1. Go to Settings\Import List\ Add Spotify Saved Albums
2. Select Monitos : Specific
3. Select Metadata : Standard
4. After validation, go to Spotify and ensure you have only one album saved : for example "Pump" From Aerosmith
5. Go back to lidarr, System\tasks\import list sync
6. Lidarr will add and monitor all the arosmith albums

**Expected behavior**
In this case, all the aerosmith album should be added unmonitored except "Pump"

**System info (please complete the following information):**
System : Synology DSM 6.x
Version : 0.7.1.1652
Mono Version : 5.18.0.240
DB Migration : 39
AppData directory : /volume1/@appstore/lidarr/var/.config/Lidarr
Startup directory : /volume1/@appstore/lidarr/share/Lidarr
Mode : Console

**Comment by ta264** [comment]
Cannot replicate, it works for me. Jump on the discord if you still need help.
