### ISSUE TITLE
Add the possibility to limit release size downloaded (and not only bitrates)

### ISSUE THREAD

**Issue by Mrpink200** [lidarr/Lidarr#1109]
**Is your feature request related to a problem? Please describe.**
Lidarr does not reconize all release quality, and it is often needed to add "unknown" to grab available release. The peoblem adding unknown is that in some cases lidarr grab dvd or br images that are not correctly named (no DVD or iso or BR in the file name, so a name filter can not be applied). 

**Describe the solution you'd like**
A possible solution would be to allow a size filter in the release. If i could limit the relase download at 1GO, i m quite sure i would avoid all of those.

**Comment by ta264** [comment]
Unknown can still have a size limit, set it to something appropriate.

You can also put a maximum size on any release in settings / indexers.
