### ISSUE TITLE
Import List : Spotify Playlist / Monitor tracks only

### ISSUE THREAD

**Issue by henry-nicolas** [lidarr/Lidarr#1111]
**Is your feature request related to a problem? Please describe.**
When using spotify import list the 2 monitoring options allow me to either monitor everything related to the artists (all artists albums) or specific ones related to the import list.
This means that when I want to add a Spotify playlist with 50 songs, I end up monitoring 1700 tracks: every albums that contains a track in the playlist are now being monitored which is a lot more than what I was looking for.

**Describe the solution you'd like**
A third monitoring choice to only monitor tracks which are mentionned on that list

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ta264** [comment]
We don't support monitoring individual tracks and given Usenet/torrent releases are for complete albums normally we have no plans to support this

**Comment by henry-nicolas** [comment]
Fine, any workaround you could suggest then? I understand the constraints but I really do not see the added value of importing a playlist of 50 tracks if that means you start flooding your system with all the related ones belonging to the same albums.

It is fine to monitor it all but then it would be good to have a playlist file generated that matches the import list so that the 50 songs I am  looking for are not lost among the 1700 other ones.

**Comment by ta264** [comment]
Yeah writing out a playlist file with the downloaded tracks is something I've been working on.

Given lidarr works at the album level I think that's about the best we can do
