### ISSUE TITLE
Disposed object error

### ISSUE THREAD

**Issue by achmetinternet** [lidarr/Lidarr#1113]
**Describe the bug**
Testing the connection to qBittorrent succeeds and there are no current downloads from lidarr in it but under system I get the error:

Unable to communicate with qBittorrent. Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

**To Reproduce**
Steps to reproduce the behaviour: install qBittorent and lidarr in jails on a FreeNAS machine ;) I can attach the log, but which one would suffice?

**Expected behavior**
The error should not be there.

**Screenshots**

**Logs**
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/4349779/Lidarr.debug.txt)(url)

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System FreeNAS
 - Mono: 5.10.1.57

**Additional context**

**Comment by ta264** [comment]
I believe this is a bug in mono (5.10 is pretty ancient)

**Comment by achmetinternet** [comment]
Ok, so I'll try to update Mono as described here but I had a hard time
understanding the instructions for FreeNAS:
https://www.ixsystems.com/community/resources/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.126/


Am Mi., 18. März 2020 um 17:08 Uhr schrieb ta264 <notifications@github.com>:

**Comment by ta264** [comment]
If you're not comfortable with those instructions I'd very much suggest you don't run lidarr on BSD - it's barely tested / supported. You'd be much better off running it in your windows desktop or a Linux server or in a Linux vm on bsd.
