### ISSUE TITLE
Unable to update Lidarr.

### ISSUE THREAD

**Issue by debug7878** [lidarr/Lidarr#1114]
I have install Lidarr on my FreeNAS-11.3-U1 followed digimoot's tutorial works great but I'm unable to update to the latest version. 

https://digimoot.wordpress.com/2020/03/07/freenas-lidarr-manual-install/

When I run the install the new update I get the following error:

Error occurred while executing task ApplicationUpdate: ApplicationName='mono', CommandLine='--debug /tmp/lidarr_update/Lidarr.Update.exe 74820 /tmp/lidarr_update /usr/local/share/lidarr/Lidarr.exe /data=/usr/local/lidarr /nobrowser', CurrentDirectory='', Native error= Cannot find the specified file

**Comment by ta264** [comment]
Please use the discord for support, this will be an issue with your setup I believe
