### ISSUE TITLE
UTF-8 in filenames cause scan abort

### ISSUE THREAD

**Issue by rootwyrm** [lidarr/Lidarr#1115]
**Describe the bug**
The presence of files with UTF-8 characters causes a false 'file not found' exception in System.IO, which causes scan to abort completely.

**To Reproduce**
Import a directory for an artist containing UTF-8 characters, particularly `\344` which is `ä`
Attempt to scan.
No entries will be found for any files; Lidarr goes into complete scan failure the second it hits the UTF-8 character, and aborts all further scanning. It will rename correctly, but substituting `\303` for `\344`.

Scan should not go into full 'bail out, return nothing' upon hitting a single error like this; it also should not be returning a file not found.

**Screenshots**
N/A

**Logs**
```
[v0.7.1.1381] System.IO.FileNotFoundException: Could not find file '/opt/talecaster/music/Eliot Lipp/How We Do Moves Made/01 Sunrise L?gg till I Spellistan.mp3'.
File name: '/opt/talecaster/music/Eliot Lipp/How We Do Moves Made/01 Sunrise L?gg till I Spellistan.mp3'
  at System.IO.FileInfo.get_Length () [0x0001d] in <9f7fe7d232ca4f4ca5e7db3b6f5f4b30>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo.get_Length()
  at System.IO.Abstractions.FileInfoWrapper.get_Length () [0x00000] in <f24414d440204889a79a64ec080409aa>:0 
  at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetImportDecisions (System.Collections.Generic.List`1[T] musicFiles, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.Music.Album album, NzbDrone.Core.Music.AlbumRelease albumRelease, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.Parser.Model.ParsedTrackInfo folderInfo, NzbDrone.Core.MediaFiles.FilterFilesType filter, System.Boolean newDownload, System.Boolean singleRelease, System.Boolean includeExisting) [0x000b3] in <f339569e234a4fc1add8b9dab7a33d21>:0 
  at NzbDrone.Core.MediaFiles.TrackImport.ImportDecisionMaker.GetImportDecisions (System.Collections.Generic.List`1[T] musicFiles, NzbDrone.Core.Music.Artist artist, NzbDrone.Core.MediaFiles.FilterFilesType filter, System.Boolean includeExisting) [0x00000] in <f339569e234a4fc1add8b9dab7a33d21>:0 
  at NzbDrone.Core.MediaFiles.DiskScanService.Scan (NzbDrone.Core.Music.Artist artist, NzbDrone.Core.MediaFiles.FilterFilesType filter) [0x00192] in <f339569e234a4fc1add8b9dab7a33d21>:0 
  at NzbDrone.Core.Music.RefreshArtistService.RescanArtist (NzbDrone.Core.Music.Artist artist, System.Boolean isNew, NzbDrone.Core.Messaging.Commands.CommandTrigger trigger, System.Boolean infoUpdated) [0x00068] in <f339569e234a4fc1add8b9dab7a33d21>:0 
```
This is a bug in how Lidarr is using System.IO, and not a bug in Mono. Also note the directory is NOT the first that should be getting scanned.

```
root@popcorn:/opt/talecaster/music/Eliot Lipp # ls -l
total 0
drwxr-xr-x  1 talecaster  media  392 Mar 10 17:09 City Synthesis
drwxr-xr-x  1 talecaster  media  400 Mar 10 17:10 Come To Life
drwxr-xr-x  1 talecaster  media  394 Mar 10 17:10 How We Do Moves Made
drwxr-xr-x  1 talecaster  media  302 Mar 10 17:11 Peace Love Weed 3D
drwxr-xr-x  1 talecaster  media  960 Mar 10 17:12 Shark Wolf Rabbit Snake
drwxr-xr-x  1 talecaster  media  376 Mar 10 17:12 Skywave
drwxr-xr-x  1 talecaster  media  446 Mar 10 17:13 Tacoma Mockingbird
drwxr-xr-x  1 talecaster  media  540 Mar 10 17:13 The Outside
root@popcorn:/opt/talecaster/music/Eliot Lipp # ls -l How\ We\ Do\ Moves\ Made/
total 103932
-rw-r--r--  1 talecaster  media   7674820 Mar 10 17:10 01 Sunrise L?gg till I Spellistan.mp3
-rw-r--r--  1 talecaster  media  11578233 Mar 10 17:10 02 Move It.mp3
-rw-r--r--  1 talecaster  media   7836913 Mar 10 17:10 03 Guilty Pleasures.mp3
-rw-r--r--  1 talecaster  media  12662877 Mar 10 17:10 04 Journeys.mp3
-rw-r--r--  1 talecaster  media  11320947 Mar 10 17:10 05 Ace in the Hole.mp3
-rw-r--r--  1 talecaster  media  12182788 Mar 10 17:10 06 Genesis.mp3
-rw-r--r--  1 talecaster  media  11183904 Mar 10 17:10 07 You.mp3
-rw-r--r--  1 talecaster  media  10002009 Mar 10 17:10 08 Another World.mp3
-rw-r--r--  1 talecaster  media   7749037 Mar 10 17:10 09 The Urge.mp3
-rw-r--r--  1 talecaster  media  14135572 Mar 10 17:10 10 The Surface.mp3
-rw-r--r--  1 talecaster  media     78744 Mar 10 17:10 cover.jpg
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: FreeBSD 12.1
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 6.8.0.105

**Comment by ta264** [comment]
I explicitly test this on stuff like BTS which is all unicode, I suspect this is an issue with BSD mono

**Comment by rootwyrm** [comment]
Found another file, same issue. Mono passes unit tests with this file, so it's something specific to Lidarr or a library associated with it. I found the exact problem - Lidarr is not handling 2-byte hex correctly _or_ outputting valid UTF-8 4-byte hex.

`[v0.7.1.1381] System.IO.FileNotFoundException: Could not find file '/opt/talecaster/music/BT/These Hopeful Machines/2-04 Le Nocturne de lumi?re.flac'.`

On disk:
```
root@popcorn:/opt/talecaster/music/BT/These Hopeful Machines # ls -l 2-04*
-rw-r--r--  1 talecaster  media  88780107 Mar  9 19:59 2-04 Le Nocturne de lumi?re.flac
root@stonehoof:/opt/talecaster/music/BT/These Hopeful Machines # stat 2-04\ Le\ Nocturne\ de\ lumi\350re.flac
250081246981 3036 -rw-r--r-- 1 talecaster media 0 88780107 "Mar  9 19:58:58 2020" "Mar  9 19:59:17 2020" "Mar 10 10:57:06 2020" "Dec 31 18:59:59 1969" 4096 173400 0 2-04 Le Nocturne de lumi▒re.flac
```

Key portion here: **\350**. The other failure was **\344**. 

```
[root@popcorn /opt/talecaster/music/BT/These Hopeful Machines]# printf '%s\n' "$(ls 2-04*)" |hexdump
0000000 2d32 3430 4c20 2065 6f4e 7463 7275 656e
0000010 6420 2065 756c 696d 72e8 2e65 6c66 6361
0000020 000a
0000021
```

So the problematic character is `e8`. But Lidarr is looking for `2-04 Le Nocturne de lumi?re.flac` literal OR `Le Nocturne de lumière.flac` with hex `00E8` and not treating `e8` as equivalent. (350 being octal mask of 303 250 for some reason. bash UTF handling is bonkers.) But that does very clearly point us to the _precise_ issue going on here. 

It's presented as valid 2-byte hex, but Lidarr itself is only accepting or looking for 4-byte.

This is further proven out by the rename results:
`02-04\ -\ Le\ Nocturne\ de\ lumi\303\250re.flac`
That is the full 4-byte octal "303 250". 
```
[root@popcorn /opt/talecaster/music/BT/These Hopeful Machines]# printf '%s\n' "$(ls 02-04* | cut -d i -f 2)"
ère.flac
[root@popcorn /opt/talecaster/music/BT/These Hopeful Machines]# printf '%s\n' "$(ls 02-04* | cut -d i -f 2)" |hexdump
0000000 a8c3 6572 662e 616c 0a63
000000a
```

Look at the hex output here; that's _not valid UTF-8 for è_. In fact, I'm not even sure what it is. So there's actually two issues. One, Lidarr isn't handling 2-byte UTF-8 (this might be a supporting library issue?) Two, Lidarr writes filenames with 4-byte UTF-8 but in a strange way that does not _actually_ appear to be UTF-8.

**Comment by ta264** [comment]
Haven't heard anything more so assuming it's just an issue with your local bad environment and closing

**Comment by gustavo-momente** [comment]
I have the same issue too, any information you'd need to fix this issue?

**Comment by ta264** [comment]
On BSB? I think this is a user config error and not a lidarr issue

**Comment by gustavo-momente** [comment]
You're right, I was digging the issue a little and in my case was that I had some latin1 encoded paths instes of `utf-8`. Sorry for the trouble.
