### ISSUE TITLE
Mono is not running with --debug switch

### ISSUE THREAD

**Issue by jamaroney** [lidarr/Lidarr#1116]
XigmaNas server running FreeBSD 12.1, w/ mono 6.8.0.105

My lidarr file in rc.d directory is set for mono to debug. It ran fine w/ lidarr 0.6.2.883. 
I upgraded to lidarr 0.7.1.1381, and I get the log message "Mono is not running with --debug switch"

**Comment by ta264** [comment]
Mono is being phased out in favour of net core so Im not going to fix this since it's just a display niggle
