### ISSUE TITLE
"RescanArtist" API doesn't actually exist.

### ISSUE THREAD

**Issue by mcampbell** [Lidarr/Lidarr#1117]
According to the Wiki it should be possible to use the `RescanArtist` Command API to rescan the disk of a given artist.    No such API exists.  In fact, "RescanArtist" doesn't appear in the source code whatsoever.

`RefreshArtist` does, but that also goes out and recatalogs the entire artist; I just want a disk scan.

[AB#218](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/218)

**Comment by RandomNinjaAtk** [comment]
You can use this: RescanFolders

**Comment by mcampbell** [comment]
Thanks.  I'm having an issue.  I'm using the same path as shown in the GUI, but getting "Sequence Contains no matching element" error.  

```
curl -v -s 192.168.1.40/lidarr/api/v1/command -X POST -d "{\"name\": \"RescanFolders\", \"folders\": [\"/music/_Blues/Lonnie Mack\"]}" --header "X-Api-Key:${API}"
```

![image](https://user-images.githubusercontent.com/692557/77463491-158cc080-6ddc-11ea-9613-8170d46047dc.png)

I've also tried with/without a trailing slash, with an actual album name (with/without trailing slash).

I'm sure it's user error, but tried everything I've thought of to try.

What am I missing?

**Comment by ta264** [comment]
I think you're trying this on develop but that endpoint is only available on nightly (lsio preview tag)

**Comment by mcampbell** [comment]
I'll give that a try; thanks.

**Comment by RandomNinjaAtk** [comment]
@mcampbell 
Also make sure you have your port and actual api key in the command. Your posted one did not have the port number, but I presume you would not want to post your api key.

**Comment by mcampbell** [comment]
> @mcampbell
> Also make sure you have your port (include http and etc.) and actual api key in the command. Your posted one did not have the port number, but I presume you would not want to post your api key.

Yeah, it's going through nginx to the right port.  That part is working fine; the error I posted came from the lidarr log file, so the request is making it to the app fine.

**Comment by mcampbell** [comment]
The `preview` lsio tag'ed version seems to be working; at least I get output from the API call.

Be happy to update the wiki - what's the procedure there; just do it?

**Comment by ta264** [comment]
Updating the wiki would be great but please make clear that this is nightly only for now
