### ISSUE TITLE
Library->Import: Number of Artists is wrong

### ISSUE THREAD

**Issue by vKnmnn** [lidarr/Lidarr#1118]
Currently the import mechanism counts the number of Artists it has matched against the Database, but it doesn't only count the unique ones.

**To Reproduce**
-  Steps to reproduce the behavior:
-  Create empty folder `testimport`
-  in it create folder `The Beatles` and folder `The Beatles ()`
-  point the importer to `testimport` folder
-  See the importer tell us that it's going to import two artists, when it only imports one.

**Expected behavior**
The number  should tell us how many new uniqe artists are going to be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/16045883/77476729-65d74300-6e1b-11ea-9406-a04c23d75f27.png)

**System info (please complete the following information):**
Version    0.7.1.1381
Mono Version    5.20.1.34
Docker    True
DB Migration    35
AppData directory    /config
Startup directory    /app/lidarr
Mode    Console

**Comment by ta264** [comment]
This screen is gone in nightly
