### ISSUE TITLE
Feature Request: Make import (able to) run in background

### ISSUE THREAD

**Issue by vKnmnn** [lidarr/Lidarr#1119]
Currently, when we use Import function, we have to wait with the screen on that page until the process finishes. 
There's nothing that tells you that it behaves like that. i aborted a scan after 15 minutes because i didn't know.

So, as a solution, we could either let this process continue in background when we switch pages, or we could post a little warning on screen about what's going to happen, like these tiny JS nag windows in browsers "do yo really wanna leave this page"

**Comment by ta264** [comment]
Done in nightly

**Comment by vKnmnn** [comment]
oh ok, looking forward to it then, thanks :)
