### ISSUE TITLE
pb connection download station synology

### ISSUE THREAD

**Issue by barto95100** [lidarr/Lidarr#1122]
Hi,

Lidarr don't connect to synology download station when I test I received the message : 

> Unknown exception: Failed to login. Reason: No such account or incorrect password
Failed to get the list of torrents: Failed to login. Reason: No such account or incorrect password

> 

But when I test the same login and password I configure in lidarr directly to GUI synology is OK 

> Version
> 0.7.1.1381
> Mono Version
> 5.20.1.34
> Docker
> True

Thank's for your help

**Comment by CPersonne** [comment]
Hello, I have the same problem on my Synology.

Same Lidarr Version
0.7.1.1381
Same Mono Version
5.20.1.34

**Comment by ta264** [comment]
Download station is horribly flaky, swapping to a proper torrent client is probably the easiest fix

**Comment by CPersonne** [comment]
I have no problem with Radarr and Sonarr.

**Comment by ta264** [comment]
Pretty sure this will be user error. Jump on the discord for help and if it turns out to be a bug we can re open
