### ISSUE TITLE
Import lists doesnt work on album titles with only special characters. 

### ISSUE THREAD

**Issue by epictrumpetkid** [lidarr/Lidarr#1126]
E.G. Ed Sheerans + and - albums won't import and cause the process to stop without importing anything

here are log files: 
20-4-14 11:38:13.3|Warn|HttpClient|HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=album&query=%2B&artist=ed%20sheeran: 400.BadRequest
{"error":"Invalid search query"}
20-4-14 11:38:13.4|Error|CommandExecutor|Error occurred while executing task ImportListSync

**Comment by ta264** [comment]
Hopefully this is fixed in the metadata server now
