### ISSUE TITLE
Support Redacted API Key Authentication

### ISSUE THREAD

**Issue by lethargy-navigator** [lidarr/Lidarr#1127]
**Is your feature request related to a problem? Please describe.**
Redacted has recently implemented API key authentication. It would be ideal if Lidarr supported authentication and other API calls with user-generated API keys.

**Describe the solution you'd like**
Lidarr should support the Redacted using API keys, which is documented @ {redacted url}/wiki.php?action=article&id=455

**Describe alternatives you've considered**
N/A

**Additional context**
From the Redacted API docs:
"To make requests to the Redacted API, you must be authenticated. Users can authenticate in two ways:

    Fetching a cookie through the login form at /login.php.
    Generating an API key in their user settings and sending a Authorization: %apikey% header with each request.
    Certain endpoints will be documented as being API key only. This is to prevent session riding / CSRF. In this situation you must authenticate with an API key.

For users with 2FA enabled, it may be easier to utilize the API key authentication option."

**Comment by Qstick** [comment]
Redacted has had a gazelle based API for a while which Lidarr has supported for a while. Is this somehow different?

**Comment by lethargy-navigator** [comment]
Sorry for not clarifying.

Redacted has recently implemented **API key authentication**. I've updated the original request.

**Comment by whoiscoos** [comment]
> Sorry for not clarifying.
> 
> Redacted has recently implemented **API key authentication**. I've updated the original request.

would be a great feature for those using 2FA

**Comment by flying-sausages** [comment]
Big +1, can't imagine this being that hard to implement. Will do some investigation in the source. I don't think it is too different from the Gazelle API.

**Comment by flying-sausages** [comment]
https://github.com/lidarr/Lidarr/blob/f77a2feeef0f85fcf162a5ae7ae86520b05cdb58/src/NzbDrone.Core/Indexers/Gazelle/GazelleRequestGenerator.cs#L88

From what we found out earlier, it is essentially only this function that needs to be re-written. 

You can authenticate using the API key by sending an `Authorization: %apikey%` header with each request.

`ajax.php?action=index` returns the `authkey` and the `passkey` which is what Lidarr currently uses.

From the chat in `#red-dev`, it seems like there's really nothing wrong with download links being generated and not being retrieved using the API, but downloading the actual `.torrent` binary would be wiser in the long run.

**Comment by flying-sausages** [comment]
> Redacted has had a gazelle based API for a while which Lidarr has supported for a while. Is this somehow different?
https://github.com/lidarr/Lidarr/issues/1127#issuecomment-614303443

Yes, Redacted API sub-classes the Gazelle API. There are endpoints which are unreachable without the use of the API keys. Just wanted to clarify this for whoever will be stumbling on this in the future.
