### ISSUE TITLE
Queue is not being populated

### ISSUE THREAD

**Issue by timmehtimtims** [Lidarr/Lidarr#1128]
Downloads are being added to NZBGet but are not being added to Lidarr queue. Downloads sitting in download folder and are not being renamed/moved.  

**Logs**
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/4493069/Lidarr.debug.txt)

**System info:**
 - Lidarr Version: 0.7.1.1381
 - Operating System Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

**Additional context**
I have reinstalled lidarr but this has not helped. I have manually refreshed the queue several times but it is not syncing. It is still sending downloads to NZBget, but failing to add them to the queue.

[AB#220](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/220)

**Comment by cwilcoxc** [comment]
Possibly a more useful set of logs:
[Lidarr.debug (1).txt](https://github.com/lidarr/Lidarr/files/4493728/Lidarr.debug.1.txt)

**Comment by bakerboy448** [comment]
No recent reports; presumably fixed between v0.7.1 and v1.
can reopen if needed
