### ISSUE TITLE
Mono 6.8.0.105 crash / * Assertion: should not be reached at interp-stubs.c:123

### ISSUE THREAD

**Issue by springjools** [lidarr/Lidarr#1130]
**Describe the bug**

Started lidarr from command shell. Get some instances of database is locked.  There is a queued update all task from yesterday, and database locks out with some artists, I think always the same. Beethoven for instance. System load is now about 4-8 while lidarr is doing this task, lockout could be because of IOWAIT.

But mono crashes anyway with this message: * Assertion: should not be reached at interp-stubs.c:123

**To Reproduce**
See above.
**Expected behavior**

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: arm debian buster (rpi 4 with 4 gb mem running raspbian buster 10)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono version 6.8.0.105

**Additional context**
Launching with user lidarr, home is at /var/lib/lidarr. Data folder is at /media/despina/var/lidarr/Lidarr
first is on 32 Gb sd-card, second is local WD-Red 3 Tb with good io-performance. System also has other stuff like kodi and deluge, but kodi was shut down at the time of this crash. Also runs under a VPN constantly.

Std out:
[lidarr.log](https://github.com/lidarr/Lidarr/files/4521347/lidarr.log)

std.err:
[lidarr.err.log](https://github.com/lidarr/Lidarr/files/4521354/lidarr.err.log)

mono crash json:
[mono_crash.0.2.json.log](https://github.com/lidarr/Lidarr/files/4521352/mono_crash.0.2.json.log)

(Files were give .log ending because github doesn't support json or .err files)

**Comment by ta264** [comment]
I believe this got fixed by dietpi
