### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by BluDragyn** [lidarr/Lidarr#1131]
**Is your feature request related to a problem? Please describe.**
No, but the white is a lot to take in sometimes.

**Describe the solution you'd like**
To see the white backgrounds replaced with a darker color. Ideally having a toggle in settings, for those who prefer a lighter colored background.

**Describe alternatives you've considered**
Currently using the Dark Reader add-on, but it would be nice to see it native

**Additional context**
n/a

**Comment by Qstick** [comment]
No plans of this anytime soon, use the themes available from places like https://github.com/gilbN/theme.park
