### ISSUE TITLE
Download Client Deluge missing Url Base option.

### ISSUE THREAD

**Issue by heathsanders** [lidarr/Lidarr#1132]
**Describe the bug**
When adding Deluge as a Download Client there is no option for adding URL Base information, therefore getting the following error: Unknown exception: HTTP request failed: [401:Unauthorized] [POST] at [https://dedarkness.lw829.usbx.me:443/json]

In order to for this to work I would need to add a URL Base of /deluge just like Sonarr does in it's default Deluge Download Client.

**Expected behavior**
Adding a URL Base option would inject the URL Base after the port and would look like this: [https://dedarkness.lw829.usbx.me:443/deluge/json] (note the deluge/ after the port)

**Screenshots**
![delugeSonarr](https://user-images.githubusercontent.com/36489046/80312602-33669000-87a3-11ea-8eeb-db6155579f48.jpg)

**Logs**

**System info (please complete the following information):**
This has been tested on the following:
 - Lidarr Version: 0.7.1.1381
 - Operating System Windows

 - Lidarr Version: 0.7.1.1381
 - Operating System Unraid 6.8.3

**Comment by ta264** [comment]
Press show advanced settings

**Comment by ta264** [comment]
Uh should have read all the way

**Comment by heathsanders** [comment]
Actually, I should have seen the "advanced settings". I clicked that the the URL Base option is now displayed and I was able to successfully add Deluge.

**Comment by ta264** [comment]
Haha assumed you'd seen it since it was in the screenshot 😂
