### ISSUE TITLE
Lidarr not moving files

### ISSUE THREAD

**Issue by Miloune** [lidarr/Lidarr#1133]
Hello,

My Lidarr isn't moving downloaded files when importing to library.
Checking log and see nothing wrong. Can you help me on this please ?

In the logs, it seems it does a copy instead of moving file:
`20-4-28 11:22:15.6|Debug|TrackFileMovingService|Copying track file: /mnt/musics_downloaded/Lindsey Stirling - Shatter Me [Deluxe Edition] (2014) FLAC/15. Take Flight (Orchestral Version).flac to /mnt/multimedia/Musiques/Lindsey Stirling/Shatter Me (2014)/15 - Take Flight (orchestral version).flac
20-4-28 11:22:15.6|Debug|DiskTransferService|Copy [/mnt/musics_downloaded/Lindsey Stirling - Shatter Me [Deluxe Edition] (2014) FLAC/15. Take Flight (Orchestral Version).flac] > [/mnt/multimedia/Musiques/Lindsey Stirling/Shatter Me (2014)/15 - Take Flight (orchestral version).flac]`

File permission:
`-rw-rw-rw- 1 root root 29872068 Apr 28 11:21 15. Take Flight (Orchestral Version).flac
`
Directory permission:
`drwxrwxrwx 2 root root 4096 Apr 28 11:21 Lindsey Stirling - Shatter Me [Deluxe Edition] (2014) FLAC`

Process started as root:
`root       946  0.4 12.7 2252004 267388 ?      Sl   Apr27   5:41 /usr/bin/mono Lidarr.exe`

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Debian
 - Mono version: 5.18.1.0

Logs file:
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/4545611/Lidarr.debug.txt)

**Comment by ta264** [comment]
Lidarr always copies torrents so you can seed.
