### ISSUE TITLE
"Circle" character in artist possibly causing issue

### ISSUE THREAD

**Issue by Skirge01** [lidarr/Lidarr#1135]
**Describe the bug**
There appears to be an issue pulling album info when an artist on Musicbrainz has a "circle" character, such as the case with "Coverdale • Page" (found here:  https://musicbrainz.org/release-group/ddcc4469-d08a-39a2-a263-f5f47771e9a8).  Lidarr pulls down the artist's general info about the group, but cannot seem to grab any album info.

**To Reproduce**
1. Add "Coverdale Page" as an artist
2. Click on Coverdale Page artist
3. View count of "0" albums for everything

**Expected behavior**
The artist should be added, as should all relevant albums from Musicbrainz.

**Screenshots**
![2020-04-28 19 58 24](https://user-images.githubusercontent.com/16962405/80549231-ab42df00-898a-11ea-9ab4-817d9698da87.jpg)

**Logs**
Can provide full logs, if necessary, but this is the section I noticed with tracing turned on:
20-4-28 19:19:48.9|Debug|Parser|Attempting to parse track info using directory and file names. Coverdale • Page
20-4-28 19:19:48.9|Debug|Parser|Parsing string 'Coverdale • Page AlbumArtSmall.jpg'
20-4-28 19:19:48.9|Trace|Parser|(?<trackNumber>\d*){0,1}([-| ]{0,1})(?<artist>[a-zA-Z0-9, ().&_]*)[-| ]{0,1}(?<trackName>[a-zA-Z0-9, ().&_]+)
20-4-28 19:19:48.9|Debug|Parser|Track Parsed. Coverdale -  - 0:[Unknown Track] : 

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.7.03190

**Additional context**
If this is the only artist with a "circle" character in the name, then it may not be worth the effort to fix this, as the sole album they released is also listed under "David Coverdale".  However, if there are others with such a character, this could be a bigger issue.

**Comment by ta264** [comment]
Albums in lidarr show under the first listed artist, in this case Coverdale.
