### ISSUE TITLE
Album from musicbrainz is not showing up

### ISSUE THREAD

**Issue by Elandril** [lidarr/Lidarr#1136]
**Describe the bug**
The album [Devotional](https://musicbrainz.org/release-group/948a2300-e58b-3af1-9143-97b94bd04b34)  from [Depeche Mode](https://musicbrainz.org/artist/8538e728-ca0b-4321-b7e5-cff6565dd4c0) is not showing in Lidarr, although the metadata profile (Albums+EP; Studio+Live+Compilation; Official)  would fit. Other releases in the "Albums + Live" category show up, e.g. [One Night in Paris](https://musicbrainz.org/release-group/15095ea0-35f8-3f0a-8422-95a9074aaf70) or [101](https://musicbrainz.org/release-group/54f99ac7-62bc-33a4-a49c-51bed2bd119e).

**To Reproduce**
1. Add artist "Depeche Mode" with metadata profile "Albums" (see screenshot).
2. See that Devotional is missing.

**Expected behavior**
The Album + Live entry "Devotional" should be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/8216235/80603665-03342100-8a31-11ea-94cc-74755d4a37ea.png)

**Logs**
20-4-29 15:33:32.6|Info|RefreshArtistService|Updating Info for Depeche Mode
20-4-29 15:33:32.8|Info|RefreshAlbumService|Updating Info for Devotional
20-4-29 15:33:32.8|Warn|RefreshAlbumService|Album [948a2300-e58b-3af1-9143-97b94bd04b34][Devotional] not found in metadata and is being deleted
20-4-29 15:33:33.0|Info|RefreshAlbumService|Updating Info for Video Singles Collection
20-4-29 15:33:33.0|Warn|RefreshAlbumService|Album [a3eb6c3e-40f0-41d2-b7ef-63cb4b6545fe][Video Singles Collection] not found in metadata and is being deleted
20-4-29 15:33:33.0|Info|RefreshAlbumService|Updating Info for The Videos 86>98
20-4-29 15:33:33.0|Warn|RefreshAlbumService|Album [354f0d5a-5738-4738-b9e6-79a690dd5ae4][The Videos 86>98] not found in metadata and is being deleted

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: FreeBSD
 - mono Version: 5.10.1.57

**Additional context**
-

**Comment by ta264** [comment]
It's a DVD video release.  These are excluded - only audio tracks are dealt with by lidarr.
