### ISSUE TITLE
Unmapped Files Mass Delete Button

### ISSUE THREAD

**Issue by JoshDrummReid** [lidarr/Lidarr#1137]
In the Unmapped files Section could you make it selectable and add a function to mass delete files you don't want to keep,

Thank you!

**Comment by Kedryn** [comment]
I saw a merge about that in mid 2019, and i thought it was already there, but it's not.
Plus, i seem to not be able do delete not-existing-anymore unmapped files from the list even one by one.

I'm using nightly 0.7.1.173 but this problem is present since i started using Lidarr

**Comment by Qstick** [comment]
Dupe #1060
