### ISSUE TITLE
{Bug} Unable to create {Album type} folders

### ISSUE THREAD

**Issue by thejasonparker** [lidarr/Lidarr#1140]
**Describe the bug**
For each artist I would like to have their work organised into 'Album Type' so it would look something like this...

Music/Artist/Album/Album 1 (2020)
Music/Artist/Album/Album 2 (2019)
Music/Artist/EP/EP (2020)
Music/Artist/Single/Single(2020)
 
So to do this I added the {Album Type} to the start of the 'Album Folder Format' field like this...
 
{Album Type}/{Album Title} ({Release Year})
 
But when I download any music or try run a 'rename' process it does not create the 'Album Type' folder structure but tags it onto the front of the title like this...
 
Music/Agent Orange/EP+Agent Orange (1980)
 
...when it should be like this...
 
Music/Agent Orange/EP/Agent Orange (1980)
 
I have checked all the file permissions and everything is ok and tried to replace the forward slash with a backslash but nothing seems to fix the issue.

Am I simply missing something?

Is this a bug or possibly a missing feature?

Thanks in advance for any help / advice - Jason

**Comment by ta264** [comment]
I think this might work if you put it into the track format and not the album folder format

**Comment by thejasonparker** [comment]
Thanks for the idea @ta264 

I tried adding this '{Album Type}/{Album Title} ({Release Year})/{track:00}. {Track Title}' to the 'Standard Track Format' but when processed it duplicates the Album Title twice like this...

/Artist/Album 1 (2020)/Album/Album 1 (2020)

I then tried to remove the 'Album Folder Format' or replace it with {Album Type} but I sadly get the following error... 

Invalid Format
'Album Folder Format' should not be empty.
Must contain Album title

It looks like it's not possible without some changes to Lidarr :(

**Comment by ta264** [comment]
You'd need to disable album folders for the artist in question

**Comment by thejasonparker** [comment]
Yes, yes, yes! I've did a quick test and it worked :)

 Thank you for all the help @ta264
