### ISSUE TITLE
Lidarr - Rutracker/Jackett  -- Unable to connect to indexer issue

### ISSUE THREAD

**Issue by Jrswitchblade** [lidarr/Lidarr#1142]
## Support / Questions

Please use https://discord.gg/8Y7rDc9 for support. Support requests or questions will be redirected to discord and the issue will be closed.

### System Information/Logs

**Lidarr Version:**
Version
Lidarr 0.7.1.1381

**Operating System:**
Ubuntu 20.04 LTS

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono 6.8.0.105

**Link to Log Files (debug or trace):**
https://pastebin.com/WvM3twAZ

**Browser (for UI bugs):**

**Comment by ta264** [comment]
That's your jackett timing out, not a lidarr issue
