### ISSUE TITLE
Spotify list import does not work when multiple playlists are selected

### ISSUE THREAD

**Issue by jlasky** [lidarr/Lidarr#1143]
**Describe the bug**
When importing a Spotify playlist, if all of the playlists are selected then none of my playlists will import. If I uncheck all but one of them then that one will be imported. Then, after that one list is done importing, I have to uncheck the one that just got imported and then check the next playlist.

**To Reproduce**
1. Go to "Settings"
2. Click on "Import Lists"
3. Click on "Add List"
4. Click "Spotify Playlist"
5. Click "Authenticate with Spotify"
6. Click "Save"

**Expected behavior**
I expect each of my many playlists to be imported into Lidarr but none of them get imported.

**Screenshots**

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Docker (unRAID, docker made by linuxserver)
 - mono (macOS/Linux) Version: 5.20.1

**Additional context**
Importing a single playlist at a time works, its just multiple playlists in sequence that don't work.

**Comment by ta264** [comment]
Please post some logs

**Comment by jlasky** [comment]
Actually, I think that this was a problem from Spotify - I've been having issues with it all day. It is working now.
