### ISSUE TITLE
Import List Spotify - Unable to connect to Import List

### ISSUE THREAD

**Issue by JezF7** [lidarr/Lidarr#1144]
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/4601512/Lidarr.txt)
When trying to get Spotify Album Import List get an error once Agree button is clicked. The agree button goes back to Authenticate and doesn't allow saving.

Error is: "Unable to connect to import list, check the log for more details"

The steps to reproduce for me are:
1. Go to Settings -> Import List.
2. Click the plus sign in the window to start the Import List configuration window.
3. Select "Spotify Saved Albums" for the configuration window.
4. Click the Authenticate button in the window that comes up.
5. Click Agree after logging into Spotify to allow Lidarr to access Spotify.
6. Go back to the Import List configuration window and the failure comes up.

I have attached the Logs.

**Comment by ta264** [comment]
Fix your jackett issues and post a new log, far too many exceptions to wade through to see what the issue could be

**Comment by JezF7** [comment]
I got the issue to repeat multiple times and removed all the Jackett issues. Fixing Jackett for one failing indexer would take days for the error to be overwritten so it was just easier to look at the log and remove all references to Jackett in the log.

The new log is attached.
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/4602279/Lidarr.txt)

**Comment by ta264** [comment]
Looking at the log I think you either have a super old mono (5.10 is minimum) or a broken install. Jump on the discord if you're still having issues
