### ISSUE TITLE
Media Management gives "There was an error loading this page"

### ISSUE THREAD

**Issue by kahn10** [lidarr/Lidarr#1152]
**Describe the bug**
When visiting Media Management under settings, A graphic of a theoatmeal.com cartoon comes up with the message "There was an error loading this page". This has happened with the last several versions.

I have tried Chrome, Firefox, and Microsoft Edge, both on Windows and on OS X, the problem occurs in all systems.

The problem occurs with an existing database, and with a fresh one.

The same error screen has appeared in the History tab in the past, but is not happening currently.

on the bottom of the page, the following appears:
```
Details:
TypeError: Cannot read property 'localeCompare' of undefined

    in a
    in a
    in h
    in div
    in div
    in div
    in t
    in a
    in a
    in h
    in Connect(a)
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in a
    in CI
    in a
    in a
    in h
    in t
    in t
    in a
    in _7
    in div
    in div
    in a
    in a
    in h
    in withRouter(Connect(a))
    in t
    in n
    in i
    in h
    in f
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1687 (Docker: hotio)
 - Operating System OS X 10.13.6
 - .net Framework (Windows) or mono (macOS/Linux) Version: Unknown

**Comment by ta264** [comment]
I can't replicate this, let me know if it's still an issue

**Comment by exilewolf** [comment]
**Describe the bug**

Can confirm this is still an issue.

My experience is more or less the same as above with a fresh install on Ubuntu 20.04. Once it errors I get the added fun that the import page will throw an error if I try to import anything else when processing. 

Side note: When I click the import button the error will pop about 15ish seconds after, then after about 60 seconds it will start importing some of the selected shows in the background but not all.

First Error : 

TypeError: Cannot read property 'map' of undefined

    in r
    in T
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in r
    in lI
    in r
    in r
    in T
    in t
    in t
    in r
    in r
    in t
    in t
    in r
    in E7
    in div
    in div
    in r
    in r
    in T
    in withRouter(Connect(r))
    in t
    in n
    in i
    in T
    in c
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e

Error on Retry : 

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in r
    in T
    in div
    in div
    in div
    in t
    in r
    in r
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in r
    in lI
    in r
    in r
    in T
    in t
    in t
    in r
    in r
    in t
    in t
    in r
    in E7
    in div
    in div
    in r
    in r
    in T
    in withRouter(Connect(r))
    in t
    in n
    in i
    in T
    in c
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e 

**System info (please complete the following information):**

- Ubuntu 20.04
- Lidarr Version 3.0.4.1052
- Mono Version 6.12.0.107

**Comment by lokiberra** [comment]
I have the same issue on the nightly Linuxserver.io docker container (0.8.0.1999)
