### ISSUE TITLE
Jackett Full Automation

### ISSUE THREAD

**Issue by DavideCampagna** [Lidarr/Lidarr#1154]
This link in Jackett:
ip:9117/jackett/api/v2.0/indexers/all/results/torznab/api?apikey=API&t=indexers&configured=true

Returns an xml file containing all configured indexers, with their categories and so on, here is an example:

````
<indexers> 
        <indexer id="anidex" configured="true"> 
                <title>Anidex</title> 
                <description> Anidex is a Public torrent tracker and indexer, primarily for English fansub groups of anime </description>
                <link>https://anidex.info/</link> 
                <language>en-us</language> 
                <type>public</type> 
                <caps> 
                        <server title="Jackett" /> 
                        <searching> 
                                <search available="yes" supportedParams="q" /> 
                                <tv-search available="yes" supportedParams="q,season,ep" /> 
                                <movie-search available="no" supportedParams="q" /> 
                                <music-search available="no" supportedParams="" /> 
                                <audio-search available="no" supportedParams="" /> 
                        </searching>
                        <categories> 
                                <category id="100010" name="♫ - Lossless" /> 
                                <category id="100009" name="♫ - Lossy" /> 
                                <category id="100011" name="♫ - Video" /> 
                                <category id="100015" name="Adult Video" /> 
                                <category id="100003" name="Anime - Dub" /> 
                                <category id="100002" name="Anime - Raw" /> 
                                <category id="100001" name="Anime - Sub" /> 
                                <category id="100013" name="Applications" /> 
                                <category id="100012" name="Games" /> 
                                <category id="100005" name="LA - Raw" /> 
                                <category id="100004" name="LA - Sub" /> 
                                <category id="100006" name="Light Novel" /> 
                                <category id="100008" name="Manga - Raw" /> 
                                <category id="100007" name="Manga - TLed" /> 
                                <category id="100016" name="Other" /> 
                                <category id="100014" name="Pictures" /> 
                                <category id="5070" name="TV/Anime" /> 
                        </categories> 
                </caps> 
        </indexer> 
        (continues with the other configured indexers...) 
</indexers>
````

Since I've discovered this I've been wondering if is possible to add a new feature. My idea is that the user should just provide the ip:port/baseurl address and the api of Jackett and then Lidarr should parse that xml in order to automatically add all the indexers from Jackett. Maybe it can even check periodically Jackett in order to add/remove indexers according to the changes made in Jackett.
Hope you'll like this and thanks for your amazing job.

[AB#224](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/224)

**Comment by Turbogame** [comment]
This is currently possible with [nzbhydra2 ](https://github.com/theotherp/nzbhydra2)if you have set up. It can load up all Jackett indexers after supplying your Jackett api. Doesn't check periodically for new indexers added, but it will suffice for indexers that periodically go offline as each indexer will be loaded individually into the program. 

In Lidarr, you only need to add a torznab (or newznab or both) indexer for your nzbhydra2 installation. Works great for reliable indexers! Good-luck!

**Comment by supersnellehenk** [comment]
Jackett has an API endpoint `ip:port/torznab/all` made for this. No need to address them all individually. Yes it takes longer to query it because it queries all your indexers at once, but it's either all at once or all individually which takes near the same amount of time (for me at least). Plus it reduces the hassle of needing to update your indexers when you add/delete one.

**Comment by DavideCampagna** [comment]
I know, but unfortunately that endpoint returns only the first 100 results and, since Jackett checks indexers sequentially, this means it doesn't check them all always

**Comment by supersnellehenk** [comment]
I'm not sure about the checking part, but I just ran that endpoint and it returns 100+ results. For my query I ran it was 199 to be exact. I don't know which indexers you're using in Jackett itself, but some don't return more than 100 results, like RARBG.

**Comment by bakerboy448** [comment]
No plans at this time

among other things prowlarr is out
