### ISSUE TITLE
Bad tagging with ID3 Genres

### ISSUE THREAD

**Issue by lopiv2** [Lidarr/Lidarr#1155]
## Support / Questions

Please use https://discord.gg/8Y7rDc9 for support. Support requests or questions will be redirected to discord and the issue will be closed.

### System Information/Logs

**Lidarr Version:**

**Operating System:**

**.net Framework (Windows) or mono (macOS/Linux) Version:**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Description of request and what problem are you looking to solve?

When tagging mp3 files, Lidarr is taggin genres, some with right names. I.E: Rock, House, etc.. But there are another genres which Lidarr is tagging with numbers: 35,45, etc...
After all, when you see them in Jellyfin for example, ordered by genres, you have a lot of genre numbers, not displaying names.

### Other Information

[AB#226](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/226)

**Comment by phit42** [comment]
I have the same issue and I believe it is sth to do with their representation in the id tag, as I suspect the numbers to be from ID3v1 format [https://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres](https://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres). In my case MediaMonkey does not seem to understand them and shows them as numbers as well.

**Comment by tehniemer** [comment]
I'm experiencing this as well, quite annoying.

**Comment by whi-tw** [comment]
+1 iTunes doesn't understand numbers or semicolons, so end up with just a string of nonsense

**Comment by bakerboy448** [comment]
Folks, a simple +1 on the OP would suffice.

Unproductive comments saying me too or +1 are just that unrproductive.

Not to mention no information about the Lidarr version was provided

Is this still an issue on V0.8 nightly builds?

**Comment by whi-tw** [comment]
> Unproductive comments saying me too or +1 are just that unrproductive.

Agreed, but only one of the three comments is not actually adding at least some extra context to the scale of the affected clients.

> Is this still an issue on V0.8 nightly builds?

I'm on 0.7.2.1878 - are you expecting some kind of change after this? I've had a look through the recent commits and none of them make any reference to `genre` - in fact, the last commit relating to genre was 2 Aug 2019.

**Comment by Pectojin** [comment]
I am still seeing this happen on v0.8.1.2135

@bakerboy448 What info would be needed to make meaningful progress in diagnosing this issue?

I have many songs tagged with genre fields such as
```
genre - Alternative Metal;40;79;137;9;Nu Metal;Pop Rock;Post-Grunge;17
unknown - musicbrainz-trackid=dbbceafa-b2c3-4930-9e65-f0b0f33cb45f
```

I am unclear on whether or not it's supposed to list this many genres semicolon separated, but the numbers definitely do not make sense. When comparing the tagging with the MusicBrainz entry it's clear that something is breaking in between the source and the result: https://musicbrainz.org/recording/dbbceafa-b2c3-4930-9e65-f0b0f33cb45f/tags

I have other songs that Lidarr is correctly producing many genre fields for (and without numbers):
 ```
genre - Acid Jazz
genre - Blues
genre - Contemporary Jazz
genre - Contemporary R&B
genre - Downtempo
genre - Electronic
genre - Funk
genre - Funk Soul
genre - Hip Hop
genre - Jazz
genre - Pop
genre - R&B
genre - Soul
unknown - musicbrainz-
trackid=2d419b8b-88b2-4611-a8de-8cbef7f88d9d
```
https://musicbrainz.org/recording/2d419b8b-88b2-4611-a8de-8cbef7f88d9d/tags

In this second example it's also very clear that the tags aren't just fetched from the recording entry, but perhaps some combination of recording + album + artist.

I've reproduced the issue and attached the output of `Lidarr.trace.txt` below. 

Steps to reproduce:
- Find song with broken tags, e.g. inspected with `extract` (apt install extract && extract song-name)
- Remove all tags from song with `eyeD3` (apt install eyed3 && eyeD3 --remove-all song-name)
- Navigate to album in UI and click "Preview Retag" -> "Retag"

[lidarr_trace.txt](https://github.com/Lidarr/Lidarr/files/7237802/lidarr_trace.txt)

**Comment by kmgear** [comment]
Repro.

Lidarr Version: 0.8.1.2135

OS: Ubuntu 20.04.3 LTS

mono: 6.12.0.122

Tagging file of type: MP3 - 2.0 - 161 kbps - 44.1kHz

Genre extra data:
Alternative Dance;4;52;Funk Rock;131;Indie Rock

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/7486650/Lidarr.trace.txt)
[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/7486652/Lidarr.debug.txt)

**Comment by ta264** [comment]
My guess is this is because you have id3v1 tags and that's how they're done for id3v1. If anyone wants to dig into it, please join the discord channel.

**Comment by Pectojin** [comment]
I'm not sure I understand. I wipe all the tag metadata and let Lidarr set whatever it wants. Can I make Lidarr not use id3v1 if that's the problem?
