### ISSUE TITLE
Feature Request: Import from local system?

### ISSUE THREAD

**Issue by Chris230291** [Lidarr/Lidarr#1156]
Hello. Not sure how difficult this would be... It would be nice to be able to import/transfer music from the machine we are accessing the web UI from. Its not a huge deal but would save us having to first transfer files from my local machine to my server.

[AB#225](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/225)

**Comment by didyouexpectthat** [comment]
What I do is I mount a CIFS/SMB share onto my system and then tell Lidarr to 'import' that directory. It's totally possible. /music/ is actually a mountpoint for somewhere else. 
![image](https://user-images.githubusercontent.com/1329077/82822999-98251100-9e5b-11ea-8de4-b610f80a021e.png)

**Comment by bakerboy448** [comment]
No plans
