### ISSUE TITLE
Add support for API post-processing (like with nzbToMedia)

### ISSUE THREAD

**Issue by didyouexpectthat** [lidarr/Lidarr#1158]
**Is your feature request related to a problem? Please describe.**
Not necessarily with Lidarr. I noticed https://github.com/clinton-hall/nzbToMedia claimed support for Lidarr and I love the tool for Sonarr/Radarr/SickChill/CouchPotato/etc... I configured it to work but I am getting the errors described in this thread: https://github.com/clinton-hall/nzbToMedia/issues/1655
nzbToMedia passes a path to software like Radarr/Sonarr to indicate where those programs should look for downloaded content to post-process (move to proper folders from a completed download folder, rename based on rename rules) but unfortunately, `api/v1/command` doesn't support a command like Rename. 

**Describe the solution you'd like**
Add support for a command like `Rename` where Lidarr is passed a local path and Lidarr will begin to process the file(s) inside. 

**Describe alternatives you've considered**
I considered that Lidarr already has torrent/nzb client monitoring and checks every minute to check the status, however, at the moment of writing, whatever I've configured in Lidarr doesn't grab files from my downloaded folder and move them to their final destination, so while nzbget returns success, the files never Move. 

**Additional context**
None to share at this time.

**Comment by ta264** [comment]
I think you're looking for `DownloadedAlbumsScanCommand`
