### ISSUE TITLE
Add support for albums with multi media

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#116]
Multi disc, etc..

- [x] Back-end Skyhook Integration
- [x] V1 API Support
- [x] Parse Disc Number from Tags
- [x] Add Disc Count Column on Artist Detail Page
- [x] Parse releases with multi-disc `-2CD-`
- [x] Add Renaming options based on Medium

**Comment by LennyPenny** [comment]
That link doesn't work:(

**Comment by Qstick** [comment]
Yes, we know. Thanks. Use Discord for support
