### ISSUE TITLE
Missing release for artist from MusicBrainz

### ISSUE THREAD

**Issue by mattgoldspink** [lidarr/Lidarr#1162]
**Describe the bug**
I've added the artist DJ Kentaro but it's missing one release which is listed on MusicBrainz. I've checked logs and events and don't see anything for that release, but all other releases are there. I created a new profile that selects everything too just to make sure I'm not skipping it due to missing Profile options.

**To Reproduce**
1. Create a profile which includes everything
2. Add "DJ Kentaro" as a new artist with this profile
3. Expand all albums and look for "Solid Steel Presents: DJ Kentaro on the Wheels of Solid Steel"

**Expected behavior**
All releases from MusicBrainz for DJ Kentaro should appear - see https://musicbrainz.org/artist/e5e9a7c1-9967-4385-b167-ff65a67779df?all=1

**Screenshots**
From Lidarr:
![image](https://user-images.githubusercontent.com/415690/83325628-92696a00-a265-11ea-85a9-c4162f8147d8.png)
From Musicbrainz:
![image](https://user-images.githubusercontent.com/415690/83325637-aad98480-a265-11ea-8d63-ce035364ae8b.png)

**Logs**
```
20-5-30 10:54:27.4|Info|RefreshArtistService|Updating Info for DJ Kentaro
20-5-30 10:54:27.9|Info|RefreshAlbumService|Updating Info for Trust
20-5-30 10:54:28.2|Info|RefreshAlbumService|Updating Info for Contrast
20-5-30 10:54:30.1|Info|MediaCoverService|Downloading Cover for [1deb47b4-2d7b-4188-b148-d742e287f6af][Contrast] https://coverartarchive.org/release/e5f45a62-919e-42b1-ae67-580d34d0abf6/8545803228.jpg
20-5-30 10:54:32.7|Info|RefreshAlbumService|Updating Info for Free
20-5-30 10:54:32.9|Info|RefreshAlbumService|Updating Info for Enter
20-5-30 10:54:34.7|Info|MediaCoverService|Downloading Cover for [c257f757-c286-3f59-9602-66dcf5fe1c74][Enter] https://coverartarchive.org/release/1a867983-07db-41e2-9d15-a4dfe499cbbc/6195488355.jpg
20-5-30 10:54:36.9|Info|RefreshAlbumService|Updating Info for "Nama" Live Mix
20-5-30 10:54:37.2|Info|RefreshAlbumService|Updating Info for Harvest Dance
20-5-30 10:54:37.5|Info|RefreshAlbumService|Updating Info for Tuff Cuts
20-5-30 10:54:38.1|Info|DiskScanService|Scanning DJ Kentaro
20-5-30 10:54:39.8|Info|DiskScanService|Completed scanning disk for DJ Kentaro
20-5-30 10:54:39.9|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-5-30 10:54:39.9|Info|ExistingLyricImporter|Found 0 existing lyric files
20-5-30 10:54:39.9|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-5-30 10:54:39.9|Info|ExistingExtraFileService|Found 0 extra files
20-5-30 10:56:23.9|Info|RssSyncService|Starting RSS Sync
20-5-30 10:56:25.0|Info|DownloadDecisionMaker|Processing 89 releases
20-5-30 10:56:28.2|Info|RssSyncService|RSS Sync Completed. Reports found: 89, Reports grabbed: 0
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Linux raspberrypi 4.19.97-v7+
 - .net Framework Version: Mono Version 6.8.0.123

**Comment by mattgoldspink** [comment]
Interestingly I see it available here: https://api.lidarr.audio/api/v0.4/artist/e5e9a7c1-9967-4385-b167-ff65a67779df

Trace logs for reference:
[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/4705460/Lidarr.trace.txt)

**Comment by ta264** [comment]
Did you refresh the artist

**Comment by ta264** [comment]
Oh all the releases have unknown status so they're filtered out. Change one to official on musicbrainz, wait for the lidarr API sync around 5 past the hour and try again

**Comment by mattgoldspink** [comment]
I see thanks - I just made the edit on musicbrainz so hopefully it'll be approved soon. I'll close the ticket for now.
