### ISSUE TITLE
Complete Download Handling - Remove

### ISSUE THREAD

**Issue by YaibaToKen** [lidarr/Lidarr#1163]
**Is your feature request related to a problem? Please describe.**
Currently, Lidarr does not remove downloads from the download clients. This can easily lead to cluttering and lack of drive space for new downloads. 

**Describe the solution you'd like**
I'd like it if we could get an option, similar to Sonarr and Radarr, to remove completed downloads that were added by Lidarr to the download client.

**Additional context**
Example from Sonarr:
![image](https://user-images.githubusercontent.com/9133736/83774480-a524da00-a67d-11ea-81a0-0de68b083ff2.png)
Example from Radarr:
![image](https://user-images.githubusercontent.com/9133736/83774698-f2a14700-a67d-11ea-96da-f2459ec1321e.png)

**Comment by Qstick** [comment]
Lidarr
![Screenshot_20200604-111554](https://user-images.githubusercontent.com/376117/83775375-d89f3e80-a654-11ea-86a7-34d4e63411ea.png)

**Comment by YaibaToKen** [comment]
I'm so so very sorry... I thought I had turned on advanced settings already... Thank you for the info and sorry for wasting your time.
