### ISSUE TITLE
Broken library after changing root folder ("Loading track files failed")

### ISSUE THREAD

**Issue by rubbo898** [lidarr/Lidarr#1166]
**Describe the bug**

Hi everyone, I'm have some issue wihle trying to move my whole library from one root folder to a different one.

**To Reproduce**

Specifically I've set everything up (manually added artist via "import" section, run the scan of the library and last step added the unmapped files).
My idea was then to change the root folder of the whole library from the "mass editor" section:

1. Check all the artists
2. modify path via root folder option

The task seems to have correctly move all the folder and files (both lidarr and manual check gave me positivi feedback), but every single artist doesn't show up any albums (or similar), returning instead the following meessage: "Loading track files failed"

**Expected behavior**

Artists sections working as usual.
I've "fixed" going back to the original root path via the same procedure. 

**Screenshots**

**Logs**

https://pastebin.com/gLq9gpUc

**System info (please complete the following information):**

- Lidarr Version 0.7.1.1381 (docker)
- OS Unraid
- Mono Version 5.20.1.34

**Additional context**

**Comment by ta264** [comment]
Dupe, fixed in nightly
