### ISSUE TITLE
A new Lidarr pre-release due? Currently on 0.7.1.1381

### ISSUE THREAD

**Issue by DejaVu** [lidarr/Lidarr#1169]
I'm on the develop branch of Lidarr and although I can see there has been tonnes of activity, my version has not been update since September 2019!? Last year Lidarr was released quite regularly. 

Any chance of a new 'Pre-Release'?

**Comment by Qstick** [comment]
Yes it's coming eventually, don't open GitHub issues for this please. Feel free to come badger us on discord. We've slowed a bit on Lidarr with development of Radarr V3 and Readarr
