### ISSUE TITLE
Missing Releases from Artist

### ISSUE THREAD

**Issue by michaeldrouin** [lidarr/Lidarr#1170]
**Describe the bug**
There have been other bugs regarding missing releases from artists, but this one is not fixable by previous updates or suggestions. It introduces inconsistency on when certain releases want to show or not. 

For example: this release shows up: https://musicbrainz.org/release/aeecfb8f-8dbf-46ab-a47a-df6e9947f6b2
But this one does not: https://musicbrainz.org/release/5821bb2e-d294-48bb-a046-fe00ec006a43

**To Reproduce**
1. Create new metadata profile to include every release type
2. Add artist: `Anabolic Frolic`
3. Only 3 releases show up (Chapter One, Chapter Three, and Chapter Eight)
4. Many other releases from artist on MusicBrainz that are under the same release type do not show up

**Expected behavior**
I would expect all other releases from artist to show up.

**Logs**

```
20-6-23 10:06:38.2|Info|RefreshArtistService|Updating Info for Anabolic Frolic
20-6-23 10:06:38.2|Debug|SkyHookProxy|Getting Artist with LidarrAPI.MetadataID of f409c6c1-fd83-4ec2-8a4d-23f5a3263246
20-6-23 10:06:38.4|Debug|ArtistMetadataRepository|1 artist metadata up to date; Updating 0, Adding 0 artist metadata entries.
20-6-23 10:06:38.4|Debug|RefreshArtistService|[f409c6c1-fd83-4ec2-8a4d-23f5a3263246][Anabolic Frolic] 0 albums up to date. Adding 0, Updating 3, Merging 0, Deleting 0.
20-6-23 10:06:38.4|Info|RefreshAlbumService|Updating Info for Happy 2b Hardcore: Chapter One
20-6-23 10:06:38.4|Debug|SkyHookProxy|Getting Album with LidarrAPI.MetadataID of badbbb88-9035-317d-b321-512ec2331041
20-6-23 10:06:38.6|Debug|ArtistMetadataRepository|10 artist metadata up to date; Updating 2, Adding 0 artist metadata entries.
20-6-23 10:06:38.6|Debug|RefreshAlbumService|[badbbb88-9035-317d-b321-512ec2331041][Happy 2b Hardcore: Chapter One] 1 albumreleases up to date. Adding 0, Updating 0, Merging 0, Deleting 0.
20-6-23 10:06:38.7|Debug|RefreshAlbumReleaseService|[e0e505d0-186d-49d2-9e0c-34982d380604][Happy 2b Hardcore: Chapter One] 16 tracks up to date. Adding 0, Updating 0, Merging 0, Deleting 0.
```

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System: Ubuntu Server 18.04
 - mono Version: 5.20.1.34

**Comment by ta264** [comment]
The second release you mention is attibuted to various artists and not anabolic frolic https://musicbrainz.org/release-group/9e600bf5-7e5d-35c9-8880-6006a4ce1fca

**Comment by michaeldrouin** [comment]
ah. that one may have been a bad example. but you see it on other artists who's releases are attributed to them. one example (and this is going to sound really bad...) is Charles Manson (https://musicbrainz.org/artist/db3d7002-d9e8-4803-82c4-d85dad3f29bb). Two of his albums for example so not show up in Lidarr (https://musicbrainz.org/release/523e5fa0-fc55-4ed9-bb78-07ec40d07f89 and https://musicbrainz.org/release/a857fe43-5d2b-4b9c-bedb-a5efe02688e8)

**Comment by ta264** [comment]
Those two both have the standard issue that there's no release status on musicbrainz.  Edit them to be correct and they'll show up after an hour or so in lidarr.

https://musicbrainz.org/release-group/70436e86-46b1-3afe-9185-b9d52656c6f2
https://musicbrainz.org/release-group/e985fa44-14f7-49ca-93ed-23550853afef
[they both say unknown in the release table in the links above]
