### ISSUE TITLE
Unable to parse albums from release name

### ISSUE THREAD

**Issue by crafty35a** [lidarr/Lidarr#1176]
Lidarr is unable to parse the new album by HAIM, "Women in Music Pt. III"

All releases are rejected.

**Comment by Qstick** [comment]
Need:
Lidarr Version
Examples of Releases that don't parse
Screenshot and/or Logs

**Comment by crafty35a** [comment]
Version 0.7.1.1705
The release was mentioned above (HAIM - Women in Music Pt. III) - https://musicbrainz.org/release-group/73b8f504-93e5-483d-918d-1006ca3a315c
Screenshot: (all releases are rejected with error "Unable to parse albums from release name")

![image](https://user-images.githubusercontent.com/1082003/86072400-7cf78380-ba4f-11ea-9b63-babf50174acc.png)

**Comment by crafty35a** [comment]
This appears to have been fixed at some point in the past, I'm not seeing this issue today on nightly.
