### ISSUE TITLE
add new from spotify

### ISSUE THREAD

**Issue by icf20** [lidarr/Lidarr#1179]
given that spotify have "verified artist" check mark is possible to add new from spotify not just musicbrainz 

example https://open.spotify.com/artist/7cEaR3OwxOjKvgUHDsk1Rr

tia

**Comment by ta264** [comment]
Musicbrainz is our data source, very unlikely we'd ever more to spotify.

**Comment by icf20** [comment]
@ta264 i dint say move to spotify i said " add new from spotify not just musicbrainz"
