### ISSUE TITLE
Interactive search - no matches found for album containing typographic apostrophe 

### ISSUE THREAD

**Issue by andrewladlow** [Lidarr/Lidarr#1180]
**Describe the bug**
Related to https://github.com/lidarr/Lidarr/pull/586 

If I try to search for the following album: https://musicbrainz.org/release/3621a45d-38f9-4c07-9b33-41ac828c6429 using the Redacted tracker (using the Gazelle API) I receive 0 matches, but the tracker API returns 3 matches when searching directly.

The request to the tracker shows the `’` being removed from the album name. If I remove the `’` from the regex filter in:
https://github.com/lidarr/Lidarr/blob/4a33d30883f6845df2347e85d018f9971e53e926/src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs#L12 I then receive 3 matches when searching within Lidarr again, which matches the tracker's result. The request to the tracker then shows the `’` is replaced by a `+` instead.

I'm not sure if this issue is exclusive to the tracker I'm testing with, or this single album. 

**To Reproduce**
1. Go to `Library` -> `Add New` -> `Koan` (https://musicbrainz.org/artist/7b062a11-13b4-4dfa-b379-5db98242a831)
2. Select the `Koan` artist
3. Select the `Knight’s Move` album
4. Attempt an `Interactive Search` 

**Expected behavior**
When searching for this album, we should receive 3 matches:
![3 matches](https://i.imgur.com/tylWt5g.png)

The debug logs for this request are:
```
20-7-7 21:43:20.4|Info|NzbSearchService|Searching 1 indexers for [Koan - Knight’s Move (2020)]
20-7-7 21:43:21.0|Debug|Gazelle|Gazelle authentication succeeded.
20-7-7 21:43:21.0|Debug|Gazelle|Downloading Feed https://redacted.ch/ajax.php?action=browse&searchstr=&artistname=Koan&groupname=Knight+s+Move
20-7-7 21:43:21.1|Debug|Api|[GET] /api/v1/trackFile?albumId=28: 200.OK (3 ms)
20-7-7 21:43:21.2|Debug|Api|[GET] /api/v1/track?albumId=28: 200.OK (38 ms)
20-7-7 21:43:21.4|Debug|NzbSearchService|Total of 3 reports were found for [Koan - Knight’s Move (2020)] from 1 indexers
20-7-7 21:43:21.4|Info|DownloadDecisionMaker|Processing 3 releases
20-7-7 21:43:21.5|Debug|DownloadDecisionMaker|Processing release 'Koan - Knight's Move (2020) [MP3 320]' from 'REDacted'
```

**Actual behaviour**
There are 0 matches found:
![0 matches](https://i.imgur.com/PoNVVJD.png)

The debug logs are:
```
20-7-7 21:42:16.6|Info|NzbSearchService|Searching 1 indexers for [Koan - Knight’s Move (2020)]
20-7-7 21:42:17.5|Debug|Gazelle|Gazelle authentication succeeded.
20-7-7 21:42:17.6|Debug|Gazelle|Downloading Feed https://redacted.ch/ajax.php?action=browse&searchstr=&artistname=Koan&groupname=Knights+Move
20-7-7 21:42:17.9|Debug|NzbSearchService|Total of 0 reports were found for [Koan - Knight’s Move (2020)] from 1 indexers
20-7-7 21:42:17.9|Info|DownloadDecisionMaker|No results found
```

**System info (please complete the following information):**
 - Lidarr Version: `0.7.1.1714`
 - Operating System: Windows 10
 - .net Framework (Windows): `4.6.2`

[AB#233](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/233)

**Comment by SawkeeReemo** [comment]
I've found this to be true when searching for torrents, apparently this does not affect Usenet searches. Almost any punctuation that exists anywhere other than the end of a string breaks the search for torrents. I can reproduce this on every occurrence.

**Comment by SawkeeReemo** [comment]
Also, Various Artist searches add "VA" to the query which also breaks torrent searches. VA searches should probably be for album title only. (Over all, an option to manually change the search string upon a fail would be a welcome addition, in my opinion, until this gets ironed out.)

**Comment by crafty35a** [comment]
I can confirm that this seems to happen for every album with an apostrophe in the name. Oddly, some albums show the apostrophe replaced in the log with some odd symbols, but others do not, e.g.:
```
20-8-10 17:03:52.1|Info|NzbSearchService|Searching 2 indexers for [M83 - Hurry Up, Weâ€™re Dreaming (2011)]
20-8-10 17:07:12.6|Info|NzbSearchService|Searching 2 indexers for [U2 - All That You Canâ€™t Leave Behind (2000)]
20-8-10 17:19:25.8|Info|NzbSearchService|Searching 2 indexers for [Oh Sees - The Master's Bedroom Is Worth Spending a Night In (2008)]```

**Comment by crafty35a** [comment]
Oddly, I am able to get results for "King Gizzard & The Lizard Wizard- Infest the Rats’ Nest"

But every other album with an apostrophe that I have tested is still returning no results, including "I’m in Your Mind Fuzz" by the same band.


> Over all, an option to manually change the search string upon a fail would be a welcome addition, in my opinion, until this gets ironed out.

Agreed, this is one of only a couple things that I really miss from Headphones.

**Comment by revers59** [comment]
@ta264 Thanks for all ! any news about this ? 
same problem here with Version 0.8.0.1918

**Comment by arutkowski00** [comment]
I also have the same issue, but with a comma in album's name.

**Comment by crafty35a** [comment]
> EDIT: it's working on develop branch.

Not so for apostrophes or periods, unfortunately.

**Comment by vitiko98** [comment]
Any news? I'm missing a lot of albums because of this problem :cry:

**Comment by B1ue-W01f** [comment]
Any update on this? Took far too long for me to figure out its just flat out not handling apostrophe's - they're ridiculously common in band names and titles.

**Comment by CPU-Blanc** [comment]
Also confirming this issue is present on 0.8.1.2135.
Searching for artist `Poppin'Party` instead searches for `PoppinParty` which yields no results on torrents

**Comment by klepp0906** [comment]
seemingly affects colon's as well.
Morgan Wallen - Dangerous: The Double Album = zero results from trackers.

**Comment by mikedal** [comment]
Following up that I'm having this issue too, with a bit more info. 
If I take the failing search query for King Gizzard and the Lizard Wizard - I’m in Your Mind Fuzz:
https://redacted.ch/ajax.php?action=browse&searchstr=&artistname=King+Gizzard+the+Lizard+Wizard&groupname=Im+in+Your+Mind+Fuzz
and add the apostrophe back in:
https://redacted.ch/ajax.php?action=browse&searchstr=&artistname=King+Gizzard+the+Lizard+Wizard&groupname=I%E2%80%99m+in+Your+Mind+Fuzz
I get the expected results.

Since a previous comment mentioned that searching for these albums works with Usenet indexers, I'm wondering if #586 was necessary for those searches to work. I don't know the context around that change, but naively it seems that at least for torrent searches apostrophes need to remain in the query.

**Comment by SawkeeReemo** [comment]
Many characters like ampersands in artist names will break the search as well. I would say apostrophes in album names are the number one breaker though right now.

**Comment by StuartKicks** [comment]
I’m having this issue too. Is there anything we can do to help?

**Comment by crafty35a** [comment]
Still an issue in 2023 - many artists can't be searched at all (for torrents) e.g. U.S. Girls, Andrew W.K., etc.

**Comment by frei0** [comment]
I see Jackett recently added support for "rawsearch" capability reporting. Not sure if it works with Lidarr+RED.

**Comment by frei0** [comment]
It seems to work :) sent pull/3514
