### ISSUE TITLE
Have a Root Directory and Output Directory

### ISSUE THREAD

**Issue by tucker19** [lidarr/Lidarr#1181]
I am still using iTunes, I know I know, but currently if I want to use Lidarr I have to point the root directory to the `Automatic Import` folder of iTunes. This causes Lidarr not to actually see my library. Would it be possible to add a second option to a artist with output directory? By default it could be the same as the root directory. This would open so Lidarr is looking at iTunes Artist directories but after downloading puts them into the Auto Import one.

**Comment by ta264** [comment]
Not going to happen I don't think. Can't you just point lidarr at the iTunes library folder?

**Comment by tucker19** [comment]
Wow, no real discussion and you just close this. You can’t just point Lidarr at the iTunes folder. ITunes does not update the library when something is added to a artist directory only when it detects something new in the Automatic Import one. I explained this already. I don’t know why you so against this either?
