### ISSUE TITLE
tidal-dl (cli) as a indexer/downloader

### ISSUE THREAD

**Issue by zobe123** [lidarr/Lidarr#1184]
would be great to use Tidal (or spotify) as a automatic source, maybe you can implement, thx

**Comment by zobe123** [comment]
found a script working well from @RandomNinjaAtk

**Comment by delize** [comment]
@zobe123 can you link the script for others? 

My guess is that it is [AMA](https://hub.docker.com/r/randomninjaatk/ama)/[AMD](https://hub.docker.com/r/randomninjaatk/amd) but would be good for others to see if it is something different.

**Comment by zobe123** [comment]
Sure,
For Audio: https://github.com/RandomNinjaAtk/docker-amd
For Videos: https://github.com/RandomNinjaAtk/docker-amvd

**Comment by delize** [comment]
@zobe123 can you expand on how you are using this in conjunction with Lidarr? I don't see how this can integrate natively with Lidarr.
