### ISSUE TITLE
Album detection incorrect

### ISSUE THREAD

**Issue by ced455** [lidarr/Lidarr#1185]
**Describe the bug**
when adding the artist Hans Zimmer, the artist does not have any Album ! 

**Expected behavior**
this guy made some albums : 
https://musicbrainz.org/artist/e6de1f3b-6484-491c-88dd-6d619f142abc

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System docker

**Comment by ta264** [comment]
Fix your metadata profile if you want those different secondary types

**Comment by ced455** [comment]
Hello, Are you talking about the Metadata Provider Source ?
if not could you point me in the right direction ?

**Comment by ced455** [comment]
My bad, for anyone searching for this issue, on the artist page scroll down, you will see : 

_Missing Albums, Singles, or Other Types? Modify or Create a New Metadata Profile!_

It will redirect you in yourURL/settings/profiles

Edit the metadata profile based on the musicbrainz tags.

For Hans Zimmer i Needed to add soundtrack cause all his musics are soundtracks

Hope it helps !
