### ISSUE TITLE
Tasks recreating/spawning non-stop

### ISSUE THREAD

**Issue by delize** [lidarr/Lidarr#1186]
**Describe the bug**
Certain tasks (for example, "Rescan folders") consistently respawn, causing dozens of tasks in the queue. Leaving certain features unusable (such as manual import tasks).

**To Reproduce**
1. Have Library that has 30,000+ tracks
2. Leave Lidarr running for 24+ hours
3. ???
4. See error, issue, problem described below

**Expected behavior**
To have only one task per queue system at a time. IE: Not have several dozen repeating tasks for folder scanning.

**Screenshots**
[screencapture-lidarr-system-tasks-2020-07-13-17_24_42.pdf](https://github.com/lidarr/Lidarr/files/4915836/screencapture-net-slum-org-lidarr-system-tasks-2020-07-13-17_24_42.pdf)
![screencapture-lidarr-system-tasks-2020-07-13-17_24_42](https://user-images.githubusercontent.com/4028612/87366675-1afa4c00-c52e-11ea-8e05-5b22a0643ad5.png)
![screencapture-lidarr-system-tasks-2020-07-13-17_24_42-2](https://user-images.githubusercontent.com/4028612/87366677-1c2b7900-c52e-11ea-8440-53d9999e23a0.png)

An example of how many tasks are generated - is shown above. 

**Logs**
Link to debug logs.
[Trace - logs.zip](https://github.com/lidarr/Lidarr/files/4915847/logs.zip)

**System info (please complete the following information):**
```
Version
0.7.1.1714
Package Version
0.7.1.1714-ls12 by linuxserver.io
.NET Core
Yes
Docker
Yes
DB Migration
40
AppData directory
/config
Startup directory
/app/lidarr/bin
Mode
Console
Uptime
00:42:10
```

**Comment by Qstick** [comment]
Pushed some command/task fixes from Sonarr/Radarr... Not sure it'll help this as I didn't dig into the cause.. but maybe get lucky

**Comment by delize** [comment]
Hey @Qstick 

I upgraded to the latest version, ran a DB command to remove all Rescan tasks, and left Lidarr running for ~1 hour. 

Unfortunately, the tasks still recreated themselves. 

I think this has something to do with refreshing the artists and then creating the rescan media tasks.

**Comment by delize** [comment]
After another 24 hours to try and check again and performing the same steps, I have not seen the Rescan Folders task spawn. 

I wouldn't close it yet, but, it seems to have stopped on my side.

**Comment by delize** [comment]
~15 hours ago, Lidarr started recreating the tasks again. Unfortunately, my trace logs don't go back that far, they only go back about 2 hours. 

Is there a way to increase the amount of trace logs collected to get this data? Otherwise, it's going to be tricky due to timing.

**Comment by delize** [comment]
It occurred with spawning ~6 tasks, but not as many as above. But was able to capture trace logs in this one. Hopefully they are helpful. 

There are 50 files, it happened with the last 4 to 5 hours worth of the logs.
[Lidarr.trace.43.zip](https://github.com/lidarr/Lidarr/files/5048486/Lidarr.trace.43.zip)

**Comment by delize** [comment]
[Lidarr.all_logs.zip](https://github.com/lidarr/Lidarr/files/5066972/Lidarr.all_logs.zip)

Until #1508  is merged going to still upload logs. As it occurred an hour ago again. :/
