### ISSUE TITLE
Tagging not possible on a gdrive / Tag writing failed for ... /  System.IO.IOException: Win32 IO returned 25. Path:

### ISSUE THREAD

**Issue by davidh2k** [lidarr/Lidarr#1191]
**Describe the bug**
When trying to tag files that reside on a google drive mounted via rclone mount lidarr fails to tag the files. This error does not happen on a local drive.

**To Reproduce**
Retag files from an Album

**Expected behavior**
Properly Tagged files

**Screenshots**

**Logs**
https://pastebin.com/S78X5BPZ

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System Linux / Docker (linuxserver.io container)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.20.1.34

**Additional context**
To rule out any permission issues I even went as far as using a umask of 000 for the gdrive mount and lidarr temporarily.

**Comment by ta264** [comment]
I'm going to close this for now because I'm fairly certain that this will just be an issue with your rclone mount settings.  Hopefully someone can help you out on the discord, and if we establish it is a bug in Lidarr we can re-open

**Comment by davidh2k** [comment]
Considering that I have Sonarr and two instances of Radarr running just fine even with lesser user rights I consider it to not be the usual "You don't have the proper permissions setup". All Services run under the service user 1007 with his respective group 2007. The gdrive is also mounted with that user. To eliviate any issues regarding I even set the umask for both the rclone mount and lidar to 000.

Here is my rclone command:

`rclone mount --daemon --rc --allow-other --umask 000 --uid 1007 --gid 1007 --buffer-size 128M --dir-cache-time 72h --drive-chunk-size 32M --fast-list --vfs-read-chunk-size 128M --allow-non-empty --vfs-read-chunk-size-limit off gdrive:/ /mnt/gdrive`

Here is a snippet of an ls -lah of an album path, from within the container
`root@74e3a83aaf52:/music/Green Day/1039_Smoothed Out Slappy Hour# ls -lah
total 399M
-rw-rw-rw- 1 abc abc 19M Jul 24 23:03 '01 At The Library.flac'
-rw-rw-rw- 1 abc abc 20M Jul 24 23:03 "02 Don't Leave Me.flac"
-rw-rw-rw- 1 abc abc 27M Jul 24 23:03 '03 I Was There.flac'
-rw-rw-rw- 1 abc abc 20M Jul 24 23:03 '04 Disappearing Boy.flac'
-rw-rw-rw- 1 abc abc 25M Jul 24 23:03 '05 Green Day.flac'
[...]
`

`root@74e3a83aaf52:/music/Green Day# ls -lah
total 0
drwxrwxrwx 1 abc abc 0 Jul 27 06:44 '1039_Smoothed Out Slappy Hour'
drwxrwxrwx 1 abc abc 0 Jul 27 06:42 '21st Century Breakdown'
drwxrwxrwx 1 abc abc 0 Jul 27 06:31 'American Idiot'
drwxrwxrwx 1 abc abc 0 Jul 27 06:45 'American Idiot (2004)'
[...]
`

From the host:

```
root@srv1 /mnt/gdrive/musik/Green Day/1039_Smoothed Out Slappy Hour # ls -lah
insgesamt 399M
-rw-rw-rw- 1 wigu wigu 19M Jul 24 23:03 '01 At The Library.flac'
-rw-rw-rw- 1 wigu wigu 20M Jul 24 23:03 "02 Don't Leave Me.flac"
-rw-rw-rw- 1 wigu wigu 27M Jul 24 23:03 '03 I Was There.flac'
-rw-rw-rw- 1 wigu wigu 20M Jul 24 23:03 '04 Disappearing Boy.flac'
```


```
root@srv1 /mnt/gdrive/musik/Green Day # ls -lah
insgesamt 0
drwxrwxrwx 1 usera usera 0 Jul 27 06:44 '1039_Smoothed Out Slappy Hour'
drwxrwxrwx 1 usera usera 0 Jul 27 06:42 '21st Century Breakdown'
drwxrwxrwx 1 usera usera 0 Jul 27 06:31 'American Idiot'
drwxrwxrwx 1 usera usera 0 Jul 27 06:45 'American Idiot (2004)'
```
