### ISSUE TITLE
Music folders copied manually to the right artist and correct album doesn't show as available on lidarr

### ISSUE THREAD

**Issue by zobe123** [lidarr/Lidarr#1194]
Describe the bug
Music folders copied manually to the right artist and correct album doesn't show as available on lidarr

To Reproduce

1. Copy album folder from other location into /music (for example, /music/Eminem)
2. Copy an album that is not yet downloaded
3. Go to lidarr and refresh manually or wait for lidarr auto refresh and nothing happens
4. Manual import works correct but slow

Expected behavior
Should show music files available of that particular album added and rename the album

System info:
- OS: Ubuntu 18.04.4 LTS
- Kernel: 4.15.0-112-generic
- Lidarr Version: 0.7.1.1722
- Mono Version: 6.10.0.104

**Comment by ta264** [comment]
This is intended behaviour - it doesn't rename files already in the library folder unless you ask it to.

You should be using the manual import feature in lidarr, not copying folders in manually. Please join the discord channel if you need more support.
