### ISSUE TITLE
Correct Eslint Issues and Re-enable Checks

### ISSUE THREAD

**Issue by ta264** [lidarr/Lidarr#120]
As mentioned in #119. Fails on things like unused variables, bad indents and trailing whitespace.  Log attached. 

[lint.log](https://github.com/lidarr/Lidarr/files/1464776/lint.log)

**Comment by Qstick** [comment]
@ta264 thanks, feel free to start knocking some of these out if you want. I’ll start trying to correct some when I’m in the files.
