### ISSUE TITLE
Just curious, are you using beets to tag the music files?

### ISSUE THREAD

**Issue by l-t-k** [lidarr/Lidarr#125]
Since headphones let me down in the past I switched over to manual downloading and tagging with an automated post process script that triggers beets to import the music files:
https://github.com/beetbox/beets

Based on that experience, beets is extremely good at it! It would be a missed opportunity not using this briljant piece of software in this project!

**Comment by Qstick** [comment]
As of now no we are not using it. You can easily setup a post processing script using Lidarr custom script capabilities (see wiki) to have beets tag after a Lidarr grab.
