### ISSUE TITLE
Fix ical feed link in settings 

### ISSUE THREAD

**Issue by arette** [lidarr/Lidarr#133]
Unable to import into Google calendar and when I enter the full URL into Chrome to download Lidarr.ics, I get:

{
  "message": "NotFound"
}

**Comment by Qstick** [comment]
What is the URL you are entering?

**Comment by arette** [comment]
http://192.168.1.XX:8686/feed/calendar/Lidarr.ics?apikey=e1db114b3bfc477c8939c312d06c5529

**Comment by Qstick** [comment]
Use `....8686/feed/v1/calendar/....`

**Comment by arette** [comment]
Ah ok I'll try that, I copied the URL from the settings which apparently doesn't (yet) include v1.  Thank you!!

**Comment by Qstick** [comment]
Let me know if it still doesn’t work for some reason

**Comment by arette** [comment]
With URL http://192.168.1.XX:8686/feed/v1/calendar/Lidarr.ics?apikey=XXXXXXXXXXXXX , I get:

{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at Lidarr.Api.V1.Calendar.CalendarFeedModule.GetCalendarFeed () [0x00748] in C:\\projects\\lidarr\\src\\Lidarr.Api.V1\\Calendar\\CalendarFeedModule.cs:90 \n  at Lidarr.Api.V1.Calendar.CalendarFeedModule.<.ctor>b__2_0 (System.Object options) [0x00000] in C:\\projects\\lidarr\\src\\Lidarr.Api.V1\\Calendar\\CalendarFeedModule.cs:30 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 "
}

**Comment by Qstick** [comment]
d031b823f2d216241d07dbcafaa597cfcf24c062 Should fix the link being incorrect, the null error seems to be result of a data mapping issue, but I’ll have a temp fix up tonight.

**Comment by Qstick** [comment]
f7f6ad159c2b5e78f23a6dfbba4cd1ad5b39308b
