### ISSUE TITLE
Synology Indexer

### ISSUE THREAD

**Issue by arette** [lidarr/Lidarr#134]
I'm using a package that allows my docker containers to reach the synology indexer in /usr/syno/bin/synoindex (https://github.com/racklin/simple-synoindex-server). This package works great with Sonarr/Radarr/etc. and I'm mapping the volume the same way in the container in Lidarr (/docker/simple-synoindex-server -> /usr/syno/bin), but alas the synology indexer does not appear to be called in the trace debug log I turned on to monitor a download event. I do see NotificationService get invoked for each TrackImportedEvent, and I did receive Gmail notification for each track but synology database was not updated with new tracks and 'synoindex' did not appear to be called at all in the trace debug logs. Note also that it passes the test in the Settings -> Connect -> Synoindex. Is this feature possibly still incomplete? Thanks!

**Comment by Qstick** [comment]
I’ll investigate this in a bit, I don’t think anyone has touched Synology notifications code since we refactored notifications service, so it may just need to be fixed up.

**Comment by Qstick** [comment]
@arette can you post logs

**Comment by arette** [comment]
[Lidarr.trace.0.txt](https://github.com/lidarr/Lidarr/files/1500124/Lidarr.trace.0.txt)

**Comment by arette** [comment]
this one is the one i described above, where i see the NotificationService and I did receive emails.  here is a call to synoindex from Sonarr debug logs:

root@NAS-ETTE:/volume1/docker/sonarr/logs# grep -ri synoindex .
./sonarr.debug.39.txt:17-11-21 22:42:19.2|Debug|synoindex|Starting /usr/syno/bin/synoindex -a "/TV_Shows/Tales From the Cryptkeeper/Season 1/Tales From the Cryptkeeper - S01E01 - While the Cat's Away WEBDL-480p.mkv"

**Comment by arette** [comment]
so I suppose I'd expect to see something like below, but I don't.

root@NAS-ETTE:/volume1/docker/lidarr/logs# grep -ri synoindex .
./sonarr.debug.XX.txt:17-11-21 22:42:19.2|Debug|synoindex|Starting /usr/syno/bin/synoindex -a "/music/WALK THE MOON/Talking Is Hard (2014)/02-walk_the_moon-sidekick.mp3"

**Comment by Qstick** [comment]
@arette you do have Update Library checked in notification settings right?

**Comment by arette** [comment]
Yes and "On Rename"

**Comment by Qstick** [comment]
Ok, I think I see the issue. Give me an hour and I’ll have a fix up

**Comment by arette** [comment]
Awesome you rock!!  How do you feel about grouping notifications (or having option to) into 1 for entire release instead if 1 for each track?

**Comment by Qstick** [comment]
I like the idea, but need to add some things to get that going. Tracks are easier due to the fact that we dealing with trackFiles and we can simply throw a notification event when we match a trackFile to a track.

**Comment by arette** [comment]
Understood , low priority feature request for future then.  Thanks again for your time developing this

**Comment by Qstick** [comment]
Is this working for you now? I saw you mention in the other thread.

**Comment by arette** [comment]
Yes it is!, wasn't sure if you were keeping this open as reminder for feature request to group notifications into one per album or I can resubmit that separately for cleanliness

**Comment by Qstick** [comment]
Go ahead and do another for that
