### ISSUE TITLE
Release Rejected - Unable to parse albums from release name

### ISSUE THREAD

**Issue by arette** [lidarr/Lidarr#136]
Examples of albums I'm unable to snatch due to presence of " ' " and possibly other chars:

```
Portugal.The Man-Waiter: "You Vultures!"
Portugal. The Man - Waiter: &quot;You Vultures!&quot; (2006) (FLAC Lossless)

Coolio-Gangsta’s Paradise
Coolio - Gangsta&#39;s Paradise (1995) (FLAC Lossless)
```

**Comment by Qstick** [comment]
@arette thanks for getting all of these on github

**Comment by arette** [comment]
no thank you guys for developing this - this is awesome!  wish i could contribute in a more meaningful way.  I do know python but not web..

**Comment by uffcd** [comment]
Another example for no files found are eligible ... 
Robbie.Williams.-.Under.the.Radar.Vol.2.2017.MP3
Files: 01 - Satellites.mp3

**Comment by Qstick** [comment]
Doing some testing and I'm having no issues with finding and grabbing a release for Coolio-Gangsta’s Paradise. Can you go into a bit more detail of whats happening and provide some logs?

**Comment by arette** [comment]
sorry my original text wasn't included as "code" so it was hiding the special characters.  could be encoding problem?  If so, might only be a problem running on docker container.  the problem is that I get "Release rejected unable to parse albums from release name" for any album that contains characters such as an apostrophe, exclamation, etc.  The apostrophe in Gangsta's Paradise is apparently breaking it.  
![lidarr_parse_error](https://user-images.githubusercontent.com/12751515/33840603-5ffe14d0-de63-11e7-9923-3c4b17044709.png)

**Comment by Qstick** [comment]
Ah I see. Let me work on it tonight

**Comment by arette** [comment]
awesome thank you! I apologize for my poor description initially

**Comment by Qstick** [comment]
Are you going thru Jackett or are the indexers setup direct in Lidarr? Just Curious

**Comment by arette** [comment]
directly thru lidarr but i do have rss off across the board so i can manually search for and snatch each release

**Comment by Qstick** [comment]
@arette 0.2.0.180 should fix this

**Comment by D4rkSl4ve** [comment]
I am getting a:  Couldn't parse album from AC - [RS500-73] Back In Black -........
![acdc](https://user-images.githubusercontent.com/38662669/39217592-bae740e8-47ee-11e8-9724-9eb7fabe72f2.jpg)

**Comment by Qstick** [comment]
@D4rkSl4ve looks like a case of poor tags in file

**Comment by sdwhwk** [comment]
I'm getting this. I've tied to look for an NZB to see if it does the same, but I have a large list of artists. Notice that some torrents are downloadable while others that are similarly named got rejected because it could not find the artist.
![2018-07-03 5](https://user-images.githubusercontent.com/11259791/42242122-6e083ba4-7ed2-11e8-8138-c430d511269d.png)

**Comment by sdwhwk** [comment]
Think I might have found the pattern in at least my AC/DC shot:

When searching for the name it includes the / and without like"ACDC". It also ignores parentheses. So "(Hard Rock)" is not considered.

But it does not include - , which is a common substitute for / , nor a space, like the previous AC/DC shot by D4rkSl4ve. It also includes brackets, so "[LP]" is included and thinks a name "AC/DC [24/192]" is that, not "AC/DC". 

So if it is not "AC/DC" or "ACDC" and it contains anything NOT in parentheses, it can't find it. May be the same for titles, but this is what I noticed on not finding the artist and listing it as a download. I found another artist with a similar problem (brackets) and it didn't recognize the download. Possibly { } might throw an error, but have not came across it yet.

**Comment by carbonbaseunit** [comment]
I, too, am having a problem with "unable to parse albums from release name"
![screencapture-192-168-1-50-8686-artist-a35237a0-4f47-40a6-b6f3-1e786db23402-2018-10-05-11_32_14](https://user-images.githubusercontent.com/37486202/46553538-9c6d7680-c892-11e8-9985-60ff6aa6928b.png)
I don't understand why something this simple is happening.  There are no off the wall tags in the name.

**Comment by Qstick** [comment]
We do not use the name, we use the tags. What do the exceptions say?

**Comment by carbonbaseunit** [comment]
Unable to par

> We do not use the name, we use the tags. What do the exceptions say?

Unable to parse album from release name
