### ISSUE TITLE
Show number of tracks when searching for a album

### ISSUE THREAD

**Issue by uffcd** [Lidarr/Lidarr#137]
Its hard to find the correct album when you cannot see how many tracks are in the release

[AB#463](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/463)

**Comment by Qstick** [comment]
Are referring to manual search and showing tracks count for each release? If so this is going to be near impossible, not every indexer provides info on track count or which tracks are in a release. We may be able to look at this for the indexers that do have this info
