### ISSUE TITLE
Albums with multiple CDs not correctly named

### ISSUE THREAD

**Issue by AuXBoX** [lidarr/Lidarr#139]
When albums have multiple cds, when file naming, all music is put in 1 folder and not in separate folders.
Example:
Currently all files from 2 cds are in folder
Aerosmith/Music From Another Dimension! (2012)/
but it should be
Aerosmith/Music From Another Dimension! (2012) CD1/
Aerosmith/Music From Another Dimension! (2012) CD2/
or 
Aerosmith/Music From Another Dimension! (2012)/CD1/
Aerosmith/Music From Another Dimension! (2012)/CD2/

**Comment by uffcd** [comment]
please not - let me have it all in one folder :) But of course tracknumbers from cd2 should be increased to match the tracks from cd1 (#01 from cd2 = number of tracks from cd1+1 )

**Comment by Qstick** [comment]
It will be optional token in renaming options

**Comment by woble** [comment]
@Qstick Could you elaborate on how it will be consumed.

**Comment by Qstick** [comment]
I believe there are a lot of people that have multi-disc all in one folder and use track naming to differentiate  (ex. 1-01, 1-02, 2-01). Lidarr currently is capable of doing this type of naming using medium tokens in track naming. I believe this is a recognized format on both Kodi and Emby (Maybe Plex also)? 

But regardless, I would like the add the ability to sort into sub-folders for multi-disc as I know some would prefer this. Its going to take some work around re-writing the filenamebuilder similar to adding the ability to sort into album type subfolders #96

**Comment by F688** [comment]
One issue with this is that tracks with same name same track number but on different CDs after being imported are shown as missing after Lidarr re-scans. Lidarr then wants to rename CD2 track as DC1. For example:

Queen - A Day at the Races - CD1 Track1 - Tie Your Mother Down
Queen - A Day at the Races - CD2 Track1 - Tie Your Mother Down (backing track mix 2011)

**Comment by rudyolph** [comment]
Definitely need the ability to have continuous track numbers consecutively for multi CD albums.  Plex has a fit if you don't and so far I haven't found a decent file name convention that gets it to work well.
So instead of this:
/Music
   /MyArtist
      /My Album
         CD1/
             01 - MySong1.flac
             02 - MySong2.flac
         CD2/
             01 - MySong3.flac
             02 - MySong4.flac
We can do:
/Music
   /MyArtist
      /My Album
             01 - MySong1.flac
             02 - MySong2.flac
             03 - MySong3.flac
             04 - MySong4.flac
