### ISSUE TITLE
Feat/Bug:  Importing artist w/ metadata cosumer enabled creates empty album folders

### ISSUE THREAD

**Issue by seanvree** [lidarr/Lidarr#143]
(Spoke about this on Gitter, but wanted to track it via GitHub)

Testing on:  Windows 10E x64 1709 FCU

**ISSUE**:  When importing an artist with metadata consumers enabled, Lidarr will create an empty folder for EVERY album in artists' profile.  

**Workaround** as of  0.2.0.175 is to disable "artists images" AND "Album images" in consumer metadata settings (Screenshot below). 

**Suggestion**:   Add option to NOT create album folders when importing artist(same function as adding a new artist not to create artists folders until data is downloaded).

![image](https://user-images.githubusercontent.com/8906637/33529714-959c84b8-d829-11e7-9653-ffe959f0f256.png)

**Comment by Qstick** [comment]
@seanvree Thanks, I have a fix ready for this, but found some other bugs for metadata files in the process. I'm trying to get a few more items fixed before loading this up.

**Comment by seanvree** [comment]
@Qstick stoked brotha!

**Comment by Qstick** [comment]
Closed in #145

**Comment by seanvree** [comment]
confirmed. Thanks @Qstick  !!!
