### ISSUE TITLE
Add Artist button fails to add due to DB Schema

### ISSUE THREAD

**Issue by mhicklen** [lidarr/Lidarr#146]
Out of the box, the Add button fails to add an artist.  A packet capture of the API response shows as follows:

`HTTP/1.1 400 Bad Request
X-ApplicationVersion: 0.2.0.160
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Wed, 13 Dec 2017 21:03:24 GMT
Connection: close
Transfer-Encoding: chunked

120
[
  {
    "propertyName": "LanguageProfileId",
    "errorMessage": "Language profile does not exist",
    "attemptedValue": 3,
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Language Profile Id",
      "propertyValue": 3
    }
  }
]
`

Adding the missing ID to the database shows issues with the Metadata and MetadataProfiles tables as well.

Looking for some guidance on how to best proceed or to offer feedback/testing.

OS: Arch Linux
Source: https://aur.archlinux.org/packages/lidarr/

**Comment by Qstick** [comment]
Update lidarr

**Comment by Qstick** [comment]
Did newer version fix the issue?
