### ISSUE TITLE
Lidarr: Trace logs including Plex auth token and client ID

### ISSUE THREAD

**Issue by SawkeeReemo** [lidarr/Lidarr#1511]
Trace logs should have auth tokens and client IDs redacted.

https://pastebin.com/m7hTewWd

System info:
 - Lidarr Version: 0.7.1.1729
 - Package Version: 0.7.1.1729-ls16 by linuxserver.io
 - Operating System: Synology NAS - DSM 6.2.3-25426 Update 2

**Comment by ta264** [comment]
Fixed in next build
