### ISSUE TITLE
Lidarr: When adding a Various Artist album, it scans every other VA album before adding the new one (takes a very very long time)

### ISSUE THREAD

**Issue by SawkeeReemo** [lidarr/Lidarr#1515]
Manually adding new VA albums takes an incredibly long time because Lidarr will ~~rescan~~ **refresh** all of the other VA albums before it will add the new one. Any way to set the VA artist to just ~~add/scan~~ **add/refresh** individual new albums, and not everything listed under VA?

**System info:**
 - Lidarr Version: 0.7.1.1729
 - Package Version: 0.7.1.1729-ls16 by linuxserver.io
 - Operating System: Synology NAS - DSM 6.2.3-25426 Update 2

**Comment by ta264** [comment]
Fixed in f2e5ec5df07e4fb2e322713affca262800451921
