### ISSUE TITLE
Add file to playlist: "Unable to find linked item at path  ..." in log - I believe it's due to apostrophe in name of file

### ISSUE THREAD

**Issue by smathev** [lidarr/Lidarr#1534]
**Describe the bug**
Adding file with apostrophe in filename to m3u8 / m3u playlist results in: 
"
Unable to find linked item at path file:///storage/data/music/artists/Coheed.and.Cambria/Good.Apollo.I’m.Burning.Star.IV.Volume.One.From.Fear.Through.the.Eyes.of.Madness-(2005)/CD.02/01 - Welcome Home.flac/storage/data/music/artists/Coheed.and.Cambria/Good.Apollo.I’m.Burning.Star.IV.Volume.One.From.Fear.Through.the.Eyes.of.Madness-(2005)/CD.02/01 - Welcome Home.flac
"
in the log.

**To Reproduce**
1. Have one or more files with an apostrophe in the filename.
2. Find file in relevant library
3. Try to add file to playlist
4. See error in logs.

**Expected behavior**
Jellyfin should be able to handle single quotes/apostrophes in filenames.

**System info (please complete the following information):**
 - Lidarr Version: 10.6.3
 - Operating System [e.g. iOS]: jellyfin-docker:latest
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
I'm fairly certain it's due to there being apostrophe in the filename. That apostrophe makes the file-location become a duplication of itself. 
I'm able to add all other files I have in my libraries, but all with an apostrophe fails in the same way:

Unable to find linked item at path file:///storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/06-Body.Movin’.flac/storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/06-Body.Movin’.flac
Unable to find linked item at path file:///storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/08-Sneakin’.Out.the.Hospital.flac/storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/08-Sneakin’.Out.the.Hospital.flac
Unable to find linked item at path file:///storage/data/music/artists/Red.Hot.Chili.Peppers/By.the.Way-(2001)/05-Don’t.Forget.Me.flac/storage/data/music/artists/Red.Hot.Chili.Peppers/By.the.Way-(2001)/05-Don’t.Forget.Me.flac
Unable to find linked item at path file:///storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/10-Flowin’.Prose.flac/storage/data/music/artists/Beastie.Boys/Hello.Nasty-(1998)/10-Flowin’.Prose.flac
Unable to find linked item at path file:///storage/data/music/artists/Red.Hot.Chili.Peppers/By.the.Way-(2001)/07-Can’t.Stop.flac/storage/data/music/artists/Red.Hot.Chili.Peppers/By.the.Way-(2001)/07-Can’t.Stop.flac

For reference, the files play without issue when I start playing them.

**Comment by ta264** [comment]
This is lidarr not jellyfin :)
