### ISSUE TITLE
Apple Music Top Albums import causes all albums to be imported instead

### ISSUE THREAD

**Issue by diabl0w** [lidarr/Lidarr#1535]
**Describe the bug**
Using the import list feature of Apple Music Top albums, instead of just an artist's top albums being imported and added to missing, every album that artist every produced is added to monitored

**Expected behavior**
Only the artist's album that is in the apple music list should be added to monitored/wanted

**Comment by ta264** [comment]
Please fill in the template.  I believe this is possible on nightly releases.

**Comment by diabl0w** [comment]
user error, there was a setting for monitor "specific album" that i thought i chose... just went back to double check and instead it was set to "all albums". resolved.
