### ISSUE TITLE
Built-in updater fails on macOS

### ISSUE THREAD

**Issue by aniqueta** [lidarr/Lidarr#1548]
**Description**
Built-in updater does not work on macOS. 

Per the logs, it appears unable to find /var/folders/.../lidarr_update/Lidarr.Update.exe. However, navigating there, it appears there is a file there just not named with .exe. However, renaming this file to trick the updater to use it leads to an error that it does not contain a valid CIL image. So, perhaps not the right file.

For this update, I tried with and without full disk access. Ideally, full disk access isn't needed (once updated).

**To Reproduce**
1. Install fresh pre-release version from releases page
2. Give Lidarr full disk access (for macOS Catalina; tried with and without)
3. Switch release channel to nightly
4. Run built-in updater

**Expected behavior**
Updater completes and refreshes with current nightly version

**Actual behavior**
Updater notifications appear normal. No error provided. Notification stating restart appears, but does not appear to work and/or new version not truly installed.

**Logs**
`20-9-2 23:13:59.2|Info|InstallUpdateService|Deleting old update files
20-9-2 23:13:59.3|Info|InstallUpdateService|Downloading update 0.7.1.1785
20-9-2 23:14:17.2|Info|InstallUpdateService|Verifying update package
20-9-2 23:14:19.0|Info|InstallUpdateService|Update package verified successfully
20-9-2 23:14:19.0|Info|InstallUpdateService|Extracting Update package
20-9-2 23:14:25.8|Info|InstallUpdateService|Update package extracted successfully
20-9-2 23:14:25.8|Info|BackupService|Starting Backup
20-9-2 23:14:26.8|Info|InstallUpdateService|Preparing client
20-9-2 23:14:27.3|Info|InstallUpdateService|Starting update client /var/folders/.../lidarr_update/Lidarr.Update.exe
20-9-2 23:14:27.3|Info|InstallUpdateService|Lidarr will restart shortly.
20-9-2 23:14:27.3|Info|InstallUpdateService|Updater Arguments: 54959 /var/folders/.../lidarr_update /Applications/Lidarr.app/Contents/MacOS/Lidarr.exe /nobrowser
20-9-2 23:14:27.3|Error|mono|Cannot open assembly '/var/folders/.../lidarr_update/Lidarr.Update.exe': No such file or directory.`

**System info**
 - Lidarr Version: [e.g. 0.3.0.430]
 - macOS 10.15.6 (19G2021)
 - Mono Version 6.8.0.123

**Comment by ta264** [comment]
Dupe #1091

**Comment by aniqueta** [comment]
@ta264 Sorry didn't see that one. Is there a workaround in the meantime? Thanks.

**Comment by ta264** [comment]
No problem, just closing to keep it organised.  Join the discord and we can help.

**Comment by aniqueta** [comment]
@ta264 Thanks for the kind offer. Just want to put here for others that I solved this by enabling full disk access (because I'm on Catalina) for the update and then turning it off. Not sure if it will need to be on for subsequent ones, but will update if so.
