### ISSUE TITLE
Add option to not remove download from download client when removing from Lidarr queue

### ISSUE THREAD

**Issue by misleadingrhino** [lidarr/Lidarr#1549]
**Is your feature request related to a problem? Please describe.**
When removing an entry from Lidarr's queue, it automatically removes it from the download client, Deluge in this case. 

**Describe the solution you'd like**
A checkbox that gives the option to remove or leave it in the download client so that even if it's the wrong item, it can be left seeding. Radarr and Sonarr both have this checkbox, so hopefully it should be easy to add. 

Thanks!

**Comment by ta264** [comment]
This is done in nightly
