### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by BlackOak1337** [Lidarr/Lidarr#1591]
**Describe the bug**
In sorting artist names the artist "The The" apears at the top instead of in the "t's"

I hope this isn't to mush opf an issue =]

[AB#265](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/265)

**Comment by bakerboy448** [comment]
Closing in favor of #3386
