### ISSUE TITLE
"Remove From Download Client" box cannot be unchecked for some items in queue

### ISSUE THREAD

**Issue by crafty35a** [Lidarr/Lidarr#1594]
**Describe the bug**
For some items in the queue, the "Remove From Download Client" box cannot be unchecked (the mouse cursor turns into a red circle/slash symbol)

**To Reproduce**
1. Go to the Queue page
2. Click the "Remove from Queue" X next to a download
3. For most items, the "Remove From Download Client" box can be unchecked, but for some it cannot.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1808
 - Operating System: W10
 - My download client is Deluge 1.3.15

[AB#270](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/270)

**Comment by crafty35a** [comment]
I just transferred all of my torrents over to qBittorrent, and the same few items have this issue. So it is not specific to the download client.

**Comment by runaroundhome** [comment]
For me, it's anything that doesn't have a "Album Title". All my other items have something listed in that column, and will let me untick "Remove From Download Client".

<img width="108" alt="image" src="https://user-images.githubusercontent.com/16973228/169163701-fcfc778c-da19-42fc-a9d5-0c21e778efb1.png">

**Comment by bakerboy448** [comment]
Yes this is known and applies to unknown/unmappable downloads.

**Comment by Mannekino** [comment]
Will this be fixed?

**Comment by PearsonFlyer** [comment]
If a release cannot be parsed (i.e. it's white and not blue), you cannot remove it from activity without removing it from your download client. This behavior is common to all of the arr apps, and will likely not change.

If you still want it in your DL client, then go there and change the category to something non-Lidarr.

**Comment by bakerboy448** [comment]
Not a bug. Downloads that are not
Matched to a entity in Starr cannot be ignored
