### ISSUE TITLE
Downloads not picked up if torrent is in a qBittorrent subcategory

### ISSUE THREAD

**Issue by MrDemous** [lidarr/Lidarr#164]
Lidarr doesn't see torrents that are in subcategories in qBittorrent e.g. RED/Lidarr

Lidarr sends the torrent and sets the label correctly (RED/Lidarr for me) in qBittorrent but then it seems that Lidarr doesn't see the torrent at all (doesn't show as downloading in Lidarr) if it's in a subcategory and therefore it doesn't import torrents when they finish downloading.

**Comment by Qstick** [comment]
https://github.com/qbittorrent/qBittorrent/issues/8168

**Comment by MrDemous** [comment]
Just an FYI. This is fixed in qBittorrent 4.1.0.
