### ISSUE TITLE
Lidarr upgrading quality from FLAC to MP3

### ISSUE THREAD

**Issue by MrDemous** [lidarr/Lidarr#165]
Lidarr seems to get confused when there is another copy of existing album in the download client (qBittorrent for me) and decides to upgrade the album to a lesser quality.

Example: I have a FLAC album on disk and another MP3 version in qBittorrent so Lidarr picks up the MP3 one from qBittorrent and replaces the FLAC with it.

**Comment by Qstick** [comment]
Should be fixed in c4c3c4f6202edf4750e7f4bdf29602ab5bfabce4.
