### ISSUE TITLE
Embed Album Art with Options

### ISSUE THREAD

**Issue by arette** [lidarr/Lidarr#168]
currently, images are downloaded to artist's root directory and name mangled presumably to deal with illegal characters/path lengths/etc (see image below).  Unfortunately, while this mechanism does address many concerns, it will not be properly picked up by virtually any indexers due to the mangled name and location of file.  It would be better to 1) handle name mangling in a different way (e.g. underscores, etc and be explicit about path lengths if that is a concern) 2) add options to control where the metadata files get placed (e.g. in the artist root folder, album root folder, or simply embed).  I would prefer to embed where possible (e.g. artwork, lyrics) and not store additional files on disc.

![2017-12-28 16_25_49-w__coolio](https://user-images.githubusercontent.com/12751515/34423684-cbc7f83a-ebeb-11e7-951a-f2ad33a37286.png)

**Comment by Qstick** [comment]
Can you provide debug or trace logs showing Lidarr saving these?

**Comment by arette** [comment]
no and I may never given changes to settings etc since these particular files were created :/  I will attempt to reproduce and post logs feel free to close this out until then.  i do see kodi metadata works nicely.  however, given that synoindex is now working (thanks again), it would be nice for the album art to work more consistently and I guess that's my main point here (see screenshot below where album art is only embedded occasionally).  i don't see anything related to this in settings, is an embed always attempted and just failing more often than not?

![2017-12-28 22_09_18-nas-ette - synology diskstation](https://user-images.githubusercontent.com/12751515/34428532-cad54c40-ec1b-11e7-8a26-abfff0f5ab24.png)

**Comment by Qstick** [comment]
Currently we are not writing any tags nor are we embedding any art. So if its already embedded then it was downloaded like that. It is a feature we want to add for future.

**Comment by arette** [comment]
ah ok great then.  not sure how/why I got the files above hopefully that's behind me

**Comment by Qstick** [comment]
@danielunderwood putting this one on hold until we switch to cover art archive on album images. This should be fairly easy to implement with taglib
