### ISSUE TITLE
Artist poster has issues when one poster missing (Web UI)

### ISSUE THREAD

**Issue by arette** [lidarr/Lidarr#169]
in web ui, some artists occasionally only show gray lidarr icon for image and the image can come and go when the artist is refreshed:

![2017-12-28 22_14_51-lidarr](https://user-images.githubusercontent.com/12751515/34428610-a8315548-ec1c-11e7-8dbd-6369bff2922a.png)

furthermore artist images on adjacent pages are affected when paging through artists using the <- & -> arrow buttons.  E.g. Muse page usually shows as

![2017-12-28 22_16_56-muse - lidarr](https://user-images.githubusercontent.com/12751515/34428625-e27c9cb2-ec1c-11e7-902a-32ef7144de07.png)

whereas, when paging right from Moon Taxi (artist with default gray lidarr icon shown at top), you get:

![2017-12-28 22_18_50-muse - lidarr](https://user-images.githubusercontent.com/12751515/34428648-1ceab0fa-ec1d-11e7-9a67-6e8186459633.png)
 

and paging from the left a good artist image Michael Kiwanuka showing for Moon Taxi lol:
![2017-12-28 22_19_59-moon taxi - lidarr](https://user-images.githubusercontent.com/12751515/34428665-42da10c6-ec1d-11e7-8f3f-00565af08330.png)

I'm only posting this because deep down I'm hoping it's related to issue #168 and album images not being handled/embedded properly although I know that's slim to none.

**Comment by dabates** [comment]
Just throwing this comment out here, as I've talked to @Qstick about this before, I believe this is also part of an issue where if you go to a artist that has an image and the DIRECTLY to one that doesn't.. it keeps the old image.. If I'm wrong, qstick and nuke this message :)

**Comment by Qstick** [comment]
This is correct, it doesn't get reset to placeholder image at times
