### ISSUE TITLE
Random Monitored Items

### ISSUE THREAD

**Issue by Paul5656** [lidarr/Lidarr#1706]
For some reason, Lidarr randomly Monitors Random Albums and Singles. eg I have 20 albums and singles monitored then a week from today I'll find I have 22 monitored. . The additions are not newly released material but rather older ones so I can't really pinpoint the root cause.

**Comment by ta264** [comment]
I expect this will be either your import lists (if you have any) or new albums being added on musicbrainz

**Comment by Paul5656** [comment]
No, its not Import list and I actually suspected it's probably an addition to MusicBrainz like you've mentioned. Is this supposed to be normal behavior or should it be classified as a bug because I'm not a fan of random newly added items on MB being automatically monitored?

**Comment by ta264** [comment]
Normal behaviour is that newly added items on musicbrainz will be monitored if and only if the artist is monitored.

**Comment by Paul5656** [comment]
Ok, I see. It's a little frustrating when you are monitoring a single item from dozens of different Artists, meaning you will eventually get dozens of unwanted auto-monitored items (as additions are added to MB) but I can probably cope with it. Thanks a lot for your help. I appreciate it.
