### ISSUE TITLE
Choose custom location for lidarr config directory on windows

### ISSUE THREAD

**Issue by ianduryfury** [lidarr/Lidarr#1719]
**Is your feature request related to a problem? Please describe.**
I have been using Lidarr until recently when I noticed how much space the MediaCover folder was taking up on my Windows drive. As I have my OS on a relatively small SSD I have had to remove Lidarr as it consumed all the free space on the drive.

**Describe the solution you'd like**
Assuming this is possible it would be nice to choose a custom location for the entire lidarr folder that is created in the "ProgramData" directory. Otherwise, just being able to relocate the MediaCover folder would help. My "lidarr.db" file alone was approximately 870MB.

**Describe alternatives you've considered**
Maybe I could batch process all the images in the database to something more managable overall. I feared this might screw up formating or that lidarr would just overwrite them again.

**Comment by ta264** [comment]
Use /data command line option
