### ISSUE TITLE
ImportListSync Failure when includes an album deleted from Musicbrainz

### ISSUE THREAD

**Issue by bakerboy448** [lidarr/Lidarr#1725]
https://www.reddit.com/r/Lidarr/comments/jmeq0z/importlistsync_failure/

Describe the bug

Spotify playlist Pop Rising includes an album deleted from Musicbrainz ID: 99aa0ad2-d8d8-4add-acb2-f64b45a9f4c7. This will cause syncing failure everytime, importing nothing to Lidarr.

To Reproduce

Steps to reproduce the behavior: 1. Go to 'Settings', then 'Import Lists' 2. Create an Import Lists task only syncing Spotify playlist Pop Rising and press the button 'Save' to trigger syncing process. 3. Click on 'System', then 'Events'. 4. Click on the button 'Refresh' to load log until you see the error message.

Expected behavior

Lidarr should record this missing album and finish importing the whole playlist.

Logs

https://pastebin.com/FKFpyRTt
System info (please complete the following information):

Lidarr Version: nightly [0.8.0.1886]
Operating System: [Synology DSM 6.2-23739]
Docker Deamon: 18.09.8
Package Version: 0.8.0.1886-ls1 by linuxserver.io

**Comment by bhagirathbhardw** [comment]
Devs, I can confirm this is an issue still Importing is failing - https://www.reddit.com/r/Lidarr/comments/lno55i/0802042_unable_to_import_from_a_list_due_to_a/
