### ISSUE TITLE
Routine Torznab parse failures against the Jackett `/all` endpoint

### ISSUE THREAD

**Issue by jeffcasavant** [Lidarr/Lidarr#1730]
**Describe the bug**
I have a Torznab indexer set up to point to my Jackett instance's `all` endpoint, which searches over all configured torrent sites in Jackett.  This is my only torrent indexer and I've had a few torrent downloads work (though not as many as I'd expect) so I assume it is working.

Despite this, I routinely see log messages for failing Torznab queries related to artists I don't actually have in my library.  Here's three of them (out of about fifteen):

```
Nov 06 15:43:40 jupiter lidarr[2987640]: [Warn] TorznabRssParser: Failed to get enclosure for: FLAC 24-bit lossless of BipTunia's 44th Album "DEREALIZATION"
Nov 06 15:43:40 jupiter lidarr[2987640]: [v0.7.2.1878] System.ArgumentNullException: Value cannot be null.
Nov 06 15:43:40 jupiter lidarr[2987640]: Parameter name: attribute
Nov 06 15:43:40 jupiter lidarr[2987640]:   at System.Xml.Linq.XAttribute.op_Explicit (System.Xml.Linq.XAttribute attribute) [0x0000e] in /build/mono/src/mono/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XAttribute.cs:357
Nov 06 15:43:40 jupiter lidarr[2987640]:   at NzbDrone.Core.Indexers.RssParser+<>c__DisplayClass46_0.<GetEnclosures>b__0 (System.Xml.Linq.XElement v) [0x0004c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0
Nov 06 15:43:40 jupiter lidarr[2987640]: [Warn] TorznabRssParser: Failed to get enclosure for: "The Sounds of Social Distancing" BipTunia Album 42
Nov 06 15:43:40 jupiter lidarr[2987640]: [v0.7.2.1878] System.ArgumentNullException: Value cannot be null.
Nov 06 15:43:40 jupiter lidarr[2987640]: Parameter name: attribute
Nov 06 15:43:40 jupiter lidarr[2987640]:   at System.Xml.Linq.XAttribute.op_Explicit (System.Xml.Linq.XAttribute attribute) [0x0000e] in /build/mono/src/mono/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XAttribute.cs:357
Nov 06 15:43:40 jupiter lidarr[2987640]:   at NzbDrone.Core.Indexers.RssParser+<>c__DisplayClass46_0.<GetEnclosures>b__0 (System.Xml.Linq.XElement v) [0x0004c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0
Nov 06 15:43:40 jupiter lidarr[2987640]: [Warn] TorznabRssParser: Failed to get enclosure for: “DO NOT DRIVE OR OPERATE HEAVY MACHINERY WHILE LISTENING TO THIS” – listen free. Triple instrumental album, BipTunia albums 39, 40, 41.
Nov 06 15:43:40 jupiter lidarr[2987640]: [v0.7.2.1878] System.ArgumentNullException: Value cannot be null.
Nov 06 15:43:40 jupiter lidarr[2987640]: Parameter name: attribute
Nov 06 15:43:40 jupiter lidarr[2987640]:   at System.Xml.Linq.XAttribute.op_Explicit (System.Xml.Linq.XAttribute attribute) [0x0000e] in /build/mono/src/mono/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XAttribute.cs:357
Nov 06 15:43:40 jupiter lidarr[2987640]:   at NzbDrone.Core.Indexers.RssParser+<>c__DisplayClass46_0.<GetEnclosures>b__0 (System.Xml.Linq.XElement v) [0x0004c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0
Nov 06 15:43:40 jupiter lidarr[2987640]: [Warn] TorznabRssParser: Failed to get enclosure for: Break Me - Sophia Heyman
Nov 06 15:43:40 jupiter lidarr[2987640]: [v0.7.2.1878] System.ArgumentNullException: Value cannot be null.
Nov 06 15:43:40 jupiter lidarr[2987640]: Parameter name: attribute
Nov 06 15:43:40 jupiter lidarr[2987640]:   at System.Xml.Linq.XAttribute.op_Explicit (System.Xml.Linq.XAttribute attribute) [0x0000e] in /build/mono/src/mono/external/corefx/src/System.Private.Xml.Linq/src/System/Xml/Linq/XAttribute.cs:357
Nov 06 15:43:40 jupiter lidarr[2987640]:   at NzbDrone.Core.Indexers.RssParser+<>c__DisplayClass46_0.<GetEnclosures>b__0 (System.Xml.Linq.XElement v) [0x0004c] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0
```

I expect that these requests are just tests for the Torznab source and they're just timing out, but I can't change the timeout in the Torznab source configuration.

**To Reproduce**
1. Install Lidarr
2. Set up Jackett as a Torznab source using the `/api/v2.0/indexers/all/results/torznab` endpoint
3. Run the RSS Sync task

**Expected behavior**
* The Torznab feed to parse correctly
* Some indication in the logs of why these requests are failing but my Torznab source seems to work for other cases.  I only see failures for artists that aren't in my library.

**Logs**
Above

**System info (please complete the following information):**
 - Lidarr Version: 0.7.2.1878
 - Operating System: Arch Linux
 - .net Framework: Mono 6.10.0

[AB#294](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/294)

**Comment by ta264** [comment]
That's just lidarr parsing the RSS feed. Not sure why it's failing but it's supposed to be happening

**Comment by jeffcasavant** [comment]
I assume the artists are coming out of the RSS feed, then.  I'll see if I can't get a copy of the RSS response to aid in troubleshooting the parse error.

**Comment by jeffcasavant** [comment]
The query is to `/api/v2.0/indexers/all/results/torznab/api?t=music&cat=3000,3010,3020,3030,3040&extended=1&apikey=<key>&offset=0&limit=1000`

The response is: https://gist.github.com/3ed1e2cc617035a9d39b9b52e64cf21d

**Comment by kanedauy** [comment]
The same happens to me, and I don't know if it is related but when I do an "Interactive Search", no mather what I'm searching I see the same results in the list.

**Comment by it-is-i** [comment]
Could this solution also be applied to Lidarr please? Thx.

**Comment by bakerboy448** [comment]
> Does fixing this issue in the branch of sonarr fix the issue for lidarr as well?

No.  Nor does that make sense given none of the *arrs use the same repo/codebase.

However, there is a bot pull for it
https://github.com/lidarr/Lidarr/issues/2187
