### ISSUE TITLE
Lidarr is not pulling all album versions in a Musicbrainz release group

### ISSUE THREAD

**Issue by Darkknight33** [lidarr/Lidarr#1733]
### System Information/Logs

**Lidarr Version:**
0.7.2.1878

**Operating System:**
Linux (Docker)

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.20.1.34

### Description of request and what problem are you looking to solve?

Tried to add Twenty One Pilots promo single that contained 5 different tracks of Chlorine. For artist metadata option, I made sure to have single & promotional selected. The release exists on MB: https://musicbrainz.org/release/16fc62f0-3b31-4a97-9e77-2d9c6497d4b0. 

The only one Lidarr pulls is in the same release group, but only contains a single track: https://musicbrainz.org/release/398e131c-4570-4cd5-8ae1-5d2d7d18cad4 

Lidarr should, I think should have some way to supply the user with all versions in the release group when doing an interactive import. Maybe I'm doing it wrong, but I can't seem to get Lidarr to even recognize there is more than one version in the same release group. 

### Other Information
Release exists on Discogs as well: https://www.discogs.com/Twenty-One-Pilots-Chlorine-194326-N-991332-W/master/1498572

**Comment by ta264** [comment]
Both are showing for me.  One was probably missing a release status before.  Lidarr deliberately omits releases with no release status.
