### ISSUE TITLE
Proxy settings not being saved.

### ISSUE THREAD

**Issue by thatnovaguy** [lidarr/Lidarr#174]
After enabling the proxy and inputting the settings, I'll click save and the page resets to it's non proxy state as though no changes were ever made.

**Comment by Qstick** [comment]
Version? Logs? Platform?

**Comment by thatnovaguy** [comment]
Version: 0.2.0.197
Platform: [Binhex Docker container](https://hub.docker.com/r/binhex/arch-lidarr/)
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/1596140/Lidarr.txt)

**Comment by Qstick** [comment]
Should be fixed in 0.2.0.223 when it finished building

**Comment by thatnovaguy** [comment]
Awesome. Thanks so much!
