### ISSUE TITLE
Feature request: Scan for library on network path (Windows)

### ISSUE THREAD

**Issue by tusharbhutt** [lidarr/Lidarr#175]
Scan for library on network path in Windows

I know you can map a drive in Windows, but it would be nice to be able to point to the network shares directly.

Thanks!

**Comment by biship** [comment]
When running as **admin**, you can just past in the UNC:
![image](https://user-images.githubusercontent.com/1854029/38416047-73f14120-3961-11e8-874c-6f7a918b43e5.png)

**Comment by Qstick** [comment]
As @biship mentioned, run as admin and you can

**Comment by Zignature** [comment]
it doesn't work for me :(
Not if I run as admin, nor when I run as a service... Any help would be much appreciated

**Comment by YipYup** [comment]
There could be many reasons it doesn't work for you. NetBIOS, Layer 2 broadcast domain, Layer 3 broadcast domain, DNS, etc. Just some hints to get you going on resolving it yourselves.

**Comment by womsley** [comment]
hmmm.
radarr and sonarr are on the same server and connecting to the same storage and they both work with  UNC paths.  Was just hoping that Lidarr would do the same.
(Server is Windows 8.1 and the data storage is a NAS box with Samba and a share)

**Comment by majorpdd** [comment]
If i run from Desktop Shortcut then it can see my Mapped Drive, when I stop it then start as service with the same user account the mapped driver become unavailable.

**Comment by womsley** [comment]
OK, an update from me and thanks to YipYup for making me think on it a little longer.
I had Lidarr running as a service and I was using the local service account.  
durr.
This account has no access beyond its local machine by default.
So, I changed the account that the service runs as (exactly as i now rememebr IO had to do with Radarr and Sonarr) to one that has sufficient rights across to where my files are stored (nas running samba).
Stop & restart the service and, hey presto.  Lidarr now sees the Multimedia share.

hope this helps?

**Comment by Qstick** [comment]
This is fixed in nightly, it asks during install
