### ISSUE TITLE
Rename folders based on first letters of artist name

### ISSUE THREAD

**Issue by tusharbhutt** [Lidarr/Lidarr#176]
Feature Request: Rename folders based on first letters of artist name

I see that you can rename files based on albums and artist, etc.  However, if you have more than a few hundred artists, this gets clunky.  Can an option be added so we can make this more granular?  Say, like:

{Artist_CleanName:1}\{Artist_Name}\{Album Title}  where the ":1" indicates the first letter of the clean name.  Media Monkey has something similar, this is how I use it: 

Public Music\MP3\Sourced\$if(<Artist>=<Album Artist>,<Artist@1>\<Artist>\<Album>,$if(<Album Artist>=Various Artists,$if(<Album:4>=The ,$Group($mid(<Album>,5,1),1)\<Album Artist>\<Album>,<Album@1>\<Album Artist>\<Album>),$if(<Album Artist>,$if(<Album:4>=The ,$Group($mid(<Album>,5,1),1),<Album@1>)\<Album Artist>\<Album>,<Artist@1>\<Artist>\<Album>)))\<Artist> - <Title> 

Thanks!

[AB#464](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/464)

**Comment by eangulus** [comment]
I'm looking for this too.

My folder structure is single letter first, then artist folder. eg. MUSIC/A/Artic Monkeys/ALBUM NAME...

**Comment by scroftster** [comment]
I also want this feature please so I can migrate from Headphones.

**Comment by YipYup** [comment]
Definitely something I'm interested in too. Did this get pushed to a further out milestone or removed from the v0.3.0 milestone due to it being a duplicate?

**Comment by YipYup** [comment]
Definitely something I'm interested in too. @Qstick Did this get pushed to a further out milestone or removed from the v0.3.0 milestone due to it being a duplicate?

**Comment by Qstick** [comment]
0.3 is going to release soon as mostly a bug fix release with little new features. 0.4 will have alot of the large features, haven't decided if this will be one.

**Comment by eangulus** [comment]
Bugger. Only thing stopping me from moving from headphones to lidarr is this.

**Comment by Qstick** [comment]
Not making 0.3 or 0.4 is not end of road. You'll see this get added eventually, just not in next month or so likely. Unless we simply make a checkbox it's going to require a healthy rewrite of organizer flow.

**Comment by eangulus** [comment]
I can't see how it would require a healthy rewrite of code unless I am missing something.

All I really want to do is be able to set the Album Folder Format value. Example:
Current: {Release Year} - {Album TitleThe}
New: {Artist Initial} \ {Artist Name} \ {Release Year} - {Album TitleThe}

**Comment by nycofox** [comment]
I would suggest something like {Artist Name:1} to select just the first letter of the artist name. This could be used for any of the variables.

**Comment by Qstick** [comment]
Feel free to submit a PR! I would welcome the contribution

**Comment by YipYup** [comment]
I'm definitely willing to wait for this. I understand it is not an easy rewrite as some have commented. It will take time and is not just as easy as thinking up the idea.

When it does come due for a rewrite, here is an idea I'd like to see considered:

Extending the use of folder and file naming variables, I think it would be awesome to be able to add in length truncation modifier for any given element. To explain,  if {Artist.Clean} was a cleaned up version of the artist name, a truncation modifier could be added after it by a colon and an number, which would indicate how many alpha-numeric character positions are desired before truncation. For example, if "Beethoven" were the artist name, {Artist} would normally result in "Beethoven". Adding a truncation modifier like so   {Artist:2} would result in "Be"; Two character positions derived from {Artist}.   Another example; {Artist:3} where Artist is "Mozart" would result as "Moz" for the first 3 characters derived from Mozart.

An example of a multi-level and dynamic folder tree may be something like this:

"\{Artist:1}\{Artist:3}\{Artist} - {Release.Year} - {Album}" would become:
\M\Moz\Mozart - 2009 - The Best of

**Comment by Qstick** [comment]
@YipYup agree that would be a nice addition (https://github.com/lidarr/Lidarr/issues/356). As soon as I can decide how we want to handle everything that relies on the fixed artist path under a root directory then we should be able to start rolling on this.

**Comment by thedude0101** [comment]
I also would really like this feature. My library is organized by first letter of Artists

**Comment by Brudertac** [comment]
Any chance to see that feature? Thanks.

**Comment by strunov** [comment]
+1

Please implement this. With 500+ artists this would be a great help organizing my music better.

**Comment by Extarys** [comment]
I installed Lidarr a moment ago and I can immediately see that it doesn't like letters folder to organize.
I hope someone have enough time soon to implement this. <3

**Comment by Loomaanaatii** [comment]
Any progress on this?

**Comment by bakerboy448** [comment]
Where there is progress to share it will be shared

Comments asking for updates or saying me too or similar are not beneficial at all

**Comment by telyn** [comment]
Heya

I'd be interested in taking this on (and a slew of other stuff in the organiser area) to really boost up what lidarr's capable of in terms of larger & more awkward libraries. All assuming it's not something someone's already intending to work on, of course - not looking to step on any toes!

Is there any design documentation around how you (the maintainers) envision the organiser component working in an ideal world? No worries if not, I can pull some stuff together from the area:organiser issues. I've just joined the discord too and would be keen to real-time chat if you think it'd be useful - I want to make sure I'm not duplicating effort after all!

In terms of timeframe I think I'd be able to manage, I'd aim to get started on it in the next couple of weeks and hopefully to be finished up with the code within 2-4 weeks from then.

Thanks for making and maintaining this wonderful tool!

**Comment by DJJo14** [comment]
I was looking for this function, and found it strange that it has not have it. it does not have to be a difficult function. so I when looking in Sonarr and others. and found thy have it in there. it is called ["{Series TitleFirstCharacter}" ](https://github.com/Sonarr/Sonarr/blob/7b694ea71d7f78bad5c03393c4cf6f7a28ada1cb/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L429) and in the[ web constructor](https://github.com/Sonarr/Sonarr/blob/d284c29b6f0e959c9b1b2f06d09c3070a7aeeed0/frontend/src/Settings/MediaManagement/Naming/NamingModal.js#L52)

so by adding after [this line](https://github.com/Lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L269)
`
tokenHandlers["{Artist FirstCharacter}"] = m => TitleThe( artist.Name ).Substring(0, 1).FirstCharToUpper();
`

and adding at the [web constructor](https://github.com/Lidarr/Lidarr/blob/e27c69cbb755c0fbb0a088759b2137872272d52a/frontend/src/Settings/MediaManagement/Naming/NamingModal.js#L46)

`
{ token: '{Artist FirstCharacter}', example: 'A' },
`

Will work? I do not know how to build C#. and I was only looking at the code for 15 min

**Comment by drdm1** [comment]
Hello

Wondering if there has been any progress on this one? I have my folders organized in this format and would very much like to see implemented.

**Comment by Qstick** [comment]
f7548f9bb70a6332c66ab90d38b7f6642518f102
