### ISSUE TITLE
Unable to search for Mungo’s Hi Fi

### ISSUE THREAD

**Issue by dippynark** [lidarr/Lidarr#1761]
**Describe the bug**
Unable to search for `Mungo’s Hi Fi`. This is due to the type of quote, so `Mungo's Hi Fi` would work. This feels similar to [this](https://github.com/lidarr/Lidarr/issues/376) but couldn't find any similar open issue.

**To Reproduce**
Add `Mungo’s Hi Fi` as an artist and run a search. Potentially the result depends on the tracker, but this is failing for the one I am using.

**Comment by ta264** [comment]
Duplicate #1180
