### ISSUE TITLE
Bug when auto searching on the artist level

### ISSUE THREAD

**Issue by emezrahi** [lidarr/Lidarr#177]
### System Information/Logs

**Lidarr Version:** 10.0.0.23398

**Operating System:** Windows 10

**.net Framework (Windows) or mono (macOS/Linux) Version:** 3.5 (with added 2.0)

**Link to Log Files (debug or trace):** https://pastebin.com/CTrPiE8h

**Browser (for UI bugs):** Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Additional Information

i was testing some things out this morning & came across a small bug. Here's exactly what i did:

1. add new artist: Metallica
2. Add all albums, monitored, but autosearch not enabled
3. went to artist & unticked all but one album
4. Clicked "Search monitored" on artist page.

The search automatically pulled 5 albums, none of which were ticked as monitored & failed to snatch the actual album monitored:

![1](https://user-images.githubusercontent.com/30807522/34618225-11ecec96-f20c-11e7-9afd-0fd860d0bf39.PNG)

**Comment by Qstick** [comment]
First off, THANKS for providing all info requested in the issue template. This makes life easy. I'll take a peak tonight

**Comment by Qstick** [comment]
Fixed 443e536005fc468768060843af1b66e5acef8eba
