### ISSUE TITLE
transmission download directory error

### ISSUE THREAD

**Issue by robjloranger** [lidarr/Lidarr#1771]
**Describe the bug**
I can change the title once I know what to call it.

There is an error reported in system > status:
```
You are using docker; download client Transmission places downloads in /data/complete but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.
```

However the download client is configured to use `/data/complete/music` and the remote path is mapped `/data/complete/music/` to `/downloads`.

The downloads both work and files are moved to the correct location once complete. I think this is just getting the configured default path from transmission, which in this case is `/data/complete`.

**To Reproduce**
I can provide docker-compose files if needed but as I said, I think the issue is where the download directory information comes from, not an actual error.

**Expected behavior**
No error.

**Logs**
Please request if needed.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.2.1878
 - Operating System docker on ubuntu 20.04
 - unsure, hotio/lidarr image

**Comment by Qstick** [comment]
Need Pull this https://github.com/Radarr/Radarr/commit/e09ca145d125a12016a6bf41a4971148bd2de870
