### ISSUE TITLE
Unable to Pull Metadata for Release Groups with non-audio releases

### ISSUE THREAD

**Issue by HaydoZV2** [lidarr/Lidarr#1779]
Description:
I am trying to import the release group Live at the Royal Albert Hall (2019) (https://musicbrainz.org/release-group/6d5817e3-56c5-4a7c-a6a5-1fdcff5732a9).

Logs contain the following error, however I am using a everything metadata profile.
`20-11-25 18:45:20.6|Warn|RefreshAlbumService|Album [6d5817e3-56c5-4a7c-a6a5-1fdcff5732a9][Live At The Royal Albert Hall] not found in metadata and is being deleted`
Note: #1136 indicates this error is due to Lidarr registering the release as a video release.

I believe the issue is caused by the first release of the group being a non-audio format which is obviously excluded by Lidarr.

Solution:
Lidarr should import release groups that have non-audio releases if at least one of the associated releases has an audio format.

**Comment by ta264** [comment]
Video releases are deliberately excluded

**Comment by HaydoZV2** [comment]
I understand that, but this is a release that has a video and separate audio release.

**Comment by HaydoZV2** [comment]
Some release groups of this type already import successfully such as Growing Up Live (https://musicbrainz.org/release-group/922aaa95-3b0f-4381-aea7-5aef1745fac4)

**Comment by ta264** [comment]
All the tracks on the CD release are marked as video
