### ISSUE TITLE
Add tidal-dl support

### ISSUE THREAD

**Issue by thisisawesome1994** [Lidarr/Lidarr#1782]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hi,

I would like you to add support for : https://github.com/yaronzz/Tidal-Media-Downloader

[AB#254](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/254)

**Comment by robca402** [comment]
I would also love this integration!

**Comment by thisisawesome1994** [comment]
Just to clarify, github.com/yaronzz/tidal-dl

**Comment by lejacobroy** [comment]
I've forked Tidal-dl ([Tidalrr](https://github.com/lejacobroy/Tidalrr)) to enhance it and I just pushed a quick&dirty update that should help you.
Add your Lidarr url and API key to the tidalrr.json config file. 
You can then use the command `python3 __init__.py --lidarr`.

Tidalrr will query your Lidarr instance and build a list of Wanted & Missing albums.
It will then match and download them (if available) from Tidal, to the path specified by Lidarr.

I'll continue to work on it in the next weeks to add functions and documentations.

Of course, you should not use is to steal or distribute music.

**Comment by cedvan** [comment]
Hi @lejacobroy ,

Tidalrr image is build to ARM, can you create a build to amd64 please ?

**Comment by thisisawesome1994** [comment]
I think you would need to parse html pages, instead of API requests to achieve this, but who knows. I would suggest the person reading this with the idea of continueing this project to take a look at deemix, and qobuz-dl by vitko

**Comment by jackmaninov** [comment]
The lidarr-extended docker image includes a script that check's lidarr's Wanted list and can grab tracks from tidal or deezer (though I've only tested with deezer). Might want to check that out: https://github.com/RandomNinjaAtk/docker-lidarr-extended

**Comment by lejacobroy** [comment]
I had a problem with my notifications so I never saw those replies.
Tidalrr is very much alive and duplicates a bit of the core functions of Lidarr.
The current way to use it, is to use Tidalrr to scan the missing albums in Lidarr. It will then match those on Tidal and download them.
It would be ideal to breakup the software into an Indexer integration and a Downloader, but it's not planned for the time being as it's a lot of work, and Tidalrr works for my use case.

Docker images to x64 and arm are available now @cedvan 

https://github.com/lejacobroy/Tidalrr

**Comment by ThinkSalat** [comment]
@lejacobroy you've made amazing progress on this! I'm going to have to check this out when I get a chacne

**Comment by Qstick** [comment]
The best way to integrate this into Lidarr is via a plugin ( see experimental plugins branch here #1829 ). Won't get a native integration
