### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by tehniemer** [lidarr/Lidarr#1789]
**Describe the bug**
Lidarr consumes a lot of memory compared to Sonarr and Radarr. Usage is all over the place.

**To Reproduce**
1. Start Lidarr
2. Do some tasks, manual importing, etc...
3. Wait
4. See memory slowly increase

**Expected behavior**
Memory use stays fairly constant. in the ~250mb range

**Screenshots**
![image](https://user-images.githubusercontent.com/11021632/101198878-bc8f5080-3629-11eb-8837-ee1582a027d3.png)

![image](https://user-images.githubusercontent.com/11021632/101198919-cb760300-3629-11eb-96f1-6964fec7234b.png)

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - Docker: Yes
 - Mono or.NET Core Version: 5.20.1.34
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch: hotio/lidarr:release

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[Trace Logs.zip](https://github.com/lidarr/Lidarr/files/5644585/Trace.Logs.zip)

**Comment by ta264** [comment]
Pretty sure this is fixed in 0.8 nightly

**Comment by tehniemer** [comment]
Is 0.8 backwards compatible with 0.7.2?

**Comment by ta264** [comment]
Its a one way upgrade

**Comment by tehniemer** [comment]
OK, thanks for the info. I'll make a copy of my current config before upgrading.
