### ISSUE TITLE
{Artist Name} is actually {Album Artist Name}

### ISSUE THREAD

**Issue by tehniemer** [lidarr/Lidarr#1791]
**Is your feature request related to a problem? Please describe.**
Now that 0.8 is starting to support various artists, the naming scheme needs updating. When naming files {Artist Name} uses the IDv3 `Album Artist` tag, there is no option for naming using the IDv3 `Artist` tag

**Describe the solution you'd like**
remap the current {Artist Name} field to the IDv3 `Artist` tag and add {Album Artist Name} that maps to the IDv3 `Album Artist` tag

![image](https://user-images.githubusercontent.com/11021632/101284807-7e1fa000-37a7-11eb-89b5-c6199eaec070.png)

**Comment by Daniel15** [comment]
@Qstick would you accept a pull request that implements this change? I'm not familiar with the Lidarr codebase but I'm very familiar with C#. My guess is that Artist Name is reading the artist from the Album but it should be reading it from the Track.

**Comment by Qstick** [comment]
@Daniel15 I think we would assuming it fixes it 😁 @ta264 is a bit more close to the tagging and data structure code now with various artists implemented. He may have an opinion on the matter as well.

**Comment by ta264** [comment]
I think my view is that we should have an extra tag "TrackArtist" rather than changing behaviour of the existing one

**Comment by tehniemer** [comment]
That would work for my needs

**Comment by Daniel15** [comment]
Submitted an initial PR here: #1910
