### ISSUE TITLE
Activity queue showing Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by OgreMHDW** [lidarr/Lidarr#1806]
I have several albums that have completed download. However they show downloaded with a yellow icon, normally indicating that Lidarr failed to import. When selecting the manual import (person icon) on the right of the download, it shows the album screen, but Object reference not set to an instance of an object (see screenshot).
![image](https://user-images.githubusercontent.com/4369476/102436085-ab045c00-3fcc-11eb-8050-4791ae344d9e.png)

**Comment by Qstick** [comment]
No template data.... 

Also, already fixed in PR #1800
