### ISSUE TITLE
Add a button to change the sort and filters to default

### ISSUE THREAD

**Issue by OgreMHDW** [lidarr/Lidarr#1818]
**Is your feature request related to a problem? Please describe.**
I have submitted a bug 1817, for an API sort key. As the user, I am unable to get back to the "default" sort when these type of issues occur? 

**Describe the solution you'd like**
I would recommend an enhancement to have a "reset sort and filter button".

**Describe alternatives you've considered**
NA

**Additional context**
This would be useful for a user that has sorting and wants to go back to the default view. Or if they filtered, they could easily select the button to remove all filters.

**Comment by Qstick** [comment]
You can get back to default sort by clearing browser cache... this button really wouldn't prevent that kind of issue as it could just as easily be the default we break...
