### ISSUE TITLE
Provide a way to start lidarr in manual mode so all scheduled tasks do not run.  Provide ability to stop all or start all scheduled tasks for debugging purposes

### ISSUE THREAD

**Issue by p1rps01** [lidarr/Lidarr#1820]
**Is your feature request related to a problem? Please describe.**
Yes trying to test downloading via sabnzbd client and perform manual imports of folders after following instructions in lidarr wiki to fix permission issues on the download directory.  I have a large number of folders in my \data\usenet\music (downloads) folder that I need to manually import.  

As soon as I start lidarr it starts running scheduled task refresh artist, housekeeping, and other tasks that consume cpu and memory that compete with my ability to browse folders to perform manual imports of a large number of folders in my usenet download directory.

**Describe the solution you'd like**
I want the ability to start lidarr in manual mode so that all scheduled tasks do not run.  I also in the tasks submenu of lidarr would like the ability to stop all tasks or start all tasks via a button.  

**Describe alternatives you've considered**
Allow users to stop individual tasks by putting check boxes beside tasks they do or do not want to run.

**Additional context**
No other suggestions.

**Comment by p1rps01** [comment]
Clarification:  Would also like the ability to stop or start tasks running in the queue in the system.tasks submenu (queue) section.

**Comment by bakerboy448** [comment]
Uh what are you running lidarr on...?

**Comment by p1rps01** [comment]
Running lidarr on a qnap server via a docker container with 80TB of storage, 64 of memory, 1 4tb ssd drive, and a i5 intel cpu

**Comment by Qstick** [comment]
Why not leave it on and let it finish? We have no plans for this at current time
