### ISSUE TITLE
Randomly monitoring „new“ albums

### ISSUE THREAD

**Issue by wieluk** [Lidarr/Lidarr#1831]
So I have set all artists to existing only but lidarr monitors albums that are newly added to musicbrainz I guess. What can I do to not monitor albums added to musicbrainz ?

**Platform Information (please complete the following information):**
 - OS: rasbian lite
 - Docker: No
 - Mono or.NET Core Version: 5.18.1.0
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch: master

[AB#264](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/264)

**Comment by ta264** [comment]
It's a binary choice - if the artist is monitored, all new albums will be monitored.  If the artist is not monitored, new albums will not be monitored.

The "existing only" option you mention is only available as a one off to edit monitored status in album studio

**Comment by wieluk** [comment]
Yeah I understand that now but my problem is that people add old songs and singles to musicbrainz and then lidarr wants to download them it is kinda anoying

**Comment by Redundant1** [comment]
This is an issue for me, as well, but for a different reason.  I only put albums I own in Lidarr and I want it to grab those albums and upgrade them until the cutoff is met.  So, I may have only 2 albums from a given artist being monitored.  If a new album is released for that artist, that new one also gets monitored, which I don't want.  If I unmonitor the artist, then the albums I have monitored will no longer be upgraded, even if the cutoff is unmet.

Let me know if you'd prefer I open this as a separate issue/feature request.

**Comment by mediacrave** [comment]
Lidarr is pretty decent, but this issue definitely makes it very frustrating as it keeps grabbing old live albums I don't want when they get added to MusicBrainz

**Comment by wieluk** [comment]
Yea maybe it should let you choose somewhere how old a album is allowed to be to set as montiored when added by musicbrainz because people sometimes add duplicates or stuff from 2000 ...

**Comment by crafty35a** [comment]
Apologies for the duplicate issue, the title here didn't match my search terms. Reposting my thoughts here.

There are at least two possible solutions that I can think of:

- Only monitor newly found albums if the release date is in the future
- Don't automatically monitor newly added albums that share a name and release date with an existing album (I assume some bands have multiple albums of the same name, but also checking the release date would avoid this potential issue)

**Comment by kromsam** [comment]
Any developments on this issue? This is really one of my major gripes with Lidarr. I have to actively maintain Lidarr all the time because it fills up my drive with albums I don't want.

**Comment by wessel145** [comment]
I think this should also be a general setting instead of a per artist setting, in my case I import my spotify liked albums, when a new album is liked on my spotify account. The 'monitor' option is set to 'specific album only'. it works as intended, as only the album will be added and monitored.

During the regular 'update' task, it will refresh the artist and 'add' all the other albums from that artist to the artist in Lidarr. Because Lidarr thinks this is 'a new album' it will be put into monitored state.

**Comment by Davo1624** [comment]
Just to add, for 'Future Albums' it would be great if when an album for a monitored artist is added to MusicBrainz, Lidarr would parse the 'Country/Date' field for the release and then do a calculation of the current date +/- 7 days (or whatever) and compare that against the 'Date' provided by MusizBrainz. If the 'DATE' does not fall within the 'x' amount of days the album is not considered a future release and would not be grabbed.

Attached is a screenshot of the MB site showing the Country/Date field (year/month/day) for reference. 

![image](https://user-images.githubusercontent.com/85573606/135154813-be13862c-0549-4a24-9acf-5e904e947a38.png)

**Comment by kromsam** [comment]
> I have to actively maintain Lidarr all the time because it fills up my drive with albums I don't want.

This is my use case. My Lidarr is synced with my Spotify albums. All the albums that I save in Spotify are added and monitored in Lidarr. But then, when a new album by this artist is added on Musicbrainz, Lidarr automatically monitors it.

This is very frustrating. Especially with classic composers, as new albums are added almost daily.

My request is very simple: Monitor the albums that I have added through my Spotify lists and manually. **And do not add any other albums automatically.**

To be honest, I am looking for a viable alternative for Lidarr at this point. This request has been open for almost a year now, and there does not seem to be any development on what I think is a very simple fix. I want to manage my own collection, and not let Lidarr do it.

**Comment by bakerboy448** [comment]
> This request has been open for almost a year now, and there does not seem to be any development on what I think is a very simple fix. 

The main development team is split across 4 apps: Prowlarr, Radarr, Readarr, and Lidarr.
There are only 3-4ish active developers who work on this, and of those exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

**Comment by kromsam** [comment]
@bakerboy448 I'm sorry. I should have stated that otherwise, and just be nicer. I just find it sad that this very useful software has this seemingly minor flaw that just makes it a hassle to use sometimes.

But to get a bit more constructive...

I recently installed Readarr, and I noticed that that has exactly the kind of settings opened that would fix this problem. When you add books from lists, you can make sure that only the one book is monitored and no new books are added.

![Screenshot 2022-01-03 at 18-07-13 General Import List Settings - Readarr](https://user-images.githubusercontent.com/47101903/147959383-50e604d2-1807-44a2-9fd8-fd4d83ae9c6d.png)

![Screenshot 2022-01-03 at 18-07-27 General Import List Settings - Readarr](https://user-images.githubusercontent.com/47101903/147959387-e8d090f9-319c-425b-81f3-778312fdb149.png)

I don't know how well all these *arrs are integrated, but bringing these settings to Lidarr would fix this issue for me.

All the best,

**Comment by crafty35a** [comment]
Good find, @kromsam.

I don't use Readarr, so I just installed it to check what that setting does. Here is a screenshot, for anyone else unaware:
![image](https://user-images.githubusercontent.com/1082003/147966470-c54b960e-9107-4b17-a06d-ab720e75ff5b.png)

A Lidarr setting similar to the "Monitor new books released after the newest existing book" option would totally solve my issues with Lidarr downloading duplicate copies of albums every time someone mistakenly makes a duplicate release group in Musicbrainz. Here's hoping we can get that feature ported over at some point.

**Comment by kromsam** [comment]
I think this is the relevant commit in Readarr:

https://github.com/Readarr/Readarr/commit/c51ae664aa6e6f5330be67e68476af76c55352f5

Maybe its author @ta264 can give an indication how difficult it would be to implement these changes to Lidarr?

**Comment by guipace** [comment]
Adding my +1 to this request. Lidarr is practically unusable for me at the moment since it's constantly downloading "new" albums and polluting my library.
I appreciate all the work devs put into the Arr suite of apps!

**Comment by kromsam** [comment]
Thanks for putting in the work @ta264 ! I wonder how I can use this merge for the artists that are already in my library? And how do I use it for the artists that I add through lists? (as that is basically the only way I add albums to Lidarr).

**Comment by guipace** [comment]
Has this fix been included in a release? Wondering when we'll see it in the wild.

**Comment by bakerboy448** [comment]
> Has this fix been included in a release? Wondering when we'll see it in the wild.

It should be in nightly and develop.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.
