### ISSUE TITLE
Option to use freeleech tokens for gazelle API indexers

### ISSUE THREAD

**Issue by linareyne** [lidarr/Lidarr#1841]
**Is your feature request related to a problem? Please describe.**
Many Gazelle-based torrent trackers, including those with presets in Lidarr, have the ability to easily use freeleech tokens for downloads when available. I want an option to use them whenever available.

**Describe the solution you'd like**
A checkbox in gazelle API indexer configs - "Use freeleech tokens when available"

**Describe alternatives you've considered**
I was using Jackett for my gazelle trackers until I realized that Lidarr has native support for them. Was working in Jackett, so I may switch back to that.

**Comment by Qstick** [comment]
58e23c934b0d89a1edabd76f2274614a93cedd13
