### ISSUE TITLE
Cant import 

### ISSUE THREAD

**Issue by DravenSA** [lidarr/Lidarr#1855]
My music is placed D:/Music/Music/{Artist Name}/{Album}
But when i try to import i can go as far as D:/Music/
I know someone might say why not move it to Just D:/Music/ But this is not am option as i have several other folders in the Root Music like Live concerts, Radio Pods, etc.

I get a warning 
"Mapped network drives are not available when running as a Windows Service, see the FAQ for more information."
But my D Drive is a local drive

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/lidarr/) or [Discord](https://discord.gg/5WQc3S8)

permissions issues....
