### ISSUE TITLE
Status is TBA for all unimported files

### ISSUE THREAD

**Issue by esawtooth** [lidarr/Lidarr#1856]
I am seeing the status column to be "?" which upon hovering shows "TBA". This is the case for really old media as well. Any recommendations on what could be wrong and how I can debug this?

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/lidarr/) or [Discord](https://discord.gg/5WQc3S8)

also please don’t use third party GitHub apps to create issues; they ignore templates
