### ISSUE TITLE
Track naming uses artist name of album rather than song

### ISSUE THREAD

**Issue by Daniel15** [lidarr/Lidarr#1881]
**Describe the bug**
If the "Rename Tracks" option is enabled, the "`{Artist Name}`" token in the track format uses the album's artist rather than the individual song's artist. This means that when importing a "Various Artists" album, each song is renamed to "Various Artists" instead of the actual correct artist.

**To Reproduce**
1. Use 0.8.0 nightly builds
2. Settings -> Media Management -> Enable "Rename Tracks" and set "Track Format" to `{track:00} - {Artist Name} - {Track Title}`
3. Wanted -> Manual Import -> import a "various artists" compilation CD

**Expected behavior**
Songs are named like `01 - Michael Jackson - Bad.mp3`

**Actual behaviour**
Songs are named like `01 - Various Artists - Bad.mp3`

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Debian Bullseye (testing)
 - Docker: Yes (linuxserver.io nightly)
 - Mono or.NET Core Version: .NET Core 3.1.10
 - Lidarr Version: 0.8.0.1989

**Comment by Qstick** [comment]
Pretty much same as #1791

**Comment by Daniel15** [comment]
@Qstick Thanks - I searched before posting but somehow missed that one.

**Comment by Qstick** [comment]
> @Qstick Thanks - I searched before posting but somehow missed that one.

Yea it needs a better name
