### ISSUE TITLE
Completed Download Handing warning persists

### ISSUE THREAD

**Issue by ItchyData** [lidarr/Lidarr#1882]
**Describe the bug**
According to the wiki, you are supposed to be able to [remove the warning](https://github.com/Lidarr/Lidarr/wiki/Health-checks#enable-completed-download-handling) about Completed Download Handling being disabled by enabling, then disabling Completed Download Handling. In practice, I don't find that this works. The warning just comes back when Completed Download Handling is disabled again. 

**To Reproduce**
1. With Completed Download Handling disabled, enable it. Click Save. The warning goes away.
2. Then disable Completed Download Handling. Click Save. The warning comes back and is persistent. 

**Expected behavior**
The warning should stay off if you enable then disable Completed Download Handling as per the wiki. If this is not the best way to implement this feature, perhaps a way to turn off specific warnings would be useful. 

**Screenshots**
<img width="861" alt="Screen Shot 2021-01-10 at 9 22 14 AM" src="https://user-images.githubusercontent.com/76266146/104125532-57640480-5325-11eb-8a1a-cc600bd38cd9.png">

**Platform Information (please complete the following information):**
 - OS: macOS Big Sur 11.1 (happened in Catalina too)
 - Docker: No
 - Mono or.NET Core Version: Mono 6.12.0.90
 - Browser and Version: All browsers
 - Lidarr Version [e.g. 0.3.0.430]: 0.7.2.1878
 - Lidarr Branch [e.g. master]: master

**Trace Logs**
https://pastebin.com/1epLBc4U

**Comment by Qstick** [comment]
> **Describe the bug**
> According to the wiki, you are supposed to be able to [remove the warning](https://github.com/Lidarr/Lidarr/wiki/Health-checks#enable-completed-download-handling) about Completed Download Handling being disabled by enabling, then disabling Completed Download Handling. In practice, I don't find that this works. The warning just comes back when Completed Download Handling is disabled again.
> 

@bakerboy448 This isn't how it works in any of the arr, we always warn when its off... Where did this wiki wording come from?

**Comment by bakerboy448** [comment]
@Drazzilb08  see Q's comment ^

**Comment by bakerboy448** [comment]
@Qstick OP is referring to the lidarr GitHub wiki per his link.
So yes, where'd that come from?

I'm assuming drazz pulled it into the new wiki as it was on the old wiki

**Comment by Drazzilb08** [comment]
> According to the wiki, you are supposed to be able to [remove the warning](https://github.com/Lidarr/Lidarr/wiki/Health-checks#enable-completed-download-handling) about Completed Download Handling being disabled by enabling, then disabling Completed Download Handling. In practice, I don't find that this works. The warning just comes back when Completed Download Handling is disabled again.

Yes this isn't the case. That wiki article needs to be updated and the GH wiki needs to refer to https://wiki.servarr.com 

> If you don't wish to enable Completed Download Handling at all and wants to remove the warning. You can enable and then disable Completed Download Handling. This obviously isn't recommended.

This is what is being referred to for this issue..

**Comment by Drazzilb08** [comment]
Update:
All instances of that line have been removed from https://wiki.servarr.com as it is a false statement. 
I am unaware of a way to disable the warning for complete download handling. Perhaps @Qstick or @bakerboy448 might have some insight into that one or anything being thought of or worked.

**Comment by Qstick** [comment]
Thanks guys
