### ISSUE TITLE
Can't remove unmatched items from queue

### ISSUE THREAD

**Issue by crafty35a** [Lidarr/Lidarr#1887]
**Describe the bug**
When unmatched items appear in the download queue, they cannot be removed with the "Remove from queue" button. I am leaving "Remove from download client"  and "Blacklist release " unchecked.

**To Reproduce**
1. Queue
2. Click the X (Remove from queue) button for an unmatched item (Album Title column will say "-")
3. Uncheck both options
4. Click Remove
5. Nothing happens, item is still shown in the queue

**Expected behavior**
Item is removed from the Queue page

**Screenshots**
![image](https://user-images.githubusercontent.com/1082003/104461398-49102580-557d-11eb-9c4c-02ccfc2a1e6a.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10 20H2
 - Docker: No
 - .NET Core 3.1.10
 - Lidarr Version 0.8.0.1996
 - Lidarr Branch nightly

**Trace Logs**
21-1-13 08:44:10.9|Warn|IgnoredDownloadService|Unable to ignore download for unknown artist/album

**Comment by crafty35a** [comment]
I am aware that manually importing these items might work to remove them from the queue, but these are all mistaken downloads that have been accumulating over a period of months, which I don't want in my library (e.g. Singles with the same name as an album, which Lidarr mistakenly grabbed instead of the album).

**Comment by spencerhughes** [comment]
I additionally have this issue. Sometimes it works, but most of the time it does not. I'm running 0.8.1.2135-ls68 by linuxserver.io and also get `22-1-2 20:31:06.4|Warn|IgnoredDownloadService|Unable to ignore download for unknown artist/album` in the logs

**Comment by CaldwellOne** [comment]
I have this issue also, I have tried many things including uninstalling/reinstalling.  Windows 10.  50 items and growing in my queue.  thanks for anything you can do.

**Comment by sarlan19** [comment]
I had the same issue. When I removed the category from the download client they dissapeard from lidarr
