### ISSUE TITLE
Player for preview

### ISSUE THREAD

**Issue by costaht** [lidarr/Lidarr#1890]
**Describe the solution you'd like**
I would like to request a Play button right next to each audio file, close to the trashcan icon. The idea is to allow us to check "what song is that" one and if the case, delete it.

![image](https://user-images.githubusercontent.com/50637431/104525957-53f3a600-55cf-11eb-845d-f42151d8dca2.png)

- Playing the second audio should stop the first one.
- A deleted track should not be downloaded automatically again.

**Describe alternatives you've considered**
Play the tracks on a separate player and manually delete them.

Thanks

**Comment by Qstick** [comment]
Dupe #770 #319
