### ISSUE TITLE
Add parser case for ruTracker format

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#191]
`(genre) ?[format] artist - album - year, FLAC/MP3 (extras) lossless/xxx kbps`

**Comment by storrgie** [comment]
Did this not make it into the recent release? (Assumed to see rutracker listed under indexers).

**Comment by Qstick** [comment]
This was in the original release. this doesn't add a rutracker indexer, just a parsing case so that we can read rutracker results. You'll have to use Jackett still.

**Comment by storrgie** [comment]
understood, thanks!
