### ISSUE TITLE
Manually search for an specific album brings unrelated results

### ISSUE THREAD

**Issue by Zamana** [lidarr/Lidarr#1916]
**Describe the bug**
When I manually search for an specific album, unrelated results are showing, generally none of them is related with the query.

**To Reproduce**
1. Go to the albums page of an Artist
2. Click on the "Interactive Search" of an specific missing album
3. Check the results.

**Expected behavior**
I expected to see only a list of related results, or none, if nothing was found.

**Screenshots**
In this case, I'm searching for the album "Before the Fire", from the "Rival Sons" band.
![rival_sons_before_the_fire](https://user-images.githubusercontent.com/6900313/104849143-f7420500-58c6-11eb-853a-7d273cd68155.png)

**Platform Information (please complete the following information):**
 - OS: VM with Debian 10 in a FreeNAS server
 - Docker: YES
 - Mono or.NET Core Version: Mono JIT compiler version 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch: develop

**Trace Logs**
Attached
[_lidarr_logs.txt](https://github.com/lidarr/Lidarr/files/5826412/_lidarr_logs.txt)

**Comment by bakerboy448** [comment]
Info Logs are useless bud.  GH Template specifically asks for trace logs. (and given this is a beta you probs want to be always running debug if not trace)

Pretty sure it's an indexer/jackett problem...
https://wiki.servarr.com/Lidarr_Troubleshooting#Searches_Indexers_and_Trackers

Support Requests -> [Reddit](https://www.reddit.com/r/lidarr/) or [Discord](https://discord.gg/5WQc3S8)

Happy to reopen if it is actually a bug, but everytime this is seen it's an indexer or jackett /all issue

**Comment by Zamana** [comment]
Hi!

Please, don't get me wrong for reopening the case. I'm just try to get things clear.

**Trace logs**

I really enable Trace logs. I don't know why they provided only that information before a docker restart. I'm sending another log.

![Screen Shot 2021-01-17 at 15 01 14](https://user-images.githubusercontent.com/6900313/104851775-c7e6c480-58d5-11eb-96af-3db4133beadc.png)

[_lidarr_logs-3.txt](https://github.com/lidarr/Lidarr/files/5826558/_lidarr_logs-3.txt)

**Indexers**

I agree that it could be something related with the indexers. But the question is that when I search directly through the indexer, I found exact replies for my query:
![Screen Shot 2021-01-17 at 15 02 25](https://user-images.githubusercontent.com/6900313/104851797-d9c86780-58d5-11eb-8a76-898141521ad2.png)

So, the question now is: if it is something related with the indexers, where should I look in order to identify the cause of this issue?

**Comment by bakerboy448** [comment]
1) those are not trace logs....see the wiki page previously linked for details
2) we strongly prefer to not give support via github as it spams people's inbox.... -> discord or reddit please; you can link them here for context, but bring some trace logs
3) Wiki Troubleshooting indicates how to troubleshoot.
3b) don't use jackett's /all endpoint
