### ISSUE TITLE
Manual Import - Select Album Release Dropdown opens in the wrong direction

### ISSUE THREAD

**Issue by lloesche** [lidarr/Lidarr#1941]
When manually importing an album and using the "Select Album Release" function the resulting dropdown expands to the left instead of the right like it does when editing the Album.

For releases with a long list of country names this essentially makes the list unreadable:
![Screenshot 2021-01-25 210048](https://user-images.githubusercontent.com/2124094/105759248-821ea180-5f50-11eb-92a5-cdfe54b6d46c.png)

My first attempt at a "workaround" was to just zoom out the browser, but even at maximum zoom the list is just ridiculously long and renders the import function unusable:
![Screenshot 2021-01-25 210111](https://user-images.githubusercontent.com/2124094/105759375-ada18c00-5f50-11eb-94ba-6416007af67b.png)

**To Reproduce**

Manually import any unmapped file to an album with a release containing a very long release name.
For instance:
- Artist `Electric Light Orchestra`
- Album `Face the Music`

**Expected behavior**

The List should expand to the right instead of the left, like it does when editing an Album:
![Screenshot 2021-01-25 210324](https://user-images.githubusercontent.com/2124094/105759573-e3467500-5f50-11eb-8eed-f29c8fda8090.png)

I don't know if this can be controlled via a style and is just coincidence that it works on the album screen.
Alternatively it might make sense to just crop such long release names instead of making all other releases unreadable.

**Platform Information (please complete the following information):**
 - OS: Windows 10 OS Version 2004 (Build 19041.746)
 - Browser and Version: Chrome 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
 - Screen Resolution: 1440p

**Comment by ta264** [comment]
Pretty sure this is fixed in 0.8 nightly but you neglected to fill out the version :(
