### ISSUE TITLE
Unable to start Lidarr with PFX certificate

### ISSUE THREAD

**Issue by Eds1989** [lidarr/Lidarr#1942]
**Describe the bug**
After Lidarr updated, my certificate settings were removed. After populating the certificate path to my PFX and entering the certificate password, Lidarr prompts to restart but fails to start the Windows service again.
Logs show a certificate error.

**To Reproduce**
Update to latest Lidarr build v8
Add path to certficate PFX and password into settings
Restart Lidarr

**Expected behavior**
Lidarr should load normally

**Platform Information (please complete the following information):**
 - OS: Windows Server 2019
 - Docker: No
 - Mono or .NET Version (System -> Status): .net Core 3.1.10
 - Browser and Version (Only needed for UI issues): 
 - Lidarr Version: 0.8.0.2041
 - Lidarr Branch: Develop

**Trace Logs**
[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/5876489/Lidarr.trace.txt)

**Comment by bakerboy448** [comment]
@ta264  @Qstick any relation to the HTTPS issues seen on Radarr?
https://github.com/Radarr/Radarr/issues/5444

**Comment by Eds1989** [comment]
I'm sure you've spotted I raised that Radarr bug as well.

Interestingly, Radarr starts and loads, but fails to login.
Lidarr just won't start at all, using the same certificate.

**Comment by gconcepts** [comment]
I'm experiencing the same issue after Lidarr update. @Eds1989 When I had the same issue with Radarr, I ended up populating the URL Base with "/radarr" and that allowed me to login when accessing via https

**Comment by Eds1989** [comment]
Yes that seems to have worked for me in Radarr! Thanks

**Comment by gold007eye** [comment]
I am having the same issue where I can't get lidarr to start since the 8.0 updates.  I have tried adding /lidarr to the URL Base as well and still no dice.  This is making it totally unusable for me and it was perfect until the update.

**Comment by bakerboy448** [comment]
@gold007eye should work if you try HTTP to lidarr not HTTPS

**Comment by gconcepts** [comment]
> I am having the same issue where I can't get lidarr to start since the 8.0 updates. I have tried adding /lidarr to the URL Base as well and still no dice. This is making it totally unusable for me and it was perfect until the update.

Find your config.xml and remove the values for the below and save then startup

<SslCertPath></SslCertPath>
  <SslCertPassword></SslCertPassword>

**Comment by gold007eye** [comment]
> 
> 
> @gold007eye should work if you try HTTP to lidarr not HTTPS

Problem is I need to use HTTPS as I have always done before this and also once I save the changes in the settings and restart lidarr I can't get in either way.  I then have to revert to a backup and start the cycle over again.  I just need to be able to use SSL cert and HTTPS as we were able to before the big update.

**Comment by bakerboy448** [comment]
@gold007eye you’re probably going to be waiting awhile then....

you don’t need to restore a backup; just edit your config to disable xml

I find it very hard to believe you **need** HTTPS and cannot do a reverse proxy to do more proper https with say nginx. And nginx is more secure than any less common HTTPS implementations (I.e. the ARRs)

**Comment by gold007eye** [comment]
@bakerboy448 I realized I didn't need to restore from backup after reading @gconcepts reply.  I honestly haven't had time to get a reverse proxy setup I have spent a lot of time researching it, but with a lot of confusion on getting it implemented where I am going across 2 different OS platforms.

**Comment by Eds1989** [comment]
I personally haven't been able to deploy a full reverse proxy in my home environment due to using RD gateway, and not being able to find a way to get this working behind a reverse proxy.
As such, I am having to publish my services on differing ports, and thus I need to use application level HTTPS rather than at the proxy level.

Any idea what it is that causes it to fail to start when specifying SSL cert settings, given it worked perfectly well before?

**Comment by RobinDadswell** [comment]
PR fixed this on the 24th Feb - issue should have been closed then
