### ISSUE TITLE
Unable to update to v0.8.0.2041 on Synology

### ISSUE THREAD

**Issue by houndtt** [lidarr/Lidarr#1943]
**Describe the bug**

Using the built-in update interface, when I trigger the update from v0.7.2.1878 to v0.8.0.2041 it appears to run but does not complete. Lidarr does not actually restart at the end of the update function and stays at the previous version.

**To Reproduce**

1. From the System menu, choose Updates
2. Click on the Install Latest button
3. Wait on the process to complete but it does not (even after several hours)

**Expected behavior**

Updater completes and Lidar restarts successfully at the updated version.

**Screenshots**

N/A

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2.3-25426 Update 3
 - Docker: No
 - Mono or .NET Version (System -> Status): Mono 5.20.1.34
 - Browser and Version (Only needed for UI issues): N/A
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch: develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Lidarr.trace.txt - https://pastebin.com/kTNkYDDZ

**Comment by ta264** [comment]
Need the updater logs too. https://wiki.servarr.com/Lidarr_Troubleshooting#Update_Logs_Location

**Comment by houndtt** [comment]
> Need the updater logs too. https://wiki.servarr.com/Lidarr_Troubleshooting#Update_Logs_Location

I've checked in the folder `/usr/local/lidarr/var/.config/Lidarr/UpdateLogs` however this seems to contain only one file which seems to be the previous update from 0.7.1.1381 to version 0.7.2.1878. It does not appear that one for the update to 0.8.0.2041 was created.

Only update log in the folder:
UpdateLogs-2021.01.27-07.00.txt - https://pastebin.com/7pxMTMpd

**Comment by necmes** [comment]
same here

**Comment by Qstick** [comment]
> > Need the updater logs too. https://wiki.servarr.com/Lidarr_Troubleshooting#Update_Logs_Location
> 
> I've checked in the folder `/usr/local/lidarr/var/.config/Lidarr/UpdateLogs` however this seems to contain only one file which seems to be the previous update from 0.7.1.1381 to version 0.7.2.1878. It does not appear that one for the update to 0.8.0.2041 was created.
> 
> Only update log in the folder:
> UpdateLogs-2021.01.27-07.00.txt - https://pastebin.com/7pxMTMpd

This is odd, when did you update from 0.7.1.1381 to 0.7.2 originally? I assume it wasn't today as the log says?

**Comment by houndtt** [comment]
> This is odd, when did you update from 0.7.1.1381 to 0.7.2 originally? I assume it wasn't today as the log says?

This was after I did a clean install today so this is why you see both updates attempted on the same day. I also conducted some tests by building a new Synology package with this version but this also failed as per this comment: https://github.com/SynoCommunity/spksrc/pull/4410#issuecomment-768274430

Coming out of this additional testing however, I did see the following line showing up in the error logs:
`System.ComponentModel.Win32Exception: ApplicationName='ldd', CommandLine='/bin/ls', CurrentDirectory='', Native error= Cannot find the specified file`

This I believe to be the root cause of the issue as I don't believe that the Synology DSM OS has this '[ldd](https://man7.org/linux/man-pages/man1/ldd.1.html)' binary. Based on a review of the code, this appears to be a single line added to the code to check if the OS is LinuxMusl: 
https://github.com/lidarr/Lidarr/blob/14c3d31c2bf64893e9e7c137a04bfc096e6d36fe/src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs#L106

If we can adapt the code to check for this type of OS in a different way in the `private static bool IsMusl()` function call then I believe this will resolve the issue.

**Comment by Qstick** [comment]
Ah yea, we fixed this on Radarr. I'll pull it over

**Comment by Qstick** [comment]
https://github.com/lidarr/Lidarr/commit/3fcd8af697e6570ba79851dfe58c071982d3ab30

**Comment by Qstick** [comment]
Can you guys confirm we are good with the new update 2042?

**Comment by houndtt** [comment]
Yes, I've done an in-app upgrade as well as built a Synology package (https://github.com/SynoCommunity/spksrc/issues/4409#issuecomment-769484307) and done an upgrade that way and all is working well for me.

**Comment by terrierl** [comment]
I completed an in app update on synology 1019+, but now I am getting the following notification:

Please upgrade to the .NET Core version of Lidarr

**Comment by bakerboy448** [comment]
That’ll be due to the SynoCommunity still not having netcore packages for anything (last I checked)

there were some comments on Radarr and Jackett GHI over there

**Comment by necmes** [comment]
thanks for correction.
working now.
