### ISSUE TITLE
Error: Failed to load Queue

### ISSUE THREAD

**Issue by houndtt** [lidarr/Lidarr#1944]
**Describe the bug**

Activity > Queue fails to display and shows an error "API Error: BadRequest: Invalid sort key artist.sortName" in the Events

**To Reproduce**

1. Go to Activity
2. Click on Queue
3. Message is shown: Failed to load Queue

**Expected behavior**

The queue of items to be downloaded is shown

**Screenshots**

N/A

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2.3-25426 Update 3
 - Docker: No
 - Mono or .NET Version (System -> Status): Mono 5.20.1.34
 - Browser and Version (Only needed for UI issues): N/A
 - Lidarr Version: 0.8.0.2042
 - Lidarr Branch: develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Lidarr.trace.txt - https://pastebin.com/u7Gwewvv

**Comment by Qstick** [comment]
Burn your browser cache. That should fix it, its got a old sortkey cached.

**Comment by houndtt** [comment]
wow! didn't think it would be that simple. this did solve the problem, thanks!
