### ISSUE TITLE
Root folder setup profile error

### ISSUE THREAD

**Issue by Mrpink200** [lidarr/Lidarr#1995]
Hi

there s a recurring annoying  very simple bug in the initial root folder setup.
It s not possible to set metadata profile "standard albums" but only to monitor the albums found in the root folder and the future release.

to do so, as far it is documented, we would need to choose 
Monitor = Existing Albums

But if so, it mark all the releases as monitored

Could you fix it and limit the enable monitored to the existing found album files in the root folder + the future releases

Many thx !

**Comment by bakerboy448** [comment]
Closing template not followed;
