### ISSUE TITLE
Root folder setup profile error

### ISSUE THREAD

**Issue by Mrpink200** [Lidarr/Lidarr#2001]
**Describe the bug**
Hi. there s a recurring annoying very simple bug in the initial root folder setup.
It s not possible to set metadata profile "standard albums" but only to monitor the albums found in the root folder and the future release.

to do so, as far it is documented, we would need to choose
Monitor = Existing Albums
But if so, it mark all the releases as monitored
Could you fix it and limit the enable monitored to the existing found album files in the root folder + the future releases

Many thx !

**To Reproduce**
1. Go to '...' settings/mediamanagement
2. Click on + to add a Root Folder
3. Add your folder. Select Monitor = Existing Albums and metadata profile = None
4. Wait for the Scan.
5. Go To Library/Album Studio : Only your albums appears and they are All Monitor

=> OK

But, if you want to have all the albums releases by your artists but only want to monitor your existing abums (to ugrade quality) and look for the forthcoming releases. In that case, do 
1. Go to '...' settings/mediamanagement
2. Click on + to add a Root Folder
3. Add your folder. Select Monitor = Existing Albums and metadata profile= **Standard Albums**
4. Wait for the Scan.
5. Go To Library/Album Studio : All the albums releases by your artists are all monitor despite you only wanted to have them all listed but only mark the one you already have and the forthcoming ones to be monitored.

=> NOT OK and really annoying

**Expected behavior**
Have all the albums releases by an artist listed, but mark only the ones you already have and the forthcoming ones to be monitored.

**Screenshots**
NA

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2
 - Docker: YES
 - Version: 0.8.0.2062
 - Package Version : nightly-2e388d7 by hotio 
 - .NET Core : Yes (3.1.10)

**Trace Logs**
Please ask if needed.

[AB#207](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/207)

**Comment by bakerboy448** [comment]
The existing Monitor Albums `Existing Albums - Monitor albums that have files or have not released yet` combined with Monitor New Albums `None - Don't monitor any new albums`  should have taken care of this, no?

**Comment by bakerboy448** [comment]
closing pending OP responding.

Believe the requested monitoring options are there with v1
