### ISSUE TITLE
Lots of Flac24 Releases are classified as Unknown

### ISSUE THREAD

**Issue by Mrpink200** [Lidarr/Lidarr#2002]
**Describe the bug**
Hi. Lots of flac 24 releases are not match correctly and are moved to unknown profile.
I tried several way to bypass but i think the only way would be to add custom words in the release names to match more releases.
As example if a release only have "TR24" in its release name, lidarr affect the release to unknown.

**To Reproduce**
Search any album release with TR24 in the file name. For example search : [TR24][OF] The Weeknd - The Highlights - 2021 (R&B) on rutorrent. The realease will be mark as unknown, not Flac24

**Screenshots**
the way we can custom release profile is great but is not enough to bypass the misclassification
on my own i ve made :

![image](https://user-images.githubusercontent.com/7417251/107441011-dc188d00-6b34-11eb-8fe1-2a0800767d8c.png)

but it only help with the release order choice

**Expected behavior**
to add words in the flac24 release association (even custom like for the preferences above) to help the right classification

**Platform Information (please complete the following information):**
- OS: Synology DSM 6.2
- Docker: YES
- Version: 0.8.0.2062
- Package Version : nightly-2e388d7 by hotio
- .NET Core : Yes (3.1.10)

**Trace Logs**
Please ask if needed.

[AB#208](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/208)

**Comment by Mrpink200** [comment]
Could you please simply add the word tr24 in the dearch strings for flac24 identification ?
Something else but relative, if it could be possible to move at the end of a release name everything between [] it would help a lot for release identification on torrents sites like rutracker that often start their flac24 release names like :
[TR24[OF][192kHz] xxxxxx

Many thx !!!

**Comment by Mrpink200** [comment]
by the way, next release of Jackett will move the genres or any other stuff between brackets at the end of a release.
https://github.com/Jackett/Jackett/pull/11125
it will solve part of the problem, but considering the word tr24 as a keysearch for flac24 releases that do not content flac or flac24 in the release name still remains

**Comment by Mrpink200** [comment]
any news to add tr24 as a flac24 keyword ??? 
it would solve so many "unknown" releases 
the work done with jacket team now solves the rerealease years versions (most of them are because flac24 remaster) ... remains the track24 not reconized as a flac 24 keyword

<img width="1056" alt="Capture d’écran 2021-03-14 à 13 20 09" src="https://user-images.githubusercontent.com/7417251/111068472-22ad2e80-84c9-11eb-997f-deaca5c8e433.png">

@Qstick , @ta264  ?

**Comment by Mrpink200** [comment]
anyone ??

**Comment by Mrpink200** [comment]
@majora2007 ?

**Comment by Qstick** [comment]
This will happen when it happens, if you continue to spam random members this thread will be closed and you'll be blocked.

In the meantime please only reply with productive conversation around this FR, such as why tr24 = FLAC.

**Comment by Mrpink200** [comment]
i m no manager of rutracker.org but it is their standard way to flag hi-res release to avoid messing with flac24 versions of vinyl rips or sacd rips or whatever that are not natives hi-res.

i got it. i will no longer bother you and try do without it and without alac24 support
