### ISSUE TITLE
Lidarr doesnt pull info from Musicbrainz

### ISSUE THREAD

**Issue by lopiv2** [lidarr/Lidarr#2008]
When you add a new artist, Lidarr doesnt pull the info for that artist from Musicbrainz (singles, albums, photos), etc...Even knowing and seeing that artist in Musicbrainz has tracks and albums.

Steps to reproduce:

Add a new artist and press refresh.

**Comment by bakerboy448** [comment]
Please follow the template and fill it out completely.

https://github.com/lidarr/Lidarr/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=

**Comment by lopiv2** [comment]
**Describe the bug**


**To Reproduce**
See no info pulling from Musicbrainz

**Expected behavior**



**Platform Information (please complete the following information):**
 - OS: 
 - Docker: 
 - Mono or .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Lidarr Branch: 

**Trace Logs**
It says unable to load General Settings

**Comment by bakerboy448** [comment]
Actually fill out the template with the requested information please.

**Comment by bakerboy448** [comment]
and actually provide logs as requested and required by the template.

**Comment by lopiv2** [comment]
Cant post trace logs because lidarr does not show me that. It says "Unable
to load general settings"

**Comment by ta264** [comment]
Closing pending a useful, reproducible bug report.
