### ISSUE TITLE
Lidarr auto-imports wrong folder

### ISSUE THREAD

**Issue by dsm1212** [lidarr/Lidarr#2014]
Lidarr import processing is expecting the torrent name to be the folder it should find. But sometimes the folder for the torrent is slightly different than the torrent name and so it never processes the result. Are these badly formed torrents or is a lidarr bug? Headphones calls the qbittorrent api to get the actual output folder name after the download starts. 

**To Reproduce**
Start a download of a torrent where the torrent name is different than the folder it contains. I can provide a few if you need them.

**Expected behavior**
I would like import processing to process anything it finds in downloads really. Or try to match what it finds in downloads with what it was expecting. Or ask qbittorrent for the download folder. Qbittorrent does provide this in their API.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: debian buster
 - Docker: Yes 
 - Mono or .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch: I don't know what the docker pulls

**Trace Logs**
21-2-14 16:26:58.3|Debug|TrackedDownloadService|Tracking 'qBittorrent:xxxxx xxxxxxxx - xxxxxxxxx xxxx - xxxxx xxx xxxx (2021) Mp3 320k': ClientState=Downloading (readonly) LidarrStage=Downloading Album='xxxxx xxxxxxxx - xxxxxxxxx xxxx - xxxxx xxx xxxx Unknown v1' OutputPath=/downloads/xxxxx xxxxxxxx - xxxxxxxxx xxxx - xxxxx xxx xxxx (2021) Mp3 320k.
2

The actual output folder was 'xxxxx xxxxxxxx - xxxxxxxxx xxxx - xxxxx xxx xxxx (2021) Mp3 320kbps [PMEDIA] ⭐️'
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Qbit 4.3+ and Lidarr v0.7 are not compatible

censored logs are useless :)
Qbit version is also useful for issues like this.

If my crystal ball is correct, we can close this

**Comment by dsm1212** [comment]
Ah ok, prob qbit version issue. I’ll see if I can pull an earlier tag.

**Comment by bakerboy448** [comment]
@dsm1212  you’ll need to pin on Qbit 4.2.5 or better yet just make the hop to lidarr v0.8 it’ll be hitting stable soonish enough
