### ISSUE TITLE
Consider Album Status when deciding to include

### ISSUE THREAD

**Issue by davehope** [lidarr/Lidarr#202]
### Description of request and what problem are you looking to solve?
Unexpected albums showing against artists I'm using the "Standard" Metadata profile, so Album / Studio. In each instance of the problem, the MusicBrainz "Status" field would help to filter out these results. Here are some examples:
The workaround of unmonitoring these is fine, but would be nice to address at some point.
### Other Information

Distured - "Summer of the Sickness"
https://musicbrainz.org/release/22c7a314-d0c2-467e-bcd4-8316681b7401
In this instance, the Status of "Promotion" should be ignored.

Bon Jovi - "Only for You, Volume 1 (Unauthorised)" (and volumes 2,3,4)
https://musicbrainz.org/release/32fb925d-1147-4ff5-8a1c-8e916558e64b
In this instance the Status of "Bootleg" should be ignored.

Nickleback - "Slow Motion - Live USA 2000"
https://musicbrainz.org/release/8e287a0f-35fe-4ff8-98e8-f79a253e38b1
In this instance the Status of "Bootleg" should be ignored.

I'm not sure if this should be raised against Lidarr or LidarrAPI.Metadata (or both).

**Comment by DZMM** [comment]
you can do this now by adding bootleg and promotion to restrictions on settings/indexers (I do this to filter out sponsored)

**Comment by davehope** [comment]
The intention of my feature request was more for the library management side of things. I.E. don't show it on the albums page as it's not an official studio release. Filtering based on status should be possible in a similar way to metadata profiles.

**Comment by Qstick** [comment]
It will likely be included into metadata profiles as a option once we add on api side

**Comment by AnnieTheEagle** [comment]
This would very much be appreciated, since there's a lot of junk albums for the bigger bands like 'The Beatles' comes up with a whopping 36 albums, most of which are junk.

Is this planned for v0.2.1 @Qstick ?

**Comment by Qstick** [comment]
@AnnieTheEagle Yea this shouldn't be to bad to add. @danielunderwood Can you get support on metadata side knocked out?

**Comment by danielunderwood** [comment]
Sure thing. Should be pretty simple, or at least I hope so.

**Comment by davehope** [comment]
Apologies for what might be a silly question, but has this been implemented in Lidarr now? - I see the PR for LidarrAPI.Metadata but unclear on whether that is enough to resolve it in Lidarr? I can't spot an obvious change in Metadata Profiles.

**Comment by Qstick** [comment]
Has not, hopefully I'll get to work on Lidarr some this weekend

**Comment by davehope** [comment]
Thanks @Qstick  , Is it worth reopening this issue until implemented?

**Comment by danielunderwood** [comment]
Oops, that's my fault. I didn't know it would close issues across repos.
