### ISSUE TITLE
Option to prevent new albums from being automatically monitored

### ISSUE THREAD

**Issue by Redundant1** [Lidarr/Lidarr#2034]
**Is your feature request related to a problem? Please describe.**
To keep my library clean and organized, I run 2 instances of Lidarr:  One for albums I have physical copies of and one for everything else.  For the physical copy instance, I only put artists and albums I own as monitored.  I want it to grab those albums and upgrade them until the cutoff is met. So, I may have only 2 albums from a given artist being monitored. Because the artist is monitored so upgrades will continue to occur, if a new album is released, an existing album updated, or (more often than you'd expect) duplicated for that artist, those will automatically get monitored, which I don't want.  As a result of this, my library is constantly adding albums I don't want monitored and grabbing them when available.  I then need to go in, verify if it's something I own, unmonitor the album, and, possibly, move the files to the other Lidarr instance.  Additionally, the other Lidarr instance may have already added the new album and grabbed it, thereby duplicating the grab.

_**UPDATE 06/23/2021:**_ There were reports that edited and/or duplicated album entries on MusicBrainz are then updated/added in Lidarr and also automatically changed to monitored.  I was recently able to confirm this behavior when an existing album was both edited AND duplicated on MusicBrainz.  This makes the issue exponentially worse.  In this most recent incident, in the span of just 7 days, my two instances of Lidarr managed to grab a single album NINE (!) times.

**Describe the solution you'd like**

I'd like the ability to prevent Lidarr from automatically adding **and monitoring** new albums for a monitored artist.  It'd be fine if Lidarr added the albums, but left them unmonitored.

**Describe alternatives you've considered (_UPDATED 11/14/2021 w/ alt. 3_)**
1.  As mentioned as a possible solution in #1831, if I unmonitor the artist to prevent new albums from getting monitored, then the albums I want monitored will no longer be upgraded, even if the cutoff is unmet.

2.  Manually going through every artist to disable every album which Lidarr automatically set to monitored; in a word: insane.  I've been running Lidarr since May 2020, so it's not even a year later, and let's just say I lost count of how many albums I had to manually disable when I reached the mid 300's.

3.  Set the download client's priority to "Paused".  This works a little better than alternative 2 because each grab is now manually approved by me after I get notified of the grab.  Additionally, it triggers me to go into the artist folder and deselect the album and, while in there, I can check all the other artist's albums to see if they also require deselection.  However, the amount of manual intervention is tedious and really negates the intended purpose of Lidarr automating all of this.

**Additional context**

[AB#170](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/170)

**Comment by tandy-1000** [comment]
I would also like this feature, because I mistakenly understood this to be the default behaviour when selecting 'monitor existing albums'.

**Comment by bakerboy448** [comment]
Please just +1 the OP comment.

comments that do not add useful details or discussion (such as “i want this too type comments”) are just noise and not good GitHub etiquette

**Comment by tandy-1000** [comment]
Sorry, I thought my addition that it should be the default behaviour would be useful. It is mostly unclear what the default behaviour is, because of no docs.

**Comment by Redundant1** [comment]
Just wanted to say **THANK YOU** so much for merging #2786 to add this ability.  It's going to save me a lot of headaches!
