### ISSUE TITLE
Connection Lost When Importing

### ISSUE THREAD

**Issue by beekness** [lidarr/Lidarr#204]
coming over from headphones ... familiar with Sonarr and Raddarr so this is awesome devs so thank you!

issues I am having importing my music folder

after 20 or so artists it says (and never regains connection): 

Connection Lost
Lidarr has lost it's connection to the backend and will need to be reloaded to restore functionality.
Lidarr will try to connect automatically, or you can click reload below.

browser: Chrome
Docker Ver.: 0.2.0.262

edit - add browser and docker

**Comment by GoodOmens83** [comment]
Having the same issue - 

Browser: safari
Docker version 0.2.0.262

**Comment by beekness** [comment]
Same here... if I hit the "X" button it refreshes the page.

I also tried doing 10 artists at a time, but get the same issue when importing it gets disconnected somehow.

**Comment by RobbieG3** [comment]
I was having this disconnection issue, regardless of page I was on, yesterday after installing the linuxserver docker container. After switching to volikon's container, I no longer have this issue.

**Comment by beekness** [comment]
I wish it worked for me, I tried I believe 3 different containers and same issue 

I have 870 artists but I don't believe it is that 

I have a synology 1817+ and 918+, both with same issue..

**Comment by rudyolph** [comment]
I get the same error regardless of importing or not.  I start the container and after a period of time this happens.  I've used several different docker images including volikon's and it occurs on all of them.

**Comment by beekness** [comment]
I wish I knew if I was doing something wrong. I have tried everything possible to get it working. it sucks it loses connection and doesn't regain and begins the process over and over.

Hopefully, they see this list and can give some insight. I would be more than happy to provide any logs and assist in getting this issue resolved.

**Comment by jacobmd** [comment]
I am also having issues with loosing connection when importing. It seems even only importing 1 artist causes the issue for me. I also tried Edge Browser with the same result.

Lidarr: 0.2.0.223
Synology: DS1817+
Docker: 17.05.0-0349
Chrome: 63.0.3239.132
Edge:  41.16299.15.0

Let me know if I can help by providing any logs.

**Comment by Qstick** [comment]
@jacobmd make sure you update Lidarr first, you are 40 builds behind

**Comment by jacobmd** [comment]
Does Lidarr require manual updates? When I go to the update page it says "No updates are available".

**Comment by Qstick** [comment]
Change branch to nightly

**Comment by beekness** [comment]
@jacobmd - I used the shadow2062 version in the registry and its working on my 1817+

@Qstick - is that possible on a synology nas? We have to use docker to install it....

**Comment by Qstick** [comment]
Possible, not recommended in docker. May want to ping the maintainer if the docker is lagging behind

**Comment by jacobmd** [comment]
Changing to nightly fixed my issue. I did not even think to try that.

**Comment by rudyolph** [comment]
I'm on the latest and it is still happening...at least in Docker anyhow.

**Comment by beekness** [comment]
@jacobmd - how did you switch over to the nightly on your Synology?

**Comment by droideparanoico** [comment]
I'm on 0.2.0.279 and still happening.

**Comment by droideparanoico** [comment]
Error still happening with 0.2.0.314 version

**Comment by Qstick** [comment]
@droideparanoico please post trace logs from this happening

**Comment by droideparanoico** [comment]
`18-3-20 19:34:26.5|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
18-3-20 19:34:26.5|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
18-3-20 19:34:26.5|Trace|EventAggregator|Publishing QueueUpdatedEvent
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsModule
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsModule
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusModule
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusModule
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
18-3-20 19:34:26.5|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
18-3-20 19:34:26.5|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
18-3-20 19:34:26.5|Trace|CommandQueueManager|Updating command status
18-3-20 19:34:26.6|Trace|EventAggregator|Publishing CommandExecutedEvent
18-3-20 19:34:26.6|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
18-3-20 19:34:26.6|Trace|Owin|SQLite error (5): database is locked

18-3-20 19:34:26.7|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.CheckForFinishedDownloadCommand
18-3-20 19:34:26.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
18-3-20 19:34:26.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
18-3-20 19:34:26.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
18-3-20 19:34:26.8|Trace|CommandExecutor|CheckForFinishedDownloadCommand <- DownloadMonitoringService [00:00:00.1970820]
18-3-20 19:34:45.8|Trace|Http|Req: 173 [GET] /logfile/Lidarr.trace.txt
18-3-20 19:34:45.8|Trace|Http|Res: 173 [GET] /logfile/Lidarr.trace.txt: 200.OK (4 ms)`

**Comment by Qstick** [comment]
@droideparanoico that doesnt tell me much, can you attach the entire log or send it to me on discord?

**Comment by droideparanoico** [comment]
@Qstick here's the entire log:
[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/1831438/Lidarr.trace.txt)

**Comment by rudyolph** [comment]
I only had this happen to me when using Lidarr in Docker on Win 10.  As
soon as I switch to the windows install of it I haven't had the issue since.

**Comment by droideparanoico** [comment]
Yes, I'm using it in Docker but not over Win 10 but on a openmediavault install

**Comment by Qstick** [comment]
@rudyolph yea same here, I've actually never been able to reproduce on Windows 10 dev environment. We got linuxserver docker fixed this weekend as well to eliminate some of the signalR connections errors. So hopefully that helps.

**Comment by droideparanoico** [comment]
@Qstick I'm using volikon docker, maybe I should try the linuxserver one

**Comment by Qstick** [comment]
You can give it a shot, but we pulled the linuxserver fix from volikon so I doubt it will do much good.

**Comment by retrography** [comment]
This happens all the time. Why is it not being reopened as a bug?
