### ISSUE TITLE
Possible to add albums with "Various Artists" types?

### ISSUE THREAD

**Issue by stayupthetree** [lidarr/Lidarr#207]
I like soundtracks and broadway cast albums. Example https://musicbrainz.org/release/19e87c02-28df-4a89-ba7e-8f5ef474c36f

Is it possible to add these types as they don't have a set "Artist"

**Comment by danielunderwood** [comment]
In the linked case, adding Lin‐Manuel Miranda as an artist may cover it. But various artists in general will hopefully be handled by #179.

**Comment by jw1986** [comment]
To add to this, it would be great to add albums released from series, like the Eurovision Song Contest https://musicbrainz.org/series/8982a047-965c-4752-adf5-1396f0aa56eb or Now That's What I Call Music https://musicbrainz.org/series/4b5f2897-9b05-4799-b895-6620e27143e7

Sadly they don't have a set artist, it's truely various each time. :(

**Comment by Goluff** [comment]
Adding by series would solve a lot of problems. When I try to import my Great Composers for example. 
https://musicbrainz.org/series/0f840b5d-33ad-46de-9662-70d977e3d3b2

**Comment by BinsonBuzz** [comment]
Can I check the status of adding Various Artists please?  "Various Artists (add compilations to this artist)" comes up when I search for various artists, but I can't add it to my artists in order to add albums

**Comment by Qstick** [comment]
Reference #517, needs to go in first

**Comment by theg00s3** [comment]
Any updates on this?

**Comment by pl77** [comment]
> 
> 
> Any updates on this?

There's a separate branch where they are trying to get this functionality.  It is a much larger change than I think most people realize, as it changes the data model from all albums being nested under an artist to separating artist and albums into individual items.  

If you visit https://github.com/lidarr/Lidarr/tree/various-artists you can see that work has been progressing on the branch.  And this pull request (https://github.com/lidarr/Lidarr/pull/839) shows that they are trying to incorporate it into a future update, without breaking lidarr's reliability or wrecking everyone's databases.

Kinda like trying to change all the tires on your car while you're driving down the road.

**Comment by cooperdk** [comment]
> Kinda like trying to change all the tires on your car while you're driving down the road.

This means that the car was manufactured with the wrong set of tires to begin with.
