### ISSUE TITLE
Albums missing for artist

### ISSUE THREAD

**Issue by 999eagle** [lidarr/Lidarr#2084]
**Describe the bug**

Some albums missing after adding/refreshing artist.

[Artist MusicBrainz link](https://musicbrainz.org/artist/92bb085a-2924-4479-b627-181a1835d2f5)
[Album MusicBrainz link](https://musicbrainz.org/release-group/7780fc85-7213-478d-a869-f9ef21e3ef6b)

**To Reproduce**

1. Make sure artist metadata profile contains primary type Album, secondary type Soundtrack and release status Official
2. Add or refresh metadata for above artist
3. Above album is one of a few missing from the artist in Lidarr

**Expected behavior**

The above album should be present in Lidarr.

**Platform Information (please complete the following information):**
 - Host OS: Arch Linux 5.11.6-arch1-1
 - Container OS: Ubuntu 18.04
 - Docker: Yes (linuxserver/lidarr) 
 - Mono or .NET Version (System -> Status): Mono 4.6 
 - Lidarr Version: 0.8.0.2086
 - Lidarr Branch: nightly

**Trace Logs**
[lidarr.trace.log](https://github.com/lidarr/Lidarr/files/6135756/lidarr.trace.log)

**Comment by ta264** [comment]
Blu-ray are deliberately omitted as they're video not audio

**Comment by 999eagle** [comment]
The MusicBrainz release is about the audio on the Blu-Ray and I have this exact release as FLAC files. Even though audio was distributed on a Blu-Ray disc here I can't add it to Lidarr

**Comment by clidx** [comment]
Perhaps control over allowed sources could be left up to the user? I am facing the same issue (spookily, for a different Final Fantasy soundtrack). If it's on musicbrainz then it would be good to be able to add it to lidarr.
