### ISSUE TITLE
Media Cover Service Error blocks musicbrainz updates?

### ISSUE THREAD

**Issue by sataris** [lidarr/Lidarr#2089]
**Describe the bug**
When there is a media cover service error, Lidarr is unable to fetch new albums/singles from musicbrainz. 

I have been trying to get the artist LVNDSCAPE to display the single  'What I'd Give' and Lidarr

a) refuses to get new albums/singles etc
b) Throws an exception for the image

I have verified that the musicbrainz single entry is correct, you can view them here (https://musicbrainz.org/release-group/fa9c812c-3a01-4026-bf13-1b495bbcd8a5) 

I know that lidarr uses it's own cached api of musicbrainz, and It's not to do with the hourly sync. I tested by adding a release to another artist and the single appeared in Lidarr as expected (with no media cover service error, which is why i believe this is related). 

**To Reproduce**
1. Add a new artist 'LVNDSCAPE' (https://musicbrainz.org/artist/0d7e5bfd-4b84-494e-8d47-cd4177ced062)
2. You will get a media cover service error 
3. There will only be 1 single available 'Down Under' (or 3 depending on your metaprofile)
4. The single 'What I'd Give' won't be present
4. There will be no image for the artist (less important)

**Expected behavior**
Lidarr should be able to ignore the media cover service error and retrieve the albums/singles from musicbrainz, and download the image

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - Mono or .NET Version (System -> Status): Mono 5.20.1.34
 - Browser and Version N/A
 - Lidarr Version: 0.7.2.1878
 - Lidarr Branch:  develop

**Trace Logs**
https://pastebin.com/PkhwjPmc

**Comment by bakerboy448** [comment]
>Lidarr Version: 0.7.2.1878

>Lidarr Branch: develop

This does not jive and you are over 200 builds out of date.
 develop is 0.8 (0.8.0.2042) , update and see if the issue persists

**Comment by sataris** [comment]
> > Lidarr Version: 0.7.2.1878
> 
> > Lidarr Branch: develop
> 
> This does not jive and you are over 200 builds out of date.
> develop is 0.8 (0.8.0.2042) , update and see if the issue persists

Sorry you are correct, I created a separate docker instance to specifically test this scenario and I used the wrong tags. 

Tried it again with a new correct instance, and the issue still persists. 

Added a new trace log as well. 

**Platform Information (please complete the following information):**

OS: Unraid
Docker: Yes
Mono or .NET Version (System -> Status): .NET 3.1.10
Browser and Version N/A
Lidarr Version: 0.8.0.2042
Lidarr Branch: develop

**Trace Logs**
https://pastebin.com/n69UyCSV

**Comment by sataris** [comment]
So after waiting a week,  this seems to have somehow resolved itself.  (Though the media cover service still occurs), so I'll close this. 

Thanks!
