### ISSUE TITLE
Empty root folders not being created

### ISSUE THREAD

**Issue by kosta880** [lidarr/Lidarr#2090]
Hello,.
since I already posted on reddit, and checked the logs, I believe this might be genuine bug.

**Describe the bug**
Empty artist folders in the root folder not being created.
Talking about:
"Create missing artist folders during disk scan".

**To Reproduce**
Check first box.
Add an artist, like Elton John...
After first automatic scan, press Refresh & Scan to scan again, and after it finishes, there is still not empty artist folder in the root folder.
Logs show nothing except that metadata can't be placed since directory doesn't exist.

**Expected behavior**
See folder created after I've added an artist into Lidarr.

**Platform Information (please complete the following information):**
 - OS: Ubuntu Server 20.10
 - Docker: Yes
 - Lidarr Version: 0.8.0.2086
 - Lidarr Branch: ghcr.io/linuxserver/lidarr:nightly

**Trace Logs**
Uncomfortable with posting the whole Trace-Log openly on the forum. If you close the issue, so be it. I can gladly privately share it, if you contact me directly.

Thanks!

**Comment by bakerboy448** [comment]
closing; impossible to troubleshoot without logs.

more than likely your root folder is completely empty and that protection is kicking in

**Comment by kosta880** [comment]
Sorry to see this. No, it's not. It has about 30 artists in there, all created manually. I also have 3 root folders. None work.
With "stuff", does this also mean content? Probably not.

**Comment by bakerboy448** [comment]
Well, then indeed it may be a bug.
literally impossible to know without logs.

Considering paths and content are typically needed for debugging, no those are not scrubbed. 

[Regex that scrubs the logs](https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs)

[Test Cases for the cleansing](https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs)

**Comment by kosta880** [comment]
Thank you. I’ll rather live with the error than openly post that tracelog on the internet.
Best I can offer is a link to that log, privately!

I am not tech savvy enough to understand those two links, sorry.
