### ISSUE TITLE
Tracked downloads are not rechecked if import fails due to missing files

### ISSUE THREAD

**Issue by kenzieeeeee** [lidarr/Lidarr#2098]
This appears to be a regression caused by setting TrackedDownload.State before checking if the relevant files/paths actually exist: 

https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Download/CompletedDownloadService.cs#L104

**Comment by ta264** [comment]
This is deliberate.  In 0.8 it is relaxed so that it is rechecked until at least some files are found.

**Comment by kenzieeeeee** [comment]
> In 0.8 it is relaxed so that it is rechecked until at least some files are found.

I'm running the latest release (0.8.0.2042) and it still seems to be affected by this. The relevant code in CompletedDownloadService also hasn't changed between then and the latest code on the develop branch.

**Comment by ta264** [comment]
Please join the discord channel if you want to discuss further
