### ISSUE TITLE
[ANNOUNCE] Docker image

### ISSUE THREAD

**Issue by mikafouenski** [lidarr/Lidarr#210]
Hello,

This is not a bug or a feature request.

I just made a docker image of Lidarr. 
* [docker hub](https://hub.docker.com/r/mikafouenski/lidarr)
* [Github](https://github.com/mikafouenski/docker-lidarr)

I'm looking forward to use this great tool you are building ! 

Nice work,
Mika.

**Comment by Qstick** [comment]
There are already multiple docker images out there.
