### ISSUE TITLE
Mechanism to use proper SSL certificates

### ISSUE THREAD

**Issue by rootwyrm** [lidarr/Lidarr#214]
## Feature Request

Lidarr does not currently provide any mechanism with which to explicitly configure or import an X509 certificate for SSL. With Let's Encrypt/ACME and related, this is an increasingly significant problem. It also creates a pretty significant impediment for using Lidarr in TaleCaster, as we use a host-level CA issued fully valid certificate for all services. (No "click here to make an exception.") This is particularly important on Docker builds since they cannot actually use HAProxy to secure transport due to lack of routing capability.

### Other Information

Method for importing isn't particularly important; if it can be done by API, that's fine, though by default my preference would be to specify it in `config.xml`. However, I understand that `http.sys` is a significant impediment to that.

**Comment by Qstick** [comment]
Closing for now, tagged maybe one day
