### ISSUE TITLE
Change label in download client after import

### ISSUE THREAD

**Issue by LinusT** [lidarr/Lidarr#216]
## Feature Request
Option to change label in download client after record has been imported by LIDARR.
Example: set label "lidarr" on download and "lidarr-imported" after successful import.

### Description of request and what problem are you looking to solve?
The topic on how/if Lidarr, Radarr, Sonarr should be indexer aware and help manage seed ratio and seed time rules etc has been up numerous times in multiple forums (and PR's). As has the best way to setup download clients to manage different rules.

Purpose with this feature request is that with it the state of the grab/import process has been fully communicated to the download client, thus allowing it, it's plugins or scripts to manage the seeding and cleanup details. I also allows for proper detection of downloads completely seeded (and automatically paused) but failed to import to trigger manual intervention.

### Other Information

Common need with Sonarr, Radarr, and Lidarr. But since Lidarr (beta) has a tendency to grab an later near silently fail to import the release it makes the issue less easy to manage in a quick manual action.

**Comment by Qstick** [comment]
Sonarr/Sonarr@39ea2dd32fe4a5d192e8393c06324a813d1db567

**Comment by Qstick** [comment]
d00285540d3a1b9436544ac2c69be420f390e4f5
