### ISSUE TITLE
fpcalc error persists after full reinstall and update of both Lidarr and Chromaprint

### ISSUE THREAD

**Issue by BobThompson** [lidarr/Lidarr#2160]
**Describe the bug**
Lidarr Error: fpcalc could not be found. Audio fingerprinting disabled.
Even though a full reinstall of Lidarr and Chromaprint have been done. Chromaprint has been updated manually to the latest version and the error persists.

**To Reproduce**
1. Go to (lidarr local address) and error "fpcalc could not be found. Audio fingerprinting disabled." persists.
2. Every health check confirms the same error.

**Expected behavior**
A working install of Chromaprint and fpcalc.

**Platform Information (please complete the following information):**
 - OS: TrueNAS-12.0-U2, Lidarr running in an iocage jail.
 - FreeBSD verstion: 12.1-RELEASE-p13
 - Lidarr Version: 0.7.2.1878
 - Mono Version: [6.8.0.105]

[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/6315290/Lidarr.trace.txt)

**Comment by ta264** [comment]
I'm pretty sure this is just a configuration issue. If we discover otherwise we can reopen. Please come by the discord channel for support.
