### ISSUE TITLE
(Synology) Startup error: Failed to check for multiple instances of Lidarr

### ISSUE THREAD

**Issue by mreid-tt** [Lidarr/Lidarr#2179]
**Describe the bug**

On startup, an error occurs when checking for instances already running on the Synology platform.

**To Reproduce**

1. From the Package Center select Lidarr
2. Stop the package and wait to complete
3. Start the package then review the log file

**Expected behavior**

Application should start without error in the log file

**Screenshots**

N/A

**Platform Information (please complete the following information):**
 - OS: DSM 6.2.4-25556
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET Core 3.1.10
 - Browser and Version (Only needed for UI issues): N/A
 - Lidarr Version: 0.8.0.2042
 - Lidarr Branch: develop

**Trace Logs**

https://pastebin.com/EC6C1BrS

**Other Details**

The error seems to stem from this function within the code: https://github.com/lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Common/Processes/ProcessProvider.cs#L338
Running on the Synology platform seems to trigger the following error:
```
[v0.8.0.2042] System.UnauthorizedAccessException: Access to the path '/proc/19002/maps' is denied.
 ---> System.IO.IOException: Permission denied
```

[AB#161](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/161)

**Comment by bakerboy448** [comment]
[Likely Related](https://github.com/Radarr/Radarr/issues/6068)  

> [
I'm not sure a lot can be done about this if DSM forbids access to /proc. It's harmless, you can just ignore it.](https://github.com/Radarr/Radarr/issues/6068#issuecomment-802941433)

**Comment by houndtt** [comment]
> [I'm not sure a lot can be done about this if DSM forbids access to /proc. It's harmless, you can just ignore it.](https://github.com/Radarr/Radarr/issues/6068#issuecomment-802941433)

I agree this is likely related, however because of this bug the in-app update feature also fails and never completes the update.

**Updater Log File**

```
21-4-20 21:46:18.9|Info|UpdateApp|Starting Lidarr Update Client
21-4-20 21:46:19.4|Debug|UpdateApp|Lidarr process ID: 16196
21-4-20 21:46:19.4|Debug|UpdateApp|Arguments:
21-4-20 21:46:19.5|Debug|UpdateApp|  16196
21-4-20 21:46:19.5|Debug|UpdateApp|  /tmp/lidarr_update
21-4-20 21:46:19.5|Debug|UpdateApp|  /volume1/@appstore/lidarr/share/Lidarr/bin/Lidarr.dll
21-4-20 21:46:19.5|Debug|UpdateApp|Using executing application: /volume1/@appstore/lidarr/share/Lidarr/bin/Lidarr.dll
21-4-20 21:46:19.5|Debug|UpdateApp|Executable location: /volume1/@appstore/lidarr/share/Lidarr/bin/Lidarr.dll
21-4-20 21:46:19.5|Info|InstallUpdateService|Installation Folder: /volume1/@appstore/lidarr/share/Lidarr/bin
21-4-20 21:46:19.5|Info|InstallUpdateService|Updating Lidarr from version (unknown) to version 0.8.1.2135
21-4-20 21:46:19.5|Info|InstallUpdateService|Verifying requirements before update...
21-4-20 21:46:19.5|Debug|ProcessProvider|Finding process with Id:16196
21-4-20 21:46:19.6|Debug|ProcessProvider|Found process 16196:Lidarr [/volume1/@appstore/lidarr/share/Lidarr/bin/Lidarr]
21-4-20 21:46:19.6|Info|InstallUpdateService|Verifying Update Folder
21-4-20 21:46:19.7|Fatal|UpdateApp|An error has occurred while applying update package.

[v0.8.1.2135] System.UnauthorizedAccessException: Access to the path '/proc/19002/maps' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.ReadNative(Span`1 buffer)
   at System.IO.FileStream.ReadSpan(Span`1 destination)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.ReadLinesIterator.MoveNext()
   at Interop.procfs.ParseMapsModulesCore(IEnumerable`1 lines)+MoveNext()
   at System.Diagnostics.ProcessManager.GetModules(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at NzbDrone.Common.Processes.ProcessProvider.<>c__DisplayClass21_0.<GetProcessesByName>b__0(Process process) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 344
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Common.Processes.ProcessProvider.GetProcessesByName(String name)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in D:\a\1\s\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 91
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in D:\a\1\s\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:line 102
   at NzbDrone.Update.UpdateApp.Start(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 56
   at NzbDrone.Update.UpdateApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Update\UpdateApp.cs:line 42
```

**Comment by RobinDadswell** [comment]
Are Synology packages not supposed to be updated via the Synology interface - thereby meaning that in-app upgrades shouldn't be done as the package maintainer for Synology should be updating this when updates are required.

**Comment by houndtt** [comment]
> Are Synology packages not supposed to be updated via the Synology interface - thereby meaning that in-app upgrades shouldn't be done as the package maintainer for Synology should be updating this when updates are required.

It depends on the app. For apps like SABnzbd, absolutely yes! However many apps including variants of Sonarr (Lidarr and Radarr) have always had in-app updating where the app was able to contact the source repository and update itself without a new Synology package build. Sometimes (especially when there are major changes in the source code), it would be useful to build a new Synology package to re-base the code.

Up until we switched to .NET Core, Lidarr was able to update itself just fine. Something in the way the processes are evaluated outside of Mono may be the root of this issue. It may be that the `GetProcessesByName` function may need to add an exception handler for permission issues browsing the process list. I'm not really sure but that's my 2-cents.

**Comment by ta264** [comment]
What Nas is this? Other Synology users have confirmed it works for them. Not sure if it's peculiar to your model maybe.

**Comment by houndtt** [comment]
> What Nas is this? Other Synology users have confirmed it works for them. Not sure if it's peculiar to your model maybe.

Hmm, I'm using a DS916+ (8GB). Can you confirm that other Synology users were able to perform a successful in-app update using the .NET Core build?

**Comment by ta264** [comment]
Yes I can (on radarr)

**Comment by houndtt** [comment]
Hmmm, I didn't think of a problem with my setup as the cause. I fired up my VirtualDSM on the same platform and was able to complete an update with Lidarr without issue (https://pastebin.com/hyNrfDAE). I'll take a closer look at my setup but failing any findings I may just backup, uninstall and reinstall Lidarr to see if this helps.

**Comment by houndtt** [comment]
I've done the uninstall and reinstall of Sonarr and Lidarr but unfortunately, in the startup log for Lidarr I am still seeing the error, just with a different process number for Sonarr. I'm unsure of what to check again. Any advice would be appreciated.

**Comment by mreid-tt** [comment]
Following the upgrade of Lidar from version 0.8.1.2135 to 1.0.1.2578, the original error seems to be no longer occurring on application startup from the Package Center. This bug report will now be closed.
