### ISSUE TITLE
theaudiodb blocking lidarr causing missing artwork

### ISSUE THREAD

**Issue by mreid-tt** [Lidarr/Lidarr#2182]
**Describe the bug**

Based on this note (https://github.com/lidarr/Lidarr/issues/1014#issuecomment-538668857), artwork is downloaded from fanart.tv and theaudiodb.com. Recently artwork from TheAudioDB fails to download with an HTTP Error - 403 Forbidden

**To Reproduce**

1. Within Lidarr add an artist with TADB artwork (like [Mat Kearney](https://www.theaudiodb.com/artist/114464))
2. Wait until the artist details refresh (but with no artwork)
3. In the log there will be HTTP 403 errors similar to this:
```
21-4-21 20:42:08.7|Warn|HttpClient|HTTP Error - Res: [HEAD] https://www.theaudiodb.com/images/media/artist/banner/tvyypy1476729221.jpg: 403.Forbidden
21-4-21 20:42:08.7|Error|MediaCoverService|Couldn't download media cover for [320d40d6-28dd-42d7-b05f-7e6e8d399a2e][Mat Kearney]
21-4-21 20:42:09.0|Warn|HttpClient|HTTP Error - Res: [HEAD] https://www.theaudiodb.com/images/media/artist/logo/yqyxut1441136707.png: 403.Forbidden
21-4-21 20:42:09.0|Error|MediaCoverService|Couldn't download media cover for [320d40d6-28dd-42d7-b05f-7e6e8d399a2e][Mat Kearney]
```

**Expected behavior**

After adding the artist the media cover art should be downloaded without error

**Screenshots**

N/A

**Platform Information (please complete the following information):**
 - OS: DSM 6.2.4-25556
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET Core 3.1.13
 - Browser and Version (Only needed for UI issues): N/A
 - Lidarr Version: 0.8.1.2135
 - Lidarr Branch: develop

**Additional Information**

Sample error logs: https://pastebin.com/AV9DWN0y

This issue was previously lodged (https://github.com/lidarr/LidarrAPI.Metadata/issues/132), however it seems that TADB is now blocking Lidarr clients with a user agent of Lidarr/0.8

[AB#172](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/172)

**Comment by houndtt** [comment]
hey @ta264, a gentle reminder on this...

**Comment by varac** [comment]
Same here, the weird thing is that the URLs in the lidarr log which produce a `403 forbidden` error can get downloaded via a browser just fine, so it's maybe a rate limit on theaudiodb's side, or they refuse the user agent ?

**Comment by varac** [comment]
i.e. https://www.theaudiodb.com/images/media/artist/logo/yqyxut1441136707.png which is shown in the original issue description can get shown in the browser

**Comment by bakerboy448** [comment]
AudioDB has been blocking Lidarr for several months now.

**Comment by h3llrais3r** [comment]
Any solution for this? Some requests seem to work, others not...

**Comment by kushfest** [comment]
I'm seeing this issue today on a new install. All cover art downloads attempted from audiodb get a 403 error.

**Comment by bakerboy448** [comment]
> I'm seeing this issue today on a new install. All cover art downloads attempted from audiodb get a 403 error.

There's no need to report what is already known.
