### ISSUE TITLE
Lidarr not grabbing albums from indexer.

### ISSUE THREAD

**Issue by apoorv569** [lidarr/Lidarr#2191]
I have `Jackett` set as the indexer, which has one of indexer thepiratebay.org. I added a bunch of bands to grab tracks for one of them is Death, but it is not grabbing all the albums it did fetch 2 but no more, even though I can search for the missing albums on thepiratebay by searching manually with >= 1 seeders.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.
