### ISSUE TITLE
Import menu button used to import your music library is missing from the Lidarr GUI after updating to 0.8.1.2135

### ISSUE THREAD

**Issue by neilbeul** [lidarr/Lidarr#2216]
**Describe the bug**
The Import menu used to import you music library is missing from the interface after updating to the latest version (0.8.1.2135) of Lidarr which I'm running on Docker which is updated automatically by Watchtower.

**To Reproduce**
I'm not sure that the situation I'm confronted with is reproducible, but I have tried to 'recreate' the container inside Portainer which made no difference at all.

**Expected behavior**
The update produced unexpected behaviour rather than expected.

**Screenshots**
This is what was expected:
![image](https://user-images.githubusercontent.com/83190703/116013821-6f406980-a632-11eb-89b7-a11fdc89c90f.png)

This is what I've got:
![image](https://user-images.githubusercontent.com/83190703/116013861-a282f880-a632-11eb-9904-a661ef449e29.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu Server 20.04.2 LTS (GNU/Linux 5.4.0-71-generic x86_64)
 - Docker: Yes, running Portainer
 - Browser and Version (Only needed for UI issues): Ive tested on Chrome and Firefox with the same results
 - Lidarr Version: 0.8.1.2135
 - Lidarr Branch: Maintaned by Watchtower - Nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[Lidarr Trace File.txt](https://github.com/lidarr/Lidarr/files/6373470/Lidarr.Trace.File.txt)

**Comment by Qstick** [comment]
This is intentionally. Import is automatic now as soon as a root folder is setup in Media Management
