### ISSUE TITLE
Custom Artist Name for folders and naming

### ISSUE THREAD

**Issue by eangulus** [Lidarr/Lidarr#222]
Hoping for a feature to set the naming of an artist.

The problem I have right now as an example is Lidarr wants to set AC/DC as AC+DC. I would like to force it to use ACDC for folders and file names etc.

[AB#471](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/471)

**Comment by robgates** [comment]
Have also seen a slight issue when it tries to rename a group with all capitols ie ABC as Abc

**Comment by marshalleq** [comment]
I think what we need is a file / folder saving template that is adjustable by the user.
