### ISSUE TITLE
Move entire install to D: drive in Windows 

### ISSUE THREAD

**Issue by MrMxyzptlk** [lidarr/Lidarr#224]
This is a request for a how to on moving Lidarr to another Windows drive beside C:

**Comment by MrMxyzptlk** [comment]
This is a request for a how to on moving Lidarr to another Windows drive beside C:

**Comment by Qstick** [comment]
Not sure I quite understand, just use the windows zip and drop it where you want

**Comment by MrMxyzptlk** [comment]
I ran a precompiled exe to install Lidarr, and it installs to C:\ProgramData\Lidarr
If I stop the service and uninstall the service, I can move the folder for Lidarr to the D: drive, re-run the installer for the service and start the service, but the service creates all of the databases and such back at the original location.

**Comment by MrMxyzptlk** [comment]
OK, I downloaded the latest zip, extracted the whole file to my D: drive, and ran the install service executable.

It still created the db and files on the C:\ProgramData\Lidarr directory rather than the folder on  my D:, where I installed from. I'm running as admin, and I changed the service to run as a local admin, but it still only let's me view the website from the localhost.

Thank your for your time.

**Comment by MrMxyzptlk** [comment]
bump. Please let me know if I'm not making myself clear, I will be happy to clarify?

**Comment by danielunderwood** [comment]
You can run lidarr with the `-data` option to choose the data directory, so it sounds like `-data D:\ProgramData\Lidarr` or similar would work for you. I'm not really familiar with Windows services though, but it looks like [this SO answer](https://stackoverflow.com/a/6491219/2383721) will tell you how to give arguments to a service.

**Comment by MrMxyzptlk** [comment]
Perfect! Thank you for your time.
