### ISSUE TITLE
Can only view Lidarr on localhost, how do I fix this issue?

### ISSUE THREAD

**Issue by MrMxyzptlk** [lidarr/Lidarr#225]
I'm running the latest dev build on Windows and it's working perfectly, get the following error in my browsers outside of the server Lidarr is installed on.

Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.

I've tried the hostname, FQDN, and IP, but it only works on the server using localhost:8686

**Comment by Qstick** [comment]
Run as admin

**Comment by STaRDoGG** [comment]
Just FTR, I had the Windows installer install the service for me, and ran into this problem.

I had read to run it as Admin, so when into the install folder, right-clicked on both the Console.exe and regular .exe, chose "run as Admin" under the Compatibility tab, restarted the service and it still didn't fix the problem.

Eventually after a couple hours of wrestling with it, as a  test I stopped the service, manually ran the regular .exe as admin and loaded the page, shut it down and restarted the service, and it suddenly worked fine.

Apparently, the main .exe needs to be run as Admin once before even the console.exe's service will work.
