### ISSUE TITLE
Option to have lidarr just move entire torrent folder to Artist folder without modifying files/analyzing etc

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#226]
This would reduce the amount of errors that Lidarr generated and stop the copy/move process from breaking. Currently Plex is able to match all albums/tracks/artist info from raw unmodified torrent files. i just want Lidarr to move the album from the torrent to the artist folder, and let plex deal with the metadata. Currently Lidarr breaks to often trying to match songs/albums that it's more effort manually fixing them. Plex seems to solve this.

**Comment by Qstick** [comment]
If we don’t analyze the files then we don’t catch fakes. Import will improve in coming weeks, this seems like a cover up to import issues which we don’t want to do

**Comment by bobloadmire** [comment]
I understand that it's a work around solution, but I haven't got any fakes
yet, and it could just be a tickbox opt in, until the situation improves.

**Comment by ta264** [comment]
IMO import is now good enough that this isn't necessary
