### ISSUE TITLE
Path of MediaCovers can be configured

### ISSUE THREAD

**Issue by Dude77777** [lidarr/Lidarr#2265]
**Is your feature request related to a problem? Please describe.**
The album covers stored in C:\ProgramData\Lidarr\MediaCover take a significant amount of space, some single covers are 128 MB big. 

**Describe the solution you'd like**
Please consider allowing the path where they are saved to be configured and potentially an option to switch off artist / albumart altogether.  Saving these to where the music is saved is probably a good option for most people.

**Describe alternatives you've considered**
Many people already have folder and artist pictures stored in the Artist / Album structure, maybe you could find a way to leverage these instead of recreating duplicate information?

Many thanks for your consideration

**Additional context**
-

**Comment by RobinDadswell** [comment]
If this is an issue you can symlink the folder elsewhere or run with the --data parameter and specify a location for the entire config directory (not on network storage). This is the same as the other Arrs.
