### ISSUE TITLE
Check for MusicBrainz id tags when importing tracks before trying to figure them out through the normal method

### ISSUE THREAD

**Issue by Rawrmonkeys** [lidarr/Lidarr#227]
### Description of request and what problem are you looking to solve?
There are already fully fledged tools that are available for tagging and managing audio files and those tools will be superior to Lidarr for performing that task for a very long time. It makes plenty of sense to check for the existence of those tags before trying to calculate from scratch.

Reasons:
1. It should reduce load on your metadata server
2. It is a valid use case for Lidarr (using Lidarr when something else manages the tags)
3. It is a great short term solution for a lot of the improvement requests being filed (including the various artists issue since the id would bypass the reason for blacklist)

### Other Information
Here is a screenshot of what the tags look like when I open with Picard (left column was tagged with Beets, right column is what Picard thinks the tags should be).
![screenshot from 2018-03-14 02-45-41](https://user-images.githubusercontent.com/37365491/37394888-2112be16-2732-11e8-8221-04a22097917e.png)

**Comment by Qstick** [comment]
Reference https://github.com/mono/taglib-sharp/issues/98

**Comment by Rawrmonkeys** [comment]
I'm sure you are already aware of this, but the release group id isn't really required for this. If my interpretation of the schema is correct (https://musicbrainz.org/doc/MusicBrainz_Database/Schema#Track), the track id is enough to get the recording id, the release id, and the track position on the release. I believe Lidarr is matching albums to the release id (as release-group doesn't contain track information).

And on a side note, if this change goes through, it could have side effects on the import process (if Lidarr options are set to generate folders and whatnot). In theory, I would be able to import from the album folder, which currently doesn't seem to work as it can't match to an artist based off song titles.

**Comment by Qstick** [comment]
Yep aware, however using the release id or release group id will at the very least allow us to match the correct album without calling to metadata since we store this info in db locally.
