### ISSUE TITLE
Add firewalld service config

### ISSUE THREAD

**Issue by k4my4b** [Lidarr/Lidarr#2278]
**Is your feature request related to a problem? Please describe.**

As firewalld is slowly taking over and most poeple are deploying it on their media servers it would be appropriate to add the necessary service configs for firewalld to prevent users having to configure this manually each time.

**Describe the solution you'd like**

Add [firewalld service file](https://firewalld.org/documentation/howto/add-a-service.html)

**Describe alternatives you've considered**

Users will have to take care of this manually (very inconvenient)

**Additional context**

[AB#136](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/136)

**Comment by bakerboy448** [comment]
closing; maybe eventually, no plans at this time
