### ISSUE TITLE
Lidarr not deleting source files after import.

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#228]
### System Information/Logs

**Lidarr Version:**
latest
**Operating System:**
windows 10

I have selected that Lidarr removes the source files after import, but it's not happening. I confirmed that the files weren't in use during import operations, logs aren't throwing any errors.

**Comment by Qstick** [comment]
Can you post trace logs, it’s not just the errors we are looking for in them. Thanks

**Comment by bobloadmire** [comment]
ok, i'll try and force deletion and grab a log. meanwhile, pretty sure it's related to this, the Sonarr guys have the same problem. https://www.reddit.com/r/sonarr/comments/84a1ds/not_deleting_from_qbittorrent/

**Comment by Qstick** [comment]
We pulled Sonarr fix for that over last nigh, should be in build 301. Please confirm that fixes it

**Comment by bobloadmire** [comment]
negative, on build 306, all files are in both locations, download folder and catalog folder.

**Comment by bobloadmire** [comment]
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/1831076/Lidarr.txt)
heres the loggyboi

**Comment by Qstick** [comment]
Is this still happening after 0.2.0.318?

**Comment by marshalleq** [comment]
Still happens to me.  Quite annoying.

**Comment by pb1051** [comment]
I have Lidarr set to rename files on my Ubuntu server and all it does is copy and rename the file. It doesn't not delete the original file.

**Comment by bobloadmire** [comment]
any update on this? still happening to me.

**Comment by j21w91** [comment]
This happens to me, too

**Comment by Qstick** [comment]
@ta264 this is fixed now, right?

**Comment by marshalleq** [comment]
Has their been a specific fix for this?  I hadn't noted one - will check if it's fixed but didn't think it was.

**Comment by Qstick** [comment]
Looking at DownloadedTracksImportService.cs, this should be working as long as no audio files are left, no large rar files exist, and Lidarr is able to move files and not copy. If any of those things are not true then it will not delete the download folder.

**Comment by ta264** [comment]
Yeah, pretty sure this works fine and it's just configuration issues.

@marshalleq jump on the discord support channel and we can try to figure out why it's not working for you

**Comment by ta264** [comment]
Closing this for now, if anyone can provide evidence of it still not working we can reoepn

**Comment by pb1051** [comment]
Working for me and confirmed ok
