### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by slimshizn** [lidarr/Lidarr#229]
## Support / Questions

Please use https://discord.gg/8Y7rDc9 for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Lidarr Version:02.0.291**

**Operating System: Docker**

**.net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.10.0.160**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Additional Information

I tried /downloads in nzbget, and got move failurs
failures*
Mappings
Lidarr
/share/CACHEDEV1_DATA/Download/Lidarr    /downloads
/share/CACHEDEV1_DATA/Music    /music
/share/CACHEDEV1_DATA/appdata/Lidarr    /config

nzbget category
/share/CACHEDEV1_DATA/Download/Lidarr

qnap dir optional location inside of lidarr
/share/CACHEDEV1_DATA/Download/Lidarr

I've tried changing nzbget category to /downloads and it failed
qnap dir i've changed that to /downloads and that did not change anything

The files are going to the download directory that lidarr is supposed to see, progress is showing while downloading. Once downloaded I'm getting the 
Import failed, path does not exist or is not accessible by Lidarr: /downloads/NOFX - Self-Entitled (2012) [FLAC]

I am able to delete this "failed import" inside of lidarr just fine and it takes it out of the download dir its supposed to be seeing to import.

**Comment by Qstick** [comment]
This appears to be support issue, we will continue working it in discord.

**Comment by slimshizn** [comment]
Issue has been fixed. When using DOCKER or Portainer and trying to point to a native host directory, Lidarr wont see /downloads if Nzbget is using the host directory (/share/music or /share/downloads). Both directories need to be named whatever the HOST directory is ( music = /share/music --> /share/music [BIND] ) (download = /share/download--> /share download [BIND] ). That being said I'm sure most people that run full unraid setups using only docker containers wont see this issue.
