### ISSUE TITLE
Add tag to monitor albums with missing songs

### ISSUE THREAD

**Issue by dorel14** [lidarr/Lidarr#2298]
Hello
i have some albums with missings songs , i'd like to monitor them so that they would be downloaded and then obtain a complete album.

Thx

**Comment by bakerboy448** [comment]
Closing; no action needed; existing functionality.
Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.
