### ISSUE TITLE
Add 'change metadata profile' to mass editor

### ISSUE THREAD

**Issue by Davo1624** [Lidarr/Lidarr#2302]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the Mass Editor page add an option to edit metadata profile to allow for mass editing/changing of metadata profiles for existing files

**Describe alternatives you've considered**
Go through each artist individually to change metadata profile which would not be ideal

**Additional context**

[AB#115](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/115)

**Comment by ta264** [comment]
This already exists, just press the 'options' button and enable the metadata profile column

**Comment by boekhold** [comment]
There is no way to reset the metadata profile to 'None'... this would be useful in my case because I messed up during my initial Music Library import, and I've got way to many listings under each artist now. I'd like to reset this to only those releases I actually have on disk...

**Comment by bakerboy448** [comment]
reopening for @Qstick for some cleanup and user improvements

- [ ] - Add Metadata Profile of `None` to mass editor
- [ ] - Default `Metadata Profile` to enabled for mass editor

**Comment by steve1977** [comment]
Would be great to see this being added. Would love to change the metadata profile in the "mass editor".

**Comment by TurboStreetCar** [comment]
> There is no way to reset the metadata profile to 'None'... this would be useful in my case because I messed up during my initial Music Library import, and I've got way to many listings under each artist now. I'd like to reset this to only those releases I actually have on disk...

I would also like to request the addition of NONE to the mass editor for metadata profile. I too seem to have set every album to standard, which imports all releases listed under the standard metadata profile, and i would also like to reduce that to only the releases i have on disk.

**Comment by Mrpink200** [comment]
i have the same need. I would be great to add this option
