### ISSUE TITLE
Change blacklist behaviour for cases where name of album like name of artist

### ISSUE THREAD

**Issue by sir-verfam** [Lidarr/Lidarr#2313]
**Is your feature request related to a problem? Please describe.**
I am trying to grab artist: "Elvis Presley", album: "Elvis" and the grabber kinda grabs every album of Elvis Presley only to find out it doesn't match after download. So I blacklist the release but it seems that means the release is blacklisted for the artist as a whole and not only the album, but this same release might be the right one for another album.

**Describe the solution you'd like**
Either optimize the algorithm to grab the releases (I myself are not sure this is possible in this case...) or change blacklisted items to be blacklisted only for this artist AND album combination not the artist alone.

**Describe alternatives you've considered**
For now i am manually trying to grab the album and removing all the blacklist entries for this artist afterwards so the remaining albums hopefully get grabbed automatically.

**Additional context**
As I don't think screenshots are of any help and I think the above should explain it good enough I am not sure if there is something more to add, but feel free to ask if necessary. I'm kinda new to github but I'll try to catch replies and act accordingly.
I'll also appreciate mention of an already existing solution to my problem which I just don't see.

[AB#1227](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1227)

**Comment by bakerboy448** [comment]
Blacklisting releases is at the System level.

I wouldn't foresee this behavior changing, but will defer to Ta or Q
