### ISSUE TITLE
Deleting Album Rsults in Remonitored and Redownloaded

### ISSUE THREAD

**Issue by B1ue-W01f** [Lidarr/Lidarr#2317]
**Describe the bug**
Deleting an album that has already downloaded results in the monitor status being reset and as a result the album is redownloaded.

**To Reproduce**

1. Go to an artist
2. I don't want a particular album that has already downloaded (i.e. a new album)
3. Un monitor album
4. Select Album
5. Delete album 
6. Album is removed from the artists page (not just the files, the album)
7. On next refresh the album is resynced and redownloaded

**Expected behavior**
Unmonitored album remains, files within it are deleted, it is not redownloaded

**Platform Information (please complete the following information):**
 - OS: Debian
 - Docker: No
 - Mono or .NET Version (System -> Status): .Net Core 3.1.13
 - Lidarr Version: 0.8.1.2135
 - Lidarr Branch: master

[AB#1255](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1255)

**Comment by bakerboy448** [comment]
fixed your post, you lost the `-->`  

trace logs as well?

> **Trace Logs**
> Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
> **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
> \
> \

**Comment by ta264** [comment]
This is expected behaviour, if you don't want the album to come back you have to select the option that comes up when you delete it to "add exclusion", otherwise it warns you exactly this will happen.

**Comment by B1ue-W01f** [comment]
@ta264 With the greatest of respect, given the album listing is going to be resynced at the next opportunity anyway and the 'unmonitored' feature is the defacto approach to monitoring assets, it would not be expected behaviour that deleting an album on a users implementation would result in the listing being temporarily removed losing all previous settings on it - i.e. monitored status, only for it to reappear defaulting to monitored shortly after.

This current approach would result in an incredibly unwieldy exclusions list, that has to be managed in parallel but separately with the unmonitored status.

I'm not quite sure what use case the exclusions list should have when the monitored / unmonitored approach is the defacto standard tbh, but if this is considered the right method, we appear to have a duplication of purpose with one approach being less convenient to manage and the other less predictable.
