### ISSUE TITLE
Wiki Links are Broken and do not abide by WikiJS link standards #4579

### ISSUE THREAD

**Issue by bakerboy448** [Lidarr/Lidarr#2318]
- [x] All Wiki Links in-app need to be corrected.  ref (https://github.com/Radarr/Radarr/commit/84d1a8983bee6ec17e4ca11bdcb97ff6254845f2)
- [x] Review and add missing healthcheck links as needed (ref https://github.com/Radarr/Radarr/commit/5696fa2efef89b829274969c389875aea4b7b4e7)
- [ ] Code correction so useful/correct links are provided; some lists return `lidarrlists` which is useless
- [X] Supported links need fixing, PR'd https://github.com/Sonarr/Sonarr/pull/4578
As a result of the MediaWiki -> WikiJS changes the wiki links are generally no longer valid. a proxy redirect is on the server to handle redirects in a best effort format, but that cannot modify the somepage#bookmark, bookmark links.  This effectively means the bulk of the in-app links are useless.

Ref previous wiki updates of:
https://github.com/Lidarr/Lidarr/commit/2cb36e61e0ee27135ccbcc9e801b8a89438c166a
https://github.com/Lidarr/Lidarr/commit/1268f90f2633d4075c787fa1f25005b585073e50
?others?

All wiki links must now be 1) lowercase and 2) any spaces replaced with `-` not `_` additionally pathing has changed e.g. Lidarr_System is now lidarr/system

[AB#1256](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1256)

**Comment by bakerboy448** [comment]
Closed by https://github.com/Lidarr/Lidarr/commit/3d1437bf18850c0e6d78cabc7422b81c68e2e7e8

**Comment by bakerboy448** [comment]
Re opening for the one outstanding task around the import links needing to use a different piece for the API that generates the infolink

**Comment by bakerboy448** [comment]
@Qstick did we fix this

> Code correction so useful/correct links are provided; some lists return lidarrlists which is useless

**Comment by Qstick** [comment]
There's been no PR or comment, so I'm assuming yes or it doesn't matter.
