### ISSUE TITLE
Compilation are considered an album release

### ISSUE THREAD

**Issue by icf20** [Lidarr/Lidarr#2328]
how to reproduce 

1 add Boney M.

2 add all albums

3 there should be something like 85

Boney M. released 7 albums, not 85,  compilations should not be considered albums 

[AB#1313](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1313)

**Comment by ta264** [comment]
Exclude compilations from your metadata profile if you don't want to see them
