### ISSUE TITLE
0.2.0.292: empty homepage (artists page)

### ISSUE THREAD

**Issue by crobe87** [lidarr/Lidarr#235]
## Bug Report
starting from ~~v. 297~~ v.292  the artists page (aka homepage) is rendered empty.
Empty means light grey with nothing on the screen. Attaching the html source of the page and the trace.
I can nav to other pages if I input the direct url in the browser (e.g. /system/status), this way the UI shows, but if i try to click the artists page, it will show empty, as above.

### System Information/Logs

**Lidarr Version:**

290 works fine
291 works fine
292 NOT WORKING aka bc5e596b2cf82e9db4cd4f26728418bb029597bf
293 NOT WORKING
294 NOT WORKING
295 works fine
297 NOT WORKING
298 NOT WORKING
299 NOT WORKING
300 NOT WORKING

**Operating System:**
DOCKER (using linux artifacts) running on ubuntu 16.04 host 
**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono 5.8.0.108
**Link to Log Files (debug or trace):**

[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/1815034/Lidarr.trace.txt)

[LIDARRartistsempty.html.txt](https://github.com/lidarr/Lidarr/files/1815050/LIDARRartistsempty.html.txt)

**Browser (for UI bugs):**
chrome, firefox, brave
### Additional Information
only the artists page. everything else works fine.

**Comment by crobe87** [comment]
saw some js errors on console, only on artists page. no errors elsewhere
![jserrors](https://user-images.githubusercontent.com/22624418/37462060-ed0f19be-2850-11e8-825b-e3408613b7a5.png)

**Comment by crobe87** [comment]
**version 297 errors:**
![v297_jserrors](https://user-images.githubusercontent.com/22624418/37462281-aebaa3f8-2851-11e8-82c1-800c737a0d3c.png)

**Comment by crobe87** [comment]
the splash screen loads correctly, it shows the message (e.g. remember to tip the waiter) and the animated icon. 
Then both the message and the icon disappear but the page stays stuck with the same light gray background color of the welcome splash. (#f5f7fa) 
And those message show in the console.

**Comment by crobe87** [comment]
did some more tests, the culprit seems **v292**. It was somehow fixed in v295, then reappeared since v297.

290 works fine
291 works fine
292 NOT WORKING
293 NOT WORKING
294 NOT WORKING
295 works fine
297 NOT WORKING
298 NOT WORKING
299 NOT WORKING
300 NOT WORKING

when it's NOT WORKING, the js errors are always the same of the picture above.

**Comment by Qstick** [comment]
I'll get this buttoned up tonight, looks like an issue when I rebased

**Comment by Qstick** [comment]
Hopefully 94cca69e925586015196fdd5fbc9c3c3327f02a3 fixes this. Can you test build 301

**Comment by crobe87** [comment]
`Hopefully 94cca69 fixes this. Can you test build 301`
Nope, that doesn't work. Same problem, same errors, same empty artists page.
Tried on incognito and different browsers.

**BTW** : I use https://github.com/hotio/docker-suitarr , it grabs the artifact from appveyor and just run the image, no updates needed no anything. you just specify the version on the docker run command. That's how I can quickly test different versions. (also it allows to use jackett too, very convenient)

Also tried on https://hub.docker.com/r/volikon/lidarr/ and the issue is happening on that container too.
All of this on ubuntu 16.04 host + docker + one of those containers above.

**Comment by screwfaze** [comment]
I too am having this problem let me know if you need any logs.

Thanks

**Comment by hikaricore** [comment]
I can confirm this issue is present on 0.2.0.301 as well. Tested on 3 different OSes and 4 different browsers.

Anything aside from the main Artists page still loads fine from saved links/history, so it's only really affecting the ability to refresh all artists imho. Sounds like the cause may be known, so take your time.  ^_^

**Comment by Qstick** [comment]
Give 302 a whirl when it builds

**Comment by hikaricore** [comment]
Seems fine in 0.2.0.303. I would assume this is the case for 302 as well. Thanks for the quick fix.  :D

**Comment by zductiv** [comment]
Working for me on .302
