### ISSUE TITLE
Feature Request / bug (?): Handle "Album + Mixtape/Street" albums

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#236]
Example here: https://musicbrainz.org/artist/713e751f-3ddb-4b77-b3b1-9e6f2e953ad5

"Album + Mixtape/Street" not listed by Lidarr.

**Comment by danielunderwood** [comment]
You need to create a metadata profile with the additional types desired, change the profile selection for the artist, and refresh the artist. Note that there is no profile option if you haven't created an additional profile.
