### ISSUE TITLE
[FEAT]: Add a "delay" option to indexers

### ISSUE THREAD

**Issue by pkreuzt** [Lidarr/Lidarr#2360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some trackers force a "wait time" for normal (non-premium) users, so you have to do manual search and wait a specific time after first grab fails, then second one after waiting works. Currently I have only seen this issue on MetalTracker, but it's possible other trackers work this way too.

### Describe the solution you'd like

It's desirable to have a "delay time" option on indexer definitions. This way Lidarr would insist on a grab after waiting for a specific time after a first grab fails. This is tracker specific, different trackers can have different wait periods. Also, this solution could be imported into Sonarr and Radarr if necessary.

### Describe alternatives you've considered

Don't know if this could be done on Jackett. In that case I would go pester them about it.

### Anything else?

Example of tracker with delay to download:

![2021-08-10-014609_992x540_scrot](https://user-images.githubusercontent.com/6936840/128788166-3f5eb590-2d6f-4e3a-b3d4-26a691213c84.png)

![2021-08-10-014711_991x610_scrot](https://user-images.githubusercontent.com/6936840/128788120-0830b298-5b79-4950-bf95-c6e3d9c73afc.png)

[AB#1423](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1423)

**Comment by bakerboy448** [comment]
This seems like the app making the request to get the download contents should handle....so Jackett and Prowlarr in this case.
