### ISSUE TITLE
Torznab not working, randomly, with Jackett

### ISSUE THREAD

**Issue by bobloadmire** [lidarr/Lidarr#237]
I am adding indexers to Lidarr, the same set I have configured in Sonarr and Radarr. They work fine when I hit the test button in Sonarr and Radarr, but some of the indexers don't work in Lidarr, Torlock for example. When I hit the test button it says no results returned from indexer and doesn't allow me to save it. Additionally the Test procedure isn't showing in the logs, as a search for the term "Torlock" in the log after testing yields no results. log attached anyway.
note some other providers work fine. I double checked the category numbers.

[Lidarr.txt](https://github.com/lidarr/Lidarr/files/1820365/Lidarr.txt)

**Comment by Qstick** [comment]
This is a Jackett issue not a Lidarr issue. They have many of the indexer configs setup to default to video categories when running test call, therefore no results return for music. I have been successful in getting them to fix them by creating issues on their git hub.

**Comment by bobloadmire** [comment]
I manually overriding the categories to the listed ones for audio though.
Thats not the issue? I noticed a lot we're listed incorrectly.

**Comment by Qstick** [comment]
For many indexers Jackett ignores the passed categories for test calls. That's the issue. Let me look at the config in Jackett source for that indexer and I'll confirm.

**Comment by Qstick** [comment]
Confirmed that Jackett doesn't use passed categories for torlock. It just tests with the fresh feed which will fail if no music releases are present in it. Jackett needs to update their torlock definition

**Comment by bobloadmire** [comment]
So start an issues on the jackett git?

**Comment by bobloadmire** [comment]
also do you have a suggestion for compatible trackers to setup in jackett?

**Comment by Qstick** [comment]
I'll stick one in tonight for you letting them know exactly what needs to be done.

**Comment by Qstick** [comment]
FYI https://github.com/Jackett/Jackett/issues/2732

**Comment by bobloadmire** [comment]
Thanks!
