### ISSUE TITLE
Jump bar crashes 

### ISSUE THREAD

**Issue by crobe87** [lidarr/Lidarr#238]
## Bug Report
When I click an initial on the jump bar inside the artists page, the script crashes and shows only an empty gray background.

### System Information/Logs

**Lidarr Version:**
0.2.0.303
**Operating System:**
host ubuntu 16.04, docker hotio/suitarr container
**.net Framework (Windows) or mono (macOS/Linux) Version:**
mono 5.8.0.108
**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**
chrome
### Additional Information
![jumpbar303](https://user-images.githubusercontent.com/22624418/37556769-e1d593ec-29fa-11e8-908f-f7ccae1eb221.png)

**Comment by Qstick** [comment]
Test 305, building now

**Comment by crobe87** [comment]
305 fixed it.
