### ISSUE TITLE
[BUG]: Organize & Rename doesn't follow renaming pattern

### ISSUE THREAD

**Issue by jeff47** [Lidarr/Lidarr#2382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In "Preview Rename" section, the names shown do not follow the naming pattern selected.  See the screenshot below.

### Expected Behavior

It the renamed file should follow the pattern shown.

### Environment

```markdown
- OS: docker
- Lidarr: 0.8.1.2135
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Brave
```

### What branch are you running?

Develop

### Anything else?

<img width="1047" alt="Screen Shot 2021-08-30 at 10 27 25 AM" src="https://user-images.githubusercontent.com/7215369/131355528-18698ce1-32f4-40f6-9300-d3cc193e20d7.png">

[AB#1537](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1537)

**Comment by ta264** [comment]
Pretty sure you haven't enabled track renaming. If it does turn out to be a bug we can reopen.

**Comment by jeff47** [comment]
Ah, sorry About that.  It's confusing the way it shows the pattern when
it's not enabled.  Maybe an item for a future update would be helpful.
