### ISSUE TITLE
[FEAT]: Wanted 'Search All' change order

### ISSUE THREAD

**Issue by nssatlantis** [Lidarr/Lidarr#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have about 8000 records that have been sitting, waiting patiently. The system itself will not go through them, thank god. But at some point I want to re-try them all. 

The issue is that the order they go in (old to new? Idfk) will mean that I will be spending AGES to let the system go through them all, last time I tried 'search all' it started at around 1.30PM and wasn't finished at 3AM the next day.

I cannot change the order to lets say, latest music (much higher chance to get captured/downloaded), or to anything for that matter. Making searching that list completely impossible.

Not to mention, the first 1000 it tries have already been tried, give broken downloads or are otherwise a pain in the ass, switching from newest music to oldest will help me a lot in this.

### Describe the solution you'd like

In the 'wanted' page, I would like to be able to change the order in which the 'search all' function goes through them. Starting at newest/latest music and tracking back. Even better would be to let us decide the sorting, so everybody has their own choice.

Because re-downloading the same 1000 songs/albums isn't doable. And leaving my PC on for 3 days while it processes 8050 records is a real pain in the ass, and it gets worse when I have to go through them by hand after that.

### Describe alternatives you've considered

Page by page... You can do 3 'at a time'. But with now 408 pages, I am not looking forward to this shit at all.

No other ideas or alternatives that I can think of.

### Anything else?

Nothing else, I hope the feature suggestion makes sense! Cheers!

[AB#1552](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1552)

**Comment by ta264** [comment]
I don't really get what changing the order solves? You'll still end up with the same bunch of broken downloads when it finishes.

**Comment by nssatlantis** [comment]
> I don't really get what changing the order solves? You'll still end up with the same bunch of broken downloads when it finishes.

Ok so if going through 8000+ records, starting from oldest to newest takes more than a day at least, knowing most torrents will only keep up with newer music and not music from let's say 50 years ago, and usually provides shady downloads posted ages ago.

I'd much rather make it start that 8000 from the latest music that has a bigger chance to download, rather than spend many hours of my time manually going through a list of that size.

Old downloads suck and fail, new ones not so much. You see my point now?

**Comment by ta264** [comment]
I don't I'm afraid.

I agree new downloads are more likely to succeed. But what do you gain by having us invest all the effort to do this?  Ultimately all the old and the new downloads will end up in the download client.  If you want something more urgently, don't rely on search all.

**Comment by nssatlantis** [comment]
There's the thing, yes, eventually they all get sent to the download client, and yes, they may be the same bad downloads with the same issues.

But the problem is that there is no sensible way for me to go through 8000 records by myself, going through 400+ pages to do them page at a time, or to just hand-pick select artists/tracks (400 artists). 

The easier method would be to filter out whatever it does find and send to the download client myself through the activity page, which takes a lot less time and effort. But the main problem I have is that if I hit 'Search All', it will go through the exact same list in the exact same order as the previous time. It will continue to check every single one again in the same order.

The 'Search All' command takes a lot of time to process, I can't run my server 24/7 due to heat, noise and costs. So at some point I have to end it. But then the next day, I can hit that button again, but it will go through everything it went through yesterday all over again, which means at the end of the day I have the same issue because I keep starting back at the starting point.

So all I was hoping to request was a way to make the 'Search All' button somehow go in the order of the missing music you already display, which you *can* sort based on for example release date. Even if it would just be set in random order, or inverted order, it would mean it searches for downloads for other music at some point too, rather than just the same tracks again.

**Comment by ta264** [comment]
No plans for this. Search all should be a one off operation, do it once and let it run all the way through.

**Comment by farhills** [comment]
I know this was closed, but I've wanted the same thing. I am exclusively on newsgroups, and most of my indexers have limited well below what's wanted. The first 1000 or 5000 items on the list get the benefit of allmindexers, but have been searched many times before without results. The remainder of the wanted list gets substantially fewer search hits.

In my use case, I allow lidarr to run passively in the background, slowly building a library. I'm not actively curating a collection, rather just letting a few lists automatically add artists.

I would like if search all was pseudo random, perhaps processing the list sequentially, but starting at a random alphabetical artist or album release date. Over time my full wanted list would eventually get a good quality search.

Just another perspective on the request. Appreciate all the effort that goes into making this great tool!

**Comment by nssatlantis** [comment]
> I know this was closed, but I've wanted the same thing. I am exclusively on newsgroups, and most of my indexers have API limits well below what's on the wanted list. The first 1000 or 5000 items on the list get the benefit of all indexers, but have been searched many times before without results. The remainder of the wanted list gets substantially fewer search hits as I only have one indexer with unlimited API hits.
> 
> In my use case, I allow lidarr to run passively in the background, slowly building a library. I'm not actively curating a collection, rather just letting a few lists automatically add artists. I run a search all once in a while manually to try and pick up new things that RSS missed for whatever reason.
> 
> I would like if search all was pseudo random, perhaps processing the list sequentially, but starting at a random alphabetical artist or album release date. Over time my full wanted list would eventually get a good quality search.
> 
> Just another perspective on the request. Appreciate all the effort that goes into making this great tool!

Since the developer was less than happy to try and understand the issue, I can give you a suggestion on a 'work-around', unfortunately it requires a lot of custom work but I guess you can't have everything.

Go to 'Wanted' page, hit the gear icon on that list, set the amount of music shown to 250 items. You can select all, search, go to page 2, select all, search. It should work with 3 pages at a time.. Best wait because I noticed it doesn't really like it.

Such a shame, my indexer some times crashes, or returns an error completely ruining the 'search all' function, not once has it completed or came close to it. And every damn time we're back going from the start of the list, searching the first 1000 un-downloadable songs and then dying yet again.

**Comment by farhills** [comment]
Good suggestion, thx.

I don't want to pile on the devs though. Time is limited and this is their project. They get to decide priorities.
