### ISSUE TITLE
[FEAT]: Allow bypassing ignored categories

### ISSUE THREAD

**Issue by stevelup** [Lidarr/Lidarr#2389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Indexer searches often fail due to Newznab categories being filtered out. It would be preferable if the pre-defined list of ignored categories was either not hard coded or can be bypassed.

### Describe the solution you'd like

Remove the hard coded list of ignored Newznab categories (or at least users to opt out of the ignore list).

in NewznabCategoryFieldOptionsConverter.cs:-

```
// Ignore categories not relevant for Lidarr
var ignoreCategories = new[] { 1000, 2000, 4000, 5000, 6000, 7000 }; 
```

### Describe alternatives you've considered

I don't believe there's any alternative.

### Anything else?

N/A

[AB#1587](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1587)

**Comment by ta264** [comment]
Please can you provide some evidence this is actually a problem?

**Comment by stevelup** [comment]
Here is one example - for whatever reason on both the indexers I use this release is categorised as 'Books > Technical' which is 8040.

![example](https://user-images.githubusercontent.com/6773103/133601053-f2000fdc-a622-45ad-a33e-0cf01ddad67f.PNG)

There seem to be many releases (particularly FLAC for some reason) which have the 8040 category.

**Comment by ta264** [comment]
This needs a bit of thought.  I wouldn't want to allow those categories to work around rubbish indexers and risk worse results from good indexers.
