### ISSUE TITLE
System/Events info modal: close buttons not working

### ISSUE THREAD

**Issue by crobe87** [lidarr/Lidarr#239]
## Bug Report
when viewing system/events, I click the "info" button to see the details of an event. A new "Details" modal opens: can't close it using mouse. 
The "X" on corner doesn't work, the "close" button does nothing. It closes only hitting ESC on keyboard.

### System Information/Logs

**Lidarr Version:**
0.2.0.306
**Operating System:**
ubuntu/docker 
**.net Framework (Windows) or mono (macOS/Linux) Version:**
0.2.0.306
**Link to Log Files (debug or trace):**
no js errors, nothing on trace
**Browser (for UI bugs):**
chrome, firefox
### Additional Information
![buttonsfail](https://user-images.githubusercontent.com/22624418/37563358-44601df0-2a7f-11e8-8a5d-694d5334b6fe.png)

**Comment by Qstick** [comment]
Thanks for all of these issues, this helps out greatly..... keep them coming!
