### ISSUE TITLE
[FEAT]: Lidarr Hungarian translate

### ISSUE THREAD

**Issue by zsigus** [Lidarr/Lidarr#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hi,
I would translate it into Hungarian
Please help to get started.

Thank you

### Describe the solution you'd like

Please send file to translate, or link project Translation Platform.

### Describe alternatives you've considered

Nothing.

### Anything else?

No.

[AB#1732](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1732)

**Comment by bakerboy448** [comment]
Once this is merged:

https://github.com/Lidarr/Lidarr/pull/2427

 contributions can be made on weblate 

https://translate.servarr.com/projects/servarr/
