### ISSUE TITLE
Quality parsing fails

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/Lidarr#245]
`Parser.ParseQuality` returns `null` instead of `Quality.Unknown`.

**Comment by majora2007** [comment]
I am unable to reproduce this after extensive testing. @Qstick can we close and re-open if any user reports this?

**Comment by Qstick** [comment]
Only thing I see is there is no else statement for ogg codec:

https://github.com/lidarr/Lidarr/blob/b661344ba8b6117cd26e5de3a0d113bc9c27207c/src/NzbDrone.Core/Parser/QualityParser.cs#L124

Should be else result = quality.unknown
