### ISSUE TITLE
add album to download queue is not working

### ISSUE THREAD

**Issue by groenator** [lidarr/Lidarr#246]
For some wired reason, and I can't tell exactly what it is. I search manually for a new album, the album is appearing in the search. But when I add the album to download queue, all I get is a white blank page. 

I am using NGBGet to download the files, sonarr, radarr are working fine, is just lidarr that doesn't process the requests as expected. 

Is there something that you could advise?

Thanks!

## Support / Questions

Please use https://discord.gg/8Y7rDc9 for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Lidarr Version:**

**Operating System:**

**.net Framework (Windows) or mono (macOS/Linux) Version:**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

**Comment by Qstick** [comment]
Was fixed in 308
