### ISSUE TITLE
[BUG]: RemoteIP address is that of reverse proxy and not external IP address like in Sonarr

### ISSUE THREAD

**Issue by stephanrenggli** [Lidarr/Lidarr#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is largely copied from this radarr issue: https://github.com/Radarr/Radarr/issues/6552
I assume the problem and solution will be similar.  
I did not find a similar issue in the lidarr issues.

I'm trying to set up Fail2ban for Lidarr and running into an issue where the IP address listed in the logs is that of my reverse proxy and NOT the actual external IP address I want to ban. Sonarr has the right IP address in the log.

### Expected Behavior

The correct IP address is shown in the log when used with a reverse proxy, similar to what I see in Sonarr.

### Steps To Reproduce

1. Set up Lidarr with proxy
2. Log in with wrong credentials
3. IP in log will be the one of the proxy, not the real IP of the client trying to log in

### Environment

```markdown
- OS: Ubuntu 18.04
- Lidarr: 0.8.1.2135
- Docker Install: Yes (linuxserver/lidarr:latest)
- Using Reverse Proxy: Yes (linuxserver/swag:latest)
- Browser: Chrome 95
```

### What branch are you running?

Master

### Anything else?

Over at radarr this was fixed by this pull request: https://github.com/Radarr/Radarr/commit/6f0d5a0583593f4ffe82f6029b609b1bbf622f83

[AB#1900](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1900)

**Comment by RobinDadswell** [comment]
Already fixed in nightly https://github.com/Lidarr/Lidarr/commit/782bdcc0a9c118f4b7a25fc90a966a6381a7f248
