### ISSUE TITLE
[BUG]: Lidarr not working with Filelist Indexer (Bad Request)

### ISSUE THREAD

**Issue by PyCoder** [Lidarr/Lidarr#2470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Filelist indexer can't find anything and produces an error.

```
All search-capable indexers are temporarily unavailable due to recent indexer errors
All rss-capable indexers are temporarily unavailable due to recent indexer errors
All indexers are unavailable due to failures
```
` FileList HTTP request failed: [400:BadRequest] [GET] at [https://filelist.io/api.php?action=search-torrents&category=11 & type=name&query=Taylor%2BSwift+Red%2BTaylors%2Bversion]`

`HTTP Error - Res: [GET] https://filelist.io/api.php?action=search-torrents&category=11 & type=name&query=Taylor%2BSwift+Red%2BTaylors%2Bversion: 400.BadRequest {"error":"11 is not a valid category!"}`

`FileList HTTP request failed: [400:BadRequest] [GET] at [https://filelist.io/api.php?action=search-torrents&category=5 & type=name&query=Taylor%2BSwift+Lover]`

`HTTP Error - Res: [GET] https://filelist.io/api.php?action=search-torrents&category=5 & type=name&query=Taylor%2BSwift+Lover: 400.BadRequest
{"error":"5  is not a valid category!"}`

### Expected Behavior

This works fine on the other hand

`https://filelist.io/api.php?action=search-torrents&username=USERNAME&passkey=PASSKEY&category=5,11&type=name&query=Taylor%20Swift+Fearless`

`[{"id":741690,"name":"Taylor.Swift-Fearless .Taylor's.Version.2CD-2021","imdb":null,"freeleech":0,"doubleup":0,"upload_date":"2021-06-08 19:28:13","download_link":"https:\/\/filelist.io\/download.php?id=741690&passkey=6e147b7280ab385b3a2796fa836698a9","size":264315966,"internal":0,"moderated":1,"category":"Audio","seeders":3,"leechers":0,"times_completed":100,"comments":0,"files":27,"small_description":"Pop, Folk, World &amp; Country"},{"id":385494,"name":"[REQ] Taylor Swift - Fearless - 2008 (CD-FLAC-Lossless)-FL","imdb":null,"freeleech":0,"doubleup":0,"upload_date":"2015-10-17 18:05:09","download_link":"https:\/\/filelist.io\/download.php?id=385494&passkey=6e147b7280ab385b3a2796fa836698a9","size":409968958,"internal":0,"moderated":1,"category":"Audio","seeders":1,"leechers":0,"times_completed":374,"comments":2,"files":28,"small_description":"Album"}]`

https://github.com/baderproductions/filelist-app

### Steps To Reproduce

1) Setup Filelist indexer under indexers
2) Add an artist
3) Click on the artist
4) Go to albums
5) Click on the search icon (magnifying glass)

Or

1) Setup Filelist indexer under indexers
2) Add an artist
3) Go to wanted
4) Select what you want
5) Click search all

### Environment

```markdown
- OS: Debian buster/sid
- Lidarr: 0.8.1.2135
- Docker Install: YES
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Anything else?

![image](https://user-images.githubusercontent.com/1201123/141394484-4c309de6-d739-4831-a75f-e34496294c48.png)
![image](https://user-images.githubusercontent.com/1201123/141394503-0ce14bc8-5461-44a4-b9d5-ca15e41d7b94.png)

[AB#1901](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1901)

**Comment by bakerboy448** [comment]
What categories do you have configured in lidarr?

Sounds like both us, prowlarr, and jackett need to drop category 5?

**Comment by PyCoder** [comment]
There are two issues...

The spaces at `category=5 & type=` and the ` %2B` instead of `%20` for the spaces in a URL.

Not working (%2B):

`https://filelist.io/api.php?action=search-torrents&username=USERNAME&passkey=PASSKEY&category=11&type=name&query=Taylor%2BSwift+Fearless`

Ret: `[]`

Working (%20):

`https://filelist.io/api.php?action=search-torrents&username=USERNAME&passkey=PASSKEY&category=11&type=name&query=Taylor%20Swift+Fearless`

Ret: `[{"id":741690,"name":"Taylor.Swift-Fearless .Taylor's.Version.2CD-2021","imdb":null,"freeleech":0,"doubleup":0,"upload_date":"2021-06-08 19:28:13","download_link":"https:\/\/filelist.io\/download.php?id=741690&passkey=6e147b7280ab385b3a2796fa836698a9","size":264315966,"internal":0,"moderated":1,"category":"Audio","seeders":2,"leechers":0,"times_completed":100,"comments":0,"files":27,"small_description":"Pop, Folk, World &amp; Country"},{"id":385494,"name":"[REQ] Taylor Swift - Fearless - 2008 (CD-FLAC-Lossless)-FL","imdb":null,"freeleech":0,"doubleup":0,"upload_date":"2015-10-17 18:05:09","download_link":"https:\/\/filelist.io\/download.php?id=385494&passkey=6e147b7280ab385b3a2796fa836698a9","size":409968958,"internal":0,"moderated":1,"category":"Audio","seeders":1,"leechers":0,"times_completed":374,"comments":2,"files":28,"small_description":"Album"}]`

**Comment by PyCoder** [comment]
> What categories do you have configured in lidarr?
> 
> Sounds like both us, prowlarr, and jackett need to drop category 5?
> 
> edit likely the spaces, could give branch `filelist-search-string` a shot

Yes the spaces and maybe the %2B?

At least for me the request doesn't work with %2B instead of %20.
