### ISSUE TITLE
[BUG]: Queue Status Indicator Turns Orange with "Stalled" Queue Items

### ISSUE THREAD

**Issue by Hossy** [Lidarr/Lidarr#2476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the queue consists of only the following types:

- "Downloading" (gray cloud with down arrow)
- "Downloading metadata"/"Queued" (gray cloud)
- "Stalled"/"Download warning: The download is stalled with no connections" (orange cloud with down arrow)

the queue indicator has an orange background indicating action is required.

### Expected Behavior

The queue indicator should have a green background and shouldn't be triggered as orange for "stalled" torrents.

### Steps To Reproduce

1. Have at least one "Downloading" and "Queued" item in the queue to present a number and a green background.
2. Add a "Stalled"/"Download warning: The download is stalled with no connections" (orange cloud with down arrow) item in the queue and the background will change to orange.

### Environment

```markdown
- OS: Ubuntu 18.04 (bionic)
- Lidarr: 0.8.1.2135-ls15 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 95.0.4638.69 (Official Build) (64-bit)
```

### What branch are you running?

Master

### Anything else?

Sonarr and Radarr do not treat "stalled" torrents as needing action.  Instead, they leave the queue indicator with a blue background.  IMHO, this makes sense.  If you compare the states of a torrent between "Downloading metadata" (which lidarr treats as "Queued") and "Stalled," both are running and waiting for seeds.  There's nothing actually wrong with them other than having no seeds.

Below are screenshots showing this situation (optional "Downloading") in all three *arrs.  lidarr shows an orange queue indicator while sonarr and radarr show a blue queue indicator.

lidarr:
![image](https://user-images.githubusercontent.com/1756846/141877823-757c4c7d-823b-426e-aee7-47bd135d7414.png)
sonarr:
![image](https://user-images.githubusercontent.com/1756846/141877956-01423351-1c5f-4385-b38b-f74783d065a5.png)
radarr:
![image](https://user-images.githubusercontent.com/1756846/141877836-1ac1bbd4-7ebd-4b7e-b184-74af86d9c533.png)

[AB#1910](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1910)

**Comment by bakerboy448** [comment]
Not a bug. Orange = need human = stalled download is not downloading in your client thus needs a human
