### ISSUE TITLE
[FEAT]: Option to not embed cover art into metadata tags

### ISSUE THREAD

**Issue by sdfg2** [Lidarr/Lidarr#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In some cases the cover art embedded into the tags of a file can double or more the size of the file.  

### Describe the solution you'd like

An option to disable embedding cover art into the metadata.

### Describe alternatives you've considered

Script to strip the tag after it's been written, or an external script to do the same, but then that would mean not keeping the file metadata synced with Lidarr

### Anything else?

 Nope.

[AB#1963](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1963)

**Comment by erri120** [comment]
Any updates on this?
