### ISSUE TITLE
[BUG]: One specific artist is not pulling all releases from MusicBrainz

### ISSUE THREAD

**Issue by ChaosBlades** [Lidarr/Lidarr#2493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After going through all my UnmappedFiles from a very large library of over 500 Artist discographies I can find reasons for all of them why they are not matching except for one Artist. Acryl Madness.

https://musicbrainz.org/artist/319e17bb-1ff9-4e63-a489-1c225e0a1816

Tested with Release Profile set to everything checked it is only pulling 3 Albums. Segments, Void Entropy, and Extending Through Hell. I am still missing the other 9 albums on MusicBrainz. With the Release Profile set it should also be pulling the Single and EPs as well but it is not. I tried to manually import but it is not seeing the missing Albums that way either. Debug logs all look normal.

The missing albums are not listed as Video and have been on MusicBrainz for at least several months. I check another artist by setting the Metadata Release Profile to Everything and it pulls everything like it should. Very weird out of over 500 Artists to be doing this.

### Expected Behavior

Pull all Releases selected for Release Profile

### Steps To Reproduce

1. Make Settings > Profiles > Metadata Profiles. Make one to include everything.
2. Add lidarr:319e17bb-1ff9-4e63-a489-1c225e0a1816 to Lidarr
2. View Artist and only Segments, Void Entropy, and Extending Through Hell albums are present

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS x86_64
- Lidarr: 0.8.1.2135
- Docker Install: Yes, release-ab44c6d by hotio
- Using Reverse Proxy: No
- Browser: Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
```

### What branch are you running?

Develop

### Anything else?

https://gist.github.com/ChaosBlades/6dd15e91fe12c6d93c8f905dd6769b4e

[AB#1978](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1978)

**Comment by ta264** [comment]
None of the missing ones have a release status set on musicbrainz.  Correct the musicbrainz entries and lidarr will pull them in after the database syncs (around 5 past the hour)

**Comment by ChaosBlades** [comment]
Would be nice if the logs said `Info: No Release Status on [ALBUM]/[EP] skipping...` unless I am blind and didn't see it.

Lidarr should be able to match existing tracks during manual matching only to albums without a release status.

**Comment by ta264** [comment]
Afraid not, the album won't appear in our metadata feed without a release status, so your Lidarr instance doesn't have any data for them.
