### ISSUE TITLE
[FEAT]: Mass Editor add all to Import Exclusion list

### ISSUE THREAD

**Issue by minermartijn** [Lidarr/Lidarr#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I got quite some artist i want to delete and add to the import exclusion list, and have to do this manually now.

### Describe the solution you'd like

Sonarr and Radarr have the feature that when you mass edit and delete you can chose to add all the titles to the import exlusion list.
![ListExclusionsSonarr](https://user-images.githubusercontent.com/51987758/143895398-e04a7d39-8433-4f88-9fb1-8b118a8eafa2.jpg)

### Describe alternatives you've considered

Cant think of an alternative idea

### Anything else?

Sorry, I think its clear what i mean. This is the first time i add a feature request so I hope i did this correctly.

**Comment by bakerboy448** [comment]
Partially related to https://github.com/Lidarr/Lidarr/issues/1588

**Comment by Qstick** [comment]
This should be fixed with the new index select re-write
