### ISSUE TITLE
More room for quality preset's bitrate

### ISSUE THREAD

**Issue by azukaar** [Lidarr/Lidarr#2500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The current interface to set a maximum value to the quality preset's bitrate is pretty limiting for FLAC. The maximum is 1.5mb/s but it's quite a low bitrate concidering some albums go all the way up to 30gb per album.

### Describe the solution you'd like

I think it should go up to at least 10mb/s, any opinion?

### Describe alternatives you've considered

A Free input?

### Anything else?

![image](https://user-images.githubusercontent.com/7872597/144028047-f44ea1e2-c487-4853-84a4-0f369fa3f5fe.png)

[AB#2015](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2015)

**Comment by Qstick** [comment]
Dupe #1146
