### ISSUE TITLE
Some Artist Pictures not downloaded

### ISSUE THREAD

**Issue by Bono-Boy** [Lidarr/Lidarr#2502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When refreshing artist. The artist picture isn't downloaded

### Expected Behavior

I have uploaded the artist thumb to fanart.tv so the picture should be added to Lidarr.

### Steps To Reproduce

Add thumb to Fanart.tv (https://fanart.tv/artist/515fa43e-d3ee-4186-a036-101f39f3be22/hazes-andr-jr/)
Once the picture is added in fanart refresh the artist within Lidarr.
Picture isn't downloaded

### Environment

```markdown
- OS: Freenas (12.2-RELEASE-p10) Jail
- Lidarr: Version: 0.8.1.2135
          Mono Version: 6.8.0.123
          DB Migration: 45
          AppData directory: /config
          Startup directory: /usr/local/share/Lidarr
          Mode: Console
- Docker Install: No
- Using Reverse Proxy: Yes (Nginx)
- Browser: Chrome (latest)
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/7643097/Lidarr.debug.txt)

[AB#2026](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2026)

**Comment by ta264** [comment]
There's a 7 day lag between things being added to fanart.tv and appearing in the API so Lidarr can see them

**Comment by bakerboy448** [comment]
also covered on the FAQ
https://wiki.servarr.com/en/lidarr/faq#how-can-i-add-missing-artist-images

**Comment by Bono-Boy** [comment]
I overlooked that. I thought it was added to lidarr when the picture was added to fanart.tv.
Thanks for the swift response on a user error.
