### ISSUE TITLE
Unable to add "Must Contain" or "Must Not Contain"

### ISSUE THREAD

**Issue by BRTPOB** [lidarr/Lidarr#251]
### System Information/Logs

**Lidarr Version:**
0.2.0.291
**Operating System:**
Ubuntu 16.04.4 LTS
**.net Framework (Windows) or mono (macOS/Linux) Version:**
4.8.1
**Link to Log Files (debug or trace):**
https://pastebin.com/2xb5HVhK
**Browser (for UI bugs):**
Firefox 59.0.1 (64-bit)
### Additional Information
I'm unable to add either Must Contain or Must Not Contain as all they do is throw an error telling me that one or the other is required. If I attempt to add both, it still errors out. There's nothing that shows up in the console when I click "Save" either. Along wtih this, I'm unable to use the Tag feature as it /also complains that the former two are also required.

**Comment by Qstick** [comment]
Update Lidarr, I can't reproduce this on 314. Also post and JS errors showing up in console.

**Comment by BRTPOB** [comment]
I've updated Lidarr, and I'm still seeing the same error. This is what the console output is:

XML Parsing Error: no root element found
Location: https://www.eskimomafia.net/lidarr/signalr/poll?transport=longPolling&clientProtocol=1.5&apiKey=1f73(cut out)&connectionToken=DOXlNrKx2fR%2Bg3TYQytfLGl1Xux3rUSdZZnW%2Fzk9eXvspzvqAKZUJ%2FModE7wsdNcFdIZLG1d1Eh5tgqS0B3vx4M%2BezEB9n%2BjqUB8DV5hiWVxP95ZyCcs4XuIqCM4pLQr%2BDN3KobWIS5cx8%2BFqcJDV7dfcxsyqkwN35uzNvgPqG%2BiRjsK7dUtGjpfMhjFvvqp0iyhQh2p7B%2FKHu5l0PUT3pFwnmWs3WurYVthUFAbwvRLg6PG%2Fr4Dvial44HBwW%2FbIhd%2FFuNaKe6l58KrDymiHDol4t4Yyz1GrW%2B1zLl0N7NkWBRGMJO33mo5McHTRKi5
Line Number 1, Column 1:
poll:1:1
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://www.eskimomafia.net/lidarr/preload.js?h=GjfNX5idKiU8WQsCNpQXDw
Source Map URL: preload.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://www.eskimomafia.net/lidarr/index.js?h=fNRMm6FEhWBEB0sofa1ckA
Source Map URL: index.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://www.eskimomafia.net/lidarr/vendor.js?h=DsOos2GxcQiNErFaunBRdw
Source Map URL: vendor.js.map[Learn More]

This is what the log looks like:
18-3-21 01:08:49.6|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /home/downloads/torrents/music/Pennywise-Live_While_You_Can-(WEB)-2018-RUMBLE
18-3-21 01:10:19.4|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /home/downloads/torrents/music/Pennywise-Live_While_You_Can-(WEB)-2018-RUMBLE
18-3-21 01:11:49.6|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /home/downloads/torrents/music/Pennywise-Live_While_You_Can-(WEB)-2018-RUMBLE
18-3-21 01:11:52.0|Warn|LidarrErrorPipeline|Invalid request Validation failed:
 -- Either 'Must contain' or 'Must not contain' is required
18-3-21 01:12:29.3|Warn|LidarrErrorPipeline|Invalid request Validation failed:
 -- Either 'Must contain' or 'Must not contain' is required
18-3-21 01:13:19.7|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /home/downloads/torrents/music/Pennywise-Live_While_You_Can-(WEB)-2018-RUMBLE

I'm running this behind a reverse proxy. Could that be tying into it?

**Comment by majora2007** [comment]
Hi @BRTPOB, is this still an issue for you? If so, can you update to the latest and check for me?

**Comment by BRTPOB** [comment]
It was an issue the last time I updated, but sure, I'll try updating and trying again. I'll do that tonight.

**Comment by BRTPOB** [comment]
Tried to update, but it didn't seem to actually update. Not sure what's going on with that. I saw git pull update files though. This seems to be the error I'm getting:

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data Resource URL: https://www.eskimomafia.net/lidarr/index.js?h=fNRMm6FEhWBEB0sofa1ckA Source Map URL: index.js.map[Learn More]

**Comment by majora2007** [comment]
So it seems you are running a development build via git rather than our appveyor builds that auto update. Can you post the version you are on?

**Comment by BRTPOB** [comment]
About

Version
    0.2.0.291
Mono Version
    4.8.1
DB Migration
    11
AppData directory
    /home/offspring/.config/Lidarr
Startup directory
    /opt/lidarr
Mode
    Console

**Comment by majora2007** [comment]
I think we should circle back to this after beta release.

**Comment by BRTPOB** [comment]
OK, I can do that.

**Comment by Qstick** [comment]
@majora2007 @danielunderwood can either of you reproduce this? I can’t seem to get restrictions to bug out like this.

**Comment by majora2007** [comment]
No, I can't reproduce at all.

**Comment by danielunderwood** [comment]
I haven't been able to either.
