### ISSUE TITLE
[FEAT] Assign/modify metadata profile via Mass Editor

### ISSUE THREAD

**Issue by lincalinca** [Lidarr/Lidarr#2516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Making changes to individual artists to metadata is time consuming and runs contrary to the principle of using Lidarr: to make it easy to manage a music library easily.

### Describe the solution you'd like

In mass editor, add the option to change the metadata profile.

### Describe alternatives you've considered

N/A

### Anything else?

I would like to be able to assign multiple metadata profiles per artist. Presently, I have to create metadata profiles for all permutations, which makes individual artist management more complicated than necessary.

[AB#2084](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2084)

**Comment by ta264** [comment]
You just need to enable the metadata profile column in mass editor
