### ISSUE TITLE
Files aren't being removed

### ISSUE THREAD

**Issue by alpe12** [Lidarr/Lidarr#2551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on an album/artist, click "delete", check "Delete the track files", click ok:
Their entry is removed from Lidarr but the files/folders aren't deleted.

### Expected Behavior

The files/folders should be deleted.
If I try to remove a single music from an album, it works.
```
|Trace|Http|Req: 604 [DELETE] /api/v1/trackFile/3731 (from 192.168.1.60 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0)
|Info|MediaFileDeletionService|Deleting track file: /media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage/music/MAN WITH A MISSION/Break and Cross the Walls I (2021)/01 - yoake.mp3
|Debug|RecycleBinProvider|Attempting to send '/media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage/music/MAN WITH A MISSION/Break and Cross the Walls I (2021)/01 - yoake.mp3' to recycling bin
|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage/music/MAN WITH A MISSION/Break and Cross the Walls I (2021)/01 - yoake.mp3
|Trace|DiskProviderBase|Deleting file: /media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage/music/MAN WITH A MISSION/Break and Cross the Walls I (2021)/01 - yoake.mp3
|Debug|RecycleBinProvider|File has been permanently deleted: /media/alpe/b7a7b057-f89e-4f10-8f2e-dc7851d3c1f2/storage/music/MAN WITH A MISSION/Break and Cross the Walls I (2021)/01 - yoake.mp3
```
If I try to remove an entire album/artist, it doesn't and the only log entry is this:
`|Trace|Http|Req: 610 [DELETE] /api/v1/album/2637?deleteFiles=true&addImportListExclusion=false&queryParams=%5Bobject%20Object%5D (from 192.168.1.60 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0)`

### Steps To Reproduce

1. click on an album/artist
2. click "delete"
3. mark the "Delete the track files" checkbox
4. click ok

### Environment

```markdown
- OS: Ubuntu 20.10
- Lidarr: 0.8.1.2135
- Docker Install: The issue happens with or without docker.
- Using Reverse Proxy: yes
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/7748804/Lidarr.trace.txt)

[AB#2232](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2232)

**Comment by webxI23** [comment]
Hi, i've not having so much to diagnose but I'm having the same problem here running on docker and I confirm that deleting 1 file only works but not when trying to delete the folder. When I rescan the "artist" the supposedly deleted folder is imported again (normal behavior as the fils are still there).

Thanks

**Comment by jakemoritz** [comment]
Same here, Lidarr has never been able to delete albums. Never seen any errors in trace logs / Docker logs

**Comment by ohsnapword** [comment]
Same issue.  Running Lidarr 1.1.0.2649 on TrueNAS Scale 22.02.4.  Lidarr has full permissions on the library folder and has no issues deleting tracks that are replaced during import.

**Comment by alpe12** [comment]
1 year 🎂.
