### ISSUE TITLE
No 32-bit arm builds for musl linux being generated

### ISSUE THREAD

**Issue by TheSpad** [Lidarr/Lidarr#2567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No 32-bit arm builds for musl linux being generated. The description for https://github.com/Lidarr/Lidarr/commit/b1165ee7c1a3096fc3cc076fca6048c90f965534 suggests it was intended to be added but it doesn't appear to actually have been committed.

### Expected Behavior

32-bit arm builds for musl linux to match the amd64/arm64 musl builds

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

[AB#2286](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2286)

**Comment by ta264** [comment]
Arm musl builds are produced for nightly builds. There's not be a release since we added them.

**Comment by ta264** [comment]
Huh I take it back, they're not being published for nightly builds either looks like

**Comment by ta264** [comment]
Looks like the musl-arm bit of that commit got lost in translation
