### ISSUE TITLE
Folders with a * at the end are not read correctly and thus any files in the folder are not found.

### ISSUE THREAD

**Issue by distributorofpain** [Lidarr/Lidarr#2568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Folders downloaded by the torrent program that have a ⭐️at the end of the folder name are unable to be browsed by lidarr.  Lidarr cannot see in the folder and says the folder is empty.  If you look at the import function it shows a whole bunch of random characters instead of the ⭐️

Example Name:  Artist - Album Name (2020) Mp3 320kbps [PMEDIA] ⭐️

Not sure why people are putting a star at the end but its happened with four ablums so far.  I can change the folder name after download and import the files manually, it just breaks the auto import function.

### Expected Behavior

ignore the star at the end or in the folder name and process the files normally.

### Steps To Reproduce

name a folder with a  ⭐️ at the end and try to have Lidarr read it.

### Environment

```markdown
- OS: Windows 10 Pro
- Lidarr: 0.8.1.2135
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Chrome ( latest )
```

### What branch are you running?

Master

### Trace Logs?

21-12-26 00:10:31.2|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: C:\torrents\Artistnamehere - albumnamehere Vol. 2 (2020) Mp3 320kbps [PMEDIA] Í·77777742Í·77777655Í·77777620Í·77777757Í·77777670Í·77777617. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder

[AB#2290](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2290)

**Comment by ta264** [comment]
I've marked this as support for now, please come by the discord channel and hopefully we can sort you out. If it does turn out to be a bug we will of course re-open and fix, but debugging via GitHub is a pain.

**Comment by distributorofpain** [comment]
Seems like a bug since its reading a star character in a folder name as "Í·77777742Í·77777655Í·77777620Í·77777757Í·77777670Í·77777617"

Anyhow, i appreciate the teams work on Lidarr :)

**Comment by ta264** [comment]
I think that's an issue with whatever you're using to display the logs. If you want to get to the bottom of it please join the discord.
