### ISSUE TITLE
Kodi (XBMC) / Emby Metadata agent fix, save Artist "poster.jpg" as "folder.jpg" and "logo.jpg" as "logo.png"

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lidarr/Lidarr#257]
## Bug Report

Kodi will not use poster.jpg as the artist image. It requires the file to be named: folder.jpg
Also the logo's are being saved with the wrong extension, they should be ".png" and not ".jpg"

## Additional Information: https://kodi.wiki/view/Music_artwork

**Comment by RandomNinjaAtk** [comment]
@Qstick it accidentally posted when I was writing the title, I added the information now.

**Comment by Qstick** [comment]
Perfect thanks, the link does say jpg a is fine, or PNG is also acceptable

**Comment by RandomNinjaAtk** [comment]
@Qstick 

Aritst image:
![image](https://user-images.githubusercontent.com/8386416/37877382-5adea3f4-3028-11e8-950a-5d8a7f4ef647.png)


Yes, PNG or JPG is fine for artist image, but not for logo:
![image](https://user-images.githubusercontent.com/8386416/37877359-1c7dd5ee-3028-11e8-9eca-0852074255fd.png)

**Comment by Qstick** [comment]
Odd ok, I'll work on this
