### ISSUE TITLE
Kodi Library not updating

### ISSUE THREAD

**Issue by gotoman00** [Lidarr/Lidarr#2574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Kodi library will not update with the Lidarr Kodi connect module. Testing works, if 'clean library' is enabled it will clean the library, but the library will not update (disabling 'clean library' does not help). Currently running Kodi 19.3.0 stable on Windows and Lidarr 0.8.1.2135 (i have also tested this on newest nightly 1.0.0.2414). Here is the jsonrpc call and response.

22-1-3 17:17:52.7|Trace|HttpClient|Res: [POST] http://127.0.0.1:8089/jsonrpc: 200.OK (1 ms)
22-1-3 17:17:52.7|Trace|HttpClient|Response content (231 bytes): {"error":{"code":-32602,"data":{"method":"AudioLibrary.GetArtists","stack":{"message":"Invalid type array received","name":"albumartistsonly","type":["null","boolean"]}},"message":"Invalid params."},"id":"93169cec","jsonrpc":"2.0"}
22-1-3 17:17:52.7|Trace|XbmcJsonApiProxy|Response: {"error":{"code":-32602,"data":{"method":"AudioLibrary.GetArtists","stack":{"message":"Invalid type array received","name":"albumartistsonly","type":["null","boolean"]}},"message":"Invalid params."},"id":"93169cec","jsonrpc":"2.0"}
22-1-3 17:17:52.7|Trace|XbmcJsonApiProxy|Looking for error in response, {"error":{"code":-32602,"data":{"method":"AudioLibrary.GetArtists","stack":{"message":"Invalid type array received","name":"albumartistsonly","type":["null","boolean"]}},"message":"Invalid params."},"id":"93169cec","jsonrpc":"2.0"}

Trace debug is attached as well.

### Expected Behavior

Lidarr should be able to update the Kodi library without issue.

### Steps To Reproduce

1. Lidarr imports new release
2. Connect modules run
3. Plex updates fine
4. Kodi receives clean library command but does not update library

### Environment

```markdown
- OS: Windows 10
- Lidarr: Lidarr 0.8.1.2135 (also 1.0.0.2414)
- Docker Install: No
- Using Reverse Proxy: No
- Browser:
- Kodi: 19.3.0 (Windows)
```

### What branch are you running?

Master (tested on Nightly as well)

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/7822212/Lidarr.trace.txt)

[AB#2316](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2316)

**Comment by spitz66** [comment]
I have the exact same problem
- OS: Windows 10
- Lidarr: Lidarr 0.8.1.2135
- Docker Install: No
- Using Reverse Proxy: No
- Browser:
- Kodi: 19.3 (Matrix)
