### ISSUE TITLE
Cannot Add Grab to Blocklist

### ISSUE THREAD

**Issue by Davo1624** [Lidarr/Lidarr#2582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding a successful grab to `blocklist` does not add it to `blocklist`

### Expected Behavior

Adding a successful grab to `blocklist` adds it to `blocklist`

### Steps To Reproduce

In `History` press the `information` icon next to a successful grab. On the `information` screen click on the `Mark As Failed` button. Nothing happens and the grab is not added to `blocklist`

### Environment

```markdown
- OS: Unraid 6.9.2
- Lidarr: 1.0.0.2422
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

2022-01-14 15:14:32.1|Error|Lidarr.Api.V1.History.HistoryController.MarkAsFailed (Lidarr.Api.V1)|{
  "$": {
    "errors": [
      {
        "errorMessage": "\u0027i\u0027 is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
      }
    ],
    "validationState": "invalid",
    "isContainerNode": false
  }
}
2022-01-14 15:14:32.1|Trace|Http|Res: 1559 [POST] /api/v1/history/failed: 400.BadRequest (3 ms)
2022-01-14 15:14:32.1|Debug|Api|[POST] /api/v1/history/failed: 400.BadRequest (3 ms)

[AB#2365](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2365)

**Comment by bakerboy448** [comment]
Same issues as radarr I assume

there were a couple fixes
https://github.com/Radarr/Radarr/issues/6708

**Comment by Qstick** [comment]
Radarr/Radarr#6708 doesn't seem related to this
