### ISSUE TITLE
Jackett - Torznab - The Pirate Bay - No Results in RSS then can't add Indexer

### ISSUE THREAD

**Issue by guntherbob20** [lidarr/Lidarr#262]
## Bug Report

**Lidarr Version:**
0.2.0.320

**Operating System:**
Ubuntu-16

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono Version
5.10.1.4

### Additional Information

I don't know if this is a Jackett or Lidarr limitation, but since I only experienced this in Lidarr I am posting this here.

I use Jackett to do the whole Sonarr/Radarr/Lidarr indexing for a torrent client. However, for whatever reason I spent days trying to add The Pirate Bay to my Lidarr instance to no success. I was able to add a RARBG or ETTV indexer just to make sure I wasn't crazy, but not The Pirate Bay. The problem I was having was that I wasn't able to test the Indexer and then save it until just now where I resolved my own issue. I noticed that The Pirate Bay RSS feed contained xml objects that contained a 3000 category. I changed the category to 2000 in the GUI and I was able to test and save the indexer. So is this a limitation on Lidarr to not find enough objects/lines in the XML to deem the indexer invalid or is this something Jackett needs to update?

Thanks for all the great hardwork!

**Comment by bobloadmire** [comment]
maybe i don't understand the issue correctly, but 3000 is correct. https://i.imgur.com/RXGA0e1.png

**Comment by guntherbob20** [comment]
Right.

This is what I am experiencing: 

This configuration would not work: https://i.imgur.com/Jxo9Wa3.png

But this configuration would work: https://i.imgur.com/tDwK9H8.png

This is the RSS feed of TPB with the Category Code 3000: [http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000&q=](url)

RSS Feed: [3000.txt](https://github.com/lidarr/Lidarr/files/1857169/3000.txt)

This is the RSS feed of TPB with the Category Code 3000,2000: [http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000,2000&q=](url)

RSS Feed: [3000 and 2000.txt](https://github.com/lidarr/Lidarr/files/1857172/3000.and.2000.txt)

**Comment by bobloadmire** [comment]
interesting.  it's also pulling cat 100201, which you didn't specify as well.

**Comment by guntherbob20** [comment]
Yeah. 

Its is a minor issue with a work around, but it just isn't very obvious what of what is occurring in the systems.

Also this is the error message I receive from the logs:  "Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings."

**Comment by bobloadmire** [comment]
May be related to this issue i had, which was a Jackett issue. So bottom of thread. https://github.com/lidarr/Lidarr/issues/237

**Comment by guntherbob20** [comment]
Yeah that other issues sounds aligned with this issue too. It seems that Jackett is just looking at the Overall Most Current RSS feed from whatever tracker instead doing like a Most Recent with a current category code, or a deeper search into a category to check if there is anything there.

I'll add my comments over there.

**Comment by Qstick** [comment]
Correct, if there are no music release in Pirate Bay recent rss then it will fail. Jackett ignores the category we pass many times when doing test calls. They have been pretty responsive in correcting these when you create an issue on their GitHub

**Comment by svillamonte** [comment]
> But this configuration would work: https://i.imgur.com/tDwK9H8.png
Hey @guntherbob20, sorry to bring this issue back to life, but I'm not able to access that configuration dialog. No matter what I try, the Torznab settings in Lidarr don't allow me to specify categories. Could you point me into the right direction?

**Comment by Qstick** [comment]
@svillamonte turn on advanced settings
