### ISSUE TITLE
Connector --> Slack: Notify on album import

### ISSUE THREAD

**Issue by andrewsayre** [lidarr/Lidarr#263]
## Feature Request
Send a single notification to Slack when an entire album is imported, instead of each track, so I don't get flooded with messages and can more easily see the entire album is now available.

### Description of request and what problem are you looking to solve?
The existing slack connector integration will send an individual message for each track that is imported, resulting in a flood of messages to the slack channel when a new album is downloaded.  It's hard to then know if the entire album is available, or if only certain tracks were imported.  The current functionality makes sense if individual tracks (not albums) are imported, but I think the majority of the time, complete albums are added at once.  This feature request is to make Lidarr smarter and only send 1 message to Slack when a complete album is imported.

### Acceptance Criteria ###
1. When all tracks are imported for a given album in a single pass, send 1 notification to slack indicating the entire album was imported.  Such as: Imported: Artist - Album (X/X tracks) - [Quality].
2. When partial albums are imported, continue to send 1 notification per track.

**Comment by Qstick** [comment]
Same as #172
