### ISSUE TITLE
Override search entries in interactive search

### ISSUE THREAD

**Issue by J4gQBqqR** [Lidarr/Lidarr#2633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, there are serious difficulties faced by international users using Lidarr to search entries from indexes.

The root cause is because of that there exists multiple ways to represent a character in hieroglyph language.
For example, in Japanese, the artist name "稲葉浩志" https://musicbrainz.org/artist/d05f99dc-7fe5-44a6-93b8-8947ef90d09b
can be represented in the following ways:
- 稲葉浩志 in Japanese
- 稻葉浩志 in Traditional Chinese
- 稻叶浩志 in simplified Chinese
- Inaba Kōshi or Inaba Koshi in Romaji

Different indexes honor different ways to identify the artiest. 

It would be very difficult to program Lidarr to search all four variations listed above. Moreover, there are other languages, such as Korean, that needs special treatment to pronunciation in other ways instead of Romaji in Japanese. The problem further complicates as some Asian artist carries English names. 

Due to the above reasons, it would be almost impossible for Lidarr to pin down a correct artist name for international artists who do not use a native Latin name.

Currently, both the automatic search or interactive search for most Japanese, Chinese, Korean aritst returns nothing because of the entries entered into the indexer is not what is needed. 

### Expected Behavior

1. The first solution is to provide a search entry override feature in "interactive search" that allow user to override any search string that is going to be sent to the search engine.
2. The second solution is to enable user to skip search indexer and override the search result directly with "a magnet link", "a torrent file" or "a usenet link".

Without such override capability, support for languages other than the Latin Character based languages is almost impossible.

If the override capability is provided, at least the following issue will be resolved:

- #1734 
- #410 
- #1180

### Environment

```markdown
- OS: Linux
- Lidarr: 0.8.1.2135-ls69 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Any
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#2537](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2537)

**Comment by dacunno** [comment]
The solutions outlined are definitely needed. A simple comma or any special character completely defeats interactive and automatic searches with no way of feeding a known good search term or direct link to a torrent.

If not a complete override solution, at the very least a toggle to drop a definable set of characters from searches.

**Comment by J4gQBqqR** [comment]
I am pessimistic about implementation of this feature as the upstream Sonarr clearly rejected the proposal.

https://github.com/Sonarr/Sonarr/issues/4886#issuecomment-1030348591

Lidarr is kind of short handed.

**Comment by bakerboy448** [comment]
No plans for user modifiable search terms.

No plans for any ability to inject random results in the search results. As with every Starr one can just add the download to the download client in Starr's category.
