### ISSUE TITLE
Failed to add/import specific artist

### ISSUE THREAD

**Issue by krin-san** [lidarr/Lidarr#266]
### System Information/Logs

**Lidarr Version:** 0.2.0.326

**Operating System:** FreeNAS 11.1-STABLE / **Jail** FreeBSD 11.0-RELEASE-p1

**mono Version:** 4.8.1

**Link to Log Files:** [Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/1866337/Lidarr.trace.txt)

**Browser (for UI bugs):** Google Chrome 65.0.3325.181 64-bit

### Additional Information

Lidarr fails to parse artist info from MuzicBrainz for `lidarr:4f93401e-f3dd-4961-8b4e-708be531c3ce` search query. On "Add New" page it respond with "Failed to load search results, please try again.", on "Import" it respond with "Search failed, please try again later.".

Artist page: https://musicbrainz.org/artist/4f93401e-f3dd-4961-8b4e-708be531c3ce

**Comment by Qstick** [comment]
@danielunderwood looks like metadata is returning encouraging error in this case

**Comment by krin-san** [comment]
I have a bunch of other russian bands successfully imported manually using `lidarr:id` and german bands with umlauts in their name. Having issues with this group only.

**Comment by danielunderwood** [comment]
Should be fixed by lidarr/LidarrAPI.Metadata#54.
