### ISSUE TITLE
Artist, Import, match logic for 'The' in artist names...

### ISSUE THREAD

**Issue by richbutler1** [lidarr/Lidarr#268]
### Description of request and what problem are you looking to solve?
Improved logic for very common scenarios trying to match band names wiht/without 'The' in their name. 
Took a lot of effort manually to correct. If during the initial automated scan, logic included both scenarios, would be great. 

Also, under Media Management, default file naming convention has track number after track title which would not keep media in logically sorted order since track names are random. Consider this as default format instead: {Artist Name} - {Album Title} - {track:00} - {Track Title}

**Comment by Qstick** [comment]
Good call on the matching, on naming convention:

Default is `{Artist Name} - {track:00} - {Album Title} - {Track Title}` is it possible you changed at some point? 

https://github.com/lidarr/Lidarr/blob/bdcdc13485c340c48dfcbb53338e72255d042aab/src/NzbDrone.Core/Organizer/NamingConfig.cs#L11

**Comment by richbutler1** [comment]
Nope. Seems like the most logical to ensure an organized sort is to have Track # just before Track Title which should be very last.

Proposing this as default: {Artist Name} - {Album Title} - {track:00} - {Track Title}

**Comment by Qstick** [comment]
I’m good changing that.

**Comment by ta264** [comment]
Just to make sure I haven't misunderstood... I have a change to make the tag parsing more tolerant of missing/extra 'The' at the beginning of an artists name.  Testing quickly, if I try to import a folder called `Kooks` the metadata  lookup already does an inexact match and ties it to the musicbrainz artist `The Kooks`.  

So if you have a folder called `Kooks` which actually contains tracks by `The Kooks` but all the tracks are tagged as `Kooks` then I think it should correctly import now.  Obviously there could be a false positive if `Kooks` was actually a separate band, but hopefully none of the albums or tracks would match up in that case.

Looking at the musicbrainz db there are 1,400,000 artists.  I think there are around 28,000 pairs where both `x` and `The x` are artists.

Is there anything more to do?

```
musicbrainz_db=# select A.gid, A.name as TheName, B.name, B.gid as NoTheName from artist A, artist B where A.name ilike 'The%' and lower(trim(substring(A.name from 4))) = lower(B.name) limit 10;
                 gid                  |      thename      |   nothename   |                 gid
--------------------------------------+-------------------+---------------+--------------------------------------
 ca3f3ee1-c4a7-4bac-a16a-0b888a396c6b | The Silhouettes   | Silhouettes   | 05129944-1acf-47fa-81e7-03a1ea046e0b
 0c1ad3d9-59f8-4d1d-baa6-713bae024367 | The Insignificant | Insignificant | 6f91cc0e-c29a-4648-aa3a-cff295afc596
 294f4d52-ba2e-423f-99ef-1ebf5ff3116a | The Wanderers     | Wanderers     | b5056fb9-571b-4cae-8528-68a6e3007955
 b0d6a97a-9e91-47cb-8e21-2583e02e3b7a | The Steppes       | Steppes       | 776242be-6af4-46d8-a57e-2b2c2bebbee6
 86b1e55d-0889-4017-a9de-2b6ec29f9d65 | The Charts        | Charts        | e5581809-5ae5-46be-af34-2c6105c943a4
 86ff6ce5-a17c-4d6c-83be-c1aed4a36271 | The Orchid        | Orchid        | 7557b7aa-db87-4f0d-8b6e-19f5a5978c88
 86ff6ce5-a17c-4d6c-83be-c1aed4a36271 | The Orchid        | Orchid        | 6eb41cea-8c89-420a-b6fe-459d4e537346
 86ff6ce5-a17c-4d6c-83be-c1aed4a36271 | The Orchid        | Orchid        | f9b17368-5a9d-456b-a6b3-d8ddd56bf0bf
 86ff6ce5-a17c-4d6c-83be-c1aed4a36271 | The Orchid        | Orchid        | 6cba59a1-6fa4-4d6c-acaf-451c46281d15
 86ff6ce5-a17c-4d6c-83be-c1aed4a36271 | The Orchid        | Orchid        | 2c81163f-708b-4eef-9e68-968381605833

musicbrainz_db=# select count(distinct(A.id)) from artist A, artist B where A.name ilike 'The%' and lower(trim(substring(A.name from 4))) = lower(B.name);
 count
-------
 13515
(1 row)

musicbrainz_db=# select count(distinct(B.id)) from artist A, artist B where A.name ilike 'The%' and lower(trim(substring(A.name from 4))) = lower(B.name) limit 10;
 count
-------
 24997
(1 row)

**Comment by danielunderwood** [comment]
Is metadata work still needed on this one? Improved searching to handle pieces like "the" and "a" should be in there now. I suppose aliases could help here.
