### ISSUE TITLE
Enhancement - In Artist, Table View, use monitor icon to toggle for that artist overall

### ISSUE THREAD

**Issue by richbutler1** [lidarr/Lidarr#269]
## Feature Request

- In Artist/List/click individual artist. Have a 'monitor all/none' icon at top of list to toggle select/deselect of full album set

- Another suggestion, add a way for user to select default quality profile for new additions or imports. e.g. all of my imports/artists defaulted to 'Any' where I prefer lossless

### Description of request and what problem are you looking to solve?
- Looking for improved UX/usability

### Other Information
Keep up the great work!!! I'm here to try to provide useful suggestions on UX/usability/features

**Comment by Qstick** [comment]
This is basically what Album studio does is it not? Also Lidarr will remember your selection for quality profile from the last used during add/import

**Comment by richbutler1** [comment]
I'm sorry, hadn't used Artist studio yet. You are exactly right, awesome feature! Wasn't aware of last quality used. Will check that. I've also found mass update fixed my profile for all quickly to lossless. Really nice tools!!!!  Please feel free to close or let me know and I'll delete.

**Comment by Qstick** [comment]
Cool, let us know if you find anything.
