### ISSUE TITLE
Change default naming scheme to have track number before track title

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#270]
`{Artist Name} - {Album Title} - {track:00} - {Track Title}` Instead of `{Artist Name} - {track:00} - {Album Title} - {Track Title}`

**Comment by biship** [comment]
What about then the same track title is on 2 different mediums?
{Artist Name} - {Album Title} - {medium:00} - {track:00} - {Track Title}
or is it recommended to use folders:
{medium:00} / {Artist Name} - {Album Title} - {track:00} - {Track Title}
