### ISSUE TITLE
EntityHistoryService error on manual track import

### ISSUE THREAD

**Issue by CPU-Blanc** [Lidarr/Lidarr#2703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logs are showing a `EventAggregator|EntityHistoryService` error while processing the `TrackImportedEvent` during manual album imports while trying to find a downloadId from history.

### Expected Behavior

No error to be produced due to a lack of downloadId

### Steps To Reproduce

1. Add an artist + album to lidarr library
2. Navigate to Wanted > Manual Import
3. Import the files

### Environment

```markdown
- OS: Windows Server 2016
- Lidarr: 1.0.0.2484
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Google Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/8219228/Lidarr.trace.txt)

[AB#2783](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2783)

**Comment by CPU-Blanc** [comment]
Just thought I'd report back and say this bug is still present in `1.1.1.2661`. Seems to prevent 'Connections' from firing as a result.

**Comment by Daniel15** [comment]
I'm seeing the same NullReferenceException in EntityHistoryService on manual import. I'm on version `1.1.2.2935`.

**Comment by CPU-Blanc** [comment]
Another update, still an issue in `1.1.4.3012`. Still prevents connections from firing properly

**Comment by drizuid** [comment]
Same steps to reproduce as OP, i have only been affected by this issue for a relatively short time.

- os: debian 11
- docker version: 23.0.2 (linuxserver.io)
- Using Reverse Proxy: Yes
- browser: chrome, edge, chromium

What branch are you running?
Nightly (1.1.4.3012)

Logs:
[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/11222290/Lidarr.debug.txt)
[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/11222291/Lidarr.trace.txt)

**Comment by CPU-Blanc** [comment]
Can confirm the error is no longer present in `1.2.0.3168`. 
Connections aren't firing on manual import but that's likely a separate issue
