### ISSUE TITLE
Unable to find artist in the Music Brainz library

### ISSUE THREAD

**Issue by paulds8** [lidarr/Lidarr#271]
### System Information

**Lidarr Version: 0.2.0.326**

**Operating System: Ubuntu 16.04 x64**

**Mono Version: 5.10.1.20**

### Description of request and what problem are you looking to solve?
Unable to add a known artist, BØRNS: https://musicbrainz.org/artist/b2befbb4-c585-4b05-8efa-3deebc8e1385

"Failed to load search results, please try again."

Fails with both the artist name and using  lidarr:b2befbb4-c585-4b05-8efa-3deebc8e1385

**Comment by Qstick** [comment]
This looks like same issue as #266

**Comment by Qstick** [comment]
@danielunderwood this one is different than #266, metadata is throwing this error https://github.com/lidarr/LidarrAPI.Metadata/issues/27

**Comment by danielunderwood** [comment]
Should be fixed by lidarr/LidarrAPI.Metadata#54.
