### ISSUE TITLE
failed to load queue

### ISSUE THREAD

**Issue by dovzamir** [Lidarr/Lidarr#2715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As in previous reports of this error: clicking Wanted --> Queue results in "Failed to load Queue"
Running 0.8.1.2135 — Apr 18 2021 develop Currently Installed on ubuntu 20.04 lts.
Restarting lidarr **_does not_** solve the problem.
What can I do? Is it possible somehow to empty the queue manually?

### Expected Behavior

clicking Wanted --> Queue shows the items presently in the queue

### Environment

```markdown
- OS: Ubuntu 20.04 lts
- Lidarr:  0.8.1.2135
- Docker Install: no
- Using Reverse Proxy: yes and no
- Browser: firefox, vivladi
```

### What branch are you running?

Develop

### Trace Logs?

[Lidarr.txt](https://github.com/Lidarr/Lidarr/files/8311393/Lidarr.txt)

[AB#2831](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2831)

**Comment by ta264** [comment]
Dupe #1944
