### ISSUE TITLE
adding Various Artists albums

### ISSUE THREAD

**Issue by Zeusy123** [lidarr/Lidarr#272]
kewl script by the way:) must appreciated!!

Is it possible to add various artists albums?

Ideally, adding by album name would be great,

Example of various artist  album is https://musicbrainz.org/release/26d1f2a3-177a-4ed7-bdf2-fb587483e4f6

Thanks in advance and keep up the GREAT work!!

**Comment by Qstick** [comment]
Same as #207 and #179

**Comment by Zeusy123** [comment]
Qstick yes i read those, but it isnt clear if adding various artists is possible. or not.

**Comment by Qstick** [comment]
It's not possible yet, that's why they are still open issues. It's coming

**Comment by karldonteljames** [comment]
Sorry to ask, I don't seem to be able to find the information. 
Where do I find the url for the testing api? 
I assume this is added to the metadata source in the settings? Thanks
