### ISSUE TITLE
Get Lidarr to listen & match (i.e. shazam it) downloaded tracks in order to ID and name them accurately

### ISSUE THREAD

**Issue by FadingArabChristians** [Lidarr/Lidarr#2723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some indexers do not name or sort music accurately/consistently causing issues in identifying files and importation.

### Describe the solution you'd like

If we could get a service like "Shazam" or "SoundHound" to identify the song and then name it based on how the song sounds.

With a quick google search it looks like AudioTag.info has an API which could be used to integrate into Lidarr

### Describe alternatives you've considered

Painstakingly going thru every song in order to match it accurately

### Anything else?

N/A

Just a huge thank you to all developers who are contributing to this amazing project! <3

[AB#2861](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2861)

**Comment by ta264** [comment]
It uses acoustid
