### ISSUE TITLE
Expose manual import to API

### ISSUE THREAD

**Issue by karaambaa** [lidarr/Lidarr#275]
### Description of request and what problem are you looking to solve?
I think it would be quiet helpful to be able to import tracks via the api. So it would be possible to use external scripts for downloading and Lidarr could take over the renaming, sorting and beautifying.

By the way, I love Lidarr. It looks so much better than everything I tried till now and it works better as well.

**Comment by Qstick** [comment]
You can trigger an import via api with DownloadedAlbumsScan command passing path parameter.
