### ISSUE TITLE
fpcalc

### ISSUE THREAD

**Issue by seanmcg182** [Lidarr/Lidarr#2771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After most recent Nightly Update (1.0.0.2551) on Ubuntu 20.04.4 the error "You have an old version of fpcalc. Please upgrade to 1.4.3" appears, and all manual import/search capability fails.

Per an apt command, "libchromprint-tools is already the newest version (1.4.3-3build1)"

I have resolved this issue by uninstalling the nightly branch and reinstalling Lidarr from the Master branch, but now I cannot keep up with new features on Nightly until this is resolved.

### Expected Behavior

Expected Behavior is no error, and functional importing.

### Steps To Reproduce

1) most current Ubuntu Server 20.04 release (reinstalled fresh OS to test, and error occurred)
2) Install Lidarr
3) Update to current Nightly Build

### Environment

```markdown
- OS: Ubuntu 20.04.4
- Lidarr: 1.0.0.2551
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

Can't locate error in Trace

[AB#3020](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3020)

**Comment by mechanimal82** [comment]
Just seen a commit by @ta264 which means this should be fixed in the next update; in the meantime it seems fpcalc was not set as executable so just run `sudo chmod +x /opt/Lidarr/fpcalc` (or wherever your Lidarr install is) and restart Lidarr will fix it

**Comment by bakerboy448** [comment]
https://github.com/Lidarr/Lidarr/commit/c9b93c19de2bd6c6ed829374cbcee44e9e9a725c
