### ISSUE TITLE
Deemix as indexer

### ISSUE THREAD

**Issue by jordanboucher42** [Lidarr/Lidarr#2781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some music is hard to find on private indexers

### Describe the solution you'd like

Integration of Deemix as an indexer to easily retrieve content from Deezer

### Describe alternatives you've considered

Add Deemix in the indexers with a connection to the Deemix Docker container

### Anything else?

Do you think this is doable?

[AB#3049](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3049)

**Comment by Qstick** [comment]
This will never be native, however there is a working plugin for this using the in testing `plugins` branch.
