### ISSUE TITLE
System Stuck in loop for 'Rescanning Folders'

### ISSUE THREAD

**Issue by vegasit** [Lidarr/Lidarr#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The system has been stuck rescanning folders for days... have restarted server, app several times.

![image](https://user-images.githubusercontent.com/32071088/165583159-0bf59ff7-3177-41f1-86a5-1091ca9daafc.png)

### Expected Behavior

to complete

### Environment

```markdown
- OS: windows 2008 r2
- Lidarr: 0.8.1.2135
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome

Version
0.8.1.2135
.NET Core
Yes (3.1.13)
DB Migration
45
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.txt](https://github.com/Lidarr/Lidarr/files/8575051/Lidarr.txt)

[AB#3055](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3055)

**Comment by bakerboy448** [comment]
Info logs are not the required Trace Logs for all bug reports.

Based on a very brief skim it seems your mounted storage at Z is having a ton of issues with being accessible and responsive.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/lidarr/) or  [Discord](http://lidarr.audio/discord) for support/questions.
