### ISSUE TITLE
OPUS support

### ISSUE THREAD

**Issue by Avamander** [Lidarr/Lidarr#2784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

They were locked and closed without the feature actually being here in `0.8.1.2135`.

### Is your feature request related to a problem? Please describe

A significant amount of my `.opus` files that work everywhere else are detected as "Unknown" in Lidarr.

### Describe the solution you'd like

OPUS files are detected properly not as "unknown".

### Describe alternatives you've considered

Not having any OPUS as an alternative is an unnecessary limitation.

[AB#3057](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3057)

**Comment by ta264** [comment]
Need way more info if you want anything done about this. Opus works fine for me (it's currently detected as vorbis)

**Comment by Avamander** [comment]
One file shown as "unknown" as seen by `ffprobe`:
```
[ogg @ 0x557cd1548ec0] 7 bytes of comment header remain
Input #0, ogg, from 'Artist - Track.opus':
  Duration: 00:04:05.44, start: 0.020000, bitrate: 129 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ENCODER         : Lavf58.29.100
      DATE            : 20200724
      TITLE           : Title
      comment         : Comment
      PURL            : https://www.youtube.com/watch?v=
      ARTIST          : Artist
      LANGUAGE        : eng
      track           : 11
```

**Comment by ta264** [comment]
Please post the trace logs requested in the bug report. If you want to get to the bottom of it the best bet is to join the discord channel for help debugging.

**Comment by Avamander** [comment]
Will try and provide the logs as soon as possible.
