### ISSUE TITLE
Separator between Artist and Album when searching

### ISSUE THREAD

**Issue by sarakha63** [Lidarr/Lidarr#2785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some indexers won't return any results when searching with Artist Album

They absolutely need this kind of search :  Artist - Album

With this issue such indexers will never return any results

### Describe the solution you'd like

Maybe an option on the indexer level to choose the separator between the artist and album query

maybe imply a retry with different separators (simple but not smart)

Or why not a field to specify the template of the q parameter of the query

I think the last one is the way to go

but the first one (which will be defaulted to nothing (space) is simple enough to be implemented quickly

### Describe alternatives you've considered

Maybe an option on the indexer level to choose the separator between the artist and album query

maybe imply a retry with different separators (simple but not smart)

Or why not a field to specify the template of the q parameter of the query

I think the last one is the way to go

but the first one (which will be defaulted to nothing (space) is simple enough to be implemented quickly

### Anything else?

Nothing more to add

[AB#3060](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3060)

**Comment by Qstick** [comment]
Need examples here. Its odd to me that we would need to add another character to get results
