### ISSUE TITLE
Files imported but then not recognized

### ISSUE THREAD

**Issue by Jerrk** [Lidarr/Lidarr#2794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes i will import an album and the files will go into the correct folder and be renamed, but they will not show up within lidarr on the artist/album even after refreshing/restarting

### Expected Behavior

the files should be recognized within lidarr

### Steps To Reproduce

not sure exactly what's happening hopefully the logs will give some clues.

1. import an album
2. check the directory for the correctly imported files
3. check the artist/album in lidarr and see no files recognized
4. refresh the artist
5. no change

### Environment

```markdown
- OS: Unraid 6.9.2
- Lidarr: 0.8.1.2135
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: firefox 99.0.1
```

### What branch are you running?

Develop

### Trace Logs?

Trace logs of refreshing the artist and the album not appearing
[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/8594361/Lidarr.trace.txt)

normal logs of the import on the 1st of april
[Lidarr.21.txt](https://github.com/Lidarr/Lidarr/files/8594369/Lidarr.21.txt)

files imported on the 1st of april still in the correct folder
![](https://i.imgur.com/vhweKT7.png)

29th of april still doesnt show up in the webUI
![](https://i.imgur.com/ET2vJwt.png)

No settings or anything has been changed, i just let lidarr run and sometimes when i check out a recent release i will find that it has not been properly recognized within lidarr.
Sometimes it even tries to download a lower quality version because it doesn't recognize that i already have a higher quality already downloaded, but then when it tries to import the lower quality version it stops and says the already existing file is of higher quality.
So the files are recognized when trying to import new files to replace them, but it does not recognize the files when viewing the album from the webUI, and it will continuously search for any matching release even if there already is one imported.

[AB#3084](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3084)

**Comment by bakerboy448** [comment]
Can reopen if it turns out to be a bug, but at a glance and a skim through the log it seems likely to be a support issue.

For future reference please follow the bug report template linked Gathering Logs wiki article for how to get and provide logs rather than uploading entire log files.
