### ISSUE TITLE
Unable to talk to APIs (OpenSSL error: "too many open files")

### ISSUE THREAD

**Issue by Anaerin** [Lidarr/Lidarr#2817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to search for new artists, or checking for updates, fails with "unable to communicate with API"

I'm using the latest develop version available on FreeBSD (v0.8.1.2135) according to the internal updater.

### Expected Behavior

Searching works as normal.

### Environment

```markdown
- OS: FreeBSD 12.1
- Lidarr: 0.8.1.2135
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 101
```

### What branch are you running?

Develop

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/8709989/Lidarr.trace.txt)
[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/8709990/Lidarr.debug.txt)

[AB#3163](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3163)

**Comment by ta264** [comment]
Disable the `root folder watching` in media management / advanced settings - filesystem watching is hopeless on BSD
