### ISSUE TITLE
Add (feat. XXXX) to Track title cleaning

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#283]
Many tracks have the feat artist in the Track Tag. This would clean that before comparing the track name to the db to find a match. Ex. `The Monster (feat. Rihanna)`

**Comment by YipYup** [comment]
It's also common to see `(ft. Artist)`, `[ft. Artist]`, and `ft. Artist`.

**Comment by majora2007** [comment]
I will need to test cleaning feat. due to the fact that some track titles officially have "feat. ARTIST" as their name and I wouldn't want to strip that and thus not match the track.

**Comment by Qstick** [comment]
I don’t think any tracks are stored in Musicbrainz with ft. In the track name are they? That’s usually handled by additional artist references.

**Comment by majora2007** [comment]
It looks like MB stores them as unofficial track titles, so we should be fine for stripping them. I'll take a look in my library and see if this degrades any matches when stripping feat out.
