### ISSUE TITLE
Sanitise disambiguation better

### ISSUE THREAD

**Issue by HamilcarH** [Lidarr/Lidarr#2831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As discussed here: https://discord.com/channels/297050658111094784/297050758656950272/982573851038871604

Disambiguation issues when there is a /.

### Expected Behavior

Change the character so that it doesn't cause issues importing tracks.

### Environment

```markdown
- OS: Unraid 6.10.x
- Lidarr:1.0.1.2578
- Docker Install: yes 
- Using Reverse Proxy: yes
- Browser: Safari
```

### What branch are you running?

Develop

### Trace Logs?

Not asked in discord

[AB#3228](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3228)

**Comment by Qstick** [comment]
Not sure I can reproduce this. Adding this artist with disambiguation in the scheme gets me a sanitized folder

![image](https://user-images.githubusercontent.com/376117/197372708-3185df5d-36ea-443f-8e45-9f30f67c55ce.png)

**Comment by HamilcarH** [comment]
Feel free to close it. In the meantime i had to do a reinstall and I no longer see the issue.

**Comment by Qstick** [comment]
Odd
