### ISSUE TITLE
Cannot set the nzbget username

### ISSUE THREAD

**Issue by sammcj** [Lidarr/Lidarr#2834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go to set the nzbget username in 'Download Client Settings' the field is read only and cannot be changed.

This means nzbget with any user other than 'nzbget' will not work.

### Expected Behavior

You should be able to enter a username of your choosing.

### Environment

```markdown
- OS: CentOS 7
- Lidarr:     1.0.2.2592
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: firefox
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#3248](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3248)

**Comment by ta264** [comment]
It's not read only for me
