### ISSUE TITLE
Spotify Saved Albums import list doesn't monitor albums of artists already in library

### ISSUE THREAD

**Issue by kromsam** [Lidarr/Lidarr#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I save an album on Spotify by an artist who is already in my Lidarr library, the album doesn't get monitored.

### Expected Behavior

An album saved on Spotify should always be monitored when I use the Spotify Saved Albums  import list.

### Steps To Reproduce

Configuration of the list:

![Screenshot 2022-06-23 at 22-25-38 General Import List Settings - Lidarr](https://user-images.githubusercontent.com/47101903/175393273-4f9ede01-7d52-4c40-9ae9-6a2ec9299174.png)

1. Add album on Spotify of artist already in Lidarr library
2. Refresh the list (by opening its settings and saving it again).
3. See that the number of list items has increased.
4. But the album is not monitored

### Environment

```markdown
- OS: Debian GNU/Linux 10 (buster)
- Lidarr: 1.0.2.2592
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-06-23 22:24:57.7|Info|ImportListSyncService|Starting Import List Refresh for List SpotifySavedAlbums
2022-06-23 22:25:02.6|Info|ImportListSyncService|Processing 341 list items
2022-06-23 22:25:08.9|Info|ImportListSyncService|Import List Sync Completed. Items found: 341, Artists added: 0, Albums added: 0
2022-06-23 22:27:17.3|Info|ImportListSyncService|Starting Import List Refresh for List SpotifySavedAlbums
2022-06-23 22:27:21.4|Info|ImportListSyncService|Processing 342 list items
2022-06-23 22:27:24.3|Info|ImportListSyncService|Import List Sync Completed. Items found: 342, Artists added: 0, Albums added: 0
2022-06-23 22:29:24.6|Info|ImportListSyncService|Starting Import List Refresh for List SpotifySavedAlbums`

[AB#3314](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3314)

**Comment by bakerboy448** [comment]
Lists do not update existing entries for artists nor albums etc.

**Comment by kromsam** [comment]
Maybe a better explanation of the purpose of lists should be given then. Because this is the behaviour I get from a list that is presented as:

`Lidarr supports multiple lists for importing Albums and Artists into the database.`

And why wouldn't this be the wanted behaviour? Lidarr has already recognised an album has been added to my Spotify Saved Albums (this you can see in the provided logs), why not monitor the album right away?

I am not sure if we understand each other properly. I could also file a feature request in that case.

**Comment by bakerboy448** [comment]
Lists have never been advertised as updating existing database entries; only importing as you've described.

Automatic Add is to add the artist/album to lidarr.

**Comment by kromsam** [comment]
I'm afraid I don't get this then. It's not about updating database entries, but about adding albums to lidarr automatically as they are saved on spotify.

It is odd that some albums are added and some are not.

**Comment by kromsam** [comment]
> If the album is not already in Lidarr and is not getting added then this is a bug

This is the case.

Just to be sure: by 'adding' also contains 'monitoring' right?

**Comment by bakerboy448** [comment]
No.

Adding meaning the album is in lidarr for that artist.   

Lists in \*arrs don't modify monitored status of existing items.

**Comment by kromsam** [comment]
I am sorry to say this but this is getting rather frustrating. As if you are just not willing to understand.

![Schermafdruk van 2022-06-26 18-11-16](https://user-images.githubusercontent.com/47101903/175823494-7cef832d-0a48-4501-90c6-3f40cf32e8e4.png)

When I pick the option 'Specific Album'. It is very clear what my expectations are.

- I save an album on Spotify
- This specific album is monitored in Lidarr

This works for all albums I add to Spotify, they are monitored in Lidarr. But not some of them. This is an issue I wanted to address.

**Comment by ta264** [comment]
Right now import lists only do anything for albums not already in lidarr. Saving an album in Spotify will not monitor an **existing** album in your lidarr. That option controls what happens to **newly** added albums. So it seems this is not a bug.

**Comment by kromsam** [comment]
Alright I will make this a feature request then

**Comment by kromsam** [comment]
> Right now import lists only do anything for albums not already in lidarr. Saving an album in Spotify will not monitor an **existing** album in your lidarr. That option controls what happens to **newly** added albums. So it seems this is not a bug.

When you look at the description and the expectations of the user, I would see this as a bug.
And even if it is not a bug, it would be a weird and inconsistent feature.

Also I am a bit disappointed that you were very quick to point out my mistakes, (although I see it as a legitimate issue,) but when I then take the step to actually create a feature request I don't hear anything from anyone.

**Comment by kromsam** [comment]
Well maybe it does say that. But that is not what I wish import lists do, that's the crucial part here, not the semantics. Maybe we should continue the discussion here, where the feature request already received acclaim:

https://github.com/Lidarr/Lidarr/issues/2855

**Comment by bakerboy448** [comment]
#2855 is closed and a duplicate of https://github.com/Lidarr/Lidarr/issues/2411 which is your request
