### ISSUE TITLE
Matching Fails in albums where tracks share the same name

### ISSUE THREAD

**Issue by smithjw1984** [lidarr/Lidarr#287]
I've encountered an issue where there are two tracks on one album that both have the same name.

For example, The 1975 album The 1975 has two tracks, number 5 and 26 that are both called Chocolate.
The files are named appropriately - "05 - Chocolate.mp3" and "26 - Chocolate.mp3" and can be distinguished if I do a manual import. However, the mapping is reset when a "refresh artist" scan is triggered. Both files then become mapped to track 26.

I've also encountered this when tracks share a similar name, for example Slipknot - Vol. 3: (The Subliminal Verses). Track 8 - Vermillion, shares a similar name to Track 11 - Vermillion Part 2.
When the Artist Refresh is triggered, both tracks become mapped to Track 8 - Vermillion.

**Comment by majora2007** [comment]
Do the "Chocolate" tracks have the Track IDv3 tag set as well?

**Comment by smithjw1984** [comment]
The track numbers are set in IDv3. 
I have attached a couple of screenshots for clarity. 

![image](https://user-images.githubusercontent.com/30339308/38507865-9ac5fd0c-3c15-11e8-86cc-8254a166066a.png)
![image](https://user-images.githubusercontent.com/30339308/38507947-cb4adff6-3c15-11e8-84ca-2ad8aecb0341.png)

**Comment by majora2007** [comment]
Thanks, I'll take a look at this.
