### ISSUE TITLE
Ability to add multiple releases of an Album

### ISSUE THREAD

**Issue by DevinCampbell** [Lidarr/Lidarr#2888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I ran into this issue when trying to add some albums from [Tech N9ne (US Rapper)](https://musicbrainz.org/artist/dde3d9b1-0e44-48bc-b0c9-d739b3570000). The Album [All 6's and 7's](https://musicbrainz.org/release-group/cebe5e8f-ba59-475d-8657-d98ce2031d9a) has five releases. Two of the releases have exclusive bonus songs that were not released in any of the other releases for the album. Currently, you can only match an Album in Lidarr to a single Release. If I choose one Release, I won't be able to import and monitor songs that are exclusive to another Release.

### Describe the solution you'd like

I would like the ability to import and monitor songs from multiple Releases of a single Album.

### Describe alternatives you've considered

Any current alternatives require not using Lidarr for monitoring.

### Anything else?

N/A

[AB#3460](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3460)

**Comment by ta264** [comment]
Duplicate #729
