### ISSUE TITLE
ID3 tagging

### ISSUE THREAD

**Issue by Kianytty** [lidarr/Lidarr#289]
## Feature Request

ID3 tag and other metadata

### Description of request and what problem are you looking to solve?

When downloaded all the information about the file/song get the correct metadata so that players pick it up correctly

**Comment by kolbyg** [comment]
This would be awesome. To add to this, Lidarr should also scan the library and fix up tags of already downloaded songs/update them when nessesary. 

Tagging has always been an issue for massive music libraries, a way to keep it consistent and updated would be greatly appreciated.

**Comment by biship** [comment]
If Lidarr doesn't properly match the release, then it could be overwriting more valid/correct tags.

**Comment by Qstick** [comment]
Yep, We don't write tags yet for that very reason.

**Comment by kolbyg** [comment]
Ok then add an option (probably an advanced option) for conflict handling.

Waiting until the matching is more reliable is fine, but knowing that this feature is coming (one day) would be great.

I've got around 40k songs I'm in the process of importing using Lidarr and the tagging is a complete mess/nonexistent.

**Comment by Qstick** [comment]
Oh its definitely coming! Don't fret about that.

**Comment by kolbyg** [comment]
Will it (eventually) correct tags on already imported files? I'd rather not reimport all the songs again to get the tags rewritten :P

**Comment by Qstick** [comment]
I would say that the odds are in your favor. :)

**Comment by Kianytty** [comment]
Really looking forward to this.

**Comment by rubdos** [comment]
Did you folks consider that hardlinks and retagging might upset the Torrent client? Just FYI :-)

One way to fix this (on supported platforms) is to use reflinks/FICLONE instead of hardlinking.

**Comment by alagave** [comment]
Looking forward to this but please allow me the option of previewing what will be changed or retagging only albums in a folder I have identified as allowable - never in my actual production archive. I use a folder named "Lidarr" for downloads and then inspect them before merging with my "Music" folder.

Perhaps, over time, I will be comfortable allowing software to handle this.

**Comment by Kianytty** [comment]
How is this coming along?

**Comment by ebnozal** [comment]
I've been using your software and I really like the design, I've been trying to import my albums, I did not realize it's not adjusting my tags and it would really awesome if when you manually imported albums that it would actually write the right tagges for when you have the files renamed and moved

**Comment by lvbaal** [comment]
looking really forward to this. Have been using the windows desktop program MusicBrainz Picard for now
