### ISSUE TITLE
Please remove requirement to include album release year in the Album Folder naming section

### ISSUE THREAD

**Issue by zedrockphotog** [lidarr/Lidarr#290]
## Feature Request
Allow "Album Folder" names to not include release date

### Description of request and what problem are you looking to solve
I would love to have the requirement to include the album release year in the album's folder name.  I have a vast collection of music, and none of the album folders have the date.  I would love to continue on with my existing naming scheme.
![lidarr pix](https://user-images.githubusercontent.com/38261618/38577732-c50986c8-3ccf-11e8-97f9-345583bf2d16.png)

**Comment by Qstick** [comment]
we are working on some more changes to naming so stay tuned, this will get fixed up soon.

**Comment by zedrockphotog** [comment]
Everyone working on this is awesome!  I put it through it's paces yesterday. And even though it's still in the early stages, it is awesome! Thank you all for your hard work!!!!

On Apr 11, 2018 6:25 AM, Qstick <notifications@github.com> wrote:

we are working on some more changes to naming so stay tuned, this will get fixed up soon.

**Comment by biship** [comment]
Can you also permit us to use {medium:00} in the Album Folder - and the ability to use it as a subfolder?
Why limit what can be used in any of the 3 fields?

**Comment by Qstick** [comment]
Because there are many albums for same artist with same name, so we are trying to prevent you from having files from two separate albums go in one folder
