### ISSUE TITLE
Blacklist feature doesn't stop releases being grabbed

### ISSUE THREAD

**Issue by oliroe** [lidarr/Lidarr#293]
### System Information/Logs

**0.2.0.358**

**Docker through Synology NAS**

**Mono Version 5.10.1.20**

Afraid there is no mention of this in the logs. Releases I have added to the Blacklist continue to be grabbed Screenshots below show a release being grabbed straight after I've added it to the blacklist

![image](https://user-images.githubusercontent.com/4500141/38695396-07c5798a-3e84-11e8-975d-e6c96d6a9864.png)

![image](https://user-images.githubusercontent.com/4500141/38695434-27c48b68-3e84-11e8-8640-5f18202880b4.png)

![image](https://user-images.githubusercontent.com/4500141/38695451-38bcd01a-3e84-11e8-86ae-62772f348fc5.png)

**Comment by oliroe** [comment]
I don't think so, I have 4 releases in my blacklist with identical file names from the same indexer.

**Comment by oliroe** [comment]
Looks like there are 4 releases with identical file names, I'll monitor it and let you know if there is an issue. For now I'll close, thanks for your help

**Comment by Qstick** [comment]
Ok, let us know if you come across anything else. Appreciate the post!
