### ISSUE TITLE
Albums fail part way through manual import

### ISSUE THREAD

**Issue by oliroe** [lidarr/Lidarr#296]
## Support / Questions

Please use https://discord.gg/8Y7rDc9 for support. Support requests or questions will be redirected to discord and the issue will be closed.

### System Information/Logs

**Lidarr Version:0.2.0.365**

**Operating System:Synology NAS and Docker**

**Mono 5.10.1.20**

**[Lidarr.trace.10.txt](https://github.com/lidarr/Lidarr/files/1925741/Lidarr.trace.10.txt)
:**

**Browser (for UI bugs):**

### Description of request and what problem are you looking to solve?
Albums are constantly failing to import when manually importing them. The import fails part way through on an individual file, stops the process and removes the download. This can be seen in the attached Trace log for Elvis Presley 1956 CD2 Track 19

**Comment by majora2007** [comment]
This is likely due to parsing of albums with multiple CDs.

**Comment by oliroe** [comment]
Almost certainly a multi cd issue, successfully manually imported circa 20 single CDs

**Comment by BanditBanditBandit** [comment]
I am constantly having this issue myself, about 1 in 3 will fail. Sometimes an error prompt from MPC pops up that the media is no longer there (which im not sure why) during the import, otherwise it will just say failed and the torrent gets removed and deleted in the middle of the import.

**Comment by Qstick** [comment]
This maybe fixed by #539 or may already be fixed , @ta264 thoughts?
