### ISSUE TITLE
Add digital medium format in Lidarr

### ISSUE THREAD

**Issue by murmelbahn** [Lidarr/Lidarr#2960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

For some albums are digital releases available on spotify/deezer/tidal etc. Sadly Lidarr doesnt show this one.
For example the Album "Basement Story" from the artist "Kellerkind".
https://musicbrainz.org/release-group/28305c19-8bfa-44ab-801c-b2fa4dca4b40
Musicbrainz shows up 2 releases, one CD and one digital medium. Lidarr only shows the CD release.
The difference between this two is the amount of tracks. So you can't simply change one for the other.

### Describe the solution you'd like

I think it would be the best to add digital medium releases per default.

### Describe alternatives you've considered

Sadly, there are no alternatives to this.

### Anything else?

Nope

[AB#3700](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3700)

**Comment by ta264** [comment]
Digital media are shown. If you need support working out why an album is missing from your lidarr, please join the discord channel.
