### ISSUE TITLE
Could something like OrpheusDL and it's plugins be supported by Lidarr?

### ISSUE THREAD

**Issue by np000001** [Lidarr/Lidarr#2962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Finding songs that otherwise cannot be found or are hard to find.

### Describe the solution you'd like

Could something like OrpheusDL ( https://github.com/yarrm80s/orpheusdl ) and it's plugins ...

TIDAL (requires paid account)
 - https://github.com/Dniel97/orpheusdl-tidal

Qobuz (requires paid account)
 - https://github.com/yarrm80s/orpheusdl-qobuz

Deezer (requires paid account)
 - https://github.com/uhwot/orpheusdl-deezer

Napster (requires paid account)
 - https://github.com/yarrm80s/orpheusdl-napster

Soundcloud (requires paid account)
 - https://github.com/yarrm80s/orpheusdl-soundcloud

Musixmatch
 - https://github.com/yarrm80s/orpheusdl-musixmatch

... be supported by Lidarr?

### Describe alternatives you've considered

Direct usage.

### Anything else?

None.

[AB#3705](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3705)

**Comment by bakerboy448** [comment]
- no plans for DDL or similar in lidarr
- The alpha plug-ins branch exists and supports a deezer plugin
