### ISSUE TITLE
Custom Script testing should provide extensive test data

### ISSUE THREAD

**Issue by sdfg2** [Lidarr/Lidarr#2968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I need actual data to test my script.  So I was manually importing an album and could not figure out what was going wrong until I found #2327.

### Describe the solution you'd like

All environment variables should be populated with test data, not just EventType, when testing a custom script.

### Describe alternatives you've considered

There are none.  At some point the script _needs_ to see what data lidarr would give it.  I've tested myself creating test strings and that works fine, but then I could be creating the test strings in a different way from what the API document states.

### Anything else?

-

[AB#3725](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3725)

**Comment by bakerboy448** [comment]
No plans for random arbitrary test payloads.

the formatting and payloads are documented 
https://wiki.servarr.com/lidarr/custom-scripts
