### ISSUE TITLE
How do I update the develop branch?

### ISSUE THREAD

**Issue by MrMxyzptlk** [lidarr/Lidarr#297]
I have a working develop branch, but I see you have fixed the poster issues, etc.
When I look in Lidarr / System it shows 'no updates available', but If I go to github it shows updates in the last few days?

Is there a way to update without having to recompile the code?

Thanks for the great job!

**Comment by danielunderwood** [comment]
Develop updates come from github releases, which will be added when we release a beta. The nightly branch currently gets builds from appveyor, but will be more prone to error once we release a beta.

**Comment by danielunderwood** [comment]
The appveyor build does support auto update, the release branch just needs to be set as nightly rather than develop. Once we release beta builds, the develop branch will point to those.

**Comment by danielunderwood** [comment]
366 is a branch build, so it isn't included in the updates. Only builds from the develop branch are included in the nightly releases.

**Comment by justinglock40** [comment]
Gettings this from the beta: Running on windows.

<img width="1067" alt="screenshot at apr 22 09-07-20" src="https://user-images.githubusercontent.com/23133649/39095844-ccb1c94e-460c-11e8-9a52-87151b4daac3.png">
