### ISSUE TITLE
Add "others-audio drama" as secondary category

### ISSUE THREAD

**Issue by steve1977** [Lidarr/Lidarr#2970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Cannot albums from musicbrainz that are category as "audio drama".

https://musicbrainz.org/artist/d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3

### Describe the solution you'd like

It seems you show all secondary release group types from musicbrainz, but not "audio drama". Would be great to add this just to capture *all* of MBZ:

https://musicbrainz.org/artist/d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3

### Describe alternatives you've considered

Tried to manually add in some way, but also not successfl.

### Anything else?

Not really

[AB#3728](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3728)

**Comment by Makario1337** [comment]
I might have a solution for your Problem: 

https://github.com/Makario1337/ExtendedReleaseAdder

**Comment by steve1977** [comment]
Sounds great! How is it implemented in lidarr-extended, which you mention it is?

So I add a path in the container lidarrAudiobookRootFolder=/audiobooks

How do I then add the audiobook artists? And does the audiobook artists pull all release types from mbz?

**Comment by Makario1337** [comment]
you specify it in your docker-run/docker-compose config as variable lidarrAudiobookRootFolder=/customaudiobookpath
then you post your artists.json in the /config folder 

for your artist it would be:

{
   "artists": ["d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3](https://musicbrainz.org/artist/d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3"]
}

**Comment by steve1977** [comment]
Under variable, I have the choice for name, key, value, and default value. Shall I place it under key?

Also, is it "customaudiobookpath" or is this a placeholder to include something like "audiobook"? Where will audiobooks be saved? Ideally, this will be a different folder from /music if possible?

**Comment by steve1977** [comment]
I am making some progress, but not yet working. See what I tried below:

1) I added "Variable" in docker container with "key" as lidarrAudiobookRootFolder and "value" as /audiobooks

2) I also added "path" in docker container with "container path" as /audiobooks and "host path" 

3) I added /audiobook as root folder in LE

4) I created a artists.json file and added:
{
"artists": ["d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3]([https://musicbrainz.org/artist/d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3"]](https://musicbrainz.org/artist/d3d9bc09-f1c1-49bc-94e0-e7897f60f4c3%22%5D)
}

4) I am seeing the following in the log
2022-09-25 21:07:45 :: Extended Release Adder :: 1
wget: server returned error: HTTP/1.1 400 Bad Request
2022-09-25 21:07:47 :: Extended Release Adder :: Adding ::
wget: server returned error: HTTP/1.1 400 Bad Request
2022-09-25 21:07:51 :: Extended Release Adder :: ERROR :: Did not find matching release , skipping...
2022-09-25 21:07:51 :: Extended Release Adder :: ERROR :: Make sure the wanted items are listed under Other + Audio Drama on Musicbrainz

5) Besides fixing my issue, I would also add one feature request. I would love to see not only "other-audiodrama" being added, but ideally the whole artist. Many other audio artists are under "spokenword". And even for popular artists like "Die Drei ???", the albums are fragmented under "Album", "Album + Soundtrack", "Album + Audio drama", "Other + Compilation + Audio drama", "Other + Live + Audio drama", and "Other + Audio drama"

**Comment by ta264** [comment]
This is not the place to troubleshoot a third party script. Please take it offline :)

**Comment by steve1977** [comment]
Fair point, sorrt!

**Comment by steve1977** [comment]
Let me still keep it open though. It may still be a good feature request to have Lidarr add the ability to add "other-audiodrama".

**Comment by Qstick** [comment]
Dupe #1021
