### ISSUE TITLE
Wrong album cover fetched from MusicBrainz

### ISSUE THREAD

**Issue by RodolfoFigueroa** [Lidarr/Lidarr#2971]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

If a release has multiple images tagged as "Front" in MusicBrainz, Lidarr will arbitrarily select one of them to be the local release's cover image. 

This selection may be different from the "canonical" MusicBrainz front cover, i.e., the one that shows when opening the release page. Moreover, it may also differ from the cover obtained when querying the Cover Art Archive API, specifically its `/release/{mbid}/front` endpoint, which, according to the documentation, "Fetches the image that is most suitable to be called the 'front' of a release".

### Expected Behavior

Taking [this](https://musicbrainz.org/release/c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c) release as an example, the release page correctly sets [this](https://ia804503.us.archive.org/28/items/mbid-c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c/mbid-c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c-32503066200.jpg) artwork as the front cover, even when there are several images tagged as "Front" in the [Cover Art tab](https://musicbrainz.org/release/c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c/cover-art). 

Moreover, [querying the Cover Art Archive API](https://coverartarchive.org/release/c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c/front) returns the same cover.

However, Lidarr incorrectly fetches [this](https://ia804503.us.archive.org/28/items/mbid-c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c/mbid-c7f4bd55-90ec-45cf-9d94-5bd0498d0b7c-32503066925.jpg) image as the album cover, as shown in [this](https://i.imgur.com/4JFFswZ.png) screenshot.

### Steps To Reproduce

1. Add a new release that has several images tagged as "Front" on MusicBrainz.
2. Let Lidarr finish updating the information.
3. There is a chance the cover art it fetches will be the wrong one.

### Environment

```markdown
- OS: Debian 11
- Lidarr: 1.0.2.2592
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 104.0.2
```

### What branch are you running?

Master

### Trace Logs?

[log.txt](https://github.com/Lidarr/Lidarr/files/9562873/log.txt)
![4JFFswZ](https://user-images.githubusercontent.com/17148278/190064456-8319a4d6-92a3-4ab6-a91e-1a549e24d112.png)

**Comment by Qstick** [comment]
This will be an issue with Metadata and not Lidarr itself, our API returns the incorrect image

https://api.lidarr.audio/api/v0.4/album/75a1c4b2-3e5e-45ca-b53e-da299e10dfd9

**Comment by Qstick** [comment]
This should be fixed with https://github.com/Lidarr/LidarrAPI.Metadata/commit/fd326042ca4b52b3c56cfa048d330ddb1edcf4a9 going forward.

It may take a bit for many of them to get through the cache.
