### ISSUE TITLE
Add "unknown" as "release status"

### ISSUE THREAD

**Issue by steve1977** [Lidarr/Lidarr#2972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Releases can be categorized of having an "unknown" release status. These releases aren't imported into lidarr.

### Describe the solution you'd like

Metadata profile allows to "tick" releases statuses. I'd love to see "unknown" being added as an option to select.

### Describe alternatives you've considered

Tried everything, but cannot import.

### Anything else?

No

[AB#3738](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3738)

**Comment by Qstick** [comment]
No plans for this, they should be fixed on MusicBrainz
