### ISSUE TITLE
UI related errors should show a notification

### ISSUE THREAD

**Issue by OmgImAlexis** [lidarr/Lidarr#298]
## Feature Request
Errors caused by UI requests should be shown to users.

### Description of request and what problem are you looking to solve?
For example in https://github.com/lidarr/Lidarr/issues/88 the user had no idea until they went to check their logs.

**Comment by Qstick** [comment]
https://github.com/lidarr/Lidarr/commit/64a8d02f77ff7917b1078461dafb122387ed05fc
