### ISSUE TITLE
CommandExecutor - Error occurred while executing task ImportListSync: Search for 'lidarr:93747376-b698-4610-a023-d256de075460' failed. Invalid response received from LidarrAPI.

### ISSUE THREAD

**Issue by amberflag48** [Lidarr/Lidarr#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to import a Spotify playlist using the Import Lists feature, but when it tries to import it it fails with the following error: `Error occurred while executing task ImportListSync: Search for 'lidarr:93747376-b698-4610-a023-d256de075460' failed. Invalid response received from LidarrAPI.`

### Expected Behavior

I would expect it to import the content of the playlist in Lidarr.

### Steps To Reproduce

1. Go to Lidarr - Settings - Import Lists.
2. From there, add a new list - Fill out all the info and connect the Spotify account, then select the desired playlist.
3. Do a 'Test' - It is successful.
4. Click on 'Save' - It starts importing the playlist, then give the above error.

### Environment

```markdown
- OS: Debian 10
- Lidarr: 1.0.2.2592
- Docker Install: Yes (LinuxServer.io)
- Using Reverse Proxy: Yes (Nginx)
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/9620630/Lidarr.trace.txt)
[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/9620631/Lidarr.debug.txt)

[AB#3770](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3770)

**Comment by bakerboy448** [comment]
Can't repro any issue for a search for that id  on 1.2.1.3195 / that id seems to now works fine
