### ISSUE TITLE
Supported-Indexers wiki page missing

### ISSUE THREAD

**Issue by OmgImAlexis** [lidarr/Lidarr#300]
### Other Information
On the indexer settings page it links to the wiki for "more info" but the wiki pages doesn't exist anymore.

For example https://github.com/Lidarr/Lidarr/wiki/Supported-Indexers#gazelle

**Comment by Qstick** [comment]
Hasn't been created yet as priorities have been elsewhere. Feel free to write one up if you want, would be happy to add it.
