### ISSUE TITLE
Manual Import Selection Checkboxes Ranges

### ISSUE THREAD

**Issue by erikt311** [Lidarr/Lidarr#3049]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When manually importing multiple albums, it’s difficult to select only specific albums from the list. Currently, there is a “check all” checkbox at the top to select all or none checkboxes. 

### Describe the solution you'd like

A “ranges” option to be able to select ranges of checkboxes. For example, select the first and last track in an album, then select “ranges” and it would select all in between tracks. 

### Describe alternatives you've considered

Or, other UI ways to filter/select ranges. 

### Anything else?

NA

[AB#3956](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3956)

**Comment by Tigggger** [comment]
I think what you are after already exists. Click on the first track in an album so it shows a tick then Shift + Click on the last (or further down if you want multiple albums) and it selects all the ones in-between.

**Comment by Qstick** [comment]
Indeed, Shift + Click allows this
