### ISSUE TITLE
"RestartRequiredHelpTextWarning" instead of correct text

### ISSUE THREAD

**Issue by nonamethanks** [Lidarr/Lidarr#3058]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In /settings/general, the "Instance Name" setting doesn't display the restart warning correctly.
![image](https://user-images.githubusercontent.com/12946050/199241342-7ca6a6a7-a577-4711-a426-dbbb91dd89c2.png)

### Expected Behavior

n/a

### Environment

```markdown
- Lidarr: 1.0.2.2592
- Docker Install: 1.0.2.2592-ls100 (linuxserver)
```

### What branch are you running?

Develop

### Trace Logs?

n/a

[AB#3990](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3990)

**Comment by bakerboy448** [comment]
Already known and has been fixed for nearly a year in a PR, but it does not appear that fixing translation issues is a priority.

https://github.com/Lidarr/Lidarr/pull/2530
