### ISSUE TITLE
Lidarr keeps rescanning entire library repeatedly on any changes. 

### ISSUE THREAD

**Issue by EricHupp** [Lidarr/Lidarr#3076]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Version
1.0.2.2592
.NET
Yes (6.0.4)
DB Migration
56
Running on Ubuntu 22.04

As noted in this thread (https://redd.it/yiz3mg) lidarr keeps rescanning the entire library when I try and add any albums or rescan an artist. As I have 160k files in my directory it does nothing but scan over and over again. 
I have more trace logs if needed. 

### Expected Behavior

Not scan all files constantly

### Environment

```markdown
- OS: Ubuntu 22.04
- Lidarr:1.0.2.2592
- Docker Install:No
- Using Reverse Proxy: yes (cadddy)
- Browser: Firefox, Chrome, Edge
- Database:
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.trace.0.txt](https://github.com/Lidarr/Lidarr/files/9962785/Lidarr.trace.0.txt)
[Lidarr.trace.1.txt](https://github.com/Lidarr/Lidarr/files/9962786/Lidarr.trace.1.txt)
[Lidarr.trace.2.txt](https://github.com/Lidarr/Lidarr/files/9962787/Lidarr.trace.2.txt)
[Lidarr.trace.3.txt](https://github.com/Lidarr/Lidarr/files/9962788/Lidarr.trace.3.txt)
[Lidarr.trace.4.txt](https://github.com/Lidarr/Lidarr/files/9962789/Lidarr.trace.4.txt)
[Lidarr.trace.5.txt](https://github.com/Lidarr/Lidarr/files/9962790/Lidarr.trace.5.txt)
[Lidarr.trace.6.txt](https://github.com/Lidarr/Lidarr/files/9962791/Lidarr.trace.6.txt)
[Lidarr.trace.7.txt](https://github.com/Lidarr/Lidarr/files/9962792/Lidarr.trace.7.txt)
[Lidarr.trace.8.txt](https://github.com/Lidarr/Lidarr/files/9962793/Lidarr.trace.8.txt)
[Lidarr.trace.9.txt](https://github.com/Lidarr/Lidarr/files/9962795/Lidarr.trace.9.txt)
[Lidarr.trace.10.txt](https://github.com/Lidarr/Lidarr/files/9962796/Lidarr.trace.10.txt)
[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/9962797/Lidarr.trace.txt)

[AB#4045](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4045)

**Comment by bakerboy448** [comment]
How many files in unmapped files?

**Comment by EricHupp** [comment]
Too many to count.  It appears to be only 1 folder on 1 drive.   I was thinking of removing the folder and trying to scan again.

**Comment by EricHupp** [comment]
Also I swapped out the drive that is listed as drive 6.  I rsynced the entire drive over to the new one, remapped the uuid in /etc/fstab and have no problems with Radarr, Sonarr, but definitely in Lidarr.

**Comment by EricHupp** [comment]
Well this is a new one.  After the latest scan.

2022-11-08 13:30:56.4|Info|ImportApprovedTracks|Importing album 10470/10470
2022-11-08 13:30:57.3|Info|ImportApprovedTracks|Importing 144791 tracks

**Comment by EricHupp** [comment]
Clearing the unmapped files tab appears to have corrected the problem.  Please close this issue.
