### ISSUE TITLE
Static content missing from Login Form when Reverse Proxy with Subfolder

### ISSUE THREAD

**Issue by nightah** [lidarr/Lidarr#311]
### System Information/Logs

**Lidarr Version:**
0.3.0.373

**Operating System:**
Host: Arch Linux
Docker Container: Linuxserver.io (Xenial)

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.10.1.47

**Link to Log Files (debug or trace):**
n/a

**Browser (for UI bugs):**
https://imgur.com/6j4UGj4

### Additional Information
Some of the static content served out on the login page (frontend/src/login.html) is not actually appearing per the above image.

It looks like this is because the login page doesn't take into account modifications to the urlBase, if I inspect the source of the page I can see that the logo is pointing to: /Content/Images/logo.svg which makes sense looking at the following: https://github.com/lidarr/Lidarr/blob/e73936184b12cc6f6fdc59b3f49ac9a6296da59c/frontend/src/login.html#L169.

**Comment by Qstick** [comment]
This seems to be working fine for me in linuxserver docker container

**Comment by nightah** [comment]
That's the same container I am using, I initially mentioned Alpine but I forgot that the Lidarr container is based on their xenial/mono base container.

I didn't specifically mention because I thought it was obvious in the image but I'm reverse proxying lidarr on the /lidarr/ URI.
All of the content that is missing, for whatever reason isn't pre-pending the /lidarr/ URI.

**Comment by Qstick** [comment]
Fixed in 44ad754c863c0e55f6099bbcf81021e40feaf137
