### ISSUE TITLE
Lidarr version API isn't up-to-date

### ISSUE THREAD

**Issue by frebib** [Lidarr/Lidarr#3154]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

https://github.com/Lidarr/Lidarr/releases/tag/v1.1.1.2762 is the latest pre-release build from the `develop` branch, but the lidarr version API reports the previous build 1.1.0.2649 as latest: https://lidarr.servarr.com/v1/update/develop?version=1.0&os=linux&runtime=netcore&arch=x64 

### Expected Behavior

https://lidarr.servarr.com/v1/update/develop?version=1.0&os=linux&runtime=netcore&arch=x64 reports 1.1.1.2762 as the latest version

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4301](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4301)

**Comment by Qstick** [comment]
Fixed
