### ISSUE TITLE
Systemd for Linux / Wiki Update  

### ISSUE THREAD

**Issue by robgates** [lidarr/Lidarr#316]
I have been running Lidarr on my Ubuntu 16 server VM for several months and modified the system file from Sonarr to work with Lidarr, I can seem to add it to the wiki and wondered if it would be of use.

Systemd
Modern Linux systems have been updated to use the new systemd standard. The method is very simple and involves creating a service file then enabling it.
Create the service file
Be sure to modify the user, group, mono path and install directory.

Create the file lidarr.service with the content:
[Unit]
Description=Lidarr Daemon
After=network.target

[Service]
User={User account for Lidarr}
Group={Group account for Lidarr}
Type=simple
ExecStart=/usr/bin/mono /opt/Lidarr/Lidarr.exe -nobrowser
TimeoutStopSec=20
KillMode=process
Restart=on-failure
[Install]
WantedBy=multi-user.target

Move the file to your system directory
Typically located in /etc/systemd/system/, verify before proceeding. Will differ based on distribution.

mv lidarr.service /etc/systemd/system/

Add lidarr to startup
systemctl enable lidarr.service

Start lidarr service
Start lidarr via systemd and verify status.

systemctl start lidarr.service
systemctl status lidarr.service

**Comment by Qstick** [comment]
Done
