### ISSUE TITLE
SSL on lindarr.audio

### ISSUE THREAD

**Issue by michaeltieso** [lidarr/Lidarr#317]
<img width="726" alt="screen shot 2018-04-23 at 13 23 54" src="https://user-images.githubusercontent.com/1500606/39123883-9d071e18-46f9-11e8-8c98-c5b71ef5eb94.png">

Link to lindarr.audio goes to `https` but it appears SSL has not been added to the site. This leads to browsers showing the website is insecure. Might be best to add SSL rather than fixing the link.

**Comment by danielunderwood** [comment]
Fixed on server side.
