### ISSUE TITLE
Ability to Listen to/Sample Tracks from the WebUI 

### ISSUE THREAD

**Issue by pumplex** [lidarr/Lidarr#319]
I know this is a big ask but I think It would greatly enhance Lidarr.

It would be great to have a play icon/button at the side of every track on the artist Album/Single pages maby even an add to playlist button to que up tracks into a playlist.

For which you could have a separate playlist page with the ability view, playback & export (m3u/pls) the playlist (for lan/http).

Thanks

**Comment by majora2007** [comment]
I think it is out of scope to have any play functionality in Lidarr. Lidarr should be focused around management, while playing content should be left to 3rd party software.

**Comment by Qstick** [comment]
Yea and if we do it not going to happen anytime soon as it would require a backend portion in core to stream to the front end ui client, given most modern browsers block loading of local files direct by js.
