### ISSUE TITLE
Feature request: Redacted and Apollo  integration

### ISSUE THREAD

**Issue by ronald245** [lidarr/Lidarr#32]
i would love to be able to use RED and AP with lidarr,

**Comment by Qstick** [comment]
This will require creating a generic Gazelle Indexer. Adding link for reference:
[https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation](https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation)

**Comment by Qstick** [comment]
Merged into react
