### ISSUE TITLE
Add disambiguation as artist naming token

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#321]
### Description of request and what problem are you looking to solve?

Add disambiguation as artist naming token to help differentiate artists with same name. Ex. Alice cooped the man vs Alice Cooper the band. 

Need to add logic to parsing so this doesn’t kill artist folder name parsing.

**Comment by mbc0** [comment]
Hi, Just moved from headphones to Lidarr and this was the first issue I found :-( Any update on a fix?

Many Thanks, loving it so far :-)
