### ISSUE TITLE
Refresh/Scan Button for each Individual Album

### ISSUE THREAD

**Issue by Cokedriver** [lidarr/Lidarr#322]
## Feature Request
Refresh/Scan Per Album

### Description of request and what problem are you looking to solve?
A Refresh/Scan button on each Album.
To make it quicker when manually adding files to the Artists Folder. 

### Other Information
OS - Windows 10

**Comment by Qstick** [comment]
The issue with this is that we don't track album by a specific location, so all this will do is refresh the album metadata, we can have it scan for tracks, but it will be the entire artist directory.
