### ISSUE TITLE
Secondary Type as it's own subsection

### ISSUE THREAD

**Issue by claym** [Lidarr/Lidarr#323]
Enhancement Request - split out Live albums to their own collapsable section, like EPs are.

Some bands, such as Pearl Jam, have hundreds of live albums, and this makes the album section a little unwieldy.

Thanks!

[AB#473](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/473)

**Comment by Qstick** [comment]
This will mean up to 14 different sub-sections under an artist depending on metadata profile.. are we good with that?

**Comment by danielunderwood** [comment]
If you hit the gear icon at the album and select the secondary release album, it will show those and allow sort. Not sure that you can do a secondary sort though.
