### ISSUE TITLE
"On Artist Added" Notification

### ISSUE THREAD

**Issue by dexn** [Lidarr/Lidarr#3265]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like a trigger for when an artist is added and another for when an artist is deleted. Like Radarr has for when a Movie gets added or deleted from the library.

### Describe the solution you'd like

Implement a trigger for "On Artist Added" and "On Artist Delete", similar to Radarr's "On Movie Added" and "On Movie Delete".

### Describe alternatives you've considered

N/A

### Anything else?

N/A

[AB#4620](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4620)

**Comment by Qstick** [comment]
Delete is already in nightly, title modified.

**Comment by bakerboy448** [comment]
https://github.com/Lidarr/Lidarr/commit/5f9c616bff6ff4006fa7ea9b4f76677e8946bb80
