### ISSUE TITLE
Add [Bonus Track] to Parser Track Token Cleanup

### ISSUE THREAD

**Issue by majora2007** [lidarr/Lidarr#327]
Some tracks have [Bonus Track] which causes matching issues. Expand the track cleanup to strip these patterns.

**Comment by alagave** [comment]
Would this include album names? My collection contains two versions with the same album name - except one has bonus tracks and one does not. I guess the same situation exists for a US and UK release - like the early Rolling Stones albums. They had the same name but sometimes different tracks or different track order.
