### ISSUE TITLE
Import Album fails to Map Tracks and shows BLANK item for Album Version on manual imports

### ISSUE THREAD

**Issue by jeffreyswiggins** [Lidarr/Lidarr#3282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When an album is not automatically imported and cannot be manually imported by the default results chosen by Lidarr then tracks will not get mapped when a manual Album is chosen.  It seems that is using some sort of BLANK Album version and even if you chose a valid version from the drop it will not Map Tracks.  If you do not select a version (leave blank) and manually map tracks import will fail.  Mapping tracks manually to a known Album version and then importing does work but very tedious for a large collection album that is 10 discs with over 100 tracks.

### Expected Behavior

You select the Album and if necessary the Album Version and tracks are Mapped as best as it can and normally very accurately

### Steps To Reproduce

1. Download an Album that will require a manual import or attempt to manually import an existing album in the Artists folder.
2. Select Tracks and then Album and Album release.  You will find that the default release is a BLANK item.
3. Select a valid Album release and it will not map tracks as expected

### Environment

```markdown
- OS: Docker
- Lidarr:1.1.2.2892
- Docker Install: Yes
- Using Reverse Proxy:Yes but same results if accessing local network with no reverse proxy.
- Browser: Does not matter.  Tested Current Versions of Google Chrome, Mozilla Firefox and Mobile Safari
- Database: Sqlite 3.38.5
```

### What branch are you running?

Nightly

### Trace Logs?

[Lidarr.debug.txt](https://github.com/Lidarr/Lidarr/files/10405538/Lidarr.debug.txt)
[Lidarr.trace.0.txt](https://github.com/Lidarr/Lidarr/files/10405539/Lidarr.trace.0.txt)
[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/10405540/Lidarr.trace.txt)
[Lidarr.txt](https://github.com/Lidarr/Lidarr/files/10405541/Lidarr.txt)

[AB#4701](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4701)

**Comment by Qstick** [comment]
Try 2896 or later, same issue?

**Comment by jeffreyswiggins** [comment]
The issue appear to have been resolved for me last week sometime when an automated update was pulled.  Been several versions updated during that time so not sure which was specifically for this but it has not been an issue for me since.

I do run the nightly builds just as a point of reference.
