### ISSUE TITLE
Request an option to not download album art

### ISSUE THREAD

**Issue by chriscrutch** [Lidarr/Lidarr#3298]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd like to use Lidarr as less of a "music collection manager" and more of a "musical release calendar." I've put a lot of time into managing my collection's metadata and album art, etc, etc, using other tools and I don't need Lidarr to do it for me. I can of course make sure that it doesn't touch my metadata or filenames, but can I also make sure it doesn't bother downloading any album art? That's gigs of data which is unnecessary for me to download and store again, I already have it elsewhere. What I don't have is any application to follow and automatically search for new releases by my favorite artists or an app to look for better versions of releases I already have.

### Describe the solution you'd like

I'd like an option to not download and store album art for use with the Lidarr database. 

### Describe alternatives you've considered

Alternatively, an option perhaps to only use artwork in the UI if there's already a "cover.jpg" or similar file in the album's folder would be ok, but I assume this would be more difficult to implement.

### Anything else?

Thank you for your hard work and your consideration. 

[AB#4753](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4753)

**Comment by Qstick** [comment]
Thanks, but no plans for making this optional at current time.
