### ISSUE TITLE
Missing Tracks

### ISSUE THREAD

**Issue by Kozhuharov** [Lidarr/Lidarr#3337]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Lidarr is not populating the songs correctly for this album https://musicbrainz.org/release/98441efe-502d-4df2-968f-2025f31375af
Missing:

Digital Media 2: Track 14
Digital Media 3: Track 2

### Expected Behavior

To populate all tracks.

### Steps To Reproduce

Just try to import this album to Lidarr https://musicbrainz.org/release/98441efe-502d-4df2-968f-2025f31375af
I think the problem is the scrapper because the missing tracks have different styling (open musicbranz and see).

### Environment

```markdown
- OS: Ubuntu LXC Container Proxmox
- Lidarr: 1.0.2.2592
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome latest
- Database: Default
```

### What branch are you running?

Master

### Trace Logs?

no trace logs

[AB#4892](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4892)

**Comment by ta264** [comment]
Those are marked as video tracks in musicbrainz. Lidarr deliberately omits video tracks as it doesn't support video files.
