### ISSUE TITLE
Unmatched albums/songs

### ISSUE THREAD

**Issue by syco** [lidarr/Lidarr#335]
Hi,
I'm running lidarr in docker, I copied some albums manually and then tried to do "Manual Import", but some albums don't get imported:
![image](https://user-images.githubusercontent.com/54575/39401728-3add2918-4b44-11e8-80a7-224aa59e8aae.png)
this should match this album: https://musicbrainz.org/release/99174338-c40b-414e-8ebd-0c2868688651

![image](https://user-images.githubusercontent.com/54575/39401736-7706761a-4b44-11e8-99a3-e15ddc5d997d.png)
In this second image there's 3 songs not matched from this album: https://musicbrainz.org/release/89de766d-fb73-4121-8aab-2310b2babc7e
And this other album is completely unmatched: https://musicbrainz.org/release/129c3643-d83e-45cc-a8d3-190e2f1ef0bc

Please let me know if I can provide more info. Thanks.

**Comment by Qstick** [comment]
This falls into #50 however feel free to jump on discord and give us some more info about what the rejections actually are. It may be a case of bad file tags
