### ISSUE TITLE
m4a Files Not Recognised?

### ISSUE THREAD

**Issue by mem-alloc** [lidarr/Lidarr#336]
## Bug Report
m4a files are not recognised by Lidarr.

**Lidarr Version:**
0.2.0.371

**Operating System:**
macOS High Sierra

**.net Framework (Windows) or mono (macOS/Linux) Version:**
5.8.0.108

### Additional Information
I have a few albums in m4a format and a few with some m4a songs, and none of the m4a files are not detected.

**Comment by Qstick** [comment]
Its an allowable extension that we pickup as a mediafile. Can you post some debug logs? Are you sure your files have embedded tags?

**Comment by mem-alloc** [comment]
Where can I see the allowable extentions? I'm 100% sure it has embedded tags, as I spent a week adding tags to all my songs before installing Lidarr.

**Comment by Qstick** [comment]
https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs

Logs would tell us what’s happening

**Comment by mem-alloc** [comment]
18-4-29 12:14:15.9|Info|RefreshArtistService|Updating Info for CÅ“ur de pirate
18-4-29 12:14:16.6|Info|DiskScanService|Scanning CÅ“ur de pirate
18-4-29 12:14:20.6|Info|DiskScanService|Completed scanning disk for CÅ“ur de pirate
18-4-29 12:14:20.6|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-4-29 12:14:20.6|Info|ExistingLyricImporter|Found 0 existing lyric files
18-4-29 12:14:20.6|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-4-29 12:14:20.6|Info|ExistingExtraFileService|Found 0 extra files
18-4-29 12:14:20.9|Info|MediaCoverService|Downloading Fanart for [130e7bd0-6d34-48a9-822f-03eff7ea95d4][CÅ“ur de pirate] http://assets.fanart.tv/fanart/music/130e7bd0-6d34-48a9-822f-03eff7ea95d4/artistbackground/cur-de-pirate-519a8c14688ab.jpg
18-4-29 12:14:22.1|Info|MediaCoverService|Downloading Logo for [130e7bd0-6d34-48a9-822f-03eff7ea95d4][CÅ“ur de pirate] http://assets.fanart.tv/fanart/music/130e7bd0-6d34-48a9-822f-03eff7ea95d4/hdmusiclogo/cur-de-pirate-55ca63cdc42b2.png
18-4-29 12:14:22.8|Info|MediaCoverService|Downloading Banner for [130e7bd0-6d34-48a9-822f-03eff7ea95d4][CÅ“ur de pirate] http://assets.fanart.tv/fanart/music/130e7bd0-6d34-48a9-822f-03eff7ea95d4/musicbanner/cur-de-pirate-55247acb96253.jpg
18-4-29 12:14:24.5|Info|MediaCoverService|Downloading Poster for [130e7bd0-6d34-48a9-822f-03eff7ea95d4][CÅ“ur de pirate] http://assets.fanart.tv/fanart/music/130e7bd0-6d34-48a9-822f-03eff7ea95d4/artistthumb/cur-de-pirate-519a8bf64d96b.jpg

<img width="1772" alt="screen shot 2018-04-29 at 12 15 05" src="https://user-images.githubusercontent.com/16860069/39408615-0b337bf0-4ba7-11e8-843f-1717f337b616.png">

**Comment by Qstick** [comment]
I would venture to say that’s an issue with the artist folder name and Lidarr not handling special characters correctly. Do you have an example of it missing m4a files in an artist without special characters in the folder name?
