### ISSUE TITLE
Feature Request: Correct Unmatched Imports

### ISSUE THREAD

**Issue by BzowK** [lidarr/Lidarr#337]
## Feature Request: Correct Unmatched Imports

Hey Guys - 
Just installed Lidar from recent compiled release in Windows today.  Great work so far!  

My request is for the ability to match albums which were unmatched during import - perhaps similar to how Headphones does it.  For example, I start importing my library already which has been going to a few hours now (it's fairly large.)  Almost everything in my library has been tagged, cleaned up, renamed, and moved by MusicBrainz Picard.  One of these albums is "Stages" by "John Groban" however, it's named "Stages (Deluxe)" in it's metadata and folder via Musicbrainz as it's the Deluxe version of the album.  Coincidentally, I edited that album and the Deluxe version is what was selected by default anyways.  

In these cases, Lidarr adds the artist, but does not recognize the album therefore doesn't add it.  So far, I haven't been able to find a way to "correct" this issue aside from renaming / tagging the files then re-importing or refreshing and with multiple albums from 500+ artists, correcting in that fashion would take a while.

Any way which one could manually match them - especially any unmatched ones in bulk - would be fantastic.

Thanks!!!

**Lidarr Version: 0.2.0.371**
**Operating System: Windows 10 x64**
**Browser (for UI bugs): Chrome**

**Comment by Qstick** [comment]
Go to the artist page and hit manual import.
