### ISSUE TITLE
Feature : Support for combined albums.

### ISSUE THREAD

**Issue by sbeaudoin** [lidarr/Lidarr#338]
**Context**
Some artists have combined two albums into one release.  For example, the artist America release "Homecoming" : https://musicbrainz.org/release-group/fa2c6a08-44a8-37b1-b89a-e2c7e7ad997d and "Hat Trick" : https://musicbrainz.org/release-group/62291b26-d942-3c25-ad24-29f2b94f475b and later combined them for "Homecoming / Hat Trick" : https://musicbrainz.org/release/27b0978e-4785-45b1-b1e1-40b6a05e18c2.

**Suggestion**
In the artist albums, add both the single albums and the combined albums.

**Comment by Qstick** [comment]
What you are suggesting is already possible by changing your metadata profile, that combined release is a bootleg release. You would have to tell Lidarr you want to see bootleg releases if you want that to show up.

**Comment by sbeaudoin** [comment]
Bootleg?  I thought those where pirate recordings during a show.  This is not the case here.  It is only the artist who make a "two for one" to help sell albums.  Although this is not exactly right, I will try it to solve my problem.  This will take a few days.

**Comment by sbeaudoin** [comment]
I activated bootleg, saved, but no bootleg sections for artist "America" and no new albums are shown.  I even launched the refresh artists task.

**Comment by sbeaudoin** [comment]
I found it by trial and error, ticked and unticked each combinations until I had it.  I had to tick "Compilations", not "Bootleg", this make more sense.  Thank you.

**Comment by MrMxyzptlk** [comment]
Where the heck are you finding those checkboxes...I tried to find compilations to no avail?

**Comment by sbeaudoin** [comment]
Right ribbon : Settings, then Profiles.  On this page, you have "Metadata Profiles".  The one created by default is "Standard".  This is where you select the release types and you can select a metadata profile for each artist when you import.  I suppose you can modify it somewhere else after the import.
