### ISSUE TITLE
Feature : Support for non inserted tracks.

### ISSUE THREAD

**Issue by sbeaudoin** [lidarr/Lidarr#339]
**Context**
Suppose I selected only EP in the metadata profile and in my collection, I have several singles, live albums, etc.  Also, suppose some of my albums are not recognized.

Presently, the application show only matched items.  What I suggest is to support non-matched or out of context tracks.

**Suggestion**
In the artist albums page, include a "Out of context" section where we will find "Album / Category / Tracks (present vs existing) grouped by category.  So, I will be able to see it and move the files elsewhere.

Also, include a "Not matched" global section where a file can't be matched to any artist.  Finally, in the artist page, include a "Not matched" section where the artist as been recognized, but not the album.  For each of those items, include a button for a window to correct the artist name (if required) and to select the release.

**Comment by Qstick** [comment]
In regards to the "Not Matched" section, that is essentially what "Manual Import" does on the artist details page and wanted page.

**Comment by alagave** [comment]
I see that but would it not be nicer to show a link adjacent to the status which shows how many tracks are on the album? That could open up subsequent lines on the display that could show lots of detail. Perhaps even a link to the error that caused it to fail import?

**Comment by Qstick** [comment]
Care to mock something up? I’ll do what I can to fit it in if it makes sense. Also I thought we already showed Import errors on manual import modal? Mouse over or click on the red exception icon on the right

**Comment by sbeaudoin** [comment]
Sorry, but I don't have time for that.  I have my own project underway and other things.

**Comment by tehniemer** [comment]
A simplified version of this would just be to show the unmatched or orphaned tracks in the music directory and a way to manually assign them to an artist/album, similar to how unmatched folders are handled in the import section.

**Comment by Qstick** [comment]
Unmatched global section implemented for 0.7
