### ISSUE TITLE
Error importing song and renaming whith non convenctional title

### ISSUE THREAD

**Issue by spupuz** [lidarr/Lidarr#345]
Error importing song and renaming whith non convenctional title:

whenever in title there is a / or, or : it fails to import the song

**Comment by spupuz** [comment]
it seems that remove or replace illegl cracter does not work

**Comment by spupuz** [comment]
there also duplicate file mp3 / flac on folder if multiple donwload and manual import

**Comment by Qstick** [comment]
S8milar to #50
