### ISSUE TITLE
Improve album version selection

### ISSUE THREAD

**Issue by Baraddon** [lidarr/Lidarr#352]
## Feature Request
- When changing the release version of a album (e.g. standard to deluxe), the dropdown menu should show how many local files of a given release match to the release. This would make the selection easier without having to look into the folder at the same time.

**Comment by Qstick** [comment]
This is going to be difficult given how things are currently setup. We need to first pull in all tracks of all releases (which we don't currently do). Then we need to save and match all local media files to tracks for each release (which we don't currently do). 

Item 1 maybe in the near future, Item two will take some work and will not likely be anytime soon.

**Comment by ta264** [comment]
Lidarr automatically swaps to the best release now so not sure this is necessary
