### ISSUE TITLE
Password is not hidden - Plex Connection

### ISSUE THREAD

**Issue by MauricioFarias** [lidarr/Lidarr#353]
**Lidarr Version: 0.2.0.371
The field "password" shows the caracters of the text you entered in Plex Connection form.
Text should be hide.

**Comment by Qstick** [comment]
I thought this was fixed here https://github.com/lidarr/Lidarr/commit/ca1ef7e15176ba63816015bf971448cccd5fe45f

**Comment by Qstick** [comment]
Confirmed by @Tailchakra
