### ISSUE TITLE
Ability to search for DVD/Bluray versions of live concerts

### ISSUE THREAD

**Issue by kelso911** [Lidarr/Lidarr#3563]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No. 

### Describe the solution you'd like

LIdarr currently only searches for music files. It would be great if it had the ability to search for a music concert DVD/Bluray as well. 

Id did do a search via an indexer, and it does not seem that many people upload music concerts and the ones that are available are not top quality. But maybe this function would encourage people to do so. 

It will probably not be a function for the masses but a great function for the handful of people that do enjoy live concerts and top quality rips. 

### Describe alternatives you've considered

I have searched high and low and cannot find a suitable alternative. I am in the process of digitizing my own concert collection and it is even difficult to separate them as music concerts on media centres. They are viewed as movies and meta data is pulled from IMDB (successfully so). So, everything is a bit of a work around. 

### Anything else?

Here are a few links to a music concert example: 

NZB file:  
https://nzb.su/details/9da387b25914340900d6822f05f21d70/Phil.Collins.Going.Back.2010.720p.BRRip.Xvid.AC3.LmB.part21

Meta Data
https://www.discogs.com/release/6101570-Phil-Collins-Going-Back-Live-At-Roseland-Ballroom-NYC
https://www.imdb.com/title/tt1787984/

**Comment by 1agent13** [comment]
Another example:
Rammstein - In Amerika
https://musicbrainz.org/release/68b5cd67-1e30-4a86-a9d5-f6254cad3291
https://www.discogs.com/release/7521649-Rammstein-In-Amerika

**Comment by bakerboy448** [comment]
No plans for lidarr to support videos
Ref  https://github.com/Lidarr/Lidarr/issues/3337
