### ISSUE TITLE
Flac files are not renamed and moved 

### ISSUE THREAD

**Issue by tigertim08** [lidarr/Lidarr#357]
Hello together, 

I have installed Lidarr on my QNAP yesterday and for mp3 files it really works perfect. But if Lidarr is downloading flac files these files are not renamed and moved. Like i mentioned it workds fine if it downloads mp3 files.  

Does anybody as an idea what I am missing? 

Thanks

**Comment by Qstick** [comment]
Fill out the required info and give logs. This sounds like an issue for support in discord
