### ISSUE TITLE
Few Downloads Stuck on 100%, No Import

### ISSUE THREAD

**Issue by Sherm1984** [lidarr/Lidarr#358]
Currently getting a few downloads that stick at 100%, upon checking qbitorrent they are complete. Some so this, others don't and I have no idea why. They aren't in rar files or anything like that 

https://i.imgur.com/nDp0HSP.png

**Comment by Qstick** [comment]
You provided zero useful info here. Logs, version, etc...

**Comment by Sherm1984** [comment]
Sorry for late reply. I have search the log files but cannot see any error there. However if I pause the torrent (Doesn't happen with nzb by the seems) it does seem to detect it's complete. So I can replicate it. I use both radar and sonar and it doesn't seem to happen there. 

[logs.zip](https://github.com/lidarr/Lidarr/files/2032052/logs.zip)

Windows 10
Microsoft Edge
qbittorrent v4.0.3
Version 0.2.0.371
DB Migration 15
AppData directory C:\ProgramData\Lidarr
Startup directory C:\ProgramData\Lidarr\bin
Mode Service

**Comment by Qstick** [comment]
Need debug or trace logs.

**Comment by Qstick** [comment]
This sounds like something related to your seeding settings, if you can provide trace logs would be glad to look closer
