### ISSUE TITLE
[BUG] Adding Artist with "monitor": "none" disregards "monitored" flags

### ISSUE THREAD

**Issue by Grygon** [Lidarr/Lidarr#3597]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Performing a POST to /api/v1/artist with the addOptions.monitor flag set to "none" results in the artist being added un-monitored, even with addOptions.monitored: true and monitored: true.

This causes issues for both external and internal integrations looking to add an album within an artist. 

Example POST body:
```JSON
{
    "addOptions": {
        "AlbumsToMonitor": [
            "REMOVED"
        ],
        "monitor": "none",
        "searchForMissingAlbums": false,
        "monitored": true
    },
    "albumFolder": true,
    "artistName": "REMOVED",
    "cleanName": "REMOVED",
    "foreignArtistId": "REMOVED",
    "images": [],
    "links": [],
    "metadataProfileId": 1,
    "monitorNewItems": "none",
    "monitored": true,
    "qualityProfileId": 3,
    "rootFolderPath": "/media/"
}
```

See https://github.com/Ombi-app/Ombi/issues/4608 for an example of this interfering with external integrations

### Expected Behavior

If I have "monitored" set to true, I expect that to be respected over a less-specific "monitor" parameter

### Steps To Reproduce

1. In Lidarr, search for an album whose artist does not exist in your library today
2. Add that album, and in the UI set the "Monitor" to "None". Logically, I'd expect this to mean I'm adding this album not adding nothing else (which is what happens
3. Observe that the Artist is not monitored, so the album itself isn't being monitored until the Artist gets monitored.

### Environment

```markdown
- OS: Ubuntu 22.04
- Lidarr: 1.1.4.3027
- Docker Install: Yes, Compose
- Using Reverse Proxy: Yes, Authentik
- Browser: Firefox and Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

N/A, see above for an API query to replicate

**Comment by bakerboy448** [comment]
` "monitor": "none"` means you've told Lidarr to monitor no existing albums nor any future albums thus don't monitor the artist.

This mirrors upstream behavior in Sonarr where you add a series and tell it not to monitor any episodes.

An artist cannot be monitored if there is nothing to monitor.

**Comment by Grygon** [comment]
@bakerboy448 
Is there a way to add an album and indicate that you want to only monitor the artist for that album then? That's the piece I'm missing here--if I'm telling it to monitor a specific album and also telling it to monitor no albums, I'd expect it to monitor no albums except where I'm being more specific by telling it to monitor a specific album.

If you disagree though I'll open a new Enhancement issue so as not to muddy the waters

**Comment by bakerboy448** [comment]
If you use Existing - that should work

but an enhancement request to improve or clarify the details of this given it's clunky wouldn't hurt

To be fair - None very much does indeed mean None :P

```none
Monitoring Options
This is a one time adjustment to set which albums are monitored
All Albums
Monitor all albums except specials
Future Albums
Monitor albums that have not released yet
Missing Albums
Monitor albums that do not have files or have not released yet
Existing Albums
Monitor albums that have files or have not released yet
First Album
Monitor the first albums. All other albums will be ignored
Latest Album
Monitor the latest albums and future albums
None
No albums will be monitored
```

**Comment by rjorgenson** [comment]
I would think there would be a way to add an album to lidarr and monitor that specific album that was added without enabling any new monitoring on anything else. This requires monitoring the artist but there is no option to monitor an artist and only monitor the specific album that we are adding to be monitored that I can see. 

If I'm using something like Ombi to send a request for an album I don't necessarily want to add anything else from that artist, but I also don't want to then have to go into Lidarr after the fact and enable monitoring on the artist and make sure all the albums are not monitored except the the one I wanted to add.

Given that albums have their own monitored flag maybe an artist could have a state for only monitoring monitored albums, I think None was the assumed behavior for that, as then marking the album as monitored would take precedence and the album would be monitored even though the artist, and by extension other albums, are not monitored, but this is not the case it seems.

Is there a way other than a new option for Artist monitoring to achieve what was described?

**Comment by Grygon** [comment]
Submitting with "monitor": "Existing" seems to replicate the behavior I want, since that isn't a selectable value in Lidarr, so it sets that to None.
![image](https://user-images.githubusercontent.com/647846/235571113-eb48c3f5-7d3b-49d8-b34b-3f5783d724e0.png)

I do want to find an artist that has an upcoming release though to see what happens there, but having trouble doing so. Will edit this once I find one. Either way, probably better behavior than current state, so will make a PR for Ombi I think no matter what.

**Comment by bakerboy448** [comment]
Monitoring at *Arr core is hierarchical stemming from episode => season => series.  That's a core set that's likely not changing.

@Grygon - `monitor new albums` != `monitor` - the option I mentioned is the one time (I.e. at add time) artist setting and Existing is a valid selectable option; that's where the block of text came from, the UI
