### ISSUE TITLE
cant import AI songs

### ISSUE THREAD

**Issue by icf20** [Lidarr/Lidarr#3604]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

AI songs dont exist in musicbrainz so there is no album to import

### Expected Behavior

import the file under "artist folder" and have a "uknown album folder" or allow me to create "AI album"

yes those songs belong to the artists because it was trained with their voice
start reading here https://twitter.com/Grimezsz/status/1650325296850018306

### Environment

```markdown
- OS: 
- Lidarr:
- Docker Install:1.1.4.3027
- Using Reverse Proxy:
- Browser:
- Database:
```

### What branch are you running?

Master

### Trace Logs?

no need logs use the brain

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
No plans for non musicbrainz sources

**Comment by bakerboy448** [comment]
No plans to change sources from MB.

Sounds like you need to reach out to and work with musicbrainz for them to develop a plan and add support for ai music
