### ISSUE TITLE
Album missing, no EPs and singles

### ISSUE THREAD

**Issue by DomiStyle** [lidarr/Lidarr#364]
**Describe the bug**
Lidarr doesn't list any EPs, singles and some albums are missing

**To Reproduce**
1. Add Felix Cartal (7208d210-66d4-413a-90c3-167b2e6bd4fb)
2. Visit artist page after scan

(Works with many artists, just an example)

**Expected behavior**
All albums, EPs and singles are shown
1 album is missing as of right now (Next Season)

Compare Lidarr to Musicbrainz: https://musicbrainz.org/artist/7208d210-66d4-413a-90c3-167b2e6bd4fb

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.2.0.371
 - Docker image: linuxserver/lidarr

**Additional context**
Not sure if the EPs and singles not being shown is a bug or just not implemented yet, but the album missing is most likely not on purpose.

**Comment by Qstick** [comment]
Just change your metadata profile to include the tyeps you want
