### ISSUE TITLE
Installer stuck at "removing Windows service"

### ISSUE THREAD

**Issue by vascozorrinho** [Lidarr/Lidarr#3654]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I install Lidarr, if I choose install as a service I'm still getting stuck at removing Windows service. I know it was supposed to be fixed but I'm still having problems

### Expected Behavior

Installer would finish correctly

### Steps To Reproduce

1. Download Lidarr.master.1.1.4.3027.windows-core-x64-installer.exe
2. Run installer and choose to install as a windows service

### Environment

```markdown
- OS: Windows 11 PRO x64
- Lidarr: 1.1.4.3027
- Docker Install: N/A
- Using Reverse Proxy: N/A
- Browser: N/A
- Database: N/A
```

### What branch are you running?

Master

### Trace Logs?

Do we have logs for the installer?

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by vascozorrinho** [comment]
Already did. Am i missing something?

![Screenshot 2023-05-11 204547](https://github.com/Lidarr/Lidarr/assets/8697036/5db604a7-0ad1-42d0-9594-4083d7290bf1)

**Comment by vascozorrinho** [comment]
Also uninstalling gives me the following error

`[Info] Bootstrap: Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.dll - Version 1.1.4.3027                                                                                                                                                                                                                                                                   [Fatal] ConsoleApp: EPIC FAIL!                                                                                                                                                                                                                  [v1.1.4.3027] DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;                                     message: Unable to resolve Microsoft.Extensions.Options.IOptions<NzbDrone.Core.Datastore.PostgresOptions> as parameter "postgresOptions" (IsSingletonOrDependencyOfSingleton)                                                                     in Singleton NzbDrone.Core.Configuration.ConfigFileProvider: NzbDrone.Core.Configuration.IConfigFileProvider as parameter "configFileProvider" FactoryId=924 (IsSingletonOrDependencyOfSingleton)                                               in Singleton NzbDrone.Host.AccessControl.FirewallAdapter: NzbDrone.Host.AccessControl.IFirewallAdapter as parameter "firewallAdapter" FactoryId=148 (IsSingletonOrDependencyOfSingleton)                                                        in Singleton NzbDrone.Host.AccessControl.RemoteAccessAdapter: NzbDrone.Host.AccessControl.IRemoteAccessAdapter as parameter "remoteAccessAdapter" FactoryId=149 (IsSingletonOrDependencyOfSingleton)                                            in resolution root NzbDrone.Host.UtilityModeRouter FactoryId=1074                                                       from container without scope                                                                                           with Rules with {TrackingDisposableTransients, AutoConcreteTypeResolution, SelectLastRegisteredFactory} and without {ThrowOnRegisteringDisposableTransient, VariantGenericTypesInResolvedCollection}                                            with DefaultReuse=Singleton {Lifespan=1000}                                                                             with FactorySelector=SelectLastRegisteredFactory                                                                        with Made={FactoryMethod=ConstructorWithResolvableArguments}                                                           Where no service registrations found                                                                                      and no dynamic registrations found in 0 of Rules.DynamicServiceProviders                                                and nothing found in 1 of Rules.UnknownServiceResolvers                                                                  at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in /_/src/DryIoc/Container.cs:line 14393                                                                                                                    at DryIoc.Container.TryThrowUnableToResolve(Request request) in /_/src/DryIoc/Container.cs:line 925                     at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request) in /_/src/DryIoc/Container.cs:line 905            at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11800         at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10790                      at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11800         at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10790                      at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11800         at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10790                      at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11800         at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10790                      at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 420                                                                                                  at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 386                                                                                                                at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8397                                                                                                                     at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 85                                                                                                                       at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 45                                                                                                                                                                                                                                                            Press enter to exit...   `

**Comment by bakerboy448** [comment]
Likely needs https://github.com/Radarr/Radarr/commit/3a1d848e59dda24b50220700b61db6046505c7a5

**Comment by geekwithoutacause** [comment]
I've got this exact same issue.

**Comment by tcntad** [comment]
> I've got this exact same issue.

Open task manager, expand lidarr setup by clicking '>' and close one of the running setup
