### ISSUE TITLE
Include existing albums in Metadata Profile

### ISSUE THREAD

**Issue by tjrp** [lidarr/Lidarr#367]
Would it be possible to have a check-box in the Metadata Profile to include existing albums. For example, I have a number of Ella Fitzgerald's albums and one compilation. If I include compilations in the profile there are literally hundreds. I would like to be able to import the one I have and then modify the profile to Standard + existing albums to able to see what I have and the standard albums that I don't.

**Comment by Qstick** [comment]
The way things are setup now, it’s not possible given we don’t pull any metadata on the types you don’t want.  We’ll have to think about how we can rework things to include something like this

**Comment by tjrp** [comment]
I was thinking that (using my example) I would first use a metadata profile including compilations to select the right album and _then_ change the metadata profile to be studio albums + existing albums to achieve the result I'm looking for. I would imagine that in this case, the metadata could be available.

**Comment by tjrp** [comment]
Sorry, closed by mistake.

**Comment by tjrp** [comment]
On reflection my use case is best resolved by implementing #397
