### ISSUE TITLE
Service does not start.

### ISSUE THREAD

**Issue by sbeaudoin** [lidarr/Lidarr#373]
**Describe the bug**
Installed 0.2.0.371 as a service on a Windows 10 1803 machine.  Tried to start the service, but failed.  Tried to run it with an admin account without success.

**To Reproduce**
1. Install Lidarr 0.2.0.371 as a service on a Windows 10 1803 machine.
2. Start the service.

**Expected behavior**
The service start and I am able to go to the web page.

**Additional context**
The application event log show the following message (in french, sorry) : 

> Une vérification de stratégie d’unmarshaling a été effectuée lors de l’unmarshaling d’un objet marshalé personnalisé et la classe {41FD88F7-F295-4D39-91AC-A85F3149A05B} a été refusée

Approximative translation :

> An unmarshaling strategy check as been performed during the unmarshaling of a custom object and the class {41FD88F7-F295-4D39-91AC-A85F3149A05B} as been denied.

Two times

**Comment by sbeaudoin** [comment]
Uninstalled and installed as a normal app.  Now, it says it conflict with port 8686 used by nzbDrone (portusedexception).  They use the same port and I can't change them at installation time?  I will stop sonarr, execute lidarr, change lidarr port and restart sonarr... 👎

**Comment by sbeaudoin** [comment]
nzbDrone (sonarr) use 8989 by default, the message is misleading.  With the help of a "netstat -a -b", I found out the culprit was the qBitTorrent web UI.  Libarr works as an app, so I reinstalled it as a service and it works.  

I suggest, at the time of installation, see if the default port is already used and, if so, ask the user for an alternative port.  Once entered, repeat the process.

You can close this as you like.

**Comment by Qstick** [comment]
That wording has been fixed in nightly to say Lidarr instead of nzbdrone.
