### ISSUE TITLE
Handling Apostrophes/Quotes in Artist Name via Import Artist

### ISSUE THREAD

**Issue by pdenner** [lidarr/Lidarr#376]
Couldn't find this as already filed, so apologies if this has already been raised. Tried to import my library via Import Artist and my previous folder scheme included the character ' in some artist names, however the parser would only recognize ‘ when trying to match. Similarly " didn't return anything but switching to ” would. It would be great to support both of these, because (I believe?) different systems default to different versions of that same character, and I don't know of a case where you'd be, say, using both ' and ‘ in the same field. 

I'm running Lidarr off my RPi (but headless) and importing via the web UI on my Mac via Chrome, if that helps.

**Comment by ta264** [comment]
I think this should be fixed now
