### ISSUE TITLE
Top Search Bar Returns 404

### ISSUE THREAD

**Issue by warlord0** [lidarr/Lidarr#377]
**Describe the bug**
Since upgrading to 0.3.0.430 30 May 2018 - develop any search either returns to the artist icons page or returns 404 error.

**To Reproduce**
1. Go to 'Top search bar'
2. Type search criteria
3. Select artist
4. Cry because it return 404

**Expected behavior**
Should take me to the selected artist page.

**Screenshots**
Attached
![capture1](https://user-images.githubusercontent.com/9975039/40739031-05555a56-643d-11e8-93b1-db0bcab9b5b3.PNG)
![capture](https://user-images.githubusercontent.com/9975039/40739039-0b1ecc06-643d-11e8-8149-6d7ebd189a8a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 66.0.3359.181 (Official Build) (64-bit)

**Additional context**
Based on Docker install using Debian Stretch.

It is possible to navigate the artist icons and select the artist to view details as expected. Only searching fails.

**Comment by majorpdd** [comment]
I still seem to get this

**Comment by Qstick** [comment]
Are you on nightly? If not you will still get it until release is made

**Comment by majorpdd** [comment]
Understood, TY
