### ISSUE TITLE
Last.fm bookmarks import list

### ISSUE THREAD

**Issue by 2fst4u** [Lidarr/Lidarr#3774]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently there is no way to automatically import your last.fm bookmarks. You can only add "user" and "tag", neither of which correspond to your bookmarks.

### Describe the solution you'd like

Add and import list for your last.fm bookmarks.

### Describe alternatives you've considered

None.

### Anything else?

None

**Comment by bakerboy448** [comment]
Last FMs API does not appear to provide any access to Bookmarks
