### ISSUE TITLE
Cannot import album with star in torrent/folder name

### ISSUE THREAD

**Issue by robca402** [Lidarr/Lidarr#3776]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When downloading a torrent with a star in the name (common with PMEDIA releases), importing fails. Everything else imports without issue.

The log states "2023-06-05 08:03:46.8|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /mnt/downloads/Moby - Resound NYC (2023) [24Bit-44.1kHz] FLAC [PMEDIA] ⭐️. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder"
Full trace log attached.

### Expected Behavior

I would expect lidarr to be able to import the album as with a folder without a star.
Sonarr/radarr both import torrents with stars without issue on the same machine.

### Steps To Reproduce

1. Search for album names with a star in it (often the PMEDIA group which are common)
2. Album will download but fail to import

### Environment

```markdown
- OS: Ubuntu 22.04
- Lidarr: 1.2.2.3242
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: Sqlite 3.37.2
```

### What branch are you running?

Develop

### Trace Logs?

[Lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/11646623/Lidarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by Rubicj** [comment]
Is this still a problem? I'm able to import PMEDIA albums with a star emoji without any problem.

**Comment by robca402** [comment]
Hi there,

Unfortunately yes this is still an issue on my install, I updated to the latest release 2.1.1.3877 and just tried to download another album. I still get the error “2023-12-26 14:43:00.5|Error|DownloadedTracksImportService|Import failed, path does not exist or is not accessible by Lidarr: /mnt/files/downloads/Paramore - This Is Why (2023) [24Bit-96kHz] FLAC [PMEDIA] ⭐️. Ensure the path exists and the user running Lidarr has the correct permissions to access this file/folder”

I can confirm that the user Lidarr is running as has full read/write to the folder as expected.

**Comment by robca402** [comment]
Okay so with the christmas break I took some time to look into this further. I set up another VM with a manual install as well as docker which all had the same issue, which ruled out lidarr. I looked into my torrent client (qBittorrent 4.5.5) and noticed it was downloading into a folder and the star emoji was being saved as ".." instead, such as 
![image](https://github.com/Lidarr/Lidarr/assets/48463801/3b143b23-5ea9-42d6-9621-facd140c0d89)
So I set up deluge to try out, which sure enough downloads it with the star in the filename as lidarr expects
![image](https://github.com/Lidarr/Lidarr/assets/48463801/e570aba3-4ad8-44d8-a75d-c650b60a0002)

This issue appears to be documented here https://github.com/qbittorrent/qBittorrent/issues/13572

So it was a qBittorrent issue, not a lidarr issue. I'm sorry to have taken your time with this, I really appreciate all of your hard work! Thanks

**Comment by robca402** [comment]
Yeah they do, well at least they did. Let me try find another example and see if that is still the case

**Comment by robca402** [comment]
Nope, they don't. When the issue started for me with Lidarr I had plenty of examples of sonarr/radarr with a star in the title that had successfully imported but that must have been before the change in behaviour of qBittorrent. Just tried to download one now and Radarr can't find the file to import in the folder.

So there is no issue here with Lidarr, just qBittorrent :). Cheers

**Comment by robca402** [comment]
Final update from me, I had a standard qBittorrent install, which even in qbittorrent-unstable PPA only had 4.5.5.

I installed a docker container which is running 4.6.2 which works as expected, correctly showing the star in the downloaded folder name. So for anyone in future with this issue you just need to run the newer version.
