### ISSUE TITLE
High ram usage lasting hours (3+ hours, 6GB)

### ISSUE THREAD

**Issue by slimshizn** [lidarr/Lidarr#378]
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/2055746/Lidarr.txt)

Title. Have a fairly large library so I could understand some ram usage when scanning the disks, but after it's done it sits at 6GB used and slowly moves down to 5.7GB used after an hour or so. 

OS: unRAID
Using Jackett, NZBGet, Deluge and Hydra with it. Any other information let me know.

**Comment by Qstick** [comment]
What version and OS. If mono, what version?

**Comment by slimshizn** [comment]
I have to go back and see if this is still happening. I added this issue back in May.

**Comment by Qstick** [comment]
Multiple memory fixes are in latest nightly, closing this for now unless something comes back up
