### ISSUE TITLE
Installer gets stuck on "Removing previous Windows Service" on a clean install of the program (and windows)

### ISSUE THREAD

**Issue by superusercode** [Lidarr/Lidarr#3806]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

https://github.com/microsoft/winget-pkgs/pull/110134
![image](https://github.com/Lidarr/Lidarr/assets/60588434/b6a8b4b3-6109-4e6e-af83-7fa2832bc15b)
winget uses a clean VM for validation

### Expected Behavior

Installs without issue

### Steps To Reproduce

1. Have a clean install of windows in a hyperv vm
2. Attempt to install lidarr with inno setup default silent flags (/VERYSILENT) and /NORESTART
3. Hangs on `Removing previous Windows Service`

### Environment

```markdown
- OS: 
- Lidarr: 1.1.4
- Docker Install: no
- Using Reverse Proxy: no
- Browser: unrelated
- Database: unrelated
```

### What branch are you running?

Master

### Trace Logs?

Hang occurs in installer, no trace created by lidarr as it is the installer that hangs

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by BrandonWanHuanSheng** [comment]
It look like the setup was hang. It look like I started the installation on yesterday at night.

**Comment by BrandonWanHuanSheng** [comment]
[Setup Log 2023-06-19 #001.txt](https://github.com/Lidarr/Lidarr/files/11798130/Setup.Log.2023-06-19.001.txt)

**Comment by BrandonWanHuanSheng** [comment]
It look like another annoying things pop up after install this application.

![Screenshot (251)](https://github.com/Lidarr/Lidarr/assets/118059864/41ebae13-e530-4af8-a144-8db4a6348b53)

It triggers the network connection to warning It say action needed for Wi-Fi. Previously, I did not see this before while during the installation.

**Comment by BrandonWanHuanSheng** [comment]
Uninstallation error log file.
[Lidarr.txt](https://github.com/Lidarr/Lidarr/files/11798500/Lidarr.txt)
