### ISSUE TITLE
Unable to open artist or album from calendar

### ISSUE THREAD

**Issue by DeadDjembe** [lidarr/Lidarr#382]
When in calendar view clicking on the artist or album does not open the artist or album (it does nothing).  This is true for all the different views (Month/Week/Forcast/Day/Agenda), and is also true for both upcoming and past albums. 

Running version: 0.3.0.430 in a docker container on the unraid platform
Browser: Chrome, FireFox, and Safari all behave the same

**Comment by Qstick** [comment]
This was intended until we figure out if clicking should just take you straight to the album or open an intermediate dialog with some info about artist and album and ability to go to respective pages from there. Thought?

**Comment by DeadDjembe** [comment]
I see, I'm glad you guys are putting thought into it. 

I think the easiest and an intuitive solution would be to link the album text to the album page, and the artist text to the artist page.  This would at least make it functional.  A more elegant solution would be something similar to what you suggested and what sonarr does, where a popup would allow you to see the album files, history, and to search for the album, with a link to the artist page.
