### ISSUE TITLE
More info on manual import / album selection screen

### ISSUE THREAD

**Issue by wizzy99** [lidarr/Lidarr#383]
When doing a manual import inside of an artist, and clicking on the album selection box, an apparently unordered list of albums is presented. It would be very helpful if at a minimum the number of tracks and year of the release were visible, and spectacular if the list could be sorted by clicking on a header. I'm trying to manually import Raiders of the Lost Ark from John Williams and have to scroll through many pages searching for it.

**Comment by krin-san** [comment]
Album release year and quick search would definitely help to find appropriate album in the _(sometimes)_ long albums list.
