### ISSUE TITLE
Cannot get to LIdarr from other computers on same LAN. 

### ISSUE THREAD

**Issue by gpoulos2** [lidarr/Lidarr#384]
**Describe the bug**
Cannot get to Lidarr from other pc's on the same LAN

**To Reproduce**
1. Windows 10. I am running Sonarr, Radarr, SAB, Plex perfectly
2. I did change the port to 9003 i checked the config.xml
3. I checked to make sure the port is open in the Win 10 firewall both way private and public.
4. I can use it on the pc that its installed on but not on any others on the same LAN.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 32 gb of ram
 - Browser Firefox
 - Version 60

**Comment by sbeaudoin** [comment]
I think you must run it as an administrator the first time so it can configure the network correctly on windows 10.  I add the same problem.

**Comment by Qstick** [comment]
Hit Discord for support
