### ISSUE TITLE
Subsonic connection doesn't support subdirectories

### ISSUE THREAD

**Issue by ejstacey** [lidarr/Lidarr#386]
**Describe the bug**
When setting up a subsonic server connection for notification/library updates, if you specify a subdirectory as part of the "host" value, you get "must be valid Host without http://"

**To Reproduce**
1. Go to Settings->Connect->Subsonic
2. For the server info, put in a domain/address that has a subdirectory (my.host/subsonic)
3. Fill in other info correctly
4. Click OK
5. See error

**Expected behavior**
The subsonic connection module handles subsonic being on a subdirectory

**Desktop (please complete the following information):**
 - OS:Linux
 - Browser any (qutebrowser atm)
 - Version 1.3.0

**Additional context**
I don't know C# well enough to be able to fix it, but even if it gets past the validation, I can see it will fail in src/NzbDrone.Core/Notifications/Subsonic/SubsonicServerProxy.cs line 73:

`            return RestClientFactory.BuildClient(string.Format("{0}://{1}:{2}/rest", protocol, settings.Host, settings.Port));
`

This will make a url in format https://my.host/subsonic:443 (or whatever port specified).  I don't know if the appropriate way to fix this is to add another field to the subsonic notification module or to just regexp across the settings.Host value and insert settings.Port before the first "/".

This gets used when you use a reverse proxy for subsonic access (apache in front for me) and serve it from a subdirectory.  You can't talk to the subsonic service directly as it also gets configured to serve from a subdirectory (SUBSONIC_CONTEXT_PATH=-/subsonic} in subsonic.sh (or .conf).

**Comment by Qstick** [comment]
Do any of the connections support subdirectories? Plex, Kodi, Emby?

**Comment by ejstacey** [comment]
It doesn't look like they do, no.  They have alternative interfaces though, so I don't have to reverse proxy them.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Qstick** [comment]
Ok, I'll see what can be done.

**Comment by Qstick** [comment]
We can likely use this logic to fix this... https://github.com/Sonarr/Sonarr/commit/9c9ad9aec3a2022ef703393baab3f02305bbba53
