### ISSUE TITLE
Cannot Update Lidarr to latest version

### ISSUE THREAD

**Issue by gipasoft** [lidarr/Lidarr#392]
Hi I have a big problem, if i try to update Lidarr to latest version I obtain this error:
```
[v0.2.0.371] NzbDrone.Core.Update.UpdateFailedException: Your Lidarr configuration '/share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config/Lidarr' is being stored in application folder '/share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr' which will cause data lost during the upgrade. Please remove any symlinks or redirects before trying again.
  at NzbDrone.Core.Update.InstallUpdateService.EnsureAppDataSafety () [0x0006f] in <60750421913847e19d61c61bd13a2b49>:0 
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x00000] in <60750421913847e19d61c61bd13a2b49>:0 
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x0006e] in <60750421913847e19d61c61bd13a2b49>:0 
```
In the System --> Status page there is this warning: `Updating will not be possible to prevent deleting AppData on Update`

What is the solution?

**Comment by gipasoft** [comment]
I have install Lidarr on a Qnap TS469 Pro firmware 4.3.4.0597

**Comment by travisboss** [comment]
This might be the same issue Asustor has with Sonarr, the request is over HTTPS but the Asustor wants to request over HTTP so it fails.

I had my radarr/sonarr solution on my asustor nas for a while but moved over to a Raspberry Pi and do not experience this issue anymore with updates. 

https://forums.sonarr.tv/t/having-a-problem-with-sonarr-and-asustor-nas/13344/10
Please review this post here about asustor, I know you have a QNAP but I think this might apply.

**Comment by gipasoft** [comment]
Hi thank for your reply, I have read the Asustor link but I dont understand how can i solve my problem, so i have manually updated the app

**Comment by Qstick** [comment]
Was this resolved?

**Comment by tigertim08** [comment]
Not that I know. I am still not able to update...

**Comment by Qstick** [comment]
Have you tried searching around for others that had the issue on Sonarr and Radarr, there seem to be a few. Closing for now as this seems to be a support issue.

I would try moving your config folder outside of the application folder (`Lidarr/lidarr`) as a attempt.

Not sure if it will help, but see https://forums.sonarr.tv/t/cannot-update-update-process-failed-your-sonarr-configuration-is-being-stored-in-application-folder-which-will-cause-data-loss-during-the-upgrade/14128

**Comment by gipasoft** [comment]
Finally I have solved my problem:
1) See in Lidarr system where is current `App_Data` directory (in my qnap: /share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config)
2) Create new `config` directory (see [here](https://github.com/lidarr/Lidarr/wiki/AppData-Directory) for detail) in my qnap: `/share/CACHEDEV1_DATA/LIDARR_CONFIG`
3) Copied all files from old APP_DATA directory in the new directory
4) Change command to start Lidarr (`/share/CACHEDEV1_DATA/.qpkg/Lidarr/Lidarr.sh`) in this new command: 
```
$MONO Lidarr.exe /data=/share/CACHEDEV1_DATA/LIDARR_CONFIG &
```

**Comment by Qstick** [comment]
Nice

**Comment by Tdotsown** [comment]
> Finally I have solved my problem:
> 
> 1. See in Lidarr system where is current `App_Data` directory (in my qnap: /share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config)
> 2. Create new `config` directory (see [here](https://github.com/lidarr/Lidarr/wiki/AppData-Directory) for detail) in my qnap: `/share/CACHEDEV1_DATA/LIDARR_CONFIG`
> 3. Copied all files from old APP_DATA directory in the new directory
> 4. Change command to start Lidarr (`/share/CACHEDEV1_DATA/.qpkg/Lidarr/Lidarr.sh`) in this new command:
> 
> ```
> $MONO Lidarr.exe /data=/share/CACHEDEV1_DATA/LIDARR_CONFIG &
> ```

new to this, can you tell me step by step, what i need to use to access the directory and also change the command to the new directory and how to move the files/folder over?

Thanks

**Comment by Tdotsown** [comment]
> Finally I have solved my problem:
> 
> 1. See in Lidarr system where is current `App_Data` directory (in my qnap: /share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config)
> 2. Create new `config` directory (see [here](https://github.com/lidarr/Lidarr/wiki/AppData-Directory) for detail) in my qnap: `/share/CACHEDEV1_DATA/LIDARR_CONFIG`
> 3. Copied all files from old APP_DATA directory in the new directory
> 4. Change command to start Lidarr (`/share/CACHEDEV1_DATA/.qpkg/Lidarr/Lidarr.sh`) in this new command:
> 
> ```
> $MONO Lidarr.exe /data=/share/CACHEDEV1_DATA/LIDARR_CONFIG &
> ```

am i doing something wrong. I went to the folder on windows using WinSCP and access the Lidarr original folder and edited the Lidarr.sh file and changed the $Mono command to the one you put. and moved the files in the original director the new LIDARR_CONFIG director.

when i start up Linarr, i get the following error message:
"SQL logic error no such table: Tracks
Version 0.4.0.524"

I have a QNAP TS-253Be on firmware 4.3.5.0728

Appreciate your inputs

**Comment by gipasoft** [comment]
> > Finally I have solved my problem:
> > 
> > 1. See in Lidarr system where is current `App_Data` directory (in my qnap: /share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config)
> > 2. Create new `config` directory (see [here](https://github.com/lidarr/Lidarr/wiki/AppData-Directory) for detail) in my qnap: `/share/CACHEDEV1_DATA/LIDARR_CONFIG`
> > 3. Copied all files from old APP_DATA directory in the new directory
> > 4. Change command to start Lidarr (`/share/CACHEDEV1_DATA/.qpkg/Lidarr/Lidarr.sh`) in this new command:
> > 
> > ```
> > $MONO Lidarr.exe /data=/share/CACHEDEV1_DATA/LIDARR_CONFIG &
> > ```
> 
> am i doing something wrong. I went to the folder on windows using WinSCP and access the Lidarr original folder and edited the Lidarr.sh file and changed the $Mono command to the one you put. and moved the files in the original director the new LIDARR_CONFIG director.
> 
> when i start up Linarr, i get the following error message:
> "SQL logic error no such table: Tracks
> Version 0.4.0.524"
> 
> I have a QNAP TS-253Be on firmware 4.3.5.0728
> 
> Appreciate your inputs

Have you try to start Lidarr from command line (using Putty):
Lidarr.exe /data=/share/CACHEDEV1_DATA/LIDARR_CONFIG

**Comment by ravensorb** [comment]
I am having the same issue with Lidarr running on Freebsd in a jail.  I have installed and configured Lidarr in /Lidarr off the root 

I am running it like this

```
/usr/local/bin/mono /Lidarr/Lidarr.exe --nobrowser --data=/Lidarr
```

Is the issue that I need a different data folder from where the main app is located?
