### ISSUE TITLE
Seperate Folders for Multi Disk Albums

### ISSUE THREAD

**Issue by SiDuB** [lidarr/Lidarr#393]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see separate tracks per disk in Multi-Disk albums

**Describe the solution you'd like**
Wanted Folder Arrangement: Artist>Album>Disk 1>Track 01

Current Folder Arrangement: Artist>Album>Track 01

**Additional context**
Currently if you have a 3 disk album in this is how it shows up in the folder.

Aerosmith  (it is a a 2 disk album)
                Young Lust- The Aerosmith Anthology (2001)
                                     Track 01
                                     Track 01
                                     Track 02
                                     Track 02
                                     etc...
Would like to see:
Aerosmith  (it is a a 2 disk album)
                Young Lust- The Aerosmith Anthology (2001)
                                   Disk 01
                                             Track 01
                                             Track 02
                                   Disk 02
                                             Track 01
                                             Track 02

Thanks for all the work you put into this.

SiDuB

**Comment by alagave** [comment]
Great idea for a user-controlled option. I would be uncomfortable asking users to restructure a large library but see benefits to allowing several options that Lidarr would recognize.

Option 1) AlbumArtist/Album, CD 1/
                                   /Album, CD 2/
                                                          Track 01

Option 2) AlbumArtist/Album/CD 1/
                                               /CD 2/
                                                         Track 01

Option 3) AlbumArtist/Album/Track 101  (disk1, track 01)
