### ISSUE TITLE
Lidarr does not follow published decision logic

### ISSUE THREAD

**Issue by akesher123** [Lidarr/Lidarr#3938]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The published decision logic is the following:

Quality
Preferred Word Score
Protocol (as configured in the relevant Delay Profile)
Indexer Priority
Seeds/Peers (If Torrent)
Album Count
Age (If Usenet)
Size

However, I am seeing Lidarr pick the wrong release based on this logic. 
Quality is the same for both releases. CD flac. They are the same quality tier in my lossless quality profile
Preferred Word Score: I have no preferred words.
Protocol: Only hooked up to torrent indexers. Both releases are torrents.
Indexer priority: both releases come from the same top priority indexer.
Seeds/Peers: The torrent with *fewer seeders* is being chosen. I think this is because here the seeds logic has a rounded log 10 instead of the true seed values https://github.com/Lidarr/Lidarr/blob/develop/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs

I'm not sure why this is here. While for difference between single digit and triple digit seeds this makes sense, however 4 and 31 seeds will both return the same value here which is a huge disparity.

### Expected Behavior

It should follow the published logic. The torrent with more seeds (all else in higher importance equal) should win.

### Steps To Reproduce

Find an album with multiple releases on one tracker. Search with Lidarr and it might pick the wrong one.

### Environment

```markdown
- OS: Unraid
- Lidarr: 1.2.6.3313
- Docker Install: Yes, binhex
- Using Reverse Proxy: no
- Browser: Chrome
- Database: Sqlite?
```

### What branch are you running?

Master

### Trace Logs?

Trace logs don't have much to note other than both releases were accepted.

This is the only thing before the final release accepted and grab: 

```
2023-07-30 15:30:27.5|Debug|DownloadDecisionMaker|Release accepted
2023-07-30 15:30:27.5|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2023-07-30 15:30:27.5|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2023-07-30 15:30:27.5|Trace|ConfigService|Using default config value for 'downloadpropersandrepacks' defaultValue:'PreferAndUpgrade'
2023-07-30 15:30:27.5|Trace|ProcessDownloadDecisions|Grabbing from Indexer Orpheus (Prowlarr) at priority 1.
2023-07-30 15:30:27.5|Trace|HttpClient|Req: [GET] http://prowlarr:9696/73/download....
2023-07-30 15:30:27.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
```
I was specifically seeing this issue on Orpheus torrents /torrents.php?id=106672&torrentid=956081#torrent956081 and /torrents.php?id=106672&torrentid=1817064#torrent1817064

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Logic is accurate and the same across Starrs.  Seeds and peers are bucketed and normalized for comparison by taking the log10.  

You can add a little control over this with the min seeders per indexer setting
