### ISSUE TITLE
Importing many arists fails

### ISSUE THREAD

**Issue by seitzbg** [lidarr/Lidarr#394]
**Describe the bug**
Tried to import 1600 artists, let it go 8 hours and still going.

**To Reproduce**
Point towards existing music, import many artists.

**Expected behavior**
Artists would be imported.

**Screenshots**
https://img.bsd-unix.net/screenshots/user1/155bLq62a.png

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: FF Quantum
 - Version: 61

**Comment by Qstick** [comment]
Need logs please.

**Comment by MrMxyzptlk** [comment]
Me, too, but I determined I had one album that was causing all of the problem.
I manually went through 'Wanted' 'Manual import on single artist until I found the 'problem child'.

Give it a try...

**Comment by Qstick** [comment]
Closing until better info
