### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Deterio** [lidarr/Lidarr#395]
I can't search for artists, this happens most of the time. On some occasions I can search for artists though. I don't know the steps to reproduce this

**Comment by DeadDjembe** [comment]
I'm having a similar issue.  When searching via the top search bar the popup window displays the artist under "existing artist", but when I click on the artist to open the artist page it gives a "Sorry, that artist cannot be found" 404 error. However, clicking on the artist from the "Artist" page (long list of all your artists) opens the correct artist with no errors.  

Running version: 0.3.0.430 in a docker container on Unraid
Browser: Chrome, FireFox, and Safari all behave the same

**Comment by warlord0** [comment]
Duplicate report of error #377

https://github.com/lidarr/Lidarr/issues/377

**Comment by Deterio** [comment]
This is not a duplicate report to my knowledge, we're talking about 2 different search bars.
I'm talking about the search bar when adding a new artist, sorry for not being clear.

**Comment by Qstick** [comment]
@danielunderwood could this be cache/cloudflare related?

**Comment by danielunderwood** [comment]
What's the log look like when the error happens? What happens when search fails? Just 'cannot find artist'? What are you searching?

**Comment by nibble4bits** [comment]
Same issue here.
![clipboard01](https://user-images.githubusercontent.com/16838891/42134154-fcc13b46-7d03-11e8-80e2-c16a91d9298a.jpg)
![clipboard02](https://user-images.githubusercontent.com/16838891/42134155-fccd1cd6-7d03-11e8-8aa4-473a60b5c204.jpg)
![clipboard03](https://user-images.githubusercontent.com/16838891/42134156-fcd537a4-7d03-11e8-8a08-0413c17a89a3.jpg)

**Comment by nibble4bits** [comment]
Also note: I've tried clearing my cache & cookies

**Comment by nibble4bits** [comment]
And the "1" in my System messages is because uTorrent crashed again, like it does often.

**Comment by francispeixoto** [comment]
I'm having the same issue. I can access artist pages from the artists list, but using the search bar, I get 404s on all my attempts. debug log is empty. I only get this in the logs when I search:

18-7-16 13:28:02.1|Debug|Api|[GET] /api/v1/artist: 200.OK (2955 ms)
18-7-16 13:28:40.8|Debug|Api|[GET] /api/v1/health: 200.OK (1 ms)
18-7-16 13:28:40.8|Debug|Api|[GET] /api/v1/system/status: 200.OK (2 ms)
18-7-16 13:28:41.0|Debug|Api|[GET] /api/v1/diskspace: 200.OK (246 ms)
18-7-16 13:28:42.5|Debug|Api|[GET] /api/v1/log/file: 200.OK (2 ms)

**Comment by Qstick** [comment]
@francispeixoto that is fixed in nightly. We will have a new release in next couple of days
