### ISSUE TITLE
Ability to manually add release for artist

### ISSUE THREAD

**Issue by corykim** [lidarr/Lidarr#397]
**Is your feature request related to a problem? Please describe.**
I was looking for "ye" by Kanye West and saw that it wasn't showing up under the list of artist's albums. Checking musicbrainz, it appears that it is listed as an EP, and I'm guessing that EP's don't get added by default. I'd like to be able to manually add this album to the artist so that I can track it.

**Describe the solution you'd like**
On the Artist page, I would like an "Add Release" button that allows me to search for a release by name, barcode, or musicbrainz ID.

**Describe alternatives you've considered**
The only alternative solution I know of is to manually download the release without using lidarr.

**Additional context**

**Comment by majora2007** [comment]
EPs get added if you select that you want to track them via your Metadata Profile.

**Comment by Qstick** [comment]
Why not just add `EP` to your metadata profile and have it pick them up for the artists you want them for?

**Comment by corykim** [comment]
Yes, thanks. I am a new user and didn't see that option.

**Comment by Qstick** [comment]
No prob, let us know if you have any other issues
