### ISSUE TITLE
Couldn't parse track from

### ISSUE THREAD

**Issue by screwfaze** [lidarr/Lidarr#400]
Hi,

I have been having this problem for a while now where Lidarr  will not automatically import anything that it snatches and always has the error "Couldn't parse track from *****************" even when its tagged correctly, sorry if this is a known issue but thought I should report it.

Thanks

**Comment by Qstick** [comment]
Examples? Version? Platform? Logs?

**Comment by screwfaze** [comment]
Hi,

I have sent you my log, Example Drake - Nice for what, version 0.3.0.446, Platform Windows.

Thanks

**Comment by majora2007** [comment]
Can you also add IDv3 tags for the file? You can use mediaInfo, Picard, or just right click-> properties. Just album, artist, and track should suffice.

**Comment by screwfaze** [comment]
![lidarr](https://user-images.githubusercontent.com/17312955/41255898-fcdcaae6-6dbf-11e8-9792-dde9c9ca9b90.PNG)

**Comment by screwfaze** [comment]
![lidarr1](https://user-images.githubusercontent.com/17312955/41256095-8834a18e-6dc0-11e8-8f57-89baa38fbe0f.PNG)

**Comment by screwfaze** [comment]
Also when doing manual search i get alot of "Unable to parse albums from release name"

**Comment by majora2007** [comment]
Interesting, musicbrainz lines up for the Drake track. I can see potential issues with the Ne-Yo. Will need to check on this.

**Comment by screwfaze** [comment]
I'm sure that at some point before this was working just fine but after some updates the Parsing has become worse. Thanks for helping guys really loving Lidarr so far!

**Comment by screwfaze** [comment]
@Qstick I have sent you the debug log.

Thanks

**Comment by Qstick** [comment]
The Drake song is due to track name and number tag being blank per the logs, I need to look further into the others.

**Comment by screwfaze** [comment]
@Qstick thanks mate

**Comment by Qstick** [comment]
Same as #50
