### ISSUE TITLE
Sort by album release date

### ISSUE THREAD

**Issue by GTunney** [lidarr/Lidarr#401]
### Description of request and what problem are you looking to solve?
I've just recently moved from headphones to Lidarr as support for headphones was slowly dying and less things were supporting it.

One of the features I liked about headphones was that you could sort by latest release and this would basically sort the artists by their album release date. I can't see anything like this on lidarr to sort by.

**Comment by Qstick** [comment]
Would it make since to sort our "Last Album" column by release date instead of name as it is now?
