### ISSUE TITLE
Case-insensitive duplicates being created by downloads.

### ISSUE THREAD

**Issue by scooterbaga** [Lidarr/Lidarr#4014]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've noticed an issue where Lidarr ignores the case of the text in existing artist or album folders. Lidarr will download files and make new folders only differing by the case in the text.

e.g. The existing Lidarr artist "Coil" will download files with the artist name "COIL". Instead of using the directory path existing in Lidarr, it creates a new folder. The same thing happens with album names. It would follow there may also be an issue with case differences in filenames, but have not seen it. I'm also not sure if it happens with any download with differing case, or just automatic downloads, etc.

I'm not sure where Lidarr is even getting the "new" folder names. Perhaps from the database of music Lidarr utilizes or even the downloads themselves? I don't update my music library very often, and I only notice the issue when entire discographies pop up as new. (Because the case-_insensitive_ application is struggling to scan the duplicate folders.) Lidarr and Unraid are case-sensitive. The issue pops up when I view files via Windows and Plex, weeks or sometimes _months_ later when updating the Plex library. Lidarr doesn't produce any errors.

### Expected Behavior

Lidarr should normalize all text before making comparisons and use existing text available when writing folders/files. (Perhaps even consider handling symbols and spaces. i.e. "and" being equivalent to "&", double spaces, etc.)

So existing folder Coil and new folder COIL are compared as equivalent and any new files written to the existing folder using the existing case.

### Steps To Reproduce

1. Import artist and album directories to lidarr with a nonsensical case structure
e.g. tHe BeAcH bOyS
2.  Download files either automatically or manually that would act on folders in step 1.
3.  This creates duplicate folders with differing case in the text.

### Environment

```markdown
- OS: Unraid 6.11.5
- Lidarr: 1.2.6.3313 (hotio)
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: firefox/chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

I'll attempt to generate logs if relevant. I'm not sure if this is expected behavior from Lidarr on a case-sensitive OS.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Steps to reproduce; not random guesses are also required

**Comment by scooterbaga** [comment]
> however it sounds like you are likely downloading to your library folder or using a third party tool to manage Lidarr's root folder - neither of which are supported at all

I'm referring to what Lidarr is doing with the library folder all by itself. Lidarr is managing the download client _and_ the root folder. My other processes are only reading from the Lidarr managed library folders.

> Unraid is Linux ans thus case sensitive and thus what you describe really isn't possible. This sounds like perhaps a bug with your windows setup and plex; neither of which have anything to do with lidarr

My apologies, I guess I'm flipping the meaning of OS' case sensitivity and insensitivity. Linux/Unraid Lidarr is 100% capable of having folders with the same name with different cases, which is the issue I'm describing. It's Windows and Plex that won't put up with two folders having the same name, regardless of case. I've updated/flipped the couple of references to "case-sensitive/insensitive".

I'll try to have trace logs up in a few hours.

**Comment by scooterbaga** [comment]
Update: Still waiting for reproduction of the main issue. I'm at the mercy of the downloads and how Lidarr chooses to handle them. Current attempt is on "waiting to import".

I _think_ I have been able to generate something similar to the album filename duplication. I have an existing album "bEaUtIfUl EyEs" that I manually imported into Lidarr. Then prompted Lidarr to download the album again. It made a second folder named "Beautiful Eyes" for the newly downloaded files. Then within Lidarr it's linking to the "bEaUtIfUl EyEs" folder.

I have Trace logs for this activity. Given how long this is playing out, I've been backing up and clearing logs. Should I be uploading multiple sets of logs as I reproduce issues?

**Comment by bakerboy448** [comment]
The bug report template links to the wiki for how to get and provide logs.

lidarr does not ever download anything.  It sounds like you are trying to put your albums in your root folder rather than under the artist folder.

screenshots would likely be prudent

Given the lack of any users reporting this, the vagueness of the issue, this does not appear to be a bug.

happy to re-open if support determines its a bug

**Comment by scooterbaga** [comment]
Importing an artist/album folder is necessary to reproduce the issue in a timely manner. Waiting for this to happen "organically" could take weeks or months. While trace logging, that is an absurd expectation. Says right in the description of the trace log feature it isn't meant to be left on. So the reproduction methods and descriptions I'm providing are to _force_ the same behavior.

I'm also a _user_, I don't know what to even _look_ for in the logs. So how does one go through weeks or months of logs they have zero experience with and no frame of reference for?

Lidarr also has pretty robust functionality for manually importing things. Not sure what the hang-up is there. Again, in this case, it's necessary to reproduce the issue in a timely manner.

Once Lidarr has an Artist folder, and is successfully acknowledging files, what's the problem? Even in that scenario, wouldn't future "things that Lidarr does automatically with a torrent application's downloads" creating duplicate folders still be an issue worth reporting?

**Comment by bakerboy448** [comment]
Again, please utilize discord for support. GitHub is not for support.

additionally, again, given your confusing and unclear narrative of the issue. Please provide exact paths of the downloads, the library folder, screenshots of history of the album in lidarr showing the pre/post import path, and screenshots of the album, artist, and download client torrent path details.

**Comment by scooterbaga** [comment]
Go fuck yourself you pedantic prick.
