### ISSUE TITLE
Setting "URL Base" results in port conflict

### ISSUE THREAD

**Issue by adamskoog** [lidarr/Lidarr#402]
When I set the "URL Base" setting to work with my reverse proxy I get the error "Port 8686 is already in use, please ensure Lidarr is not already running." It is impossible to get Lidarr to start with this configuration, if I edit the config manually to remove the custom URL Base it begins working again at the default URL. I've got Sonarr and Radarr setup with a nearly identical configuration, just with a different Base URL respective to each and they are working correctly.

**To Reproduce**
1. Go to Settings -> General
2. Edit URL Base to be "/Lidarr"
3. Click "Save Changes"
4. On "Restart Lidarr" dialog click "Restart Now"
5. Lidarr Windows Service will now fail to restart with error: "Epic Fail: PortInUseException: Port 8686 is already in use, please ensure Lidarr is not already running.

**Expected behavior**
Expect application to be able to run without port conflict error when configured to have a different Base URL. This is necessary in cases where using a reverse proxy and works as expected in both Sonarr and Radarr.

Logs: https://pastebin.com/tix9vdbm

**System info:**
 - Lidarr Version: 0.3.0.430
 - Operating System: Windows 10 1803 - 17134.112
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.5

**Comment by Qstick** [comment]
Haven't seen anyone else report this. Are you sure you have things setup correctly

**Comment by adamskoog** [comment]
I'm running sonarr and radarr with the same configuration. This is the only setting I've changed besides using forms authentication since I did the install. So I guess if something got borked on the install that could be an issue. I might try that tomorrow if I get some time.

**Comment by adamskoog** [comment]
I uninstalled the application and reused the installer for the version above.
1. Ran through the installer with all defaults.
2. At the end of the install, had it open the lidarr web ui.
3. Navigated to settings -> general -> change URL Base = "/lidarr"
4. On pop up, click Restart Now.
5. Service will not start due to it believing another instance is running.

Beyond this, I would be curious how I would have things set up incorrectly considering I've had Sonarr and Radarr setup in this fasion and working correctly for quite some time. If you have any troubleshooting steps I would be open to trying them, but I fail to see where above I could have gone wrong.

**Comment by adamskoog** [comment]
Any suggestions for things to do differently with the setup?

I've reinstalled again. Any time I have a value in for URL Base the service will not start. If I remove it, it starts working again. I even tried manually stopping the server, editing the config with the new value and restarting failed. I'd be willing to help t/s, but I'd need some guidance I what information you would need.

**Comment by Qstick** [comment]
Try and stop the service, run lidarr.exe as admin, make the changes, and then start the service back up.

**Comment by adamskoog** [comment]
@Qstick That seems to have been the ticket to get it up and running.

**Comment by Qstick** [comment]
Awesome!

**Comment by adamskoog** [comment]
@Qstick I ran into some permissions issues and checked what the service was running as. Sonarr and Radarr both have the radio button for "Local System account" ticked, where as Lidarr had "This Account" ticked with "Local Service" filled in. Changing this I now see my folders that were missing before. Kind of wondering if it was related to the above now as well since that seemed to boil down to a permission issue as well. Hopefully that helps you with t/s.

**Comment by Onfire7** [comment]
Confirmed, the Local System account was the issue.
I had the same issue with the latest installer as soon as I changed the base url.
While It wasn't starting I changed it to the regular Local System account option and it started up right away with my base url still set. Thanks for the help @adamskoog!

Not sure how we would go about fixing this, but we probablly should get it changed by default.

**Comment by adamskoog** [comment]
Glad it helped someone out, hopefully they can get the installer fixed.

**Comment by KrunchMuffin** [comment]
I just ran into this issue as well. running now after running as admin.
