### ISSUE TITLE
Allow copying over cue and log files

### ISSUE THREAD

**Issue by ismay** [lidarr/Lidarr#403]
**Is your feature request related to a problem? Please describe.**
Not really a problem

**Describe the solution you'd like**
I like to include cue and log files for downloads, so I know what the origin of the rip is. Helps with judging the quality of the rip and whether to replace it. A toggle that when activated will copy over files ending in .log and .cue would be nice.

Could maybe be more general, like a pattern that allows for wildcard matching of files that you want to keep. People might want to keep .m3u, .pls files, etc. So allowing the user to specify something like:

```
Additional files: "*.cue, *.log, *.pls"
```

**Describe alternatives you've considered**
Have not considered any alternatives, don't know of any.

**Comment by ismay** [comment]
Ok, so I missed that this is already available in the advanced settings :). I think this can be closed.

**Comment by ekyriakides** [comment]
@ismay How did you get this to work? No longer what I try *.log, .log, log.. it doesn't seem to copy them over.
