### ISSUE TITLE
Option to add "Special versions"

### ISSUE THREAD

**Issue by Haringstad** [lidarr/Lidarr#407]
It's a bit frustrating when you have special versions of a single, that you cannot add to a certain artist.

I would like to be able to import special versions (singles, maxi-singles or mixes)

**Describe alternatives you've considered**
Creating a fake album folder

**Comment by Qstick** [comment]
Unsure exactly what you want here, but sounds like multiple releases per release group? #517 lays the path for this.

**Comment by Qstick** [comment]
Closing in lieu of #729
