### ISSUE TITLE
Dotnet 7 or 8 migration

### ISSUE THREAD

**Issue by xaviergxf** [Lidarr/Lidarr#4070]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi Everyone, has anyone been working on migrating the project to .net 7 or 8 already?

### Describe the solution you'd like

Migration to dotnet 7/8

### Describe alternatives you've considered

Migration to dotnet 7/8

### Anything else?

No

**Comment by Qstick** [comment]
We'll move to 8 after release, we stick to LTS
