### ISSUE TITLE
NZBHydra Only looking at "Audio"

### ISSUE THREAD

**Issue by Viper911** [lidarr/Lidarr#409]
I put Hydra as my only indexer and run and Lidarr finds no releases.  I look in Hydra and only see a search in the Audio category in the history and if I hit the rerun button it only searches the Audio category.  If I keep the same search and search the MP3 then results come back.  I looked at the iundexer settings and all are listed in the category 3000 and 3010 are both in there the forst being Audio and the Second being MP3.  

Not sure if Lidarr is not parsing through all categories or what.

BTW if I add the external indexer directly (like dog) it works just fine.  Thoughts?

**Comment by Qstick** [comment]
I'll give this a test and see which side of the fence this is on.

**Comment by JagerSprinkles** [comment]
Just want to say that I'm having this exact issue as well.

**Comment by Qstick** [comment]
I can't seem to reproduce this, when sending search to Hydra, results are being returned for all categories that are passed in the searched and defined in indexer settings.

Lidarr creates this search string:
`http://1.2.3.4:5076/api?t=search&cat=3000,3010,3020,3030,3040&extended=1&apikey={redacted}&offset=0&limit=100&q=Breaking%20Benjamin%20Dark%20Before%20Dawn`

And I get results in Lidarr from categories 3010 and 3040. Also repeating the search in NZBHydra returns the same results for both Flac and MP3.

What version of Hydra are you running?

**Comment by Qstick** [comment]
![image](https://user-images.githubusercontent.com/376117/42416397-f5cbf862-823a-11e8-8b79-eedab98605bd.png)

**Comment by JagerSprinkles** [comment]
Sorry, I completely forgot I had just moved to nzbHydra2. I'm not sure if this issue is affecting the other version of Hydra.

I am currently running version 1.5.1 of Hydra2.
https://github.com/theotherp/nzbhydra2

**Comment by JagerSprinkles** [comment]
I found this in the logs of Hydra2. I hope it helps.

![tweoolllll](https://user-images.githubusercontent.com/6476475/42416542-6c76bcd2-823f-11e8-8a94-49f80856d521.PNG)

**Comment by JagerSprinkles** [comment]
This seems to be an issue on Hydra2's end. I modified my Audio category as such and the search is working as intended now.

It seems that the default Audio category in Hydra2 only searches the category 3000 by default.

![tweoolllll](https://user-images.githubusercontent.com/6476475/42416600-9b525a5a-8241-11e8-89e6-56e0a6a85612.PNG)

**Comment by Viper911** [comment]
Dumb question.  How did you add the categories to it?  I can type in that field something like 3010,3030 but it doesn’t save, nor add the little boxes with the “x”.


________________________________

**Comment by Qstick** [comment]
I'm using the same version on Hydra with default categories and don't seem to have this problem. Really searching with 3000 should return any of the sub results should it not?

**Comment by JagerSprinkles** [comment]
Viper, type the number you want, like 3010, then press enter. You need to do it after each entry.

Qstick, I'm not sure how Hydra handles the categories for the searches. I just know that I didn't receive any search results before I added the extra categories to the audio category in Hydra. I also removed the setting in the "Required words", mine was set to "mp3, flac" so maybe that had something to do with it too.

**Comment by Qstick** [comment]
Ok, regardless seems to be an issue with how Hydra is handling our requests. Does it make a difference if you remove 3000 and only use the sub categories in Lidarr indexer setup?

**Comment by JagerSprinkles** [comment]
I agree that it is a Hydra issue.

Using just the sub categories in the Lidarr indexer setup seems to return just about the same results. The only difference is that Drunken Slug returns 7 additional results when I add back the 3000 category.
I am using Pink Floyd - Dark Side of the Moon as the test album.
