### ISSUE TITLE
Renaming conflict for a 2xCD has the same track name and number on both discs

### ISSUE THREAD

**Issue by smithbr** [lidarr/Lidarr#411]
**Describe the bug**
With a 2xCD release which contains the same track name and number on both discs, there's no clear way for Lidarr to handle this situation, and it results in at least one track having to remain un-renamed (and forever show up in the Organize queue for that artist)

**Example Release**
https://musicbrainz.org/release/e866a680-e105-48d2-95f1-8c9cb01e5387
Both discs contain a track number 5 with the same title

**To Reproduce**
1. Add a new artist (e.g. Cap’n Jazz)
2. Import or download the album (e.g. Analphabetapolothology)
4. See Lidarr error when track is unable to be renamed due to a conflicting file of the same name

**Expected behavior**
Lidarr handles the conflicting tracks in a graceful way (not clearly defined yet).
Some possible ways could be:
- Using Disc folders for multi-disc releases
- Using alternative naming conventions for conflicting tracks (e.g. '01 - TrackName 1.format')
- Probably something more clever than I'm thinking about

**System info (please complete the following information):**
 - Lidarr Version: 0.3.0.430 Beta
 - Operating System: Mac OS X High Sierra
 - mono (macOS/Linux) Version: 5.12

**Comment by Qstick** [comment]
What do your naming settings look like?

**Comment by smithbr** [comment]
![image](https://user-images.githubusercontent.com/1495361/42403626-5b84b1d0-8137-11e8-885b-e4ae46e9e361.png)

**Comment by Qstick** [comment]
Closing as it’s very similar to 393 for multi disc folders which should be implemented soon
