### ISSUE TITLE
Lidarr install on Microsoft Windows Server 2016 Standard

### ISSUE THREAD

**Issue by neil1775** [lidarr/Lidarr#413]
**Microsoft Windows Server 2016 Standard Lidarr install not working**

After using the "Lidarr.develop.0.3.0.430.windows-installer.exe", and selecting install windows service, Lidarr fails to render on a local web page, http://localhost:8686/.

Radarr, Sonarr, already present on system as windows services, and working properly on other ports.

**To Reproduce**
Install on Microsoft Windows Server 2016 Standard using default settings, attempt to browse to http://localhost:8686/

**Expected behavior**
Lidarr renders on web page http://localhost:8686/.

**Screenshots**
![lidarr ss](https://user-images.githubusercontent.com/40900503/42397772-b6cfa648-8156-11e8-97ab-a19f9a2a7302.jpg)

**Logs**
18-7-6 14:32:01.8|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:32:02.3|Info|Router|Application mode: UninstallService
18-7-6 14:32:02.3|Info|ConsoleApp|Exiting main.
18-7-6 14:32:02.6|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:32:03.0|Info|Router|Application mode: InstallService
18-7-6 14:32:03.7|Info|ServiceProvider|Installing service 'Lidarr'
18-7-6 14:32:04.4|Info|ServiceProvider|Service Has installed successfully.
18-7-6 14:32:04.6|Info|ConsoleApp|Exiting main.
18-7-6 14:32:04.9|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:32:05.3|Info|Router|Application mode: Service
18-7-6 14:32:05.6|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:32:06.0|Info|MigrationLogger|*** VersionMigration migrating ***
18-7-6 14:32:06.4|Info|MigrationLogger|*** VersionUniqueMigration migrating ***
18-7-6 14:32:06.5|Info|MigrationLogger|*** VersionDescriptionMigration migrating ***
18-7-6 14:32:06.7|Info|MigrationLogger|*** 1: InitialSetup migrating ***
18-7-6 14:32:06.7|Info|InitialSetup|Starting migration to 1
18-7-6 14:32:06.8|Info|MigrationLogger|*** 2: add_reason_to_pending_releases migrating ***
18-7-6 14:32:06.8|Info|add_reason_to_pending_releases|Starting migration to 2
18-7-6 14:32:06.9|Info|MigrationLogger|*** 3: add_medium_support migrating ***
18-7-6 14:32:06.9|Info|add_medium_support|Starting migration to 3
18-7-6 14:32:07.2|Info|MigrationLogger|*** 4: add_various_qualites_in_profile migrating ***
18-7-6 14:32:07.2|Info|add_various_qualites_in_profile|Starting migration to 4
18-7-6 14:32:07.3|Info|MigrationLogger|*** 5: metadata_profiles migrating ***
18-7-6 14:32:07.3|Info|metadata_profiles|Starting migration to 5
18-7-6 14:32:07.4|Info|MigrationLogger|*** 6: separate_automatic_and_interactive_search migrating ***
18-7-6 14:32:07.4|Info|separate_automatic_and_interactive_search|Starting migration to 6
18-7-6 14:32:07.4|Info|MigrationLogger|*** 7: change_album_path_to_relative migrating ***
18-7-6 14:32:07.5|Info|change_album_path_to_relative|Starting migration to 7
18-7-6 14:32:07.5|Info|MigrationLogger|*** 8: change_quality_size_mb_to_kb migrating ***
18-7-6 14:32:07.5|Info|change_quality_size_mb_to_kb|Starting migration to 8
18-7-6 14:32:07.6|Info|MigrationLogger|*** 9: album_releases migrating ***
18-7-6 14:32:07.6|Info|album_releases|Starting migration to 9
18-7-6 14:32:07.6|Info|MigrationLogger|*** 10: album_releases_fix migrating ***
18-7-6 14:32:07.6|Info|album_releases_fix|Starting migration to 10
18-7-6 14:32:07.7|Info|MigrationLogger|*** 11: import_lists migrating ***
18-7-6 14:32:07.7|Info|import_lists|Starting migration to 11
18-7-6 14:32:07.8|Info|MigrationLogger|*** 12: add_release_status migrating ***
18-7-6 14:32:07.8|Info|add_release_status|Starting migration to 12
18-7-6 14:32:07.8|Info|MigrationLogger|*** 13: album_download_notification migrating ***
18-7-6 14:32:07.8|Info|album_download_notification|Starting migration to 13
18-7-6 14:32:07.9|Info|MigrationLogger|*** 14: fix_language_metadata_profiles migrating ***
18-7-6 14:32:07.9|Info|fix_language_metadata_profiles|Starting migration to 14
18-7-6 14:32:08.1|Info|MigrationLogger|*** 15: remove_fanzub migrating ***
18-7-6 14:32:08.1|Info|remove_fanzub|Starting migration to 15
18-7-6 14:32:08.2|Info|MigrationLogger|*** 16: update_artist_history_indexes migrating ***
18-7-6 14:32:08.2|Info|update_artist_history_indexes|Starting migration to 16
18-7-6 14:32:08.3|Info|MigrationLogger|*** 17: remove_nma migrating ***
18-7-6 14:32:08.3|Info|remove_nma|Starting migration to 17
18-7-6 14:32:08.4|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:32:08.5|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:32:08.6|Info|MigrationLogger|*** VersionMigration migrating ***
18-7-6 14:32:08.8|Info|MigrationLogger|*** VersionUniqueMigration migrating ***
18-7-6 14:32:08.8|Info|MigrationLogger|*** VersionDescriptionMigration migrating ***
18-7-6 14:32:08.9|Info|MigrationLogger|*** 1: InitialSetup migrating ***
18-7-6 14:32:08.9|Info|InitialSetup|Starting migration to 1
18-7-6 14:32:09.0|Info|MigrationLogger|*** 2: add_reason_to_pending_releases migrating ***
18-7-6 14:32:09.0|Info|add_reason_to_pending_releases|Starting migration to 2
18-7-6 14:32:09.0|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:32:09.1|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:32:09.1|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:32:09.1|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:32:09.1|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:32:09.1|Info|MigrationLogger|*** 3: add_medium_support migrating ***
18-7-6 14:32:09.1|Info|add_medium_support|Starting migration to 3
18-7-6 14:32:09.2|Info|MigrationLogger|*** 4: add_various_qualites_in_profile migrating ***
18-7-6 14:32:09.2|Info|add_various_qualites_in_profile|Starting migration to 4
18-7-6 14:32:09.3|Info|MigrationLogger|*** 5: metadata_profiles migrating ***
18-7-6 14:32:09.3|Info|metadata_profiles|Starting migration to 5
18-7-6 14:32:09.6|Info|MigrationLogger|*** 6: separate_automatic_and_interactive_search migrating ***
18-7-6 14:32:09.6|Info|separate_automatic_and_interactive_search|Starting migration to 6
18-7-6 14:32:09.8|Info|MigrationLogger|*** 7: change_album_path_to_relative migrating ***
18-7-6 14:32:09.8|Info|change_album_path_to_relative|Starting migration to 7
18-7-6 14:32:09.8|Info|MigrationLogger|*** 8: change_quality_size_mb_to_kb migrating ***
18-7-6 14:32:09.8|Info|change_quality_size_mb_to_kb|Starting migration to 8
18-7-6 14:32:10.0|Info|MigrationLogger|*** 9: album_releases migrating ***
18-7-6 14:32:10.0|Info|album_releases|Starting migration to 9
18-7-6 14:32:10.0|Info|MigrationLogger|*** 10: album_releases_fix migrating ***
18-7-6 14:32:10.0|Info|album_releases_fix|Starting migration to 10
18-7-6 14:32:10.2|Info|MigrationLogger|*** 11: import_lists migrating ***
18-7-6 14:32:10.2|Info|import_lists|Starting migration to 11
18-7-6 14:32:10.2|Info|MigrationLogger|*** 12: add_release_status migrating ***
18-7-6 14:32:10.2|Info|add_release_status|Starting migration to 12
18-7-6 14:32:10.3|Info|MigrationLogger|*** 13: album_download_notification migrating ***
18-7-6 14:32:10.3|Info|album_download_notification|Starting migration to 13
18-7-6 14:32:10.4|Info|MigrationLogger|*** 14: fix_language_metadata_profiles migrating ***
18-7-6 14:32:10.4|Info|fix_language_metadata_profiles|Starting migration to 14
18-7-6 14:32:10.4|Info|MigrationLogger|*** 15: remove_fanzub migrating ***
18-7-6 14:32:10.4|Info|remove_fanzub|Starting migration to 15
18-7-6 14:32:10.5|Info|MigrationLogger|*** 16: update_artist_history_indexes migrating ***
18-7-6 14:32:10.5|Info|update_artist_history_indexes|Starting migration to 16
18-7-6 14:32:10.6|Info|MigrationLogger|*** 17: remove_nma migrating ***
18-7-6 14:32:10.6|Info|remove_nma|Starting migration to 17
18-7-6 14:32:10.8|Info|OwinHostController|Listening on the following URLs:
18-7-6 14:32:10.8|Info|OwinHostController|  http://*:8686/
18-7-6 14:32:11.4|Info|LidarrBootstrapper|Starting Web Server
18-7-6 14:32:11.5|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
18-7-6 14:32:12.4|Info|ProfileService|Setting up default quality profiles
18-7-6 14:32:12.9|Info|MetadataProfileService|Setting up default metadata profile
18-7-6 14:32:12.9|Info|LanguageProfileService|Setting up default language profiles
18-7-6 14:33:21.5|Info|NzbDroneServiceFactory|Attempting to stop application.
18-7-6 14:33:21.5|Info|OwinHostController|Attempting to stop OWIN host
18-7-6 14:33:21.6|Info|OwinHostController|Host has stopped
18-7-6 14:33:21.6|Info|NzbDroneServiceFactory|Application has finished stop routine.
18-7-6 14:33:21.6|Info|ConsoleApp|Exiting main.
18-7-6 14:33:52.8|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:33:53.2|Info|Router|Application mode: Service
18-7-6 14:33:53.4|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:33:53.5|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:33:53.6|Info|OwinHostController|Listening on the following URLs:
18-7-6 14:33:53.6|Info|OwinHostController|  http://*:8686/
18-7-6 14:33:53.8|Info|LidarrBootstrapper|Starting Web Server
18-7-6 14:33:57.8|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:33:58.2|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:33:58.2|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:33:58.2|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:33:58.2|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:33:58.2|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:33:58.3|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
18-7-6 14:36:58.0|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:36:58.4|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:36:58.4|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:36:58.4|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:36:58.4|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:36:58.4|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:36:58.5|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
18-7-6 14:46:14.0|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:46:14.4|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:46:14.4|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:46:14.4|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:46:14.4|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:46:14.4|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:46:14.5|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
18-7-6 14:47:26.6|Info|RssSyncService|Starting RSS Sync
18-7-6 14:47:26.6|Warn|FetchAndParseRssService|No available indexers. check your configuration.
18-7-6 14:47:26.6|Info|DownloadDecisionMaker|No results found
18-7-6 14:47:26.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
18-7-6 14:49:42.8|Info|NzbDroneServiceFactory|Attempting to stop application.
18-7-6 14:49:42.8|Info|OwinHostController|Attempting to stop OWIN host
18-7-6 14:49:42.8|Info|OwinHostController|Host has stopped
18-7-6 14:49:42.8|Info|NzbDroneServiceFactory|Application has finished stop routine.
18-7-6 14:49:42.8|Info|ConsoleApp|Exiting main.
18-7-6 14:49:48.0|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:49:48.4|Info|Router|Application mode: UninstallService
18-7-6 14:49:48.4|Info|ServiceProvider|Uninstalling Lidarr service
18-7-6 14:49:48.4|Info|ServiceProvider|Stopping Lidarr Service...
18-7-6 14:49:48.4|Info|ServiceProvider|Service is currently Stopped
18-7-6 14:49:48.4|Warn|ServiceProvider|Service Lidarr is already in stopped state.
18-7-6 14:49:53.7|Info|ServiceProvider|Lidarr successfully uninstalled
18-7-6 14:49:53.7|Info|ConsoleApp|Exiting main.
18-7-6 14:49:53.9|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:49:54.7|Info|Router|Application mode: InstallService
18-7-6 14:49:54.9|Info|ServiceProvider|Installing service 'Lidarr'
18-7-6 14:49:54.9|Info|ServiceProvider|Service Has installed successfully.
18-7-6 14:49:55.0|Info|ConsoleApp|Exiting main.
18-7-6 14:49:55.7|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.Console.exe - Version 0.3.0.430
18-7-6 14:49:56.7|Info|Router|Application mode: Service
18-7-6 14:49:57.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\lidarr.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:49:57.4|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Lidarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-7-6 14:49:57.4|Info|OwinHostController|Listening on the following URLs:
18-7-6 14:49:57.4|Info|OwinHostController|  http://*:8686/
18-7-6 14:49:58.6|Info|LidarrBootstrapper|Starting Web Server
18-7-6 14:50:02.3|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:50:02.6|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:50:02.7|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:50:02.7|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:50:02.7|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:50:02.7|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:50:02.8|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
18-7-6 14:54:16.6|Info|Bootstrap|Starting Lidarr - C:\ProgramData\Lidarr\bin\Lidarr.exe - Version 0.3.0.430
18-7-6 14:54:16.9|Warn|ProcessProvider|Couldn't get process info for Lidarr.Console

[v0.3.0.430] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at NzbDrone.Common.Processes.ProcessProvider.GetExeFileName(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 325
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in C:\projects\lidarr\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 306

18-7-6 14:54:17.0|Info|SingleInstancePolicy|1 instance(s) of Lidarr are running
18-7-6 14:54:17.0|Warn|SingleInstancePolicy|Another instance of Lidarr is already running.
18-7-6 14:54:17.0|Info|BrowserService|Starting default browser. http://localhost:8686
18-7-6 14:54:17.0|Info|ProcessProvider|Opening URL [http://localhost:8686]
18-7-6 14:54:17.0|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running

**System info (please complete the following information):**
 - Lidarr Version:  .0.3.0.430
 - Operating System OS Name:                   Microsoft Windows Server 2016 Standard
                                 OS Version:                10.0.14393 N/A Build 14393
 - .net Framework Version: Microsoft .NET Framework, version 4.0.30319.42000

**Additional context**
A re-install was performed in an attempt to resolve the issue, as indicated in the logs.

**Comment by Qstick** [comment]
Try a browser other than IE
