### ISSUE TITLE
Folder Move Instead Of Just Files

### ISSUE THREAD

**Issue by TurboLancer** [Lidarr/Lidarr#4149]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No it is not.

### Describe the solution you'd like

When the download(s) is complete, instead of just moving the files inside the downloaded folder, lidarr will move the whole folder and not just files inside of the folder.

### Describe alternatives you've considered

After the download is complete, I have to move the album folders (not files) to where Lidarr moves them for my album location and the covers and albums names display correctly, This not ideal for me and leans me towards not using Lidarr because it is extra steps I have to take to make Plex display and play properly.

### Anything else?

When using Plex for Music, Plex does not show the correct album(s) because Lidarr only moved the files, not the folder, and leaves key files behind. For example Lidarr downloads the albums and combined the song files only from each album to one folder and it is just a list a songs from multiple albums; Therefore I see wrong albums names and covers.

**Comment by bakerboy448** [comment]
None of the Starrs move folders for imports; no plans.

the album songs / book files / movie / episode(s) are imported along with an extras the user specifies.  The latter _may_ may broken with lidarr still and would have an existing GHI.

Please use [Discord](http://lidarr.audio/discord) for support/questions.
