### ISSUE TITLE
Issue importing music on new installation

### ISSUE THREAD

**Issue by armsby** [lidarr/Lidarr#415]
**Describe the bug**
Lidarr says that Folder is not writable but it does create the Lidarr_write_test.txt in the folder

I have verified from the docker container that the user abc can create files and folders in /music
and the Lidarr_write_test.txt is created.
abc@54e57c61f741:/music$ ls -al Lidarr_write_test.txt
-rwxrwxrwx 1 abc abc 0 Jul  9 07:56 Lidarr_write_test.txt

the user abc does have write access

**Expected behavior**
music being imported

**Logs**

[Debug] Api: [GET] /api/v1/filesystem?path=%2Fmusic%2F: 200.OK (36 ms) 
[Warn] LidarrErrorPipeline: Invalid request Validation failed: 
 -- Folder is not writable by user abc 
[Debug] Api: [POST] /api/v1/rootFolder: 400.BadRequest (16 ms) 

**System info (please complete the following information):**
 - Lidarr Version: 0.3.0.430
 - Operating System docker

**Comment by Qstick** [comment]
Sounds like a permission issue, jump on discord and someone can likely help. There are also many forum and reddit posts for similar problems and resolutions in Sonarr
