### ISSUE TITLE
Additional Quality Profiles and Definitions for HiRes

### ISSUE THREAD

**Issue by 2goobers** [Lidarr/Lidarr#4153]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Lidarr's default quality profiles and definitions are not granular enough at the HiRes / Lossless definition quality levels.

There are over a dozen different definitions for low quality mp3's but only one for 16 bit flac and one for 24 bit flac when there is more to the quality of flac than the bit depth.

### Describe the solution you'd like

A new quality profile for HiRes music.

Additional / Expanded options for quality definitions for FLAC. Eg:
In lossless:
16FLAC44 = 16 bit / 44.1 khz
or standard FLAC

In HiRes:
24FLAC48 = 24 bit / 48 khz
24FLAC96 = 24 bit / 96 khz
24FLAC192 = 24 bit / 192 khz

These qualities are often specified in the Search Title.

And maybe an MQA for Master Quality Authenticated.

### Describe alternatives you've considered

I can add a custom quality profile for HiRes. But don't think I can add new quality definitions

### Anything else?

I think this feature request would also address the features / problems from #1146 and #2500.

**Comment by 2goobers** [comment]
Hi Res music although it has been around a while for mastering, etc did not really start getting more mainstream until recently with Apple, Amazon, and Tidal starting to release stuff in Hi Res. So it does depend on what music you listen to.

But here is my search for Tool - Fear Innoculum:

![image](https://github.com/Lidarr/Lidarr/assets/46365641/3ca2f0b8-422c-46f9-8ba4-b880923f47ef)

There are two 24/96s with only one being tagged as a 24 bit flac.
One is a standard flac.
And one says it is a 24/48 flac, although based on the file size, i think this is a lie.

I should add my reason for wanting this feature is that some audio equipment maxes out and wont play the higher res files. Eg, Sonos only plays up to 24/48 and Lidarr has downloaded 24/96 for me. These still play in other gear I have, but would be nice to be able to select.

**Comment by Qstick** [comment]
This is why we have custom formats, extending qualities further isn't planned
