### ISSUE TITLE
Directly adding an album break's lidarr's ability to find other albums by that artist.

### ISSUE THREAD

**Issue by BastionNtB** [Lidarr/Lidarr#4161]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When directly adding a new artist to Lidarr via adding one of their albums seems to break Lidarr's ability to find that artist's other albums. Regardless of metadata profiles and the like.

### Expected Behavior

When adding an album for an artist, I would expect it to add the artist in Lidarr properly like it does when adding the artist directly.

### Steps To Reproduce

1. Find an artist NOT currently in Lidarr.
2. Find an album from that artist.
3. Search to add that album directly.
4. Nagivate to artist/album in Lidarr.
5. Notice that album is the ONLY one to show under releases, regardless of what they've already released.
6. If you search and add another album, it will add it to the list, but none of the other ones will automatically be pulled in.
7. To fix, you must delete the artist entirely from Lidarr, and add the artist separately from the album, then you can monitor the album from the artist page.

### Environment

```markdown
- OS: Ubuntu Server 22.04
- Lidarr: 1.3.5.3530
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Edge Chromium
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs?

[lidarr.trace (1).txt](https://github.com/Lidarr/Lidarr/files/12741671/lidarr.trace.1.txt)
The attached log files was me replicating the steps above for Tremonti's Cauterize

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Closing - No other complaints nor recent complaints

If this is still occurring please provide updated trace logs, any updated details, and a more recent version
