### ISSUE TITLE
Beets integration for cover art and convert (docker)

### ISSUE THREAD

**Issue by DavidHenryThoreau** [Lidarr/Lidarr#4174]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Is that possible to add a metadata based on beets (from that page settings/metadata) I mean in order to re-encode lossless to ogg or mp3 and to fetch informations and add cover art to metadata 
In docker container the custom script is not possible

### Describe the solution you'd like

In the docker container add beets and ffmpeg and other dependencies needed to use all beets possibilities 

### Describe alternatives you've considered

If beets integration is not possible add an option that can :
- edit metadata
- cover
- convert audio format to another

### Anything else?

Nice stable software :

**Comment by luzpaz** [comment]
Anyone able to stepup to make this happen ?

**Comment by Qstick** [comment]
Custom script is still possible with docker. That's the best way to go here.

**Comment by DavidHenryThoreau** [comment]
Can you paste links for that scripts ? Cover art / add remove is possible with that scripts ?

**Comment by Qstick** [comment]
You have to make the script, or find someone else to do it. All I'm saying is that the custom script implementation is the best way to handle this.

**Comment by DavidHenryThoreau** [comment]
I've found but no cover art integration.
https://github.com/TheCaptain989/lidarr-flac2mp3

**Comment by DavidHenryThoreau** [comment]
I mean a front-end integration
