### ISSUE TITLE
Change App Data directory

### ISSUE THREAD

**Issue by tigertim08** [lidarr/Lidarr#418]
Hello all, 

I have Lidarr installed on a Qnap TVS-463. Can anyone please tell me how I can change the AppData directory /share/CACHEDEV1_DATA/.qpkg/Lidarr/lidarr/.config/Lidarr? 

I would like to remove the folder to /share/CACHEDEV1_DATA/.qpkg/Lidarr/

**Comment by Qstick** [comment]
Use discord for support questions
