### ISSUE TITLE
Lidarr Removing Albums from Plex

### ISSUE THREAD

**Issue by ghost** [Lidarr/Lidarr#4204]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When lidarr grabs a new album either as new or to upgrade an existing album. Once it’s downloaded and imports to Plex, all or some of the other albums from that same artist disappear in Plex apart from the one that just downloaded.

They are still in the file structure on my NAS, just not in Plex. I have to manually re scan my library and they come back again but Plex adds them as New again so it has to re analyse them for loudness, play counts disappear, and custom tagging I have to do again etc.

Any idea why this is happening?

This happens with any artist and not a specific one. It’s driving me nuts!

### Expected Behavior

Album imports without removing existing albums from that same artist in plex.

### Environment

```markdown
- OS: Ubuntu 20.04
- Lidarr: 1.3.5.3530
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge, Chrome, Safari
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

I've been through the logs and cant see anything in there that will assist in diagnosing this issue.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by rdavey228** [comment]
Not sure why this got closed. I never had this issue when manually importing albums before having Lidarr so this is a Lidarr issue.

I have the file rename feature switched on and Lidarr renames the files upon importing them.

As an example I have an artist AC/DC and already have 10 albums from them. Lidarr finds a better quality copy of the back in black album I already have and downloads it and imports the downloaded files upgrading the album from Mp3 to FLAC.

When I go into plex, a number other already existing albums from that are now missing from Plex after its just imported that new album. I have to manually run a library scan for them to show up again.

I dont see how thats a plex issue? Lidarr is doing something when interacting with plex thats causing those other albums to drop off that I have to re scan for them again to show up.
