### ISSUE TITLE
Reports or Database export

### ISSUE THREAD

**Issue by alagave** [lidarr/Lidarr#421]
With large media collections it is sometimes more useful to export data to a program which can be used to create catalogs or custom lists. Some examples of use would be to 1) find all tracks with name "x" to assist in creating playlists, 2) compare the orphan tracks one has collected with missing tracks in the database and 3) create an arbitrary catalog determined by a users criteria such as all tracks by any artists in the psychedelic genre in 1964.

The simple solution is to allow export of the database in CSV format, which can then be imported into the tool of choice by the user.

Reporting is not currently within the core functions of Radarr or Sonarr but are nonetheless a useful and desirable feature. Development cycles would be best used to implement an export capability.

Export every piece of info and just let the import function filter out what is not desired. A database dictionary will also be necessary for proper and correct interpretation of data fields.

**Comment by Qstick** [comment]
There are other tools that can do this given our simple db format, additional we have an api that can be pinged from any other program to get data.
