### ISSUE TITLE
Activity Queue

### ISSUE THREAD

**Issue by drakus72** [lidarr/Lidarr#422]
**Describe the bug**
When refreshing the queue, it does nothing but spin. Will not show or update the queue

**To Reproduce**
1. Go to 'Activiey'
2. Click on 'Queue'
3. Click 'Refresh'
4. I see no errors being reported in the log files

**Expected behavior**
The queue to show all current downloads

**Screenshots**
https://imgur.com/a/ucwLbWg (Arrow circle just keeps spinning with over 500 in queue

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.3.0.454
 - Operating System Win Sever 2016
 - .net Framework (Windows) most current

Letting Debug run a little while before posting debug log.

Edit: Took over 45 min for the queue to update and show what it has grabbed and downloaded.

**Comment by Qstick** [comment]
One thing to note, you are on a branch build for a feature not yet merged, may want to stick to develop builds

**Comment by Qstick** [comment]
Closing until more info is provided.
