### ISSUE TITLE
Unable to access interface from network

### ISSUE THREAD

**Issue by georgecarstoiu** [lidarr/Lidarr#424]
**Describe the bug**
Unable to connect to remote installation within same network

**To Reproduce**
1. Install app
2. Try accessing interface remotely from same network

**Expected behavior**
The interface is shown

**Comment by Qstick** [comment]
What platform is Lidarr running on? Windows? What version of Lidarr?

**Comment by georgecarstoiu** [comment]
Windows 10 - Lidarr 0.3.0.430 Beta

I have been having this issue ever since I started testing, but I thought it was because of the alpha stage.

Tried disabling firewall, but issue was still there.

**Comment by Qstick** [comment]
You need to run as admin once to allow Lidarr to register itself. If running from service make sure service user has admin privileges or stop run standalone as admin then restart service.
