### ISSUE TITLE
Manual import - Better overview what's wrong (especially missing tracks)

### ISSUE THREAD

**Issue by PeterCodar** [Lidarr/Lidarr#4267]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

After downloading an album and during manual import there is no obvious indicator what's wrong.
For example I see 19 x "worst track" with a white exclamation mark on a red circle.

But the main reason because the automatic import fails is a completly missing track.

![image](https://github.com/Lidarr/Lidarr/assets/18629146/a08c33a6-9778-41f9-b0c9-39b123d8f870)

### Describe the solution you'd like

I would like to see on top if there is a missing track.
In such a case I could delete the folder entirely (I don't collect incomplete releases).

### Describe alternatives you've considered

An option to discard incomplete releases?
If the same number of tracks is not available as specified in the selected album, discard/remove such a release.

### Anything else?

That's all.

**Comment by bakerboy448** [comment]
What's the error/hover say from activity? Not all expected tracks in release or something like that?

Manual import is only looking at what files are available so it may not exactly be feasible or make sense to add in dummy for things that don't exist.  This would likely need to get appetite upstream in sonarr (~season pack ≈ ~album)

**Comment by PeterCodar** [comment]
>What's the error/hover say from activity?

One or more albums expected in this release were not imported or missing

![image](https://github.com/Lidarr/Lidarr/assets/18629146/07b9136f-1b10-42c9-a4f3-e8f4454e05df)

**Comment by bakerboy448** [comment]
Identifiable by missing tracks in the hover over. Same as episodes in sonarr.
