### ISSUE TITLE
Release rejected - Better indication what exactly caused it

### ISSUE THREAD

**Issue by PeterCodar** [Lidarr/Lidarr#4271]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm not sure, maybe it is related to https://github.com/Lidarr/Lidarr/issues/2632

As you can see in this screenshot, a found possible album match has been rejected by two causes:
The size and my custom format.

This FR is about the size.
If the rejection is based on quality settings: Which quality exactly is causing this?
There is no obvious setting I can find for "maximum allowed 116,1 MB"?

![Lidarr - Release rejected](https://github.com/Lidarr/Lidarr/assets/18629146/1abf17dc-7ef9-46b7-8f42-d39e98c1be26)

### Describe the solution you'd like

Indicate that the setting - for example - "MP3-VBR-V2" with the current settings is causing the rejection.

You could show it as the same "MP3-VBR-V2" label. Just color the background red - for example.
![image](https://github.com/Lidarr/Lidarr/assets/18629146/96d09c0f-16df-4de0-b505-ee28a4f2f68a)

### Describe alternatives you've considered

Alternative solution:
Let the user disable the entire quality settings if an "Interactive Search" is used.

### Anything else?

Nothing else.

**Comment by bakerboy448** [comment]
The Quality sizes is based on the bitrate for the quality selected which is then multiplied by the run time as indicated in the UI

the quality is clearly displayed as well, so not sure what this ask is?

**Comment by PeterCodar** [comment]
@bakerboy448
If it "is clearly displayed":
Please tell me from the above screenshot which quality setting is causing the rejection and has to be modified?

**Comment by bakerboy448** [comment]
The reject hover over is blocking the quality of the album I believe, so it's not possible from your screenshot to say what quality the album is

Similarly your quality sizes cut off which quality

**Comment by PeterCodar** [comment]
🤦‍♂️ Of course, you are both right!

Without hovering over the exlamation mark, I can now also see it. 🧐
![image](https://github.com/Lidarr/Lidarr/assets/18629146/01e3af89-4763-4135-a52f-f01d2ec1395a)

I'm sorry!
