### ISSUE TITLE
Version 1.4.5.3639 shows sonar logo on header

### ISSUE THREAD

**Issue by pcolucch** [Lidarr/Lidarr#4274]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonar logo showing instead of lodarr

### Expected Behavior

Change to lidarr logo 

### Environment

```markdown
- OS: web gui
- Lidarr:1.4.5.3639
- Docker Install:no
- Using Reverse Proxy:cloudflare tunnel
- Browser:chrome
- Database:
```

### What branch are you running?

Master

### Trace Logs?

![Screenshot_20231103-133257_Chrome](https://github.com/Lidarr/Lidarr/assets/63805528/e22ea0cd-638f-4998-a16e-e0464afa2f38)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
not a lidarr issue;  tunnel or reverse proxy

Please use [Discord](http://lidarr.audio/discord) for support/questions.
