### ISSUE TITLE
Use Album Disambiguation/Type when searching and picking releases

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#432]
**Is your feature request related to a problem? Please describe.**
When multiple albums exist with the same name Lidarr may choose the wrong album (ex. Weezer)

**Describe the solution you'd like**
Use the disambiguation to prefer releases in order to attempt to pick the correct release. By prioritizing releases that contain the disambiguation we are not limiting ourselves to not grab a backup release if no release contains.

**Additional context**
Album disambiguation is already stored in DB and used in UI and naming.

**Comment by Qstick** [comment]
@gismo2004 since you have already been in these files, this maybe something easy to implement on the search side. I don’t know that we want to add the type to search string in all cases, but for single and live types it may make sense? Haven’t done a lot of testing on effects this would have.

**Comment by gismo2004** [comment]
Sounds good, I will check this. But don't expect to get it too fast. Time is very limited, and sine I'm completely new to all this stuff it might take some time to fully understand how to...

While we at it, are there plans to also search for discographys?

**Comment by Qstick** [comment]
We have some logic to parse and handle them when they come up in artist search and RSS feed though I haven’t done a lot of testing on them. I’ve seen some reports of them being grabbed and some reports of issues. Current logic only grabs if it sees all albums in discography are wanted.

It uses the years parsed from release title to determine what albums it believes are inside.
