### ISSUE TITLE
Lidarr cannot find / load new albums on MusicBrainz

### ISSUE THREAD

**Issue by iAmRenzo** [Lidarr/Lidarr#4371]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

From (at least) one artist, new album information isn't downloaded into lidarr.

### Expected Behavior

Get new album information when its available

### Steps To Reproduce

There are two new albums in 2023 (may) **https://beta.musicbrainz.org/artist/75ebdfa0-4a8a-496a-a57f-e4bb93b14d4c**
<img width="848" alt="Scherm­afbeelding 2023-12-16 om 11 15 38" src="https://github.com/Lidarr/Lidarr/assets/1183790/5cc909b3-ebd8-4988-97b9-e55c35a68fc4">
No in Lidarr. Settings for albums are good, album should be there.

Adding the album by search or lidarr:albumID doesn't work either.

### Environment

```markdown
- OS: Synology NAS
- Lidarr: 2.0.7.3849
- Docker Install: Yes
- Using Reverse Proxy: -
- Browser: Safari Mac
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

[lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/13692208/lidarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/en/lidarr/faq#why-can-i-not-add-a-new-release-or-artist-to-lidarr

**Comment by iAmRenzo** [comment]
@bakerboy448 It is not an other album, its a regular album.

Why is it not a bug but a 'support request'?

**Comment by bakerboy448** [comment]
Please use [Discord](http://lidarr.audio/discord) for support/questions.

GitHub is not for support.
The FAQ link provided that it appears was ignored explains why releases would not be appearing in lidarr
