### ISSUE TITLE
Still having issues with Artist poster / banner...

### ISSUE THREAD

**Issue by MrMxyzptlk** [lidarr/Lidarr#439]
Latest beta, no errors...

Some of my artists no matter how many times I delete and add...never get a poster or banner.
For instance: Bread, Blind Faith, Cat Stevens, Credence Clearwater Revival...and many more.

LOVE your app so far, keep up the great work!

**Comment by majora2007** [comment]
Are you sure the data exists in MusicBrainz?

**Comment by Qstick** [comment]
looking at CCR. Our api returns images and they show up fine in Lidarr. 
https://api.lidarr.audio/api/v0.3/artist/109958eb-a335-4c5e-907e-597ff4c6af46

Looking at Cat Stevens, there are two artists in musicbrainz “Cat Stevens” and “Yusuf Islam”, fanart.tv has all the images under the Yusuf Islam musicbrainz Id. Add that to Lidarr and you’ll get images.

Blind Faith has no images on fanart.tv except logos, add some images to fanart.tv and they will show in Lidarr.

Bread is same as Blind Faith, add some artist thumb and banner images to fanart.tv and they will show in Lidarr

**Comment by Qstick** [comment]
Cat Stevens is fixed on fanart.tv now

**Comment by MrMxyzptlk** [comment]
Thank you!
