### ISSUE TITLE
Ability to change album title name

### ISSUE THREAD

**Issue by leaderdog** [Lidarr/Lidarr#440]
Hi,

I would like to be able to change the name of the Album Title. Example:

We all know and love White Zombie - Astro-Creep 2000
That's all anyone ever called the album title. but Lidarr assumes the full title:
White Zombie - (1995) - Astro‐Creep- 2000- Songs of Love, Destruction and Other Synthetic Delusions of the Electric Head
I recall seeing those words on the cover, but no one in their right mind called the album by that.

So the problem now is when I format my songs with 
Band Name - Album - Number - Song Title.flac
we wind up with well... nothing, Lidarr won't rename it.

Just for smiles and farts, here's what the file name would look like if it was possible to even do it, which is way too long of a file name:
`White Zombie - Astro‐Creep- 2000- Songs of Love, Destruction and Other Synthetic Delusions of the Electric Head - 11 - Blood, Milk and Sky, Where the Sidewalk Ends, the Bug Parade Begins.flac`

When I tell Lidarr to rename it to this it won't do it.  It creates the folder, but fails to move the file.

The Rob Zombie name titles are just as ridiculous:
`Hellbilly Deluxe: 13 Tales of Cadaverous Cavorting Inside the Spookshow International`
&
`Hellbilly Deluxe 2: Noble Jackals, Penny Dreadfuls and the Systematic Dehumanization of Cool`

again, no one calls it that, it's just Hellbilly Deluxe.  I didn't rename these, or if I tried it failed.

Here's what the log has in it:
`18-8-5 09:13:37.8|Error|DiskTransferService|Failed to properly rollback the file move [H:\_mp3\White Zombie\White Zombie - (1995) - Astro-Creep 2000 Songs of Love, Destruction and Other Synthetic Delusions of the Electric Head\04. Creature of The Wheel.flac] to [H:\_mp3\White Zombie\White Zombie - (1995) - Astro-Creep- 2000- Songs of Love, Destruction and Other Synthetic Delusions of the Electric Head\White Zombie - Astro-Creep- 2000- Songs of Love, Destruction and Other Synthetic Delusions of the Electric Head - 04 - Creature of the Wheel.flac], incomplete file may be left in target path.`

Thanks.

[AB#444](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/444)

**Comment by Qstick** [comment]
For now, not going to implement. Try Readarr
