### ISSUE TITLE
Unkown artist - no download possible at all

### ISSUE THREAD

**Issue by bendschs** [lidarr/Lidarr#441]
I think Lidarr is missing out on big potential because of its stubborn behavior when found releases don't match the exact name of the artist (even if the release is shown under the artists ablum section). For instance: if two artists are working together or an artist has solo and band releases lidarr will ignore good torrents. At leaset in manual search you should be able to hit the download button, but it does not even show up.

I think i am not the only one complaining about this.

cheers
bendsch

**Comment by phunkysai** [comment]
Seconded...here is a screenshot where Lidarr won't let me manually download the mp3 version of an album for this reason (this is happening on multiple artists/albums). If it comes up in the manual search, I should be able to manually download it...

![lidarr_noarrow](https://user-images.githubusercontent.com/250881/46081705-2a4ab280-c16b-11e8-88f8-7d274717e7fe.png)

**Comment by Yonn-Trimoreau** [comment]
@Qstick can you please reference the corresponding commit?

**Comment by RevenantOne** [comment]
I'm also getting this issue with 0.4.0.549 installed for several artists.

https://imgur.com/a/CvfkEj7

**Comment by YodaSpow** [comment]
Have same Glitch:
https://i.imgur.com/lUiFfOy.png
