### ISSUE TITLE
Add option to move Unmapped Files to another directory

### ISSUE THREAD

**Issue by PearsonFlyer** [Lidarr/Lidarr#4410]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, the only options for Unmapped Files is to delete them or map them. Many users have asked if there's a way to move these Unmapped Files out to another folder outside of the root folder as a 3rd alternative.

### Describe the solution you'd like

In Unmapped Files, either on an individual file or when multi-selected, ideally there would be an additional option to move files. When moving files, a directory selector box should pop up like when selecting a root folder. This should allow selection of any directory that Lidarr can access, to allow users to move things outside of the current Lidarr root folder(s).

### Describe alternatives you've considered

The only current alternative is to script this process manually.

### Anything else?

I'm happy to mock up screens if needed, but I think what I'm describing seems pretty clear.

**Comment by hardKOrr** [comment]
A great start / alternative would be to expose the unmapped files in the api.  This would allow for easier scripting around it in the meantime.  This also would alleviate Lidarr of the 'duty' of removing files its explicitly not managing.

**Comment by Qstick** [comment]
> A great start / alternative would be to expose the unmapped files in the api.  This would allow for easier scripting around it in the meantime.  This also would alleviate Lidarr of the 'duty' of removing files its explicitly not managing.
> 

Anything shown in the UI comes from the API

**Comment by Qstick** [comment]
Dupe #2161
