### ISSUE TITLE
Imported download misses some files and reports "Audio File Detected"...

### ISSUE THREAD

**Issue by benzo8** [lidarr/Lidarr#442]
**Describe the bug**
Downloading an album via NZBGet, Lidarr imports all but one or two files and shows

> 18-8-7 22:34:57.9|Warn|DownloadedTracksImportService|Audio file detected: [/storage/temp/music/Air - Love 2 (2009) FLAC/Air - Love 2 - 11 - You Can Tell.flac]

That track is then not imported/moved/renamed - it just stays in the downloads folder.

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System: Ubuntu 16.04 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 4.80

**Comment by Qstick** [comment]
This usually means Lidarr had trouble identifying that track. Can you give debug or trace logs so we can see what Lidarr doesn’t like?

**Comment by ta264** [comment]
This should be fixed in #592 - it'll at least prompt you to do a manual import.
