### ISSUE TITLE
Slow loading - is this normal?

### ISSUE THREAD

**Issue by mechanimal82** [lidarr/Lidarr#445]
I've tried looking, but seems not mentioned anywhere... basically I'm wondering if there's an issue with my setup or if it's normal for Lidarr to take several minutes to load the webpage? I've noticed on a fresh reboot of my system when accessing Lidarr I can have the site up in around 30 seconds... but after some time it can take anywhere up-to 5 minutes to load... is this normal? I don't have the same issue with Sonarr or Radarr.

My system is a dedicated remote server with 16GB RAM, i7 and running on SSD.

Thanks

**Comment by Qstick** [comment]
No, are there any js errors or log errors

**Comment by Qstick** [comment]
Use discord for support
