### ISSUE TITLE
Lidarr detected as security threat by windows defender (detplock)

### ISSUE THREAD

**Issue by baywet** [lidarr/Lidarr#446]
**To Reproduce**
Windows 10 Pro N x64, current build (public ring), all updates installed
Installed latest updates, ran a windows defender security center scan.

**Expected behavior**
Lidaar not to be detected as a security threat.

**Logs**
startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Lidarr\Lidarr.lnk
file: C:\ProgramData\Lidarr\bin\Lidarr.exe
file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Lidarr\Lidarr.lnk
file: C:\Users\Public\Desktop\Lidarr.lnk
uninstall: HKLM\SOFTWARE\Wow6432Node\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\{56C1065D-3523-4025-B76D-6F73F67F7F93}_is1
regkey: HKLM\SOFTWARE\Wow6432Node\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\{56C1065D-3523-4025-B76D-6F73F67F7F93}_is1

**System info (please complete the following information):**
 - Lidarr Version: [0.3.1.471]
 - Operating System [windows 10 N x64 pro, current public build]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
Not sure whether this is a false positive, or something else tried to hide itself in Lidarr's stuff, or Lidarr's repository has been compromised. If the later I wanted to report it because it could be quite serious.

**Comment by bboyles303** [comment]
Happening here too with latest Defender updates.

**Comment by Qstick** [comment]
Repo isn't compromised, build hash matches our build server. It's a false positive, feel free to bump to a newer installer until we get it resolved if you feel better. Or just use the ZIP
