### ISSUE TITLE
Turning Torrents & Usenet On and Off

### ISSUE THREAD

**Issue by mccorkled** [Lidarr/Lidarr#448]
It would be great if there was an option under 'download clients' to turn off torrents or usenet completely. I frequently disable one or the other of my clients but this does not stop searching all of my indexers which can jam up my api calls. It is a pain to have to go through and disable 15+ indexers when a single switch could disable indexers and client at once.

Thank you

[AB#441](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/441)

**Comment by YipYup** [comment]
Install NZBHydra2, and then configure Lidarr to point only at your NZBHydra2 installation. Configure all your torrent and usenet indexers there. Then you can easily go into NZBHydra and quickly toggle on or off Torrents, Usenet, or Both.
