### ISSUE TITLE
Ultimate Indexer Release Parsing Issue

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#449]
Post any and all Indexer release parsing issues here (releases that Lidarr doesn’t automatically grab), will add to list and mark off as complete. 

- [ ] Metallica - ...And Justice for All (1988) [FLAC Lossless]
- [ ] Adventure_Clue-Red_-_Blue-WEB-2016-AZF
- [ ] Deadmau5 - while(1<2) [Explicit]
- [ ] Deadmau5-While 1 is Less Than 2-Deluxe Edition-2CD-FLAC-2014-PERFECT
- [ ] Gorillaz - The Now Now 2018 (flac mp3)
- [x] Gorillaz - The now now - 2018 [FLAC]
- [ ] Imagine Dragons - Origins (2018) MP3
- [ ] Imagine Dragons - Origins (Deluxe) (2018) MP3

This is not an issue for track or file parsing issues

**Comment by HamilcarH** [comment]
Lidarr is unable to parse track due to lack of track number, however MusicBrainz picard shows a track number.

<img width="363" alt="file" src="https://user-images.githubusercontent.com/11900737/43992409-49ed4fa0-9d7e-11e8-9010-c1e1e147778e.png">
<img width="606" alt="lidarr" src="https://user-images.githubusercontent.com/11900737/43992410-4a0664cc-9d7e-11e8-8830-42428a0924e1.png">
<img width="425" alt="picard" src="https://user-images.githubusercontent.com/11900737/43992411-4a24d3b2-9d7e-11e8-9c09-62e00ea75d94.png">

I hope there is enough detail !

**Comment by alculete** [comment]
same problem 
![image](https://user-images.githubusercontent.com/2129497/44081597-63d34b1c-9faf-11e8-9d79-e0891fb98962.png)

noticed that it happens only if there is only one file since are not numbered

**Comment by francesco2013** [comment]
01 - Break On Through (To The Other Side).flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:01 Break On Through (To The Other Side): FLAC 24bit v1
02 - Soul Kitchen.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:02 Soul Kitchen: FLAC 24bit v1
03 - The Crystal Ship.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:03 Soul Kitchen: FLAC 24bit v1
04 - Twentieth Century Fox.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:04 Twentieth Century Fox: FLAC 24bit v1
05 - Alabama Song (Whisky Bar).flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:05 Alabama Song (Whisky Bar): FLAC 24bit v1
06 - Light My Fire.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:06 Light My Fire: FLAC 24bit v1
07 - Back Door Man.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:07 Back Door Man: FLAC 24bit v1
08 - I Looked At You.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:08 I Looked At You: FLAC 24bit v1
09 - End Of The Night.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:09 End Of The Night: FLAC 24bit v1
10 - Take It As It Comes.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:10 Take It As It Comes: FLAC 24bit v1
11 - The End.flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:11 The End: FLAC 24bit v1
12 - Moonlight Drive (Version 1).flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:1214 Moonlight Drive (Version 1): FLAC 24bit v1
13 - Moonlight Drive (Version 2).flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:13 Moonlight Drive (Version 2): FLAC 24bit v1
14 - Indian Summer [8 19 66 Vocal].flac
Couldn't parse album from: The Doors - The Doors (Expanded) [40th Anniversary Mixes] - 1:14 Indian Summer [8 19 66 Vocal]: FLAC 24bit v1

And many many more ...

**Comment by francesco2013** [comment]
@HamilcarH still I dont really have it very clear why the parser needs a track number when the name of the track could be simply matched with a regex to any db online ...

**Comment by Qstick** [comment]
@francesco2013 problem with those is the album name is `20th Century Masters: The Millennium Collection: The Best of Jerry Lee Lewis` in musicbrainz and `The Best of Jerry Lee Lewis: 20th Century Masters The Millennium Collection` in your tags

**Comment by francesco2013** [comment]
1 - Nine To The Universe.mp3
Couldn't parse track from: Jimi Hendrix - Nine To The Universe - 1:06 Nine To The Universe : MP3-320 v1
2 - Jimi-Jimmy Jam.mp3
Couldn't parse track from: Jimi Hendrix - Nine To The Universe - 1:07 Jimi/Jimmy Jam: MP3-320 v1
3 - Young-Hendrix.mp3
Couldn't parse track from: Jimi Hendrix - Nine To The Universe - 1:08 Young/Hendrix : MP3-320 v1
4 - Easy Blues.mp3
Couldn't parse track from: Jimi Hendrix - Nine To The Universe - 1:09 Easy Blues : MP3-320 v1
5 - Drone Blues.mp3
Couldn't parse track from: Jimi Hendrix - Nine To The Universe - 1:10 Drone Blues: MP3-320 v1

**Comment by francesco2013** [comment]
@Qstick regarding your answer is the algorithm not being able to match the content even if it is reversed ? I mean 20th Century Masters: The Millennium Collection: The Best of Jerry Lee Lewis is almost the reverse of The Best of Jerry Lee Lewis: 20th Century Masters The Millennium Collection. Is it only accepting perfect matches ?

**Comment by Qstick** [comment]
Currently it’s pretty much exact match, we are currently working on parsing heavy, from release searching and select to track parsing

**Comment by KrunchMuffin** [comment]
Pink.Floyd-The.Dark.Side.Of.The.Moon-Experience.Edition-2CD

> 101-pink_floyd-speak_to_me.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:01 Speak To Me: FLAC v1
102-pink_floyd-breathe_(in_the_air).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:02 Breathe (In The Air): FLAC v1
103-pink_floyd-on_the_run.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:03 On The Run: FLAC v1
104-pink_floyd-time.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:04 Time: FLAC v1
105-pink_floyd-the_great_gig_in_the_sky.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:05 The Great Gig In The Sky: FLAC v1
106-pink_floyd-money.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:06 Money: FLAC v1
107-pink_floyd-us_and_them.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:07 Us And Them: FLAC v1
108-pink_floyd-any_colour_you_like.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:08 Any Colour You Like: FLAC v1
109-pink_floyd-brain_damage.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:09 Brain Damage: FLAC v1
110-pink_floyd-eclipse.flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:10 Eclipse: FLAC v1
201-pink_floyd-speak_to_me_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:01 Speak To Me (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
202-pink_floyd-breathe_(in_the_air)_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:02 Breathe (In The Air) (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
203-pink_floyd-on_the_run_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:03 On The Run (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
204-pink_floyd-time_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:04 Time (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
205-pink_floyd-the_great_gig_in_the_sky_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:05 The Great Gig In The Sky (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
206-pink_floyd-money_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:06 Money (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
207-pink_floyd-us_and_them_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:07 Us And Them (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
208-pink_floyd-any_colour_you_like_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:08 Any Colour You Like (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
209-pink_floyd-brain_damage_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:09 Brain Damage (Live At The Empire Pool, Wembley, London, 1974): FLAC v1
210-pink_floyd-eclipse_(live_at_the_empire_pool_wembley_london_1974).flac
Couldn't parse album from: Pink Floyd - The Dark Side Of The Moon (Experience Edition) - 1:10 Eclipse (Live At The Empire Pool, Wembley, London, 1974): FLAC v1

**Comment by Qstick** [comment]
Closing this, post individual cases if you have them
