### ISSUE TITLE
Lidarr uses download path on deluge, not "move completed to" path

### ISSUE THREAD

**Issue by ACiDGRiM** [Lidarr/Lidarr#451]
When handling completed downloades with Deluge, lidarr is searching the original path of the torrent, not the new path when moved to the completed folder.

```
18-8-15 08:14:25.9|Warn|ImportApprovedTracks|Couldn't import track /mnt/content/Downloads/incomplete/torrent/Kanye West-The Life Of Pablo-CD-2016-FLAC/01 - Ultralight Beam feat. Chance The Rapper & Kirk Franklin.flac

[v0.3.1.471] System.UnauthorizedAccessException: Access to the path "/mnt/content/Music/Kanye West/The Life of Pablo (2016)" is denied.
```

[AB#445](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/445)

**Comment by Qstick** [comment]
This looks like an issue of deluge communicating it’s done before the torrent is actually moved. Please upload trace logs and required bug report info

**Comment by D4rkSl4ve** [comment]
AcidGrim:  is it moving some of the songs, and then just drop the connection between the two and delete the rest of the songs?   MIne is able to move 5-7 songs, then <poof> from songs 6< get deleted magically.  I have to re-download, pause it, not allow Lidarr to move or anything, do it manually, import into Lidarr for renaming and parsing...

**Comment by bakerboy448** [comment]
Pretty sure this would have been fixed by now and no information required for bug reports was provided.
 if it is still occuring in v1, can reopen w/ the proper bug report information
