### ISSUE TITLE
Artist Folder Name ignored when reorganizing/renaming files

### ISSUE THREAD

**Issue by Ltty** [Lidarr/Lidarr#4517]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Artist Folder Format: {Artist NameFirstCharacter}/{Artist CleanName}
Root Folder: /Music/

When renaming/reorganizing music, music is placed in /music/Artist Name/

### Expected Behavior

Artist Folder Format: {Artist NameFirstCharacter}/{Artist CleanName}
Root Folder: /Music/

When renaming/reorganizing music, music should be placed in /music/A/Artist Name/

### Steps To Reproduce

2. Go to Library
3. Select Artists
4. Select All
5. Rename Files
6. Organize

### Environment

```markdown
- OS: Ubuntu 20.04
- Lidarr: 2.0.7.3849
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs?

[lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/14068593/lidarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Folder renaming needs to be folder move/rename not organize (file rename), no?  Someone should update the lidarr faq for how to rename folders.

**Comment by Ltty** [comment]
Functionality that has been working before as defined in the documentation does not work anymore after an update, that's the definition of a bug.

The Artist Folder Format, in particular {Artist NameFirstCharacter}/{Artist CleanName} is simply ignored. {Artist NameFirstCharacter} is not used moving files despite being set correctly. 

This has been working for the past months just fine... 😉

It's not a support question, I know how to set up Lidarrr...

Thanks 😉

**Comment by bakerboy448** [comment]
Organize/rename would likely not rename folders like you've indicated.

folders created during import have nothing to do with a rename/organize and are two completely different processes

**Comment by Ltty** [comment]
Thanks, this indeed solved the issue. What I do not understand though is why reorganizing the files moves the folders out of the structure. In any case, thanks for the help.

**Comment by Ltty** [comment]
My library was organized in "music/A/Artist Name" accordingly.

I had some media that wasn't associated automatically and I had to manually map them to the albums.

In the past, when I manually mapped files, they were then moved to the correct folders and renamed according to the file name settings. This didn't work in this case. The files were mapped correctly, but not moved to the correct folders or renamed. 

So I went over and tried a bulk rename. What happened then is that all my music that was in "music/A/Artist Name" was moved to "music/Artist Name".

Only setting the root folder as you described above fixed the issue. So I did not expect that renaming the files would make a change to my folder structure.

Best

**Comment by primalcurve** [comment]
This is a classic case of seeing a workaround as a fix, and then mentally moving the "fix" into "this is how it's done."

This """""solution""""" ignores the fact that newly added music **also** ignores the `Artist Folder Format`. Unlike with Sonarr and Radarr where its equivalent is functional (`Series Folder Format` and `Movie Folder Format` respectively), the `Artist Folder Format` is permanently stuck at its default and ignores user input. This is a bug. The behavior of devs in this thread is embarrassing.

I fully expect the replies to be blaming me for user error, but I'll be impressed if someone looks past the nose on their face and actually reads what we're talking about instead.
