### ISSUE TITLE
Lookup Album returns missing properties when Album is in the lidarr database

### ISSUE THREAD

**Issue by tidusjar** [lidarr/Lidarr#457]
**Is your feature request related to a problem? Please describe.**
It seems that when calling the lookup for an album e.g. `api/v1/album/lookup?term=trench` and the album `Trench` by `Twenty One Pilots` is monitored in Lidarr we are missing quite alot of information e.g. the whole artist property, the whole images property.

If I lookup for an album that is not in Lidarr e.g. `Iowa` by `Slipknot` then I get these properties.

**Describe the solution you'd like**
It would be nice if the json respose didn't change dramastically if it's in the libaray or not

**Describe alternatives you've considered**
and alternative would be to include the artist name and foreign id and the images property when it's already in lidarr.

**Additional context**
This is for Ombi, and for the search result, when it's already in Lidarr then I need to do a further 2 calls to get the artist information and the images. This would slow the search down.

**Comment by tidusjar** [comment]
Thanks! What about the images?

**Comment by Qstick** [comment]
Thought they were already in there when I was testing, I'll go back and double check
