### ISSUE TITLE
Artist pictures local filesystem

### ISSUE THREAD

**Issue by ronajon** [Lidarr/Lidarr#4571]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Artist pictures are now being taken from fanart.tv.
i've submitted several artist pictures, but they get rejected all the time. 

### Describe the solution you'd like

next to taking pictures from fanart.tv it would be a nice feature to be able to upload or assign artist pictures from a local filesystem.
This could be done by uploading, but also specifying a folder where the artist pictures are stored. 

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by bakerboy448** [comment]
No plans to allow local lidarr metadata
