### ISSUE TITLE
Can't manually import files

### ISSUE THREAD

**Issue by BinsonBuzz** [lidarr/Lidarr#458]
**Describe the bug**
I'm trying to manually import files but everytime it fails. I've tried breaking into smaller chunks but no luck and get the error message

**To Reproduce**
1. Go to 'wanted' click on manual import, select network folder then interactive import.
2. get error "Unable to load manual import items"

https://pastebin.com/jpgELR2J
https://paste.ee/p/Oxd0B

 - Lidarr Version: 0.3.1.471
 - Operating System unraid linuxserver docker

**Comment by BinsonBuzz** [comment]
I've managed to fix this

**Comment by 0x0f906** [comment]
> I've managed to fix this

But decided not to share with the internet.

**Comment by jbridgma** [comment]
I'm encountering the same error, it would be good to know what the resolution was here.
