### ISSUE TITLE
Issues Installing Lidarr

### ISSUE THREAD

**Issue by zeieri** [lidarr/Lidarr#460]
I installed Lidarr using the same method used for Sonarr/Radarr (also outlined in the wiki).

When I execute the starting command:

/usr/bin/mono /opt/Lidarr/Lidarr.exe -nobrowser

I get the following error:

Cannot open assembly '/opt/Lidarr/Lidarr.exe': No such file or directory.

I check the directory and as the command states, Lidarr.exe is missing. Am I missing a step here? Is the EXE not in the Lidarr.git to clone? I also downloaded the lidarr-develop.zip, extracted it and checked, no Lidarr.exe.

Thanks!

**Comment by Qstick** [comment]
What version, package did you download?

**Comment by zeieri** [comment]
I used the following:

https://github.com/lidarr/Lidarr.git

Is there a way for me to check the package? Or should I be downloading from the dev branch itself?

**Comment by Qstick** [comment]
If you are running from source you have to build it and compile it. Just download the built package from release page
