### ISSUE TITLE
Multi database support?

### ISSUE THREAD

**Issue by ned-kelly** [lidarr/Lidarr#461]
Any chance we can get support for a database (and perhaps overall architecture) other than sqlite in the short term? - I'm currently looking at trying to drop [SQLrelay](http://sqlrelay.sourceforge.net/) into the solution as a short term fix...

Long story short - I've got over 1TB of audio files, and well over 100,000 artists in my system and it's just a bit too much for poor Lidarr to take (even on a beefy dual-cpu box with the docker container running on SSD backed storage)...

For now I'm looking at trying to move the main `lidarr.db` it onto a ramdisk, and then back it up every few minutes (since it probably won't ever be bigger then several hundred MB or a GB) but i've got serious performance issues when trying to do anything against Lidarr and/or the API.

To give you an idea - a standard query such as: `http://<server-ip>:8686/api/v1/artist` returns roughly a 6MB json response.

Keen for feedback (other than delete some artists)

**Comment by Qstick** [comment]
Given native SQLite is 4 to 8 times faster than sqlrelay (per benchmark tests on SQLRelay site), what do you expect to gain from SQLRelay?

Also 100,000 artists, holy s$*@. We could really use your db for some benchmark testing :) to make speed improvements all around. I'm sure a artist refresh is painful.

Would love the help.

**Comment by ned-kelly** [comment]
Let me see what I can send you - I've actually just resorted to writing bash scripts to interact with Lidarr (tasks like refreshing the filesystem etc are just too slow) and not the GUI - Each json request takes minutes to respond when clicking around the UI (And for now I'm just running the database and the shm and wal files on a ramdisk)

I think my last.fm adder didn't help the situation 👼 - However if you want to benchmark it's one way to get a load of trending artists and tracks into the system pretty quickly - https://github.com/ultimate-pms/ultimate-media-server-core/tree/master/scripts/lidarr

**Comment by ned-kelly** [comment]
@Qstick - Can I send you my database file to play with? (Privately - I'd rather not post on the web - so perhaps send me a PM with your email) I'm just seeing too many locked errors now:

```
[Error] TaskExtensions: Task Error
System.Data.SQLite.SQLiteException (0x80004005): database is locked
```

And querying Lidarr via API is taking several minutes to just return all artists (via: `/api/v1/artist`).

On a side note, the system works fine with other SQLite setups I have so perhaps some changes with the Inner workings of Lidarr need to occur (I'm using mainly Beets for my other SQLite database - which has several hundred thousand records in it and still performs really fast - To the point I actually have multiple processes accessing Beets via CLI, and I've only ever seen one "locked" error with 3 processes constantly reading/writing from the same DB file).

As it stands: Currently going to blow away my Lidar database - import all my music first, then start a fresh - It's just become unusable.

**Comment by Qstick** [comment]
Sure thing!

**Comment by ned-kelly** [comment]
Just emailed you

**Comment by Qstick** [comment]
Closing this for now for cleanup, still have your db and am testing with it
