### ISSUE TITLE
File on disk not detected

### ISSUE THREAD

**Issue by goose-ws** [lidarr/Lidarr#462]
Lidarr is not detecting a single track on an album, even though it is present and readable on the disk.

**Screenshots**
![capture](https://user-images.githubusercontent.com/874014/44721050-b13a3b80-aa96-11e8-9edf-2e8760b05661.PNG)
![capture](https://user-images.githubusercontent.com/874014/44721098-cc0cb000-aa96-11e8-9494-fb522016efb2.PNG)

**Logs**
Trunctuated log:
[log.txt](https://github.com/lidarr/Lidarr/files/2327852/log.txt)

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System: Debian Stable
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.14.0.177

**Additional context**
I tried deleted and re-grabbing the album, without success.

**Comment by Qstick** [comment]
Likely a tag mismatch

**Comment by goose-ws** [comment]
How do I check and/or correct a tag mismatch?

**Comment by Qstick** [comment]
Ensure the tags for that song match the track title exactly how it is in Lidarr. Or just manually import it.

**Comment by goose-ws** [comment]
I can't import, I get the message that all tracks have already been imported.

How can I check the tags to ensure a match?
