### ISSUE TITLE
How to improve matching

### ISSUE THREAD

**Issue by goose-ws** [lidarr/Lidarr#463]
Is there a way I can improve matching for tracks/albums? Most of my stuff ends up being "Couldn't parse album from:" with files that are reasonably named. Screenshot attached.

**Screenshots**
![capture](https://user-images.githubusercontent.com/874014/44737154-333e5a80-aabf-11e8-8dd5-8f98378e8eff.PNG)

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
- Operating System: Debian Stable
- .net Framework (Windows) or mono (macOS/Linux) Version: 5.14.0.177

**Comment by Qstick** [comment]
Tag mismatch, we are working on improvements and this is a duplicate

**Comment by goose-ws** [comment]
Got it. Is there a way I could contribute (Other than coding, which I'm not very good at) to help?

Perhaps in the mean time I could suggest a button to "Match tracks" next to the "Select Album" button, which would chronologically match the tracks for the number of tracks in the grab? That way the user wouldn't have to manually go down the list and match the first item to track one, the second to track two, etc.
