### ISSUE TITLE
Auto import is still an issue.

### ISSUE THREAD

**Issue by Haywood78** [lidarr/Lidarr#465]
When Lidarr begins the import on some albums. EX. Def Leppard album: Rock of Ages: The Definitive Collection. 
It only imports 16/17 tracks of the first disc.

Any two disc album that is grabbed, Lidarr never imports the second disc. 

Am I missing something? Or is this an actual bug? I have tried several different settings/combinations no resolve. 

Log error below. 

18-8-28 18:34:08.9|Info|NzbSearchService|Searching 6 indexers for [Def Leppard - Rock of Ages: The Definitive Collection (2005)]
18-8-28 18:34:13.4|Info|DownloadDecisionMaker|Processing 9 releases
18-8-28 18:34:14.2|Info|Nzbget|Adding report [Def.Leppard-Rock.of.Ages.the.Definitive.Collection-2CD-Retail-2005-Recycled.INT] to the queue.
18-8-28 18:34:14.6|Info|DownloadService|Report sent to GET. Def.Leppard-Rock.of.Ages.the.Definitive.Collection-2CD-Retail-2005-Recycled.INT
18-8-28 18:34:14.6|Info|AlbumSearchService|Album search completed. 1 reports downloaded.
18-8-28 18:35:41.7|Warn|DownloadedTracksImportService|Audio file detected: [C:\ProgramData\NZBGet\complete\Def.Leppard-Rock.of.Ages.the.Definitive.Collection-2CD-Retail-2005-Recycled.INT\104-def_leppard-lets_get_rocked-rec.mp3]
18-8-28 18:43:08.8|Info|RssSyncService|Starting RSS Sync
18-8-28 18:43:09.4|Error|GlobalExceptionHandlers|Task Error

[v0.3.1.493] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.HttpListenerException: An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<CloseNetworkConnectionAsync>d__50.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<CloseNetworkConnectionAsync>d__50.MoveNext()<---

After reading debug logs. I'm going to rebuild Lidarr server from scratch.

**Comment by Qstick** [comment]
Currently the only way Lidarr identifies the tracks are from the second disc is using the `discnumber` tag. If this is not set then Lidarr fails. We are working on making this more streamlined.

**Comment by Qstick** [comment]
Fixed by e260a29b5725837ebece957a0e204ddf7d1a7de3
