### ISSUE TITLE
Soundtracks as a first-class object

### ISSUE THREAD

**Issue by GaroRobe** [lidarr/Lidarr#467]
**Why bother?**
The issue is, first and foremost, that there is no proper way to find/track/download OSTs for movies, games or anime. And I already have quite a collection. It gets even worse when I'm trying to plunge it into Plex. So, 1) find and download, 2) integrate into Emby/Plex/whatever.

**My take on automatized solution**
Since the central issue is that soundtracks are, basically, a music collections and "fall apart" when you try to bind them to Artist, I propose to categorize them differently in terms of Lidarr entities:

1. Instead of [Artist] use [Product] (such as "Cowboy Bebop", "Silent Hill 3" or "The Dark Knight")
2. [Album] - same as in case with any other music
3. [Track] - override with "[Artist] - [Track]" (would be nice to overwrite tags for library!)

I'm not yet familiar with the code, but I expect something like a inherited "Soundtrack" from "Artist". That's a thing subject to research.

Also, I briefly searched for data sources I could use for metadata.

https://vgmdb.net - looks very promising for anime and games. I tried few queries and am greatly satisfied with it
http://www.soundtrackinfo.com/ - should do the trick for movies

**Alternatives?**
Picard or Mp3Tag helps a great deal, but fall short on streamlining the process part.

**Comment by ta264** [comment]
This will be covered by #844 (they'll show up as various artists)
