### ISSUE TITLE
Allow to List Albums alphabetically. 

### ISSUE THREAD

**Issue by neuman1812** [lidarr/Lidarr#468]
**Is your feature request related to a problem? Please describe.**

When importing songs manually with an artist that has an extensive librabry,  finding the album can sometimes be an issue.  

**Describe the solution you'd like**

Allow under the manual import option,  when selecting Album,  Allow column to be sorted alphabetically.

**Additional context**

This screen https://i.imgur.com/aCKqhKH.png

**Comment by danielunderwood** [comment]
Sorting by name and other fields and album search on manual import was added in #437 and should be available on nightly builds. This will be in the next release we make.
