### ISSUE TITLE
Ignoring port on URL when adding new indexer

### ISSUE THREAD

**Issue by fewyn** [lidarr/Lidarr#470]
**Describe the bug**
When adding a Newznab custom indexer (NzbHydra2) Lidaar keeps ignoring the port I've had added in.

**Screenshots**
![firefox_2018-09-02_13-47-55](https://user-images.githubusercontent.com/18294/44959068-0ae79f00-aeb7-11e8-843e-eed35cc3ebb9.png)

**Logs**
https://gist.github.com/fewyn/4cb8c8cc8ab59d4e19f22d9e7ba558f3

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System Ubuntu 18.04.1

**Comment by Qstick** [comment]
No issues here, do you have any indexers setup in hydra?
