### ISSUE TITLE
Album notification still sending one for each track for Manual Import

### ISSUE THREAD

**Issue by i814u2** [lidarr/Lidarr#473]
**Describe the bug**
When manually importing an album, notifications are sent for each track. For my pushover connection, I only have the boxed checked for sending a notification for a full album. The other three "on this or that" boxes are unchecked.

**To Reproduce**
1. Setup a connection (I used pushover)
2. Only check "On Album Import"
3. Manually import an album (I used Interactive mode)
4. Receive more than one pushover notification (each just says the artist and album and then "1 Tracks Imported")

**Expected behavior**
Only receive one notification per album.

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System: Ubuntu 16.04.5  as a host, Lidarr running in docker (hotio/suitarr:lidarr)
 - Mono Version: 5.12.0.226

**Comment by Qstick** [comment]
Can you provide debug logs of this happening. Thanks

**Comment by i814u2** [comment]
Brief update:

My original steps included:
 - moving an album to my "import" folder.
 - going to the wanted page and clicking on manual import.
 - choose the import folder.
 - click interactive import.
 - ensure files are properly matched, only select full albums worth of match tracks (unselect the rest).

(yes, tedious, but I don't yet know how well things will work and I'd rather not risk things)

If I get to the point of clicking manual import, pointing to the import folder, and clicking quick import, nothing happens (my tests are now with a single album, to be clear).
If I manual import, point to the actual single album, and click quick import, it imports and sends a single notification (as originally expected).

So it looks like it's related to the interactive import. But I'd still expect to have an option where I could point it at folders, let it import them, and only notify me about albums (since that's all that is checked in that connection).

Just thought I'd provide an update after a bit more testing.

**Comment by i814u2** [comment]
[Lidarr.trace.txt](https://github.com/lidarr/Lidarr/files/2364677/Lidarr.trace.txt)

Here's a trace log for the interactive manual import option. Let me know what else I can provide, or if you wanted one from the "quick import" option.

I did notice it was showing an error about the path not existing for the poster.jpg image. Is that a separate issue or possibly related? Other artists (which I've added while testing this issue) do show artwork. Though, I'm not certain whether they did right away, or just after some scheduled maintenance task(s). I saw it, so thought I'd mention it.

**Comment by Qstick** [comment]
Thanks, yea I can see where the album import event is being triggered for each track. Just got to figure out why now. I’ll look thru code tonight

**Comment by i814u2** [comment]
Quick, additional item which I just noticed: If you run the interactive import, it leaves the empty album directory, even if it matches all the files. The quick import removes the empty directory if it matches all the files (otherwise leaves what it couldn't match, as hoped/expected).

I just wanted to mention this in case it wouldn't have been handled by any fix ideas.

**Comment by Qstick** [comment]
Nice catch, thanks for all the digging on this. We are planning to release this week and a fix for this likely will not make it until after that

**Comment by i814u2** [comment]
No worries. I appreciate all the help and fast responses. I'd love to offer more help, but realistically don't have time to start looking into the code. Some day, maybe.

**Comment by Qstick** [comment]
Fixed in bb02d73c423e264672f31b37fccfa07b637ab79e
