### ISSUE TITLE
Create a default release profile with out-of-box ignored words (ex. EXE)

### ISSUE THREAD

**Issue by hughesjs** [Lidarr/Lidarr#475]
**Describe the bug**
When attempting to download an album, it pulls an obviously sketchy ".exe" file over usenet (AV  promptly deals with this file). I added ".exe" to restrictions and this hasn't helped.

**To Reproduce**
1. Download an album (Coldplay as an example).
2. Observe ".exe" being downloaded.

**Expected behavior**
Obviously fake files (i.e. not even matching the expected extensions) would be skipped. Restrictions would apply to file extensions as well as names.

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System: Windows 10
 - .net Framework (Windows) Version: 4.7.2

[AB#449](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/449)

**Comment by Qstick** [comment]
Whats the release name that its pulling. Lidarr has no idea what is in the nzb/torrent until after it downloads. So if the release name is valid and looks like a release, there is no real way to stop this... besides not using trash public indexers.

**Comment by hughesjs** [comment]
> slayer - repentless [2015] [mp3.320kbps].exe
Amongst others in a similar format. I use NZBFinder which isn't free...

**Comment by gismo2004** [comment]
as this is marked as Bug:

`	Line 2777: 19-1-3 18:14:47.5|Debug|DownloadDecisionMaker|Processing release '"Slayer - Repentless [2015] [Mp3.320kbps].exe"' from 'nzbf'
	Line 2778: 19-1-3 18:14:47.5|Debug|Parser|Parsing string '"Slayer - Repentless [2015] [Mp3.320kbps].exe"'
	Line 2782: 19-1-3 18:14:47.6|Debug|QualityParser|Trying to parse quality for "Slayer - Repentless [2015] [Mp3.320kbps].exe"
	Line 2785: 19-1-3 18:14:47.7|Debug|AcceptableSizeSpecification|Beginning size check for: "Slayer - Repentless [2015] [Mp3.320kbps].exe"
	Line 2786: 19-1-3 18:14:47.7|Debug|AcceptableSizeSpecification|Item: "Slayer - Repentless [2015] [Mp3.320kbps].exe", meets size constraints.
	Line 2790: 19-1-3 18:14:47.7|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: "Slayer - Repentless [2015] [Mp3.320kbps].exe"
	Line 2791: 19-1-3 18:14:47.8|Debug|ReleaseRestrictionsSpecification|["Slayer - Repentless [2015] [Mp3.320kbps].exe"] contains these ignored terms: .exe
	Line 2791: 19-1-3 18:14:47.8|Debug|ReleaseRestrictionsSpecification|["Slayer - Repentless [2015] [Mp3.320kbps].exe"] contains these ignored terms: .exe
	Line 2803: 19-1-3 18:14:48.0|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Contains these ignored terms: .exe`

this works for me 

indexer is NZBFinder and ignore word is ".exe"

Are you planning kind of "global ignore list"?

**Comment by Qstick** [comment]
Thats sort of what I was thinking, as for this case I can't think of any time anyone would want a release with .exe in the title due to security concerns, so shouldn't that be a case of something we should ignore out of the box?

I suppose the other way about it would be ship Lidarr with a few default ignored words such as `.exe`. That may be easier. Or a default, soon to be, release profile.
