### ISSUE TITLE
[Issue] Won't pull metadata for Albums with no OFFICIAL releases

### ISSUE THREAD

**Issue by TylerVigario** [Lidarr/Lidarr#4755]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Does not work

### Expected Behavior

Should work

### Steps To Reproduce

Use program

### Environment

```markdown
- OS: All that I tested
- Lidarr: Latest develop
- Docker Install: Nope
- Using Reverse Proxy: Nope
- Browser: Not applicable
- Database: Default...
```

### What branch are you running?

Develop

### Trace Logs?

![Screenshot 2024-04-14 182807](https://github.com/Lidarr/Lidarr/assets/1435595/eb11905b-cf9a-4038-ae52-be8325d3c82f)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
[not a bug. ](https://wiki.servarr.com/en/lidarr/faq#i-cannot-find-a-release-in-lidarr-but-it-is-on-musicbrainz)

> Report a new bug, **if you are not 100% certain this is a bug please go to our Discord first**

Please use [Discord](http://lidarr.audio/discord) for support/questions.

Refer to the FR: https://github.com/Lidarr/Lidarr/issues/3731

Also the most invalid bug report I have ever seen...abide by the template or don't waste time please.

- " I have searched the existing open and closed issues" [you did not](https://github.com/Lidarr/Lidarr/issues?q=is%3Aissue+is%3Aopen+official)
- "should work" is not valid
- "Does not work" is not valid
- "all that I have tested" is not an OS that exists
- "Latest develop" is not a version
- "Default" is not a valid database
- a screenshot of console logs are not trace logs
- Checking the box claiming you followed the wiki when you clearly did not....

**Comment by TylerVigario** [comment]
@bakerboy448 That link is not strictly relevant, and you may need to re-read the title. I know that if a release has no specified status ("unknown"), it will not show within Lidarr. This concerns actual statuses ("promotion," etc.), but you might not care. 

BTW, you're bug report strategy sucks. Everything filled out is relevant, correct in your eyes or not.

**Comment by bakerboy448** [comment]
> This concerns actual statuses ("promotion," etc.)

regardless. *Not a bug* as official only is intentional. Thus grounds for closure

>  you're bug report strategy sucks. Everything filled out is relevant, correct in your eyes or not.

1) \* your
2) users don't get to determine what is or is not relevant. The information requested is required for a reason.
3) the information provided is invalid for bug reports and is not the required information noted on the bug report template. Thus grounds for closure as invalid.
4) no trace logs provided thus grounds for immediate closure as invalid

**Comment by TylerVigario** [comment]
> > This concerns actual statuses ("promotion," etc.)
> 
> regardless. _Not a bug_ as official (and a few others) only is intentional. Thus grounds for closure
> 
> * Official
> * Promotion
> * Bootleg
> * Pseudo-Release

Shows how much you know/care

**Comment by zakkarry** [comment]
Right over this dude's head.

**Comment by TylerVigario** [comment]
Good luck to both of you 🤣

**Comment by zakkarry** [comment]
Thanks
