### ISSUE TITLE
Unclear UI on quality definitions page

### ISSUE THREAD

**Issue by hughesjs** [lidarr/Lidarr#477]
**Describe the bug**
The UI leaves "kilobits per second" visible even when the boxes are hidden as per the "advance features" setting. This led me to raise issue #476 in error. The real issue appears to be unclear UI.

**Expected behavior**
The heading text to be hidden along with the controls when advanced options is off.

**Comment by Qstick** [comment]
@hughesjs are you going to take this one on yourself?
