### ISSUE TITLE
Sharing Indexer and Download Configurationwith Xarr 

### ISSUE THREAD

**Issue by hughesjs** [lidarr/Lidarr#479]
Describe the problem
It's a pain in the ass if you're running Radarr, Lidarr and Sonarr to go around and adjust your indexer and download client settings on each one separately when, in all likelihood, they're nigh identical (except maybe categories).

Describe any solutions you think might work
Either store these settings in an XML file and add a configuration option to set which file to load these configs from or add an export/import indexers mechanic.

Additional context
Sonarr Issue: https://github.com/Sonarr/Sonarr/issues/2725
Radarr Issue: https://github.com/Radarr/Radarr/issues/3010

**Comment by Qstick** [comment]
This can be done with the current API, someone just needs to write a program or integrate into jackett/nzbhydra
