### ISSUE TITLE
Manually adding track titles

### ISSUE THREAD

**Issue by StephenCYang** [Lidarr/Lidarr#4858]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Walter Carlos' A Clockwork Orange OST initially released with "only" 10 tracks, when in reality it has 15. I haven't yet found a release that actually lists all the tracks.

### Describe the solution you'd like

I'd like a manual option of entering the information for those missing tracks.

### Describe alternatives you've considered

I've considered adding a "new" release to MusicBrainz but neither Discogs nor Amazon nor Wikipedia list the missing tracks. What's even more mysterious is that there's no mention at all about these tracks as if the person writing the album information has never actually listened to it.

### Anything else?

Usually surprise tracks by other artists get listed so normally this would not be an issue. Example: Ludo's [You're Awful I Love You](https://en.wikipedia.org/wiki/You%27re_Awful,_I_Love_You)

This is the first I've ever run into.

**Comment by StephenCYang** [comment]
Update, I just confirmed that the example of Ludo's doesn't import/name the hidden track either.

**Comment by bakerboy448** [comment]
No Plans to allow entering data in lidarr that does not exist on musicbrainz
