### ISSUE TITLE
Deleting tracks after download and just keeping info files in original downloaded folder | Not deleting info files after and making multiple folders in root, dumping tracks into root artist folder.

### ISSUE THREAD

**Issue by G120824** [Lidarr/Lidarr#4868]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

So I have been using Lidarr for a while and I'm not sure if its how I have it set up but please check this. When an album is downloaded it seems to move the songs from the album into the root artist folder without creating an album folder. Then it saves the info files in the downloaded folder outside of the library artist folder.

For Example, i have just downloaded an album using Lidarr. A new release which it has nabbed for me. After SAB Completed this i navigate to the folder and there are two folders. The sorted folder of the artist then the downloaded folder. All the tracks in the artist folder not inside an album folder

![image](https://github.com/Lidarr/Lidarr/assets/55493966/ff684144-ce26-4790-b8d4-9a3efe0a3de6)
This is my main root music folder

![343145485-45f228b6-efb5-4d45-8de2-6453c9ebf91f](https://github.com/Lidarr/Lidarr/assets/55493966/380778f5-7640-43c8-a67a-be5501b264fb)
This is the folder that should be deleted containing files I don't want

![Example](https://github.com/Lidarr/Lidarr/assets/55493966/ba4924d5-2236-4708-8587-2abfb3b5f4d6)
And this is the artist folder with all the tracks just thrown into the root artist folder without being sorted into an album folder with the name like it used to be.

I have recently upgraded this computer and its happened since. You can see above how the older albums before the upgrade have been organised on "YEAR - Name Of Album" => All tracks inside.]

I have removed the artist name however I disclaim this is royalty free music. I have not used nor will I use Lidarr to download any copyrighted material.

Bare in mind also Lidarr it used to do this similarly. However it used to delete the tracks and just keep the info files. Id set up a delete folder in advanced settings to catch them and they'd all be in the delete folder. Id have to manually put them back into folders and delete waste files. It still does this on occasion, it did this recently. The same stuff however when id go into the artist folder there would be no tracks. It just keeps the download folder and info files. I can reproduce this quite easily.

Please please please get in touch as this has been happening for 2 years now.

### Expected Behavior

Download the tracks and delete the info files.
Sort the folders by Artist => "YEAR - Album Title" => "Track Name", "Track Name"

![image](https://github.com/Lidarr/Lidarr/assets/55493966/0fc6d8b0-b0fa-407a-ad22-5a38541cb4cc)

### Environment

```markdown
- OS: Windows 11
- Lidarr:2.3.3.4204
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

[lidarr.txt](https://github.com/user-attachments/files/15988031/lidarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report. Info logs are not valid for bug reports.

Please use [Discord](http://lidarr.audio/discord) for support/questions.
