### ISSUE TITLE
Deleting files after download

### ISSUE THREAD

**Issue by G120824** [Lidarr/Lidarr#4869]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

While related to the other bug i reported this is the main one.

This has been happening for a while.

Basically Lidarr will nab the latest album. Send it to SAB. Download it. Put the album folder in my root music folder not sorted.

Delete the tracks and leave me with just the info files.

Using advanced settings I told it to put deleted files into this folder rather than delete them. And there they are all the tracks.

![image](https://github.com/Lidarr/Lidarr/assets/55493966/abdded4e-3af0-40ab-8666-6280176ad3f9)
![image](https://github.com/Lidarr/Lidarr/assets/55493966/83a59515-99e2-47ef-88a8-75e6680c769b)
![image](https://github.com/Lidarr/Lidarr/assets/55493966/0618d065-ed78-4864-983e-79663d69b554)

This has been happening for ages and I'm sick of it. Basically makes this app useless.

My music folder with 2 folders. This should be in the root artist folder above:
![image](https://github.com/Lidarr/Lidarr/assets/55493966/44e8c6d9-a27e-4bd4-bc8c-6bc0721ad5ec)
![image](https://github.com/Lidarr/Lidarr/assets/55493966/5d392204-8eea-40cc-8dfb-62b8f57493c3)

Album missing from root artist folder. Because its outside of it and the tracks are in the bin...
![image](https://github.com/Lidarr/Lidarr/assets/55493966/dbd505a3-6536-4dcb-8cc9-0eee8f39b26b)

### Expected Behavior

It should be saving the tracks into the album folder in the artist folder as shown with my other music collection.
And deleting the info files.
See the logs for issues. I am a C# Developer myself and noticed an error but not sure what has caused it.

### Environment

```markdown
- OS: Windows 11
- Lidarr: 2.3.3.4204
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

[lidarr.txt](https://github.com/user-attachments/files/15988449/lidarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report. Info logs are never valid for bug reports.
