### ISSUE TITLE
Monitor New album does not update monitoring status for listed album with a release date in the future

### ISSUE THREAD

**Issue by Mrpink200** [Lidarr/Lidarr#4873]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

when switching in artist profil monito new almbums to "new albums", it does not tick the album listed with a release date after today's date;
For example : Nick cave and the bad seeds with album Wild god that has a release date on Aug 30th 2024 cannot be marked as monitored when selecting the option.

### Expected Behavior

The album should be selected as monitored as the release date is after today's date

### Steps To Reproduce

explained in current behaviour

### Environment

```markdown
Version : 2.4.0.4222
Version du paquet : nightly-1941e24 by hotio
.NET : Yes (6.0.29)
Docker : Yes (synology)
Database : Sqlite 3.44.2
```

### What branch are you running?

Nightly

### Trace Logs?

none

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Mrpink200** [comment]
Same as : https://github.com/Lidarr/Lidarr/issues/3778
Sorry
Please fix

**Comment by bakerboy448** [comment]
Duplicate of #3778
