### ISSUE TITLE
Disregard Mac OS DS_Store (and similar) files during scans

### ISSUE THREAD

**Issue by blade316** [lidarr/Lidarr#489]
**Is your feature request related to a problem? Please describe.**
Currently when performing a scan and the parsing files, Lidarr is trying to do something with the Mac OS (X) based files such as .DS_Store

18-9-14 21:40:38.2|Debug|DiskScanService|Scanning '/media/Andrea Bocelli' for non-music files
18-9-14 21:40:38.2|Debug|DiskScanService|25 non-music files were found in /media/Andrea Bocelli
18-9-14 21:40:38.2|Debug|ExistingMetadataImporter|Looking for existing metadata in /media/Andrea Bocelli
18-9-14 21:40:38.2|Debug|Parser|Parsing string '.DS_Store'
18-9-14 21:40:38.2|Debug|Parser|Episode Parsed. DS Stor -  - 0:[Unknown Track] : 
18-9-14 21:40:38.2|Debug|QualityParser|Trying to parse quality for .DS_Store
18-9-14 21:40:38.2|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.2|Debug|Parser|Parsing string '.DS_Store'
18-9-14 21:40:38.2|Debug|Parser|Episode Parsed. DS Stor -  - 0:[Unknown Track] : 
18-9-14 21:40:38.2|Debug|QualityParser|Trying to parse quality for .DS_Store
18-9-14 21:40:38.2|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.2|Debug|Parser|Parsing string 'album.nfo'
18-9-14 21:40:38.2|Debug|Parser|Episode Parsed. album nf -  - 0:[Unknown Track] : 
18-9-14 21:40:38.2|Debug|QualityParser|Trying to parse quality for album.nfo
18-9-14 21:40:38.2|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.2|Debug|Parser|Parsing string 'album.nfo'
18-9-14 21:40:38.2|Debug|Parser|Episode Parsed. album nf -  - 0:[Unknown Track] : 
18-9-14 21:40:38.2|Debug|QualityParser|Trying to parse quality for album.nfo
18-9-14 21:40:38.2|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.2|Debug|ExistingMetadataImporter|Extra file folder has multiple Albums: /media/Andrea Bocelli/Romanza [1996]/album.nfo
18-9-14 21:40:38.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-9-14 21:40:38.2|Debug|ExistingLyricImporter|Looking for existing lyrics files in /media/Andrea Bocelli
18-9-14 21:40:38.3|Info|ExistingLyricImporter|Found 0 existing lyric files
18-9-14 21:40:38.3|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /media/Andrea Bocelli
18-9-14 21:40:38.3|Debug|Parser|Attempting to parse track info using directory and file names. Andrea Bocelli
18-9-14 21:40:38.3|Debug|Parser|Parsing string 'Andrea Bocelli .DS_Store'
18-9-14 21:40:38.3|Debug|Parser|Episode Parsed. Andrea Bocelli  DS Stor -  - 0:[Unknown Track] : 
18-9-14 21:40:38.3|Debug|QualityParser|Trying to parse quality for Andrea Bocelli .DS_Store
18-9-14 21:40:38.3|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.3|Debug|ExistingOtherExtraImporter|Unable to parse extra file: /media/Andrea Bocelli/.DS_Store
18-9-14 21:40:38.3|Debug|Parser|Attempting to parse track info using directory and file names. Romanza [1996]
18-9-14 21:40:38.3|Debug|Parser|Parsing string 'Romanza [1996] album.nfo'
18-9-14 21:40:38.3|Debug|Parser|Episode Parsed. Romanza -  - 0:[Unknown Track] : 
18-9-14 21:40:38.3|Debug|QualityParser|Trying to parse quality for Romanza [1996] album.nfo
18-9-14 21:40:38.3|Debug|Parser|Quality parsed: Unknown v1
18-9-14 21:40:38.3|Debug|ExistingOtherExtraImporter|Unable to parse extra file: /media/Andrea Bocelli/Romanza [1996]/album.nfo
18-9-14 21:40:38.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-9-14 21:40:38.3|Info|ExistingExtraFileService|Found 0 extra files

**Describe the solution you'd like**
I suggest adding a function to disregard any of these Mac OS (X) based files, and possibly adding an option where the user could add in comma separated file extensions that are to be ignored during scans.

**Describe alternatives you've considered**
Mac based users could disabled the creation of the .DS_Store type and similar type files, however they do have a purpose on Mac, and I actually do have certain programs that use them, so it would be good to just have Lidarr ignore them, as they offer no purpose for Lidarr.

**Additional context**
N/A.

**Comment by Qstick** [comment]
Functionality already exists for this. I'll have to test why things are not working

**Comment by blade316** [comment]
@Qstick ok that would be great ... let me know if you need me to test anything on my side

**Comment by Qstick** [comment]
@blade316 this should work now on nightly
