### ISSUE TITLE
Incorrect Album Track Count

### ISSUE THREAD

**Issue by blade316** [lidarr/Lidarr#495]
**Describe the bug**
I have noticed a couple of albums where Lidarr is presented the wrong track count.
An example is 'Andrea Bocelli - Amor' (not Amore) ... the track count for the album is 16, however Lidarr reports its as only 6 tracks. All the track names are displayed, just the track count that is wrong.

The MB URL is https://musicbrainz.org/release/4c023f54-4ad2-44f4-8aa1-6765c8292fea which reports the correct number of tracks.

**To Reproduce**
1. Add Andrea Bocelli as artist
2. Allow it to download the metadata
3. Open the Amor album

**Expected behavior**
Should be displaying 16 track count instead of 6

**Screenshots**

![image](https://user-images.githubusercontent.com/19606551/45597117-8c3c4700-ba0a-11e8-96fe-c52454b2509c.png)

![image](https://user-images.githubusercontent.com/19606551/45597134-d291a600-ba0a-11e8-86f2-12955d99f54f.png)

![image](https://user-images.githubusercontent.com/19606551/45597144-fb19a000-ba0a-11e8-8d8b-737b80b4337c.png)

**Logs**
Cant see any entries for Amor in debug.

**System info (please complete the following information):**
Version: 0.3.1.471
Mono Version: 5.12.0
DB Migration: 18
AppData directory: /config
Startup directory: /usr/lib/lidarr
Mode: Console
OS: Docker

**Additional context**
Its also not picking up that I have existing files for Amor plus a heap of other albums, but I will log that as a separate issue.

**Comment by Qstick** [comment]
I can’t reproduce this, shows 16 for me

**Comment by Qstick** [comment]
![e9a74bdc-e2b8-4b4d-86da-5b9769109f3a](https://user-images.githubusercontent.com/376117/45599991-8bcc8d80-b9c3-11e8-8085-6db48af71b73.jpeg)

**Comment by blade316** [comment]
hmmm weird, I removed the whole artist Andrea Bocelli and added again, now the track count is correct for that album.

Oh well, we can close this one off.
