### ISSUE TITLE
Many albums downloading full song list, then not importing some of the songs so incomplete Albums

### ISSUE THREAD

**Issue by restalfep** [lidarr/Lidarr#499]
**Describe the bug**
When using Lidarr it sometimes downloads the full album properly but it seems more often than not it downloads the full album (then imports only some of the songs and deletes the rest), then under Artists if you check that album you can see that it is missing those songs. When I try to find them again under Wanted or search it just never completes the album. I also tried deleting the entire artist and media and trying again but whatever songs it is missing then it misses them again. I can't figure out what would cause this as I tried enabling all metadata options, changed quality settings, etc. The album track correctly shows the right amount of songs, but it always misses the same songs if it misses them the first time. One time the log even showed "audio detected: and the song name but it never imported it and just deleted it eventually". 

**To Reproduce**
1. Go to '...' - Add a few artists and albums
2. Click on '....' - After download check the albums and a few will not be 100% of the albums (and you will see those artists under Wanted still. 
3. See error - Searching under Wanted or deleting and retrying leads to the exact same songs missing if they were missing the first time. It correctly downloads all songs but then just doesn't add those missing songs. 

**Expected behavior**
To correctly download the songs or figure out why this bug is happening so I can fix it. 

**Logs**
The logs don't seem to show anything relevant since it just downloads the entire album, then misses importing some of the songs, then deletes everything from downloads so missing songs are gone anyway. 

**System info (please complete the following information):**
 - Lidarr Version: 0.3.1.471
 - Operating System Raspberry Pi 3 B+ (Raspbian/Debian 9/Linux)
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.14.0.177

**Comment by restalfep** [comment]
After working on this more, it seems as long as I make it so it doesn't delete "empty folders" then it seems I can go back and manually import them. They weren't able to parse the first time around but it seems to happen quite often. Is there a better way to automate this somehow? Ie. have something else go through and adjust the file tags and then resend for Lidarr to scan?

**Comment by Qstick** [comment]
Let us know what the parsing errors are so we can improve. Closing this as there are already numerous other parsing issues open

**Comment by Qstick** [comment]
Nah We are pushing another release tonight, so you are in luck

**Comment by restalfep** [comment]
Awesome!! Thanks

**Comment by restalfep** [comment]
Upgarded and so far 3/3 have been perfect after testing. Don't want to speak too soon but seems great now! Thanks again, issue resolved (hopefully don't jinx it).
