### ISSUE TITLE
Unable to add new root folder

### ISSUE THREAD

**Issue by dgwharrison** [lidarr/Lidarr#503]
New to lidarr but been using sonarr and radarr for a long while.

Version 0.4.0.524
Windows, as a service, installed from installer, clean install never used before

I'm completely unable to add a new root folder (the first and only one). I've tried from:
Artist>Import (safari 12.0, Chrome Windows 69.0.3497.100, Firefox Mac 62
Settings> Last FM User (this is where I first noticed It as I was going through setup), Chrome Windows as above

You can quite quickly and easily navigate to the folder, in my case: C:\MusicDisk1\iTunes Media\Music\ however when you press save the dropdown box for root folder is not populated at all. 

I've also tried working around it by pasting in the location, doesn't help. I even tried the keyboard shortcut which I noticed under the keyboard shortcuts section under the profile link in the top right, control + s, doesn't appear to be implemented in chrome windows.

I have no idea if the control works if you already have a root folder and you wish to add an additional. 

I eventually opened the database lidarr.db from C:\ProgramData\Lidarr and inserted a row for my path in the RootFolders table. Restarted the service, now all is well.

**Comment by Qstick** [comment]
Logs? Errors in logs?

**Comment by dgwharrison** [comment]
Seems to be browser side. I attempted to add another root folder to generate a log message for c:\users\dan\music (which I don't use but that's not the point), it failed as previously described. However when I searched Lidarr.txt from c:\ProgramData\Lidarr\logs\ I found no entry for c:\users\dan\music and the last entry was after the time that I entered it, I scrolled and couldn't identify an error related to this. There are bucket loads of errors because the service doesn't have permissions in my download folder, which I'm about to fix, but nothing for adding the root folder.

**Comment by dgwharrison** [comment]
Where do we put logs?

**Comment by Qstick** [comment]
Do you see any errors in browser console?

**Comment by dgwharrison** [comment]
Sorry for the delay. Yeah I ran it in chrome just now and yes it gives an error. I'm not sure how to export the entire error from the console but below is a cut and paste, below that is a link to a screencast, you can skip to the end, note that I have made sure 'local service' has permissions in that folder (service for the win but it's going to be a support nightmare, you're gonna get permission questions all the freaking time).
`
  | (anonymous) | @ | raven.js:1422
-- | -- | -- | --
  | send | @ | xhr.js:151
  | ajax | @ | ajax.js:696
  | _jquery2.default.ajax | @ | jquery.ajax.js:45
  | (anonymous) | @ | rootFolderActions.js:61
  | (anonymous) | @ | thunks.js:13
  | (anonymous) | @ | index.js:8
  | (anonymous) | @ | middleware.js:13
  | (anonymous) | @ | index.js:60
  | (anonymous) | @ | redux.js:449
  | ImportArtistSelectFolderConnector._this.onNewRootFolderSelect | @ | ImportArtistSelectFolderConnector.js:55
  | ImportArtistSelectFolder._this.onNewRootFolderSelect | @ | ImportArtistSelectFolder.js:59
  | FileBrowserModalContent._this.onOkPress | @ | FileBrowserModalContent.js:86
  | Link._this.onClick | @ | Link.js:19
  | (anonymous) | @ | react-dom.production.min.js:14
  | ka | @ | react-dom.production.min.js:15
  | (anonymous) | @ | react-dom.production.min.js:15
  | xa | @ | react-dom.production.min.js:17
  | Ba | @ | react-dom.production.min.js:18
  | Da | @ | react-dom.production.min.js:18
  | za | @ | react-dom.production.min.js:18
  | Ga | @ | react-dom.production.min.js:21
  | Fd | @ | react-dom.production.min.js:84
  | sh | @ | react-dom.production.min.js:216
  | Pb | @ | react-dom.production.min.js:39
  | Id | @ | react-dom.production.min.js:86
  | uh | @ | react-dom.production.min.js:216
  | Hd | @ | react-dom.production.min.js:85
  | wrapped | @ | raven.js:376
`

https://www.screencast.com/t/mXUFwNBZ

**Comment by Qstick** [comment]
Looks like a permission issue with the share/folder. You can jump on Discord to get help if you haven’t got it sorted
