### ISSUE TITLE
Disable automatic import of unmapped files

### ISSUE THREAD

**Issue by cherryontopknife** [Lidarr/Lidarr#5063]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a huge library, over 500k songs, much of which I do not want Lidarr to scan. However, Lidarr always scans all of the unmapped files. This causes issues trying to manage downloads/ files within Lidarr itself, and causes instability for my entire machine.

### Describe the solution you'd like

An option to disable automatically scanning and attempting to import unmapped files

### Describe alternatives you've considered

I've tried limiting RAM, tweaking configuration settings, and restarting Lidarr on a schedule, but it still just attempts to import unmapped files after a few hours, causing issues.

### Anything else?

I'm surprised this isn't already a feature. Lidarr shouldn't have to be all or none IMO.

**Comment by bakerboy448** [comment]
Lidarr owns its root folder. remove media outside of lidarr's folder you dont want lidarr to manage
