### ISSUE TITLE
Music folders copied manually to the right artist and correct album doesn't show as available on lidarr

### ISSUE THREAD

**Issue by alculete** [lidarr/Lidarr#507]
**Describe the bug**
Music folders copied manually to the right artist and correct album doesn't show as available on lidarr

**To Reproduce**
1. Copy album folder from other location into /music (for example, /music/Eminem)
2. Copy an album that is not yet downloaded 
3. Go to lidarr and refresh manually or wait for lidarr auto refresh and nothing happens

**Expected behavior**
Should show music files available of that particular album added and rename the album 

**System info (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS x86_64   
 - Kernel: 4.15.0-36-generic
 - Lidarr Version: 0.4.0.524
 - Mono Version: 5.12.0.301

**Comment by Qstick** [comment]
Logs? This works fine if Lidarr can identify said files

**Comment by alculete** [comment]
I was able to set it manually by selecting each music. Thank you
