### ISSUE TITLE
ror after upgrading to version 2.4.3.4248

### ISSUE THREAD

**Issue by u2597511** [Lidarr/Lidarr#5108]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After the update, the endless process of migration to the new version began after the launch of the service

### Expected Behavior

Correct completion of the installation

### Steps To Reproduce

1. pkg update
2. pkg upgrade
3. service lidarr restart

### Environment

```markdown
- OS: Jail on FreeBSD 13.1-RELEASE-p9 n245431-b8ec9bde091 TRUENAS
- Lidarr: 2.4.3.4248 — Jul 14 2024
- Docker Install: not installed
- Using Reverse Proxy: NPM
- Browser: Chrome
- Database: Postgres 16.4
```

### What branch are you running?

Master

### Trace Logs?

```
service lidarr start
```
couple minutes
```
service lidarr stop
```

[Logs](https://gist.github.com/u2597511/d8b5979b21af2f9ab8fd3f910b751afe)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mvanbaak** [comment]
Not that this will magically fix your issue, but please plan a FreeBSD upgrade.

13.1 isn't even legacy anymore, so not supported at all.
I advise you to go to 14.1. Nobody should be running 13 anymore :)

**Comment by bakerboy448** [comment]
- unsupported EOL OS
AND
- Logs indicate lidarr is consistently starting back up
- Logs indicate a 4s gap between last log event and lidarr starting back up
- Logs do not indicate any sort of lidarr shutdown

it seems reasonable to conclude an external factor is killing and starting lidarr; not a lidarr bug accordingly based on what is shown
