### ISSUE TITLE
Use MusicBrainz Picard MP3 Tag IDs to match Artist and Specific Album Release

### ISSUE THREAD

**Issue by ChaosBlades** [lidarr/Lidarr#512]
Just added my huge library that has been painstakingly through MusicBrainz Picard and I am finding that Lidarr is not using any of the MusicBrainz IDs added to the MP3 Tags to match Artist and Album release. I would have to go through over 2,000 albums and manually select the release to get the correct number of tracks to match. Also finding it is selecting bands with the same name but the wrong band and like described not using the MusicBrainz IDs already in the MP3 Tags to use the correct artist.

![annotation](https://user-images.githubusercontent.com/7530545/46787668-41aaa380-cd06-11e8-9d0c-ed8bd60921f9.png)

**Comment by ChaosBlades** [comment]
It is looking at the MP3 embedded metadata and pulling the MediaBrainz artist and album IDs from that instead of searching the folder/files names on MediaBrainz? It looks like it is adding the artist based on folder name then pulling random releases from MediaBrainz then trying to match the MP3s to that.

MusicBrainz Picard Found every Arkona album instantly without having to do any searching. Just pulled the information based on the embedded metadata.
![mediabrainz](https://user-images.githubusercontent.com/7530545/46900078-4d16df80-ce6a-11e8-94ee-a0451580800e.png)

Lidarr on the other hand only managed to find 2 albums and a few tracks. It isn't even pulling the releases with english characters.
![lidarr](https://user-images.githubusercontent.com/7530545/46900085-6455cd00-ce6a-11e8-993a-0cefd634159e.png)

**Comment by ChaosBlades** [comment]
On the Yav album Lidarr selected the de083395-aca4-4dd1-974a-76466e39f574 release with 2 CDs. But 711e49c1-169e-44d9-8edc-773c7f67ee08 was embeded in the MP3s and should have been selected by Lidarr.

**Comment by Qstick** [comment]
Correct, all we use is internal metadata currently, we don't identify based on filename. But you are correct that we only use it to select release group, we are not changing release based on the metadata tags as of yet. (Being worked on). Also, we are much like Sonarr still, in that we expect all music to be in a single artist folder. Thus if a track is in that artists folder then we associate with that artist, we don't use tags for artist as we do for album and track.

**Comment by Qstick** [comment]
Would also be interested to see why the other tracks in that folder are failing, can you run a manual scan for that artist and post the trace log?

**Comment by ChaosBlades** [comment]
Looks like it is having trouble with Russian characters.
[Lidarr Trace Log.txt](https://github.com/lidarr/Lidarr/files/2476317/Lidarr.Trace.Log.txt)

**Comment by a575606** [comment]
I was going to open a new issue, but it may relate to what @ChaosBlades describes above. I kept getting this error in my logs after a successful download and the album refused to import half the tracks:

Request Failed. GET /api/v1/track: Expected query to return 14 rows but returned 7

It took me a while to catch on, but apparently the 2 disc vinyl release was selected for the album in question so it wasn't matching the normal cd or digital release. I never specified a release, so I'm assuming it happened during import and refresh of the artists? Anyway I thought it was strange and have noticed it happen a few times. Often it's a pretty random release as well, like vinyl or some re-release with different numbers of tracks and it refuses to match with the standard release downloaded or imported. I never release it until errors similar to the above appear in the log, and changing the release midway through importing an album throws things out of whack a bit. 

Maybe I missed some configuration setting? Just thought I'd mention in case it was worth a look. Running on synology via docker. 

Version
    0.5.0.583
Mono Version
    5.18.0.240
DB Migration
    22
