### ISSUE TITLE
Better matching for Albums and Singles of the same name

### ISSUE THREAD

**Issue by sasjafor** [lidarr/Lidarr#516]
**Is your feature request related to a problem? Please describe.**
When an Artist has an Album and a Single of the same name, manual import of the artist fails for that Album, because Lidarr always tries to match the Album with the single. Also a manual import on the Artist page doesn't work, only selecting the album and assigning all tracks individually works.

**Describe the solution you'd like**
Better matching that can try to match an album with both the Single and the Album instead of just failing when it can't match with the first release it finds.

**Describe alternatives you've considered**
Alternatively, it would already be a great help, if in the manual import on the artist page, one could just select the album and then have Lidarr try to match it again. Instead of having to assign all tracks individually. If this is already possible, I'd be glad to know how.

**Additional context**
I'm using a metadata profile that includes Albums and Singles.

**Comment by Qstick** [comment]
Fixed with bb02d73c423e264672f31b37fccfa07b637ab79e
