### ISSUE TITLE
Allow manual mapping to albums for manual imports

### ISSUE THREAD

**Issue by SawkeeReemo** [Lidarr/Lidarr#5169]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would save so much time if, when we are manually importing albums, that we could manually select the album we already know if in our database instead of waiting for the attempt at the auto-scan to find it. My thinking is, if the auto=scan couldn't find it the first time, scanning again now can be a waste of time and resources. Being able to manually link the album with an option to auto-scan would be much better UX in my opinion.

### Describe the solution you'd like

To be able to manuall link a manual import to the album instead of waiting for what can be a very lengthy scan every time.

### Describe alternatives you've considered

There are no alternatives that I'm aware of.

### Anything else?

N/A

**Comment by bakerboy448** [comment]
No plans to change the manual import process from upstream and not parse files for manual import

**Comment by SawkeeReemo** [comment]
> No plans to change the manual import process from upstream and not parse files for manual import

I'm not talking about parsing. I'm saying just let us choose the album first. When you have a huge library it can take a really long time to match things. Where as when I do it myself, it takes seconds. Take the heavy lifting off of Lidarr and save tons of time. (...he says having spent the past 3 days fixing things...)

**Comment by bakerboy448** [comment]
_switching logs from trace to debug significantly improved app effort time_

As per discord discussion

Trace for lidarr and readarr truly should be temporarily as it does cause noticeable performance impacts.  Prowlarr sometimes depending on the specific indexers. Radarr and Sonarr are fine to keep on trace.
