### ISSUE TITLE
ReleasePushModule returns HTTP/1.1 405 Method Not Allowed

### ISSUE THREAD

**Issue by dcman** [lidarr/Lidarr#518]
**Describe the bug**
ReleasePushModule returns HTTP/1.1 405 Method Not Allowed
I use the same script to push from autodl to Radarr and Sonarr. 
**To Reproduce**
Run script:
`title=$1
downloadUrl=$2
apiKey=$3
date=$(date -u +"%Y-%m-%d %H:%M:%SZ")

echo $date $title $downloadUrl $apiKey  >>~/.scripts/log/music.log

{
/usr/bin/curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Api-Key: $apiKey" -X POST -d '{"title":"'"$title"'","downloadUrl":"'"$downloadUrl"'","downloadProtocol":"torrent","publishDate":"'"$date"'"}' http://localhost:46539/api/release/push
} &> /dev/null`
**Expected behavior**

**Screenshots**

**Logs**
18-10-19 01:05:20.8|Debug|Api|[POST] /api/release/push: 405.MethodNotAllowed (0 ms)
18-10-19 01:06:03.9|Debug|Api|[POST] /api/release/push: 405.MethodNotAllowed (0 ms)
HTTP/1.1 405 Method Not Allowed
X-ApplicationVersion: 0.4.0.524
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Fri, 19 Oct 2018 01:06:03 GMT
Transfer-Encoding: chunked
Keep-Alive: timeout=15,max=100

{
  "message": "MethodNotAllowed"
}
**System info (please complete the following information):**
Version
0.4.0.524
Mono Version
5.10.1.47
DB Migration
20
AppData directory
/home/srwaxalot/.config/Lidarr
Startup directory
/mnt/mpathi/srwaxalot/Lidarr
Mode
Console

**Additional context**

**Comment by Qstick** [comment]
Lidarr (like Sonarr V3) requires API version: `http://localhost:46539/api/release/push` should be `http://localhost:46539/api/v1/release/push`
