### ISSUE TITLE
Add Bulk Monitor/Unmonitor Button to Singles and EPs

### ISSUE THREAD

**Issue by WhiteLP11** [Lidarr/Lidarr#519]
HI, I changed the metdata profiles so that I would also see singles, EPs, Broadcasts  aso. After that all these were added to all of my artists with monitoring on. After that I had to go over all of my artists to unmonitor all of the junk that was added. Total mess afterwards.

1) The changed profile new founds should not be added as monitored!
2) Under artist above the list of monitored checks there should be the master monitor button to unmonitor everything under the singles list or EPs list aso. The Sonarr has similar feature with seasons, where you can unmonitor whole season.

[AB#455](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/455)

**Comment by Qstick** [comment]
Probably won’t change number 1 because you can easily just create a new metadata profile and apply it to certain artists instead of changing the existing ones. Also, you will have people arguing the opposite if changed, that they should be monitored by default because you actively added them.

Number 2 would be helpful, so I’ll see about getting that added

**Comment by WhiteLP11** [comment]
Ok, I get your point. Still It would be great if there would be a pop up window or description what happens if you change the profile that is already assigned. Under the profiles 1 sentence would save somebody in future from this enormous hassle that I had.

**Comment by y2kbadbug** [comment]
This is more of a bigger bug, because I didn't even assign everyone that profile and all 300 of my artists have EVERYTHING monitored now after I spent 3 hours the other day unmonitoring all the junk.  The profile feature is completely flawed if its doing that.

**Comment by Qstick** [comment]
@y2kbadbug I can’t reproduce what you are describing

**Comment by Qstick** [comment]
4b367d31297c5646e3e18f9a1b5b32da9f1b3bd0
