### ISSUE TITLE
Removing Remote Path Mapping displays wrong popup text

### ISSUE THREAD

**Issue by mgyellow** [lidarr/Lidarr#521]
**Describe the bug**
When you delete a remote path mapping, you get a confirmation popup with the following text:

> Delete Delay Profile
Are you sure you want to delete this delay profile?

**Steps to reproduce the behavior**
1. Go to Settings
2. Select [Download Clients]
3. Click on [wrench] of an existing remote path mapping
4. In the [Edit Remote Path Mapping] popup, click on [Delete]
5. See wrong text popup

**Expected behavior**
Popup with following text:
> Delete Remote Path Mapping
Are you sure you want to delete this remote path mapping?

**Logs**
N/A

**System info:**
 - Lidarr Version: 0.4.0.524
 - Operating System Windows 10 v1803 build 17134.345
 - .net Framework 4.7.2

**Additional context**
When pressing [Delete] on the popup, the Remote Path Mapping gets deleted as expected, only the text is wrong

**Comment by Qstick** [comment]
This is already fixed in nightly, thanks for report though!
