### ISSUE TITLE
Album Not Showing Under Artist

### ISSUE THREAD

**Issue by JeepXJman** [lidarr/Lidarr#524]
When adding  Luke  Comb's, the Album "This One's for You Too" does not come up, even when all MetaData  Profiles are selected.

https://musicbrainz.org/release/50b89a64-537f-4939-9238-48aa0da36b8e

**System info (please complete the following information):**
 - Lidarr Version 0.4.0.524
 - Operating System Win 10

**Comment by Qstick** [comment]
It’s not another album. It’s another release of `This ones for you`. Thus it’s the same album but different version. If you want it instead then go to Album edit and change the release.
