### ISSUE TITLE
Change calendar 'unreleased' border color for easier visibility

### ISSUE THREAD

**Issue by kitsuneDEV** [lidarr/Lidarr#527]
In my opinion it makes little sense why Downloaded and Unreleased are both greens hardly apart from each other. An unused color like yellow/orange would make more sense.
How about a color that is already in use, the one for the notification bubble like besides Activity in the menu.

So I suggest changing the CSS border-left-color values for -unreleased- to #FFA500

**Comment by Qstick** [comment]
Should we also have a different color for albums that only have partial tracks in library? (ex. 5 of 8 tracks are in user library)

**Comment by kitsuneDEV** [comment]
For anyone eager to have this you could install a userstyle extension and create a new style for your Lidarr with:

> *[class*="unreleased"] {
>      border-left-color: #FFA500 !important;
> }
