### ISSUE TITLE
Lidarr and Readarr won't start due to missing sqlite library, but Radarr and Sonarr does

### ISSUE THREAD

**Issue by trex2000** [Lidarr/Lidarr#5304]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Both Lidarr and Readarr won't start with the following error.

FluentMigrator.Runner.MigrationRunner|Unable to load shared library 'libsqlite3.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsqlite3.so.0: cannot open shared object file: No such file or directory

I have checked and the libaries are 

### Expected Behavior

On fresh install, the apps won't load due to missing sqlite3 library. The libraries are installed, and available here:
root@barney:/usr/lib/x86_64-linux-gnu# ls | grep libsq
libsqlite3.a
libsqlite3.so
libsqlite3.so.0
libsqlite3.so.0.8.6
libsquashfuse_ll.so.0
libsquashfuse_ll.so.0.0.0
libsquashfuse.so.0
libsquashfuse.so.0.0.0

root@barney:/var/lib/lidarr/logs# apt install libsqlite3-0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsqlite3-0 is already the newest version (3.45.1-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.

root@barney:/var/lib/lidarr/logs# apt install libsqlite3-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsqlite3-dev is already the newest version (3.45.1-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.

root@barney:/var/lib/lidarr/logs# apt install sqlite3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sqlite3 is already the newest version (3.45.1-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.

I allso created a symlink to the folder where the sw is installed, still no change.
I am running Radarr and Sonarr natively in the same manner, these 2 work without an issue.
I have no other idea what I could try out.

### Steps To Reproduce

Install natively under Ubuntu LTS and try to launch the application(s).

### Environment

```markdown
- OS: Ubuntu 24.04.1 LTS
- Lidarr:2.7.1.4417
- Docker Install:no
- Using Reverse Proxy:no
- Browser: All
- Database:SQLITE
```

### What branch are you running?

Master

### Trace Logs?

[readarr.txt](https://github.com/user-attachments/files/18125565/readarr.txt)
[lidarr.txt](https://github.com/user-attachments/files/18125638/lidarr.txt)
[lidarr.debug.txt](https://github.com/user-attachments/files/18125639/lidarr.debug.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
~ to https://wiki.servarr.com/en/lidarr/system#currently-installed-sqlite-version-is-not-supported

**Comment by trex2000** [comment]
Thanks. I've missed this in the wiki.
