### ISSUE TITLE
Missing album from artist on MusicBrainz

### ISSUE THREAD

**Issue by Giligilitelj** [lidarr/Lidarr#531]
I added the artist group "Walk of the Earth" to Lidarr.
I do not understand why it doesn't show their album "My Rock" in the list,
[https://musicbrainz.org/release-group/bbb34509-526c-4f8c-87ea-8f9784006120](url)
although I checked on MusicBrainz and all metadata seems to be alright.
The album is not a different release, not an EP or single, it is a studio album with
only one release, and metadata profile for group is set to include all types.

**Comment by Qstick** [comment]
Looks like release is pending approval or recently changed. This should resolve in short order
