### ISSUE TITLE
Allow scheduled task intervals to be customised.

### ISSUE THREAD

**Issue by RevenantOne** [lidarr/Lidarr#532]
**Is your feature request related to a problem? Please describe.**
The default interval for the Refresh Artist scheduled task is 24 hours. My music library seems to take longer than this to scan. I'm not grabbing any metadata and I've disabled file analysis. I do have several artists requesting every type of media profile, but this isn't the default setting.

**Describe the solution you'd like**
The ability to customise the interval in between scheduled tasks being executed.

**Describe alternatives you've considered**
I've tried to reduce the time it takes for the task to complete by disabling file analysis and metadata. 

**Additional context**
![Refresh Artist Inerval](https://imgur.com/a/u2GEp7j)

**Comment by Qstick** [comment]
This may help https://github.com/lidarr/Lidarr/commit/78a0b5f8b713f873532304b0c5d5b947bee0aa96

**Comment by RevenantOne** [comment]
If I understand this update correctly, if I set it to manual then Lidarr will not detect any new albums automatically?

While I can see why it would be useful for incremental updates I don't think it will fit my needs in this case. I'm pretty sure my Lidarr install has been unable to complete a Refresh Artist scan since I started using it a couple of months ago.

That said, I found a guide to manually change the interval via lidarr.db and I've managed to set the interval to 7 days and for the first time Lidarr managed to get to the I's after leaving it for more than 24 hours. (And this is with mp3 albums are taking ~1 to 2 mins and flac ~3 to 4 mins.)

**Comment by Qstick** [comment]
Lidarr will still handle new albums fine if you have completed download handling turned on. It just won't find anything added/grabbed outside of Lidarr

**Comment by kitsuneDEV** [comment]
I really need this to work too.
How exactly do I install the version that includes this? I'm on the 'develop' branch v0.4.0.524

**Comment by Qstick** [comment]
We are pushing release today or tomorrow so you will have it very soon

**Comment by hikaricore** [comment]
Out of curiosity, has there been any progress on this?

A large number of people are behind this on FeatHub if it makes any difference: https://feathub.com/lidarr/Lidarr/+49

No rush, I understand Lidarr is still in the early stages of development, just figured it couldn't hurt to ask.

**Comment by ta264** [comment]
Not directly.  I am working on improving the scanning so it only tries to scan unmatched files
