### ISSUE TITLE
Manual Import is not kept after Update all or restart

### ISSUE THREAD

**Issue by Hakujou** [lidarr/Lidarr#533]
Hello,

Currently, if we perform some manual import on redundant tracks, it won't be kept after triggering an "Update all" (or if Lidarr restarts, it seems).
For example, Daft Punk released a single named "Human after All", then an album with the same name.

The default matching is incorrect, as 9/10 tracks are bound to album, and the first track (also named "Human after all") is bound to the single. I correct it with a manual import and everything is fine.

However, if I trigger an "Update all", then the track goes back to the single and will override my "manual import" override.

Could you please fix this behavior ?

Thanks

**Comment by Qstick** [comment]
This really is almost same as #516
