### ISSUE TITLE
"Failed to load Lidarr", after providing credentials

### ISSUE THREAD

**Issue by mptpro** [Lidarr/Lidarr#5342]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using the web interface I go to the login screen.  Log in.  And I am presenting with the message...

```
Failed to load Lidarr
Version 2.9.0.4508
```

### Expected Behavior

To go past the login screen.

### Environment

```markdown
- OS: Docker on Ubuntu
- Lidarr: Version 2.9.0.4508
- Docker Install: lscr.io/linuxserver/lidarr:develop
- Using Reverse Proxy: no
- Browser: Brave
- Database: unknown
```

### What branch are you running?

Develop

### Trace Logs?

Looking in the log (attached)), I see...

```
code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
```
[lidarr.0.txt](https://github.com/user-attachments/files/18265353/lidarr.0.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
For support and inquiries, please use our [Discord](http://lidarr.audio/discord) channel. GitHub is designated solely for bug reports and feature requests. It seems that this issue may fall under a support request, so we kindly ask you to visit our Discord for assistance. Thank you.
