### ISSUE TITLE
Snap applications show up as disk locations

### ISSUE THREAD

**Issue by Serneum** [lidarr/Lidarr#542]
**Describe the bug**
Snap applications show up as disk locations. This clutters up the UI and looks a bit strange since all of them are always at 100% utilization.

Sonarr and Radarr have both solved this issue already.
Sonarr: https://github.com/Sonarr/Sonarr/issues/2743
Radarr: https://github.com/Radarr/Radarr/issues/3122

**To Reproduce**
1. Go to System
2. Click on 'Status'

**Expected behavior**
`/snap` and any subdirectories should not be shown in the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/1091716/48645562-06aa2880-e9b4-11e8-9b2a-f5621cc585eb.png)

**System info (please complete the following information):**
 - Lidarr Version: 0.4.0.524
 - Operating System: Ubuntu 18.04 LTS
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.6.2

**Comment by Qstick** [comment]
Already been fixed here https://github.com/lidarr/Lidarr/commit/6103afcc09534d93c01ecb1324e0a6462aa8b1bf

**Comment by Serneum** [comment]
Ah, cool. I'll double check my release or wait for the next one. Thanks!

**Comment by Qstick** [comment]
It'll be next one
