### ISSUE TITLE
After installation prodcedured followed, it fails

### ISSUE THREAD

**Issue by faxmayo** [lidarr/Lidarr#543]
**Describe the bug**
I have followed step by step the installation procedure of this web and when I start the service the process fails. So, I have run manually the command /usr/bin/mono /opt/Lidarr/Lidarr.exe -nobrowser and the result is:

Unhandled Exception:
System.TypeLoadException: Could not load type 'NzbDrone.Common.EnvironmentInfo.StartupContext' from assembly 'Lidarr.Common, Version=0.4.0.524, Culture=neutral, PublicKeyToken=null'.

I have been searching about NzbDrone and it seems to be a similar software to SickChill. I have this latter installed so I do not need any other. My question is, Can I Run Lidarr on a raspberry pi 3 without installing Sonar/NzbDrone on it? Is it possible? Thank you very much.

**Comment by danielunderwood** [comment]
NzbDrone is just old naming. You shouldn't need anything other than mono to run.

You are trying to run from a linux build and not from source, correct? What's your mono version?

You'll probably want to join [our Discord](https://discord.gg/8Y7rDc9) for extended support.
