### ISSUE TITLE
Support for genre folders at root level

### ISSUE THREAD

**Issue by ravensorb** [Lidarr/Lidarr#544]
**Is your feature request related to a problem? Please describe.**
I have my music library setup like this
```
/mnt/Media/Music/<genre>/<Artist>/<Album>/<Song>
```
And it seems that lidarr is not sure what to do with this type of organizational structure.  It sees the "genre" as the Album name for some reason.

**Describe the solution you'd like**
Ideally it would be great if the folder path structure was configurable or if it could be ignore in the scan and defined in the rename section

**Describe alternatives you've considered**
Considering the size of my library it i'd rather not reorganize everything so might be easier to go back to headphones as it seems to be able to support this format.  

[AB#460](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/460)

**Comment by Qstick** [comment]
requires https://github.com/lidarr/LidarrAPI.Metadata/issues/72

**Comment by Fmstrat** [comment]
I'd like to +1 this. Switching over to Lidarr but other management software such as MediaMonkey allow for the `{Genre}` start folder. Helps a lot with really large libraries. Unfortunately the folder structure is the only thing keeping me from switching at this point.

**Comment by sPOiDar** [comment]
With the new file-hierarchy support landing, would be nice to see the option to use `{Genre}` when building filenames, though we might need something like https://github.com/lidarr/Lidarr/issues/979#issuecomment-768936887 to allow people to restrict genres to a single white-listed entry per release.

**Comment by nrickett** [comment]
For whatever its worth I would like to see this added as well, but since this has been an open request since 2018 I guess its pretty low on the list. What kind of donation needs to be made in order to get his higher on the priority list?

**Comment by BioSs54** [comment]
Some news about this integration ?

**Comment by Qstick** [comment]
I'll see about knocking this out.

**Comment by nrickett** [comment]
I was able to accomplish this by using these settings in Root Folders:

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/80401969/209446858-7ae7547a-cdaa-41d9-a70d-7220e484321a.png">

**Comment by Qstick** [comment]
ec41951ea50a2c55e3f2dd29964d2b7fa8f7e183
