### ISSUE TITLE
Installing Lidarr on Freenas 11.2

### ISSUE THREAD

**Issue by fontes31** [lidarr/Lidarr#546]
Hi,

I tried to install lidarr on my freenas 11.2. After creating the lidarr on rc.d and trying to start the service i have this error:

root@teste:/usr/local/etc/rc.d #  service lidarr start 
/usr/local/etc/rc.d/lidarr: 2017-11-24: not found
Starting lidarr.
Unmatched '"'.
Unmatched '"'.
/usr/local/etc/rc.d/lidarr: WARNING: failed to start lidarr

I do not know where is the problem, i checked the file lidarr on rcd

**Comment by Qstick** [comment]
Hit discord for support
