### ISSUE TITLE
Warning message: Missing root folder: /volume1/music/

### ISSUE THREAD

**Issue by koitail** [lidarr/Lidarr#548]
**Describe the bug**
I mounted a new drive on my NAS and transferred all my music collection onto it. After moving the default folder to the new volume, the error message would not disappear.

**To Reproduce**
1. In Synology DSM, the default music folder is /volume1/music/.
2. Change the location of the default music folder via Synology Control Panel from volume1 to volume2.
3. Use "Mass Editor" on Lidarr to direct the path of music to the new location
4. Confirm that /volume1/music/ does not exist under both "Import" and "Mass Editor".
5. A warning message "Missing root folder: /volume1/music/" will appear after Step 2. And it persists after Step 3&4.

**Expected behavior**
Root folder changes to /volume2/music automatically, or after setting manually. No warning messages are given.

**System info (please complete the following information):**
 - Lidarr Version: 0.4.0.524
 - Operating System: Synology DSM 6.2.1-23824 Update 1
 - mono Version: 5.8.0.108

**Update: 27 Nov**
The warning message has changed to "Multiple root folders are missing: /volume1/music | /volume1/music/" Since both directories are identical, this may suggest another bug.

After some investigation, it appears that the some of the newly-added artists from list import were routed to the non-existent "/volume1/music" folder. All of my current lists have their root folder set to the new "/volume2/music" folder before today's download, which is strange. When I added another list, the artist folders were set to the correct path. I individually clicked the save button of every list already with the correct new root folder, and will see if the old lists still set their new artist folders to the wrong path.

The warning message has also reverted to the original one after editing.

**Update: 28 Nov**
The warning message has somehow disappeared. No actions were taken.

**Comment by Qstick** [comment]
The warning will show if any artist or any list use a root folder. The multiple warning with same paths could definitely be a bug though

**Comment by a575606** [comment]
This also is happening to me. I have a permanent notification in the health section saying: 

Missing root folder: /volume1/Music/

I migrated from the syno community package to a docker container. The files are in the same place but it's a different path. I used the Mass Editor to update all root folders and it was still showing. Then I opened the database file and found another reference to the old path in Import Lists and changed it. But, it's still showing up. Anything else I can check?

**Comment by triksmelb** [comment]
Is this a confirmed issue or am I overlooking something? Also used the Mass Editor to make sure the folder is no longer referenced but the warning continues to appear "Missing root folder: /music/Albums/" All songs are definitely referencing and located now in /music/Artists/"

**Comment by ta264** [comment]
It's not as issue afaik, you probably have the folder tied to a list or something

**Comment by triksmelb** [comment]
Is there a way to see what the warning is referring to - quite hard to find in a several TB library.
