### ISSUE TITLE
"No files found are eligible for import" but there are

### ISSUE THREAD

**Issue by imPRAGMA** [lidarr/Lidarr#550]
**Describe the bug**
In activity after finishing a torrent download it never finds eligable files.

**To Reproduce**
1. Install latest Pre-Release
2. Setup 1337x using Jackett
3. Add Owl City
4. Search for Cinematic (2018) album
5. When it finishes downloading it will occur.

**Expected behavior**
Import and move on

**System info (please complete the following information):**
 - Lidarr Version: Latest Pre-Release 0.4.0.524
 - Operating System: Windows
 - .net Framework: 4.7.2

It cant find files as its searching: C:\Users\PRAGMA\DelugeDownloads\Owl City - Cinematic (2018) Mp3 (320kbps) [Hunter]
but it created a folder inside that named "Owl City - Cinematic (2018)" perhaps theres some kind of issue caused by that?
Regardless if I move the flacs it never works, I try restarting e.t.c still no luck

This is happening for every single torrent I finish

**Comment by Qstick** [comment]
Can you post trace logs? this sounds like permissions issues. @ta264 thoughts?

**Comment by imPRAGMA** [comment]
I installed as a windows service and I have only had it a couple hours since posting this issue.
So it would be kinda odd

**Comment by Qstick** [comment]
What user is the service tied to?

**Comment by ta264** [comment]
What have you set the root artist folder to?

**Comment by imPRAGMA** [comment]
> What user is the service tied to?

My main? i only have 1 user (which is admin)

> What have you set the root artist folder to?

How do I check?

**Comment by ta264** [comment]
Go to the artists page and press edit and its listed as Path

**Comment by imPRAGMA** [comment]
Theres no edit? https://i.imgur.com/EWgr5dg.png

**Comment by ta264** [comment]
You have to click on the relevant artist first

**Comment by imPRAGMA** [comment]
`D:\Plex\Music\Alan Walker` it seems to autoappend the artist name to end of that music path

**Comment by ta264** [comment]
I'm out of ideas then. Without logs there not much else we can do

**Comment by imPRAGMA** [comment]
How do I get logs?

**Comment by imPRAGMA** [comment]
[logs.zip](https://github.com/lidarr/Lidarr/files/2638682/logs.zip)
4 log files.

**Comment by ta264** [comment]
Try it not as a service then and let us know
