### ISSUE TITLE
Recognize Artist from Single Tracks

### ISSUE THREAD

**Issue by Menaxerius** [lidarr/Lidarr#558]
Hi, 
My Music Library Structure looks like This, I have a folder for each Letter, so A, B, C, D and so on, and inside those Folders I have all music files like Artist - Song.mp3 as example while Artist A belongs into folder A and so on. My issue now is, I can't as example choose Folder A and let it "scrape" there. Would be great if there is an option to check files without folders.
Thanks

**Comment by Qstick** [comment]
Scanning re-work will likely solve this
