### ISSUE TITLE
Handling additional files on import

### ISSUE THREAD

**Issue by SoTHISIsFitness** [Lidarr/Lidarr#559]
When Lidarr imports albums, it isn't deleting the source folder because it isn't empty. Currently, Lidarr doesn't seem to have a way to handle "extra" files aside from the option to import an album's nfo.

Please create an option to tell Lidarr to delete any extra files after successful import (perhaps limit it to non-audio files?). Then, after successful import, the folder WILL be empty, and Lidarr will clean it up and delete it.

[AB#459](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/459)

**Comment by Qstick** [comment]
This should already be happening, will investigate

**Comment by SoTHISIsFitness** [comment]
Not the same, no. It's moving the source music files, but any extra files, such as jpg or nfo files are left behind. This issue also presents when renaming files - if a file is renamed/organized and moved, the original folder may be left behind if any extra files remain.









---- On Fri, 18 Jan 2019 19:24:33 -0500 Qstick <notifications@github.com> wrote ----




Same as https://github.com/lidarr/Lidarr/issues/228 ?

**Comment by ta264** [comment]
Are you still having issues with this? If so please post a debug log file.

For what it's worth, lidar will delete folders that contain extra files but no audio files for me.

**Comment by bryangauvin** [comment]
I am having the same issue. Any solution?

**Comment by ta264** [comment]
Do you have a log file? Lidarr is deleting folders just fine for me, even when non audio files are left behind

**Comment by bakerboy448** [comment]
Closing pending additional information and the relevant logs
