### ISSUE TITLE
IPTorrents base URL error

### ISSUE THREAD

**Issue by didyouexpectthat** [lidarr/Lidarr#561]
**Describe the bug**
I am attempting to use IPtorrents.
When I try to test or save the URL provided by IPtorrents, Lidarr complains that the `'Base Url' is not in the correct format.`

**To Reproduce**

1. Navigate to IPTorrents
2. Go to RSS
3. Configure the RSS options, select download link (in lieu of web link), select appropriate music categories
4. IPtorrents produces URL in following format:
`https://iptorrents.com/t.rss?u=USERID;tp=APIKEY;3;80;93;37;download`
where 3, 80, 93, and 37 are the 4 different categories for music. 
5. Copy and paste URL into Lidarr's Add Indexer settings
6. Hit Test connection
7. See error.

**Expected behavior**
I expect the URL from IPTorrents to work when adding indexer IPTorrents.

**Screenshots**
![image](https://user-images.githubusercontent.com/1329077/49420600-17db8f00-f741-11e8-8896-71af9efbb975.png)
![image](https://user-images.githubusercontent.com/1329077/49420635-4eb1a500-f741-11e8-8fa1-bc2cb510ee6b.png)

**Logs**
```
18-12-4 05:22:39.1|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- 'Base Url' is not in the correct format.
18-12-4 05:22:39.1|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (8 ms)
18-12-4 05:22:40.9|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- 'Base Url' is not in the correct format.
18-12-4 05:22:40.9|Debug|Api|[POST] /api/v1/indexer: 400.BadRequest (7 ms)
```

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.576
 - Operating System: Debian 9
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono Linux 5.16.0.220

**Additional context**
Nothing else. 
Thank you.

**Comment by Rsslone** [comment]
Same here.

**Comment by Qstick** [comment]
I've got no way to test/debug this as I have no account.

**Comment by didyouexpectthat** [comment]
I can confirm that both of the URLs produce the same output.

**Comment by Qstick** [comment]
So does `https://iptorrents.com/torrents/rss?u=snip;tp=snip;3;80;93;37;download` work in Lidarr?

**Comment by didyouexpectthat** [comment]
Yes, it does.

**Comment by Qstick** [comment]
Perfect!

**Comment by didyouexpectthat** [comment]
IPTorrents made this change on November 26th. Is there a way to support both URL styles?

**Comment by Qstick** [comment]
Yep, working on that now.

**Comment by mattiasghodsian** [comment]
Still not working

https://iptorrents.com/t.rss?u=USERID;tp=KEY;24;79;22;5;99

**Comment by Dwight2019** [comment]
Hi,  

I'm still facing this same issue when trying to configure IPTorrents.

**Comment by Qstick** [comment]
Version?

**Comment by Dwight2019** [comment]
Version: 2.0.0.5322

**Comment by Qstick** [comment]
This is Lidarr repo, that’s not a valid version of Lidarr

**Comment by Dwight2019** [comment]
My apologies - This is for Sonarr, seems they have a very similar GUI and error messages.

**Comment by Qstick** [comment]
Yea I don't think they have fixed this yet

**Comment by squeeb** [comment]
Still not fixed.

**Comment by mcbobke** [comment]
Still not fixed.

**Comment by kynrek** [comment]
Still not fixed.
