### ISSUE TITLE
Unable to parse album title with special characters

### ISSUE THREAD

**Issue by 4tjARdp2KWnF** [lidarr/Lidarr#564]
**Describe the bug**
Trying to import the 3rd album from Caravan Palace whose title is simply "<|°_°|>" (aka Robot Face).

https://musicbrainz.org/release-group/1346c819-d57b-4c38-aa55-1e599dfc3645

**To Reproduce**
1. Set logging level to trace.
2. Click Refresh & Scan button on Caravan Palace artist.
3. Observe failure in logs.

**Expected behavior**
All tracks from this album should be imported.

**Logs**
[Debug] Parser: Starting Tag Parse for /music/Caravan Palace/<|<C2><B0>_<C2><B0>|>/01-caravan_palace-lone_digger.mp3 
[Trace] Parser: File Tags Parsed: Artist: Caravan Palace, Album: <, Disc: 0, Track Numbers(s): 1, TrackTitle: Lone Digger 
[Debug] Parser: Audio Properties : MPEG Version 1 Audio, Layer 3 VBR, Bitrate: 128, Sample Size: 0, SampleRate: 44100, Channels: 2 
[Debug] QualityParser: Trying to parse quality for /music/Caravan Palace/<|<C2><B0>_<C2><B0>|>/01-caravan_palace-lone_digger.mp3 
[Debug] Parser: Quality parsed: MP3-VBR-V0 v1 
[Debug] ParsingService: Cleaning Album title of common matching issues. Cleaned album title is '<' 

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.576
 - Operating System:  Docker image from https://github.com/linuxserver/docker-lidarr
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.16.0.220

**Comment by ta264** [comment]
Please can you post a full set of Trace logs?  Go into settings and set the degub level to trace, I think it's under general.

I'm not sure that album name should trip it up, I think there might be another issue.

**Comment by ta264** [comment]
Closing this pending log files. In any case it should be fixed in #592
