### ISSUE TITLE
Add "Preview Rename" at root level

### ISSUE THREAD

**Issue by 4tjARdp2KWnF** [lidarr/Lidarr#566]
**Is your feature request related to a problem? Please describe.**
I've encountered a situation where an artist has released two albums with the same name but in different years.  MusicBrainz shows these as separate albums.  I've decided to globally change my album folder names from just 'Album' to 'Album (Year)'.

**Describe the solution you'd like**
I wish there was a 'Preview Rename' button at the top post level (the level that shows all the artists) so that with one click, I can convert my entire library to the new naming format.

**Describe alternatives you've considered**
I have been using linux utils find/grep from the command line to locate album names that need to be updated, going to the artist in the web interface, and clicking the 'Preview Rename' button there.

**Comment by gismo2004** [comment]
This is already available?!

Go to "Mass Editor", select artists you want to rename (or "all") and press the "Rename Files" button.

**Comment by Qstick** [comment]
Agree
