### ISSUE TITLE
New 'UI' option - Always expand <item>

### ISSUE THREAD

**Issue by 4tjARdp2KWnF** [lidarr/Lidarr#567]
**Is your feature request related to a problem? Please describe.**
Every time I go to an artist, I always find all the sections are collapsed.  I am always expanding the 'Album' section.

**Describe the solution you'd like**
Add an option to the 'UI' section, that presents check boxes for which types should be automatically expanded or left collapsed.  A checked checkbox would mean automatically expand it.  An unchecked checkbox would mean leave it collapsed.

**Describe alternatives you've considered**
I manually expand the sections and it's very repetitive (i.e. read: frustrating).

**Comment by ravensorb** [comment]
Completely agreed

**Comment by TangoMikeOscar** [comment]
Agreed, its very annoying.
