### ISSUE TITLE
Provisioning Lidarr with predefined settings (proxy, trackers, downloaders)

### ISSUE THREAD

**Issue by dakipro** [lidarr/Lidarr#568]
(maybe this exists already, I could not find any more info, only place in files I was able to find proxy and indexers etc is inside sqllite file lidarr.db)
**Is your feature request related to a problem? Please describe.**
I use Ansible to provision Lidarr, and would like to pre-set which downloader it should use, which proxy, indexers etc. 

**Describe the solution you'd like**
configuration file where Lidarr would get such configuration from (maybe even some boot-feed file, where it would read data and copy it in database, then delete the file)

**Describe alternatives you've considered**
Perhaps create API endpoints to push such config parameters after lidarr is up. Even some parameters from command line would fine, pretty much all provisioning tools can do any of the alternatives

**Additional context**
Traefik uses yml file/format for configuration, like https://docs.traefik.io/user-guide/examples/

**Comment by Qstick** [comment]
I believe the proxy info is in config.xml which you could deploy with Lidarr, and API is already available to push indexers or clients if you wanted to.

**Comment by Qstick** [comment]
Proxy info is actually stored in the db config table. if you wanted you could deploy with a db that is configured how you want it or use the API to modify the config values during setup.
