### ISSUE TITLE
Allow GET / POST of ForeignArtistId / Musicbrainz Album Id via API

### ISSUE THREAD

**Issue by RevenantOne** [lidarr/Lidarr#578]
**Is your feature request related to a problem? Please describe.**
I've imported a sizable library of music and Lidarr seems to have trouble picking the correct release. I've been using beets as my music library so I know what's been imported should match as it's gets all the metadata from Musicbrainz as well. Despite this I still have over 2000 albums that require manual matching.

**Describe the solution you'd like**
An API endpoint that allows the GET and POST of an albums ForeignArtistID field.
(I'm aware the [Album](https://github.com/lidarr/Lidarr/wiki/Album) endpoint contains it, but I cannot update this as far as I know)

**Describe alternatives you've considered**
I've tried manually updating the lidarr.db (using a SQL statement I found on Reddit but am unable to find now...) with the correct ForeignArtistId/Musicbrainz Album ID and despite Lidarr displaying the correct ForeignArtistId for the affected albums it still mismatches tracks. (I assume it's a missed update or something that causes the mismatches)

**Comment by Qstick** [comment]
Which version are you on?

**Comment by ta264** [comment]
This will be fixed in my rewrite of the import code - once it's finished anything that's got the correct musicbrainz id tags should import seamlessly

**Comment by RevenantOne** [comment]
> 
> 
>anything that's got the correct musicbrainz id tags should import seamlessly

Just to clarify, I use Lidarr to just grab the releases and use a custom SABnzbd post processing script that imports releases, tags them, moves them, etc via beets. Lidarr uses the same root directory as beets so in they should see exactly the same thing and just work... in theory.

Does this qualify as being imported by Lidarr or do I need to set Lidarr to do the renaming and moving of files?

**Comment by ta264** [comment]
Yes, that would count as being imported by lidarr.

If you're feeling brave, try the freshly minted 0.5.0.633 which should seamlessly import anything tagged by beets.
