### ISSUE TITLE
API endpoint /release/push doesn't add release correctly - protocol wrong?

### ISSUE THREAD

**Issue by petwri** [lidarr/Lidarr#579]
**Describe the bug**
When adding a previously found release via the API endpoint /release/push, the DL is not added properly to the queue, the download protocol seems to be missing.

**To Reproduce**
Call `/release/push` with parameters `{'title': result["title"], 'downloadUrl' : result["downloadUrl"], 'protocol' : result["protocol"], 'publishDate' : result["publishDate"]}` as defined in the [API doc
](https://github.com/lidarr/Lidarr/wiki/Release-Push)

**Expected behavior**
The release should be added to the DL-queue with the correct protocol and started right away.

**Logs**
The json reply fom the API call contains a `{u'protocol': u'unknown'`, the download is added to the queue, but it says the protocol unknown, the download client not available.

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System Ubuntu 16.04 / Linux 4.12.14-041214-generic
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.16.0.220

**Comment by Qstick** [comment]
Believe this is changed to DownloadProtocol now instead of Protocol. Try that when calling release push. I'll correct the docs

**Comment by petwri** [comment]
Thanks, downloadProtocol works!
