### ISSUE TITLE
"error": "Invalid non-ASCII or control character in header: 0x0009"

### ISSUE THREAD

**Issue by MrTyton** [lidarr/Lidarr#581]
**Describe the bug**
Cannot grab album from manual search.

**To Reproduce**
Add amazarashi, try to search for the first album with jpopasia. It then fails to grab, and the system reports an indexer error.

**Logs**
`Downloading torrent file for release 'amazarashi - Chihoutoshi no Memento Mori`

`NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [*(url)*/dl/jpopsuki/?jackett_apikey=*key*&path=*path*&file=amazarashi+-+Chihoutoshi+no+Memento+Mori%09%09%09[FLAC+%2F+Lossless+%2F+WEB]+[2017.12.13]]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00131] in C:\projects\lidarr\src\NzbDrone.Common\Http\HttpClient.cs:100 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\projects\lidarr\src\NzbDrone.Common\Http\HttpClient.cs:264 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteAlbum remoteAlbum, System.String torrentUrl) [0x00024] in C:\projects\lidarr\src\NzbDrone.Core\Download\TorrentClientBase.cs:134 
{
  "result": "error",
  "error": "Invalid non-ASCII or control character in header: 0x0009",
  "stacktrace": "  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter (System.Char ch) [0x00015] in <708a61b06ae647a09457b7bb52b351ad>:0 \n  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters (System.String headerCharacters) [0x00015] in <708a61b06ae647a09457b7bb52b351ad>:0 \n  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters (Microsoft.Extensions.Primitives.StringValues& headerValues) [0x00012] in <708a61b06ae647a09457b7bb52b351ad>:0 \n  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast (System.String key, Microsoft.Extensions.Primitives.StringValues& value) [0x00000] in <708a61b06ae647a09457b7bb52b351ad>:0 \n  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item (System.String key, Microsoft.Extensions.Primitives.StringValues value) [0x0002d] in <708a61b06ae647a09457b7bb52b351ad>:0 \n  at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetContentDispositionHeader (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileResult result) [0x0004e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.SetHeadersAndLog (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileResult result, System.Nullable`1[T] fileLength, System.Boolean enableRangeProcessing, System.Nullable`1[T] lastModified, Microsoft.Net.Http.Headers.EntityTagHeaderValue etag) [0x00023] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Infrastructure.FileContentResultExecutor.ExecuteAsync (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.FileContentResult result) [0x0004b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.FileContentResult.ExecuteResultAsync (Microsoft.AspNetCore.Mvc.ActionContext context) [0x0001e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync (Microsoft.AspNetCore.Mvc.IActionResult result) [0x00049] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync] () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResultExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync] (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x003df] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters () [0x00030] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 \n  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 \n  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 \n  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <0137008cf4d14ba98441b2fbac6ddcc8>:0 "
}`

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System Linuxserver Docker Image
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by Qstick** [comment]
This is a jackett error thats getting passed thru to Lidarr.
