### ISSUE TITLE
Ability to add sampler series

### ISSUE THREAD

**Issue by hr1232** [lidarr/Lidarr#582]
**Is your feature request related to a problem? Please describe.**
Sampler Series like [Bravo Hits](https://musicbrainz.org/series/1350fce9-08ab-40ba-a7bb-ed3cfb869499) cannot be added because they need to be queried differently from musicbrainz.

**Describe the solution you'd like**
Allow to add not only artists but also samplers

**Additional context**
look at headphones for an example they have a dropdown menu to select artist or sampler

**Comment by Qstick** [comment]
Will add this after we have support for Various Artists.

**Comment by varac** [comment]
@Qstick which issue tracks `support for Various Artists` ?

**Comment by varac** [comment]
Found it: #207

**Comment by ta264** [comment]
It requires #839 then #844 will enable it

**Comment by Ageraluon** [comment]
Now that the various-artists tree has been merged, any update on this perhaps?
https://github.com/lidarr/Lidarr/pull/839

Adding a series via its id might be the first step, might now be actually a rather quick thing to do (?)

**Comment by ta264** [comment]
Implemented in #2224
