### ISSUE TITLE
Lidarr hangs a long time on retrieving non-existent Root Path

### ISSUE THREAD

**Issue by irritatedcone** [lidarr/Lidarr#584]
**Describe the bug**
I switched file-servers a few weeks back and added my new path as the new root folder.
Everytime I went to request something it would take a long time to show me the paths I could use (manually adding them gave me the "already configured as root path" message).
When I removed the no longer existing path everything was near instant again.

It takes too long for Lidarr to stop trying to reach that path.
It also doesn't show you ANY path until it times out, and it doesn't say it's still searching for paths.

This issue is in Sonarr, Radarr and in Lidarr, so I'll create a bug report in all.

**To Reproduce**
1. Have existing root path
2. Switch root path to new server / folder
3. Make sure old path is dead
4. Attempt to request something

**Expected behavior**
It shows you what paths you have instantly, instead of after 7-8 minutes.

**Screenshots**
![root paths](https://user-images.githubusercontent.com/44037605/50725173-f7b13e00-10f9-11e9-9d75-76d0a2384ada.PNG)
0b = dead fileserver
12.5TB = new fileserver
(Change Films to Music for actual path name)

**Logs**
No logs made - I figured out that this was the issue after removing the non-existent path. Since the path doesn't exist anymore I can't re-add it to provide debug logs :(

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: Windows Server 2016

**Comment by Qstick** [comment]
Reference upstream: https://github.com/Sonarr/Sonarr/issues/2877

**Comment by Qstick** [comment]
Fixed https://github.com/lidarr/Lidarr/commit/74cb2a6f5235111b1877178e628c94e7708d4d17
