### ISSUE TITLE
Not displaying all albums

### ISSUE THREAD

**Issue by ekyriakides** [lidarr/Lidarr#591]
**Describe the bug**
I've added a new artist (Allen/Lande, https://musicbrainz.org/artist/8123f944-5770-4bb8-baf6-8a217a1abff8) which clearly have 4 albums but Lidarr only picks up 2.

**To Reproduce**
1. Go to Add New
2. Search for Allen/Lande or add by ID (https://musicbrainz.org/artist/8123f944-5770-4bb8-baf6-8a217a1abff8)
3. Click to see albums

**Expected behavior**
4 Albums should show up

**Logs**
```
9-1-15 17:28:04.5|Info|AddArtistService|Adding Artist [8123f944-5770-4bb8-baf6-8a217a1abff8][Allen/Lande] Path: [/music/Allen+Lande]
19-1-15 17:28:04.5|Info|RefreshArtistService|Updating Info for Allen/Lande
19-1-15 17:28:09.8|Info|RefreshTrackService|Starting track info refresh for: [1040f40f-7a06-46a9-b8d4-dad7000340f9][The Great Divide]
19-1-15 17:28:09.8|Info|RefreshTrackService|Finished track refresh for album: [1040f40f-7a06-46a9-b8d4-dad7000340f9][The Great Divide].
19-1-15 17:28:09.8|Info|AddAlbumService|Adding Album The Great Divide
19-1-15 17:28:10.1|Info|RefreshTrackService|Starting track info refresh for: [48d1b25c-4a7b-35ff-849f-a335fc645720][The Battle]
19-1-15 17:28:10.1|Info|RefreshTrackService|Finished track refresh for album: [48d1b25c-4a7b-35ff-849f-a335fc645720][The Battle].
19-1-15 17:28:10.1|Info|AddAlbumService|Adding Album The Battle
19-1-15 17:28:10.1|Info|DiskScanService|Scanning Allen/Lande
19-1-15 17:28:10.1|Info|MetadataService|Artist folder does not exist, skipping metadata creation
19-1-15 17:28:10.1|Info|DiskScanService|Completed scanning disk for Allen/Lande
19-1-15 17:28:10.1|Info|ArtistScannedHandler|[Allen/Lande] was recently added, performing post-add actions
19-1-15 17:33:33.0|Info|RssSyncService|Starting RSS Sync
```

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System UnRAID with Docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.18.0.225

**Comment by ta264** [comment]
I guess this is because Allen/Lande is not the first artist credit for the missing two albums.  Not sure whether we should relax that constraint.

**Comment by ekyriakides** [comment]
@ta264 Given it's much harder to change MusicBrainz to have Allen/Lande as the first contributing artist, maybe it would be a good idea for Lidarr to have them show up (or maybe an option to).

**Comment by ekyriakides** [comment]
@ta264 I've submitted an edit to have Allen/Lande first - Will revert to see if that fixed the issue. It might be a good idea though to have an option for what you suggested above.

**Comment by ta264** [comment]
It'll take at least 24 hours to filter through to lidarr so give it time.

This is really an issue for the metadata API rather than lidarr. @qstick @imadeofwaxdanny would it be safe to relax this on the metadata side?

I guess the danger is the album would show up 3 times if you also added Allen and Lande separately which might cause even more complaints...

**Comment by ekyriakides** [comment]
Great - thanks for the input. I've already submited changes.

**Comment by danielunderwood** [comment]
@ta264 perhaps it's something we could do when we get to add by album? Then we could have a constraint that albums are unique and allow multiple artists to add/show them while actually handling parsing logic on a per-album basis.

**Comment by Qstick** [comment]
I would agree that once we break the artist folder reliance and centralize around album objects we can use artist metadata for the artist list and albums can show up under each artist. Parsing would be unaffected at that point.

**Comment by Cantello** [comment]
So the artist has to be the first credited? I have two albums that I cannot add as I have only the second artist added to the library (https://musicbrainz.org/release/99025112-73d7-42fd-8dea-50886f78b10e & https://musicbrainz.org/release/7b3820d1-9749-4dc8-a829-385da4c3672a).
Seems to be a bit cumbersome to add all contributing artists in order to get all releases from one particular artist, but I can understand the underlying problems...

**Comment by ta264** [comment]
Correct, the album will only be listed under the primary artist
