### ISSUE TITLE
Feature Request: Delete option for unmapped files

### ISSUE THREAD

**Issue by y2kbadbug** [lidarr/Lidarr#599]
When dealing with unmapped files, I was looking for an option to possibly clean out unmapped files, or select files for deletion.

Two options I think would be good to take into consideration
1) Option to clean all unmapped files, either by artist, global, etc.
2) Option to delete files when clicking view unmapped files under the Artist section.
3) Possibly a global option to view all unmapped files for entire directory, so we can clean them out.

I think the biggest thing is getting a Delete option when viewing unmapped files in general.

Thanks!

**Comment by Qstick** [comment]
Scanning re-write should make this much easier. We will have better eyes on what is mapped and what is not.
