### ISSUE TITLE
Lidarr doesn’t import Apple Music M4P Files

### ISSUE THREAD

**Issue by Ashkaan** [lidarr/Lidarr#603]
**Describe the bug**
My entire downloaded Apple Music library is empty according to Lidarr.

**To Reproduce**
Add Artists to Lidarr from my library.

**Expected behavior**
All of my downloaded tracks should be detected by Lidarr.

**Logs**
```
19-1-26 00:23:03.2|Info|ArtistScannedHandler|[Chromatics] was recently added, performing post-add actions
19-1-26 00:23:03.5|Info|MediaCoverService|Downloading Fanart for [c89ea689-c053-4d97-bada-8b81a6236f58][Chromatics] http://assets.fanart.tv/fanart/music/c89ea689-c053-4d97-bada-8b81a6236f58/artistbackground/chromatics-4f633f6b38487.jpg
19-1-26 00:23:03.6|Info|RefreshTrackService|Starting track info refresh for: [dc91b099-b1fa-4cfc-8e18-e80e8fbca236][Sparks EP]
19-1-26 00:23:03.6|Info|RefreshTrackService|Finished track refresh for album: [dc91b099-b1fa-4cfc-8e18-e80e8fbca236][Sparks EP].
19-1-26 00:23:03.6|Info|AddAlbumService|Adding Album Sparks EP
19-1-26 00:23:04.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
19-1-26 00:23:04.1|Info|ExistingLyricImporter|Found 0 existing lyric files
19-1-26 00:23:04.1|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
19-1-26 00:23:04.1|Info|ExistingExtraFileService|Found 0 extra files
19-1-26 00:23:04.2|Info|RefreshArtistService|Updating Info for Chromeo
```

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.18.0.240

**Additional context**

**Comment by ta264** [comment]
Can you post a directory listing of your Apple music download files?

**Comment by Ashkaan** [comment]
For example, I have this album, but it doesn't show.
Chromeo\White Women
Zero of my thousands of albums show up.

**Comment by Qstick** [comment]
We need to actually see the directory listing and the files inside. Can you post a screenshot or list of files not being imported?

**Comment by Ashkaan** [comment]
It's everything.  I mean tens of thousands of songs.  This is not a simple character mismatch.  You would think that at least a percentage would be named perfectly.  There is a more systemic issue here.

**Comment by ta264** [comment]
Just a sample then. Have no idea what format is used or if the directory structure is compatible

**Comment by Qstick** [comment]
Thanks that’s what we needed, m4p is not caught by the importer, we will look at adding it. It all depends on how much info we can get from the file given it’s aac with apple drm copy protection.

**Comment by Ashkaan** [comment]
Is there any way to have it at least show up (even as Unknown)?

**Comment by Qstick** [comment]
Yea we can add it as a valid media extension so that scan service picks it up as an audio file.

**Comment by Ashkaan** [comment]
Any chance this can get implemented soon?

**Comment by ta264** [comment]
Its not top of the list.  It's hopefully straightforward but we don't have any sample files to test with.

**Comment by Ashkaan** [comment]
Here you go: https://we.tl/t-DdEAw5qOmC

**Comment by ta264** [comment]
There are some test builds [here](https://ci.appveyor.com/project/Lidarr/lidarr/builds/22728494/artifacts).  Please can you give it a go and let me know if it works as expected?  I have tested that the tags can be read but I don't have a full library in `.m4p`  to test the import/quality stuff properly.

**Comment by Ashkaan** [comment]
Yes, it worked!!!

It says "Unknown" under the Audio Info, but this is major!

![image](https://user-images.githubusercontent.com/5667978/53597454-0eeb3580-3b57-11e9-8280-348d2d3a9472.png)

**Comment by Qstick** [comment]
@ta264 see 
https://sentry.io/organizations/lidarr/issues/912762173/?project=209545&statsPeriod=14d&utc=false for the codec format to catch in the formater to fix unknown

**Comment by ta264** [comment]
This version should fix the unknown audio info
https://ci.appveyor.com/project/Lidarr/lidarr/builds/22756495/artifacts

**Comment by Ashkaan** [comment]
Yes, thank you so much!

![image](https://user-images.githubusercontent.com/5667978/53667867-2134a480-3c27-11e9-93e4-33d249f66e0f.png)
