### ISSUE TITLE
Internationalized artist search problems

### ISSUE THREAD

**Issue by rootwyrm** [lidarr/Lidarr#610]
This is a list of artists with internationalization which return results on Musicbrainz but fail to return results on Lidarr for various reasons.

[Snail's House](https://musicbrainz.org/artist/cfd45526-701e-457a-b3bd-013506a890a6) - lidarr:lidarr:cfd45526-701e-457a-b3bd-013506a890a6
* Lidarr fails search "Snail's House"
* Musicbrainz succeeds with correct artist as top result
* DOES import by MBID
* DOES import releases correctly
* MB: `’`, Lidarr input box: `'` - IDN apostrophe issue
* [LidarrAPI.Metadata #96](https://github.com/lidarr/LidarrAPI.Metadata/issues/96)

[Yukihiro Fukotomi](https://musicbrainz.org/artist/5ae575a5-3c2d-4cbb-9fe5-be806d5946ae) - lidarr:5ae575a5-3c2d-4cbb-9fe5-be806d5946ae
* Lidarr fails search "Yukihiro Fukotomi"
* Musicbrainz succeeds locating the correct artist by Romanized name "Yukihiro Fukotomi" (Sort Name)
* Musicbrainz artist is: 福富幸宏
* Lidarr SUCCEEDS with "福富幸宏"

[Yasuyuki Okamura](https://musicbrainz.org/artist/da3d15ea-4011-4cc7-bd73-b4192891c1d4) - lidarr:da3d15ea-4011-4cc7-bd73-b4192891c1d4
* Lidarr fails search "Yasuyuki Okamura"
* Musicbrainz succeeds with the correct artist as first result (Sort Name)
* Musicbrainz artist is: 岡村靖幸
* Lidarr SUCCEEDS with "岡村靖幸"

[Кипелов](https://musicbrainz.org/artist/76f95aaa-9be1-47a1-8db8-731cb77cf938) - lidarr:76f95aaa-9be1-47a1-8db8-731cb77cf938
* Lidarr fails search "Кипелов"
* Musicbrainz succeeds with the correct artist as first result (Artist Name)
* Musicbrainz artist is: Кипелов
* Lidarr FAILS with "Кипелов"
* Lidarr UUID result produces artist result "Кипелов"

Will add more as I run into them.

**Comment by Qstick** [comment]
#2 and #4 are solved in https://github.com/lidarr/LidarrAPI.Metadata/pull/97

**Comment by ta264** [comment]
These should all be resolved now
