### ISSUE TITLE
Manual Import - Select Album - Album not in List

### ISSUE THREAD

**Issue by rudyolph** [lidarr/Lidarr#611]
For artists with very large numbers of albums not all of the albums appear to be showing up in the album selection drop down box when trying to manually import a file.

1.) Add artist Andew Lloyd Weber
2.) Try to manually import a file into album: Jesus Christ Superstar (1970 original London concept cast)

That album would show up in the list but it is not in the list.  

 - Lidarr Version: 0.5.0.583
 - Operating System: Win 10
 - .net Framework (Windows)

**Comment by Qstick** [comment]
Add or edit your metadata profile to include soundtracks, works fine here

![38a12e52-122f-45fb-8a11-299ae2c99776](https://user-images.githubusercontent.com/376117/52155944-4992a880-2653-11e9-81b3-080ac7c316ce.jpeg)

**Comment by Qstick** [comment]
No, it will be sortable in 0.6

**Comment by rudyolph** [comment]
[image: image.png]

**Comment by rudyolph** [comment]
![image](https://user-images.githubusercontent.com/28231598/52156940-8bbee880-2659-11e9-95f6-28d2eac6e952.png)

**Comment by rudyolph** [comment]
It is not in my list even with the album-soundtrack metadata profile used.

**Comment by rudyolph** [comment]
Is that drop down a limited size?

**Comment by Qstick** [comment]
Nope, scroll bar on side as you can see. I’m running nightly so possible it was fixed in near future.

![a2f345ec-3f6d-4b6f-87fa-0afa9524e31f](https://user-images.githubusercontent.com/376117/52157118-a6de2800-265a-11e9-9184-2e36708aae7e.jpeg)

**Comment by rudyolph** [comment]
yeah i know there is a scrollbar...but the list could still be limited to be a max size.

**Comment by Qstick** [comment]
You are right, the presence of a scroll bar doesn’t mean it’s not limited... but it’s not limited. If you want to jump on Discord we can try to get it figured out, it will be easier to go back and forth.

**Comment by rudyolph** [comment]
brt
