### ISSUE TITLE
Reverse Proxy Nginx

### ISSUE THREAD

**Issue by dlwebmaestro** [lidarr/Lidarr#614]
**Describe the bug**
When trying to setup a reverse proxy, I get a 400 error.  (Bad request - invalid hostname.)  I know the host name is correct.  

**To Reproduce**
1. Set URL base to /lidarr
2. Restart Lidarr
3. Insert reverse proxy code into nginx.conf
4. Restart Nginx
5. Browse to https://domain.com/lidarr
6. See error

**Expected behavior**
It should load Lidarr.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.5.0.583]
 - Operating System: Windows 10
 - .net Framework Versions: 2.0.50727, 3.0, 3.5, 4, 4.0

**Additional context**
Here is the code I use in my nginx.conf file.  I use the same code for Radarr and Sonnar, changing the ports and folder names of course, and they both work as expected.

```javascript
      location /lidarr/ {
               #auth_request /auth-admin;
               add_header X-Frame-Options "SAMEORIGIN";
               proxy_set_header Host $host;
               proxy_set_header X-Forwarded-Host $server_name;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Ssl on;
               proxy_set_header X-Forwarded-Proto $scheme;

               proxy_pass http://127.0.0.1:8686;
               proxy_redirect http://127.0.0.1:8686 https://$host;
       }
```

**Comment by ta264** [comment]
This is certainly possible, I personally use an nginx reverse proxy.  There must be an error with your config. Note we are using the sonarr V3 API so there's no guarantee that what works for sonarr or Radarr should work here.

My config:
```
    location /lidarr {
        proxy_pass http://192.168.0.3:8686;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
```

Though this does work for all three apps.
