### ISSUE TITLE
Disabling Completed Download Handling removes all items that couldn't be imported automatically from queue

### ISSUE THREAD

**Issue by sasjafor** [lidarr/Lidarr#619]
**Describe the bug**
When I disable completed download handling, all items that were previously shown in the activity queue, which were downloaded but not automatically imported, disappear.

**To Reproduce**
1. Disable completed download handling
2. Go to Activity -> Queue

**Expected behavior**
That as yet unimported items stay in the activity queue so that I can import them manually. I want to (for now) always import manually, as using the automatic import is just too much of a headache at the moment. Too often have songs disappeared, just because they couldn't be imported automatically. 
And disabling deletion of downloaded files after import is also not an option, because then a lot of junk will remain (.nfo files, .cue files, etc). 

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System Linux, unRAID
 - mono Version: 5.18.0.240

**Comment by ta264** [comment]
This has been fixed in a sense - an item will remain in the import queue if not all items are imported.  But completed download handling must be enabled and I don't imagine that will change.

**Comment by sasjafor** [comment]
Yeah that will definitely help. As I can have download handling activated without fearing that a song might get lost and I can still manually import it. Thank you.
