### ISSUE TITLE
Release Group in the 'Live' section not appearing

### ISSUE THREAD

**Issue by rmccu** [lidarr/Lidarr#620]
**Describe the bug**
When I add an artist with a profile that has all checkboxes selected (and refresh), I am not seeing one of the release groups for the artist. If you look at the artist page on MusicBrainz (https://musicbrainz.org/artist/4a536dbf-8632-4cfd-b9ea-cdb35cb47c44), you will notice 2 release groups named "No Quarter". One is a "(live album)" under the "Album + Live" section, the other is "(concert video)" under the "Live" section. I cannot get the "(concert video)" to show up in Lidarr.

**To Reproduce**
1. Add the artist "Jimmy Page & Robert Plant" (4a536dbf-8632-4cfd-b9ea-cdb35cb47c44)
2. Set the profile to include EVERYTHING (refresh if needed)
3. Notice the album "No Quarter (live album)" is available (96223279-d70a-3e8b-be19-3cddd9a772a8)
4. However, the release group "No Quarter (concert video)" is not available (3aed06f4-d09a-4598-8c2d-d3f774c836a5)

I want to add that album/release group. Here is the MusicBrainz link: https://musicbrainz.org/release-group/3aed06f4-d09a-4598-8c2d-d3f774c836a5

**Expected behavior**
The "(concert video)" version of the album should show up on the Artist page in Lidarr.

**Screenshots**
I think I explained my issue sufficiently, but please ask what clarifying screenshots I can add.

**Logs**
Let me know if this is necessary, but I don't know that this would help.

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: FreeNAS 11.2
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.10.1.57

**Additional context**
N/A

**Comment by rmccu** [comment]
I also posted this in the discord chat, wasn't sure what the appropriate location was for this.

**Comment by rmccu** [comment]
I am also seeing this with Eliminator by ZZ Top. There are a couple of versions of this album that are "CD + DVD-Video" that do not appear:
https://musicbrainz.org/release-group/c58b50f0-d7a4-322c-b281-d86ebe3b8acf

**Comment by Qstick** [comment]
Given Lidarr doesn’t support video files, what’s the reason for wanting to see it?

**Comment by ta264** [comment]
I mentioned this on discord but for the record on here: I think the Jimmy Page one is missing on 583 because it's missing a primary type.  But even if that is fixed, on the 0.4 metadata feed (so 595+) will explicitly remove any video tracks.  And the fingerprinting PR will remove any video media even of the tracks are not explicitly marked as video.

**Comment by rmccu** [comment]
Ok, I think I understand what you were trying to say now @ta264. So, what I have is some audio files that have been extracted from the DVD-Video. Would I need to add another release to the "Album + Live" release that represents the audio files from the DVD-Video?
