### ISSUE TITLE
Add Alac 24Bits in profile

### ISSUE THREAD

**Issue by Mrpink200** [Lidarr/Lidarr#621]
Hello

Many thanks for the good work with this app.
I find it really helpfull to organize and maintain a music library with the best possible audio tracks quality !!

For itunes compatibility reasosn, i have converted all my flac24 files to alac 24 bits to have all my music both on my audiophile music player (volumio on a RPI + dac) and my macbook. I was fed up having duplicates between my alac classicla lossless 16 bits and what i found with flac24bits

Now that my organisational issue is solved with all my 24 bits files integrated to itunes thx to alac24, i m lost with lidarr that does not seem to consider ala24 as a hightest audio quality format than standard lossless file.
Could it be possible to create an alac 24bit profile (like what have been done with flac 24) to solve this situation ?

Many thx !!

Best Regards
Al

[AB#323](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/323)

**Comment by rmccu** [comment]
I am in a similar position and would love to see this change.

**Comment by retrography** [comment]
Why not customized quality profiles/definition? Like that we can add DSD, DSF, and whatever else we like. Also, maybe a way to strictly exclude some quality profiles like Vinyl Rips? I tried adding quality definitions in sqlite, but it seems the number of definitions is hard coded into the software, as any change swiftly breaks it.

**Comment by Qstick** [comment]
Vinyl rips can be excluded by using release profiles. Improving qualities is something we have thought about but is not high on the list right now. Theres a bit more to it than just allowing user to add and name a quality. Lidarr has to know how to parse that quality, how to identify the track is of a certain quality, etc..

**Comment by Mrpink200** [comment]
please :( :( :(

**Comment by Mrpink200** [comment]
> Vinyl rips can be excluded by using release profiles. Improving qualities is something we have thought about but is not high on the list right now. There's a bit more to it than just allowing user to add and name a quality. Lidarr has to know how to parse that quality, how to identify the track is of a certain quality, etc..

alac24 should be as easy as flac24, no ?
it s a real pain in the ass, lidarr re download  flac 24bits version i have downloaded and converted to alac 24bits :(
i do not find any way to avoid this :'(

**Comment by Mrpink200** [comment]
up :(

**Comment by Mrpink200** [comment]
I do not understand how a that simple request can be ignored. I finally convert back all my library to flac24 :(

**Comment by bakerboy448** [comment]
It’s not ignored.

there is only so much time in a day and so many resources to work on items.

if you want it right now then dive in and make a PR to add it 

Also it looks like this thread is full of several comments that do not provide benefit to the conversation.  Comments such as me too, I want this, why isn’t this done yet, and other non-productive comments may result in threads being locked.

**Comment by jeffbyrnes** [comment]
Never having worked on a C# project before, I nonetheless somewhat blindly tried to add an ALAC 24bit quality in #3882. Builds failed, so I’ll try to stumble my way through 😅
