### ISSUE TITLE
Lidarr -Not able figure out quality of releases

### ISSUE THREAD

**Issue by JonathanGorbutt** [lidarr/Lidarr#626]
Hi Everyone,

Quite new to Lidarr but was asked to post this on here when discussing in the discord...

Lidarr seems to have problems grabbing quality of releases even though its clear as day in the title of the release for example please see image below:

https://i.imgur.com/iKfsh0s.png

Hope this helps

-Jonathan

**Comment by ta264** [comment]
Added to #449
