### ISSUE TITLE
Wrong album entries

### ISSUE THREAD

**Issue by aristosv** [lidarr/Lidarr#627]
**Describe the bug**
I added artist AC/DC and got 18 released albums. That's incorrect, there's only 17 released albums from AC/DC as seen here. https://en.wikipedia.org/wiki/AC/DC_discography. Lidarr added "Highway to Hell" twice. In 1979 & 2001. The 2001 entry should not exist.

**To Reproduce**
Add artist AC/DC, you'll see 18 released albums. There should only be 17.

**Expected behavior**
Show only 17 released albums.

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System Debian Stretch (Container)

**Comment by Qstick** [comment]
This is a musicbrainz issue, not a lidarr issue.

**Comment by aristosv** [comment]
Is there a way I can remove the wrong entry from lidarr?

**Comment by Qstick** [comment]
Someone has already put in an edit to fix it. Should go thru soon
