### ISSUE TITLE
Disable built in update when running in docker

### ISSUE THREAD

**Issue by ta264** [lidarr/Lidarr#628]
It's not good practice to update an application in a docker container.

https://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed/46181627

#617 adds detection of a docker environment.should we use that to disable the inbuilt update?

**Comment by Qstick** [comment]
Take a peak at Sonarr Phantom-develop commits from 12/29, believe functionality was added to the updater to do this.
