### ISSUE TITLE
Downloaded files are stuck in queue

### ISSUE THREAD

**Issue by smidley** [lidarr/Lidarr#634]
**Describe the bug**
Downloaded files are stuck in queue.

**To Reproduce**
When I look in my activity log, it says that there are files that are waiting to be downloaded, but when I open deluge, I can see that the files are already fully downloaded, but haven't been imported to lidarr yet.  In the activity queue, there releases are listed and they have a little download button or remove button.  Looks like they haven't begun to download yet.

**Expected behavior**
I would expect lidarr to communicate with deluge and realize that the releases have been downloaded and they are ready to be processed.

**Screenshots**
None

**Logs**
None

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System Server 2019
 - .net Framework (Windows) or mono (macOS/Linux) Version: Windows

**Additional context**
None

**Comment by ta264** [comment]
Sounds like a configuration error to me. Try asking for support on discord, the required back and forth will be easier there.
