### ISSUE TITLE
Two albums with the same name, song is mis-matched on refresh

### ISSUE THREAD

**Issue by rmccu** [lidarr/Lidarr#638]
**Describe the bug**
I have a set of FLAC files for [The Essential Van Morrison](https://musicbrainz.org/release/d4d6dc87-f304-465c-b40a-336ad1a37d40) released in 2015. The 3rd track on the first disc is _Spanish Rose_. There is another album named [The Essential Van Morrison](https://musicbrainz.org/release/5bb774d9-d780-4d8c-a023-d5f527d63a85) released in 2010 where the 3rd track is also _Spanish Rose_.

Note that this means there are 2 release groups with the same album name. I have the audio files for the one from 2015 which is a 2 disc set.

What happens is when the daily refresh task runs and the artist is refresh, the 3rd track is moved to the earlier, single-disc release.

I do not want that to happen. Is there a way I can keep this from happening?

**To Reproduce**
1. Add "Van Morrison"
2. Set a profile that includes Album, Compilation, and Official
3. Refresh
4. Obtain the audio files for the 2015 release of [The Essential Van Morrison](https://musicbrainz.org/release/d4d6dc87-f304-465c-b40a-336ad1a37d40)
5. Import audio tracks to the 2015 release
6. Refresh Van Morrison
Notice that the 3rd track is moved to the 2010 release of [The Essential Van Morrison](https://musicbrainz.org/release/5bb774d9-d780-4d8c-a023-d5f527d63a85)

**Expected behavior**
I would expect that once the track is associated to the 2015 release it would stay there.

**Screenshots**
N/A

**Logs**
Not sure if this is required

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: FreeNAS 11.2-U2
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.10.1.57

**Additional context**
N/A

**Comment by ta264** [comment]
This is fixed in nightly

**Comment by ta264** [comment]
At least it should be... Please reopen if you can reproduce on nightly.
