### ISSUE TITLE
Minor GUI issue / Safari / v0.5.0.644

### ISSUE THREAD

**Issue by agster27** [lidarr/Lidarr#642]
**Describe the bug**
Movement Arrows in the top right hand of the screen the right most arrow gets cut off.

See screenshot:

<img width="1335" alt="screen shot 2019-02-28 at 11 47 34 am" src="https://user-images.githubusercontent.com/43124684/53583007-a6985600-3b4e-11e9-80e5-a5f14a899230.png">

**Comment by Qstick** [comment]
Hmm thought I had fixed that. Will investigate. Thanks

**Comment by agster27** [comment]
This is isolated to Safari.

**Comment by danielunderwood** [comment]
I can't seem to reproduce on Safari. What version are you running?
