### ISSUE TITLE
"Update All" not reapplying metadata profiles / v0.5.0.644

### ISSUE THREAD

**Issue by agster27** [lidarr/Lidarr#643]
**Describe the bug**
If you change an active Metadata Profile ( by active I mean Metadata Profiles you are using on artists ), when you click "Update All" it will not update all Artists. However if you go into an artist and click on "refresh and scan" it will reapply that profile and update that one artist.

Reproduce it:

Ok here it goes. On initial import I had my Metadata Profile called "Standard" setup with all Primary Types checked and Secondary Types Checked. I figured that would be the best. ( I had no idea how MusicBrainz worked and boy was that a mistake. )

For example let's look at Phish who shows 636 Albums, which is mostly their live recordings and I do not want their live recordings.

<img width="1281" alt="screen shot 2019-02-28 at 11 48 29 am" src="https://user-images.githubusercontent.com/43124684/53583943-97b2a300-3b50-11e9-824e-f91e0e05dc85.png">

So to clean up my DB I modified the "standard" metadata profile to the below:

<img width="534" alt="screen shot 2019-02-28 at 11 48 40 am" src="https://user-images.githubusercontent.com/43124684/53583872-6cc84f00-3b50-11e9-9613-26807903f219.png">

Then I clicked on "Update All" as shown below and let Lidarr take a full day to rescan.

<img width="428" alt="screen shot 2019-02-28 at 12 00 43 pm" src="https://user-images.githubusercontent.com/43124684/53583893-7ce02e80-3b50-11e9-85ce-64e6bc583bd4.png">

Phish 636 albums were still there after the scan.

So I went into the Artist and clicked on "Refresh and Scan"

<img width="635" alt="screen shot 2019-02-28 at 12 04 29 pm" src="https://user-images.githubusercontent.com/43124684/53584159-07289280-3b51-11e9-8340-af8b89b6eada.png">

Boom that worked:

<img width="1276" alt="screen shot 2019-02-28 at 11 57 41 am" src="https://user-images.githubusercontent.com/43124684/53584200-1dcee980-3b51-11e9-8b27-43f2f645813a.png">

**_So when I clicked "Updated All" to update all Artists shouldn't have that reapplied the Metadata Profile Standard and update all artists?_**

**Comment by Qstick** [comment]
Cant seem to reproduce this in latest nightly, works as expected for me when clicking `update all`
