### ISSUE TITLE
Latest docker: fpcalc could not be found. Audio fingerprinting disabled.

### ISSUE THREAD

**Issue by dr0ther** [lidarr/Lidarr#656]
**Describe the bug**
I get the error described in the title

**To Reproduce**
Navigate to   System -> Status

**Expected behavior**
No errors

**Screenshots**
attached

**Logs**
attached

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.643
 - Operating System: Docker (debian)

<img width="597" alt="screen shot 2019-03-06 at 7 59 03 pm" src="https://user-images.githubusercontent.com/24509885/53926974-00b38280-404b-11e9-9059-d2f8be890dde.png">
[lidarr.txt](https://github.com/lidarr/Lidarr/files/2939134/lidarr.txt)

**Comment by Qstick** [comment]
That’s not an error it’s a warning that fpcalc is not installed so you cannot use audio fingerprint

**Comment by iAmRenzo** [comment]
Sorry to respond. I understand that this is a warning. But after a reboot of my Synology I got this warning. It was previously installed but now it's not. Which looks like an error 😉
How to fix?
