### ISSUE TITLE
Manual Import button not working

### ISSUE THREAD

**Issue by KoopaTroopas** [lidarr/Lidarr#657]
**Describe the bug**
The Manual Import button on the Wanted page seems to not be working.  I have tried restarting Lidarr and the host OS but the bug remains.  I was able to get it working once, but I'm not sure what I did to achieve that.

**To Reproduce**
1. Go to Lidarr's webpage
2. Click on the Wanted tab
3. Click on the Manual Import Icon
4. Nothing Happens

**Expected behavior**
It should launch the Manual Import wizard

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: Ubuntu 18.04
 - Mono version: 5.18.0.268

**Additional context**
I have tried both Firefox and Chrome, issue persists on both

**Comment by KoopaTroopas** [comment]
Actually, I was just able to get it working.  I don't know if this is intended behavior, but when I add something to be monitored it works.  However, when nothing is monitored and the Wanted list is empty is when this issue comes up

**Comment by ta264** [comment]
Yep, known issue when the wanted list is empty.  It's already fixed in nightly.
