### ISSUE TITLE
MusicBrainz Release ID not used to select correct album

### ISSUE THREAD

**Issue by tehniemer** [lidarr/Lidarr#679]
**Describe the bug**
Lidarr doesn't strictly adhere to MusicBrainz Release ID tag

**To Reproduce**
1. Tag a bunch of albums in MusicBrainz Picard to get correct Release ID info into the files
2. Import into Lidarr
3. Lidarr will have chosen some albums as incorrect versions. 

**Expected behavior**
Correct album version will have been chosen

**Screenshots**
![Image 1552747901](https://user-images.githubusercontent.com/11021632/54476986-4b629680-47d1-11e9-972d-aaa99b5e65c7.png)

![Image 1552747965](https://user-images.githubusercontent.com/11021632/54476987-4b629680-47d1-11e9-8073-7f4a075f0df6.png)

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: Docker
 - Mono Version: 5.18.0.268

**Comment by ta264** [comment]
Fixed in nightly

**Comment by tehniemer** [comment]
@ta264 So if I update to the nightly and re-scan my library will Lidarr correct the issue, or will I have to re-import?

**Comment by ta264** [comment]
Upgrading to nightly and rescanning should fix. Change to the lsio lidarr:preview container, don't upgrade lidarr inside the container.

**Comment by tehniemer** [comment]
Right, thank you.

**Comment by tehniemer** [comment]
That seems to have done the trick

**Comment by ta264** [comment]
Thanks for reporting back. The track matching has had a fairly comprehensive rewrite so bug reports of it not working correctly would be very helpful.

**Comment by tehniemer** [comment]
I haven't dived deep, but a spot check of a couple known mismatched albums looked good. I'll take a look again after the scan has completed.

**Comment by tehniemer** [comment]
Seems good for the most part, but there was at least one obscure album that show up in Musicbrainz that weren't matched at all by Lidarr.

**Comment by tehniemer** [comment]
That's the thing, lidarr isn't even finding the album. 

this is the album
https://musicbrainz.org/release/161a015f-f0bf-4bce-a303-5316cfa6691a

and these are the two artists credited
https://musicbrainz.org/artist/ded77213-b4b8-415f-bb86-d96c3c1b6a53
https://musicbrainz.org/artist/a5a1ed69-fbdc-480f-9859-df37bd47f031

Lidarr doesn't find the album for either of the two artists. I've added both artists using 'lidarr:ded77213-b4b8-415f-bb86-d96c3c1b6a53' and 'lidarr:a5a1ed69-fbdc-480f-9859-df37bd47f031' so the matches should be correct. 

I don't know if a debug log will give you any relevant information, but I can provide one if needed.

**Comment by Qstick** [comment]
This is because release type is set to unknown for the release group in musicbrainz

**Comment by tehniemer** [comment]
Got it, so should Lidarr handle unknown releases differently? It seems like it is a legitimate configuration in musicbrainz rather than a fluke.

I did change the release group of that album to something Lidarr recognizes and now it pulls into the artist TNT, but not Air. K even though they are both credited as artists of that album.

**Comment by Qstick** [comment]
There are options in metadata profile on what release statuses you want Lidarr to pull in.

**Comment by tehniemer** [comment]
Yes, but "unknown" is not an option.
