### ISSUE TITLE
Connnection Lost

### ISSUE THREAD

**Issue by samcro1967** [lidarr/Lidarr#680]
This happens every few mins.  I am running it on Windows 10 in a Docker container.  This has happened from when I first installed it over a year ago.  It was reported previously as a bug when importing, but it happens no matter what you are doing.  I submitted a previous bug report ([#240](https://github.com/lidarr/Lidarr/issues/204#issuecomment-469177441)) and it was closed, but it looks like it was never fixed.  I believe I am running the latest version of Windows, Docker, and Lidarr so opening a new bug report in case it fell thought the cracks or I missed something.

![image](https://user-images.githubusercontent.com/2319445/54493085-06566700-489a-11e9-9803-8f8c8319f5a6.png)

Client OS - Microsoft Windows [Version 10.0.17134.590]
Docker version 18.09.2, build 6247962
![image](https://user-images.githubusercontent.com/2319445/54493045-ab247480-4899-11e9-9c97-76ce4fade622.png)

**Comment by ta264** [comment]
You could try the `linuxserver/lidarr:preview` docker image to see if it's fixed on nightly.  Otherwise, can you try it outside of docker?  I suspect this is an issue with using docker on windows.

**Comment by samcro1967** [comment]
I am not seeing it in the preview image (0.5.0.752).  Appears it may be fixed!  I also installed locally (Lidarr.develop.0.5.0.583.windows-installer) and am not seeing it either.
