### ISSUE TITLE
Track Naming

### ISSUE THREAD

**Issue by Joleun** [lidarr/Lidarr#681]
**Is your feature request related to a problem? Please describe.**
Only just starting to use Lidarr, and while I'm still setting everything set up, the track naming options are causing something of an issue/dilemma.

My existing library is based on artist/album folders with all tracks going into the one album folder whether it was a single cd, or multi cd album.  Track naming within the folder varies a little as follows: 

Single cd: track number - track title
Multi cd:  disc number-track number - track title

With the renaming options available, I am faced with choosing between one, or the other.  If I want to include the multi cd albums with {medium:0}-{track:00} - {Track Title} that would mean that all my single cd albums, which are the majority obviously, are named incorrectly.  Even if I did that the single cd album's tracks would then be named 1-01 etc, and I find including the cd number unnecessary in that case which is why I named them as I did originaly. 

**Describe the solution you'd like**
Separate track naming options for single, and multi cd albums.  I was going to suggest a user option to omit {medium:0} and the variant in the case of single cd's, but that doesn't work due to the following text.  

**Describe alternatives you've considered**
Unless I've missed something, I don't believe there are any easy alternatives.  I'd have to accept the awkward naming and rename most of my library if I want to include everything.  For now, I think I'll not monitor any multi cd albums.

**Comment by iFredOS** [comment]
Nice! I was about to post this request.

It should give us the option with a checkbox (disabled by default) to only use the medium when the album have 2 or more discs. Like you wrote, otherwise this incorrect because now all my album with a single CD show a "1-00 Track Title". I'm sure this is easy for them to add this feature.

**Comment by Joleun** [comment]
It's good to see at least one other thinks the same way.

I considered the yes/no option as a solution at first, but as mentioned, it doesn't work.  It would with the naming format used leave the hyphen before the track number with single cd albums.  That's when I recalled that Sonarr allows multiple naming formats for different types of episodes, and considered something similar would be ideal as it would allow complete freedom to set it up however one wished covering everyone's possible needs.

**Comment by iFredOS** [comment]
> It's good to see at least one other thinks the same way.
> 
> I considered the yes/no option as a solution at first, but as mentioned, it doesn't work. It would with the naming format used leave the hyphen before the track number with single cd albums. That's when I recalled that Sonarr allows multiple naming formats for different types of episodes, and considered something similar would be ideal as it would allow complete freedom to set it up however one wished covering everyone's possible needs.

I forgot about the hyphen. I agree. Maybe add another syntax to add that if the number of medium is 1, don't use those File Name Tokens. Or simple new File Name Tokens that can be used only if you have more than 1 medium. I wish I know how to code, I would add this myself.

**Comment by Qstick** [comment]
This is done in 0.7
