### ISSUE TITLE
Import List creates duplicate artists

### ISSUE THREAD

**Issue by pb1051** [lidarr/Lidarr#687]
**Describe the bug**
All my artists were uploaded from a media folder. I then connected a LastFM list to my Lidarr instance. The setting to allow this list to create an artist folder caused Lidarr to create a duplicate artist for the artist if they already existed in my database. It does not create a another artist folder in my media database at least!

**To Reproduce**
1. artists were uploaded from a media folder
2. connected a LastFM list to my Lidarr instance
3. setting to allow this list to create an artist folder 
4. create a duplicate artist for the artist if they already existed in my database.

**Expected behavior**
Lidarr should check if the artist exists before creating the artist again in Lidarr.

**Screenshots**

Duplicate Artist created by Import List
![2019-03-21_9-39-23](https://user-images.githubusercontent.com/6139274/54760738-a83dc280-4bbe-11e9-84e6-31242093406a.png)

Not duplicated in database  (awesome!)
![2019-03-21_9-40-39](https://user-images.githubusercontent.com/6139274/54760743-abd14980-4bbe-11e9-98e2-b7725bf2f71e.png)

Original artist
![2019-03-21_9-44-45](https://user-images.githubusercontent.com/6139274/54760752-affd6700-4bbe-11e9-87d2-319da58f02a8.png)

Duplicate from list import
![2019-03-21_9-45-30](https://user-images.githubusercontent.com/6139274/54760758-b390ee00-4bbe-11e9-850e-87ea05d4ed4b.png)

**Logs**
Log for the incident are gone.

**System info (please complete the following information):**
 - Lidarr Version: [0.5.0.583]
 - Operating System [Ubuntu 18 LTS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [not sure]

**Additional context**

**Comment by Qstick** [comment]
These are likely not duplicate artist but instead two different artist with same name. Likely the mapping is incorrect from the list. What are the mbids for each?

**Comment by pb1051** [comment]
@qstick you are possibly correct. I know for one artist they were different MBIDs. I will confirm the next time I see the issue. It's strange that LastFM would provide the incorrect MBID for such popular groups.

**Comment by Qstick** [comment]
Agree, I just want to make sure it's not a mapping error on our side somehow.
