### ISSUE TITLE
Album Search Broken due to ResourceMapping

### ISSUE THREAD

**Issue by Qstick** [lidarr/Lidarr#690]
**Describe the bug**
Calls to album search fail due to resource mapping. Currently these are failing out at `AlbumResource.cs` Line 60 because an album search returns album objects which do not yet have releases, or an artistId in DB. So the call to release service fails and the lazyload of artist fails. 

ex. http://localhost:8686/api/v1/album/lookup?apikey={redacted}&term=kiss

**Expected behavior**
Album search should return search results without adding items to the DB. Null checks likely needed to be added to the resource mapping so that results are still returned. 

This is likely what is killing Ombi on nightly.

**Comment by mouzzampk2014** [comment]
Hi, I'm using latest tag shall o switch to nightly? I'm on Dockers.

**Comment by Qstick** [comment]
No, nightly is broken

**Comment by mouzzampk2014** [comment]
Oh okay I will wait for 0.7 😁

Hassan Arshad

**Comment by Qstick** [comment]
0.5.583 should be working

**Comment by mouzzampk2014** [comment]
Is this fixed? :)

**Comment by ta264** [comment]
Should be fixed on nightly

**Comment by mouzzampk2014** [comment]
I will give a go in an hour. Thank you so much

**Comment by ta264** [comment]
Make sure to switch container image if you're not on nightly currently otherwise you'll have problems if you ever recreate the container. You want `linuxserver/lidarr:preview`

**Comment by mouzzampk2014** [comment]
Yes I'm on preview currently so should be okay

**Comment by mouzzampk2014** [comment]
Nope still same issue :( and I am on 0.5.0.753

**Comment by ta264** [comment]
Hmm, it was working for me

**Comment by mouzzampk2014** [comment]
> Hmm, it was working for me

Let me clear my log and retry again. Must be fixed its just me been thick. Just give me couple of hours. Thanks again
