### ISSUE TITLE
404 Error when searching for artists

### ISSUE THREAD

**Issue by Thomas12323** [lidarr/Lidarr#699]
HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.3/search?type=artist&query=m: 404.NotFound
404 page not found
 That is the bug when I am trying to search for an artist,I am on the latest version

**Comment by ta264** [comment]
Yes, the metadata service is currently down. We'll look into it.

**Comment by Thomas12323** [comment]
> Yes, the metadata service is currently down. We'll look into it.

Thanks for the quick reply and information!

**Comment by danielunderwood** [comment]
Services should be back up now.
