### ISSUE TITLE
Import unsorted tracks

### ISSUE THREAD

**Issue by bkk2009** [lidarr/Lidarr#708]
I have many unsorted songs in one folder. These are not in any sub folders for artists or albums, just in one main folder. The files are named correctly as Artist - Song Name.

Can we have a way to import these to Lidarr, and Lidarr correctly reads the artist for importing and can then leave the songs where they are, or move them to newly created subfolders under Artist/Album?

**Comment by Qstick** [comment]
Similar to #558, closing as the end solution will take care of both.
