### ISSUE TITLE
Custom attributes in rtorrent based on source

### ISSUE THREAD

**Issue by rubdos** [Lidarr/Lidarr#718]
**Is your feature request related to a problem? Please describe.**
I want to post-process all torrents that come from tracker O with a custom script. This script needs to know the original torrent ID at this tracker.

**Describe the solution you'd like**
I would like Lidarr to attach the release URL of the tracker as a custom attribute in rtorrent, such that rtorrent can fire a post-processing script specific for the tracker. This URL seems to be available in Jackett, and can e.g. be attached to `custom2` in rtorrent.

**Describe alternatives you've considered**
The current post-processing script fetches the list of downloaded torrents from the tracker to check what release to post-process, which is typically *15-30 minutes behind*. This means that in 99% of the cases, the post-processing fails.

[AB#334](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/334)

**Comment by rubdos** [comment]
Maybe noteworthy: I am running Lidarr inside a Docker container, so it's quite difficult to call this script from within Lidarr. Additionally, I don't think [Lidarr's supplied ENV](https://github.com/lidarr/Lidarr/wiki/Custom-Post-Processing-Scripts) has a field that refers to the Tracker's ID of the Torrent.

**Comment by ta264** [comment]
This sounds quite a niche request... you might have more luck fetching the history of downloaded torrents from lidarr rather than your tracker.  You can use the download_id environment variable to match up with the results from here https://github.com/lidarr/Lidarr/wiki/History

**Comment by rubdos** [comment]
> This sounds quite a niche request... 

Yeh, I figured so much.

> you might have more luck fetching the history of downloaded torrents from lidarr rather than your tracker. You can use the download_id environment variable to match up with the results from here https://github.com/lidarr/Lidarr/wiki/History

That should do it, I suppose! Is that `downloadId` the infohash? It sure looks like it.
