### ISSUE TITLE
Album missing, with right settings

### ISSUE THREAD

**Issue by iAmRenzo** [lidarr/Lidarr#719]
Lidarr doesn't show any album under the artist [Bob Zimmerman](https://musicbrainz.org/artist/25b0096f-529a-40e6-824a-96a14ed26650)

On MusicBrainz there is one album, a soundtrack.

 - Lidarr Version: 0.5.0.583
 - Synology, Docker
 - mono (macOS/Linux) Version: 5.16.0.179

**Comment by ta264** [comment]
This works for me on nightly.
