### ISSUE TITLE
Lidarr complaining about NZBGet download folder, truncated path?

### ISSUE THREAD

**Issue by c0rnflake** [lidarr/Lidarr#723]
Just updated to the most recent nightly, 0.5.0.794 and lidarr is complaining about the NZBGet download folder with the following message:

You are using docker; download client NZBGet places downloads in /downloads/dst/Musi but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

The download folder is being truncated in the message as downloads are placed in /downloads/dst/Music

Is this simply incorrect in the error message or has the actual path lidarr is using to check been truncated?

Version 0.5.0.794
Mono Version 5.18.1.0
Docker True
DB Migration 29
AppData directory /config
Startup directory /app/lidarr
Mode Console

**Comment by Qstick** [comment]
https://github.com/nzbget/nzbget/issues/622

**Comment by ta264** [comment]
Using an absolute path in nzbget dest dir works around this

**Comment by Qstick** [comment]
Fixed on nzbget side
