### ISSUE TITLE
Add support for Gotify notifications

### ISSUE THREAD

**Issue by stephanrenggli** [lidarr/Lidarr#727]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to use a self-hosted notification service as an alternative to Pushover.

**Describe the solution you'd like**
Gotify is very similar to Pushover. You can host it yourself (as a Docker container for example).

**Describe alternatives you've considered**
The currently available notification services work well.

**Additional context**
Gotify: https://gotify.net/

**Comment by stephanrenggli** [comment]
Hi, I was able to get this working (basically just copy & paste from Pushover).
I submitted a pull request: https://github.com/lidarr/Lidarr/pull/730

Am I doing this the right way?

**Comment by Qstick** [comment]
Yes, thanks. We will review it
