### ISSUE TITLE
Single + Remix and Single + Demo not in list

### ISSUE THREAD

**Issue by texke** [lidarr/Lidarr#728]
Hi,

Adding artist Solar Fields (https://musicbrainz.org/artist/a2af1f31-c9eb-4fff-990c-c4f547a11b75) with every Metadata type won't show the releases under Single + Remix or Single + Demo.
The Singles without secondary types are in the list (Demo type isn't available in Metadata types aswell)

Tested on Nightly to be sure
Version 0.5.0.802
Mono Version 5.18.1.0
DB Migration 29
Ubuntu 18.10

**Comment by texke** [comment]
Seems like a MB cache issue... suddenly the Remix showed up, but the Demo still doesn't.

**Comment by Qstick** [comment]
Seems to work fine for me

![8383BACF-BB5C-4423-AF76-F0ECD03CA94E](https://user-images.githubusercontent.com/376117/55919814-57b9f380-5bc5-11e9-9f03-9855f44c3a22.jpeg)

**Comment by texke** [comment]
@Qstick That's odd, I'm on 808 now and can't select "Demo" type:
![image](https://user-images.githubusercontent.com/4090858/55935123-15c79680-5c33-11e9-9a4f-be3ebed27c14.png)

And with everything selected, I'm not getting "Cluster" in the list.
![image](https://user-images.githubusercontent.com/4090858/55935290-8969a380-5c33-11e9-90a2-eaa9a5eab135.png)

No trace of secondarytype demo allowed:
[https://pastebin.com/3WgCz0Pe](https://pastebin.com/3WgCz0Pe)

Am I missing a setting? :(

**Comment by texke** [comment]
Added the part:
  {
    "secondaryAlbumType": 10,
    "allowed": true
  },
to the Scondary column in table MetadataProfiles and it's showing up.

Seems updating from Development didn't add the Demo to the profiles in the DB, every new profile looks fine, my mistake!
