### ISSUE TITLE
Same artist slug for artists with special characters

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/Lidarr#73]
Artists with special characters in their slug can produce the same slug as another. For example, Adèle and Adele both have the url `/artist/adele`. Adding a conflicting artist results in `Title slug is in use by another artist with a similar name`.

**Comment by Qstick** [comment]
Maybe we should just use the MBId as the slug?

**Comment by danielunderwood** [comment]
That would probably be a good choice. I'd imagine that there are also
conflict issues that aren't caused just by special characters now that I
think about it.

**Comment by Qstick** [comment]
We can use last bit from mbid plus clean title if we want to keep the name as part of slug.

**Comment by Qstick** [comment]
f1b1904e076573fca50b3b529a5994b71b142ad0
