### ISSUE TITLE
Album Api with foreignAlbumId query returns all albums

### ISSUE THREAD

**Issue by tidusjar** [lidarr/Lidarr#731]
**Describe the bug**
When calling `api/v1/album?foreignAlbumId=f0607e1d-c2e1-41a4-b69b-f3fc396a5e67` it is returning all the albums for that artist. 

This is not documented but I noticed that this is called in the UI when clicking into an album, and I was hoping it would just return the Album information that is part of the query string

**To Reproduce**
1. Call the above api and pass in a valid `foreignAlbumId`
2. See the response contains all albums by that artist

**Expected behavior**
Returns the single album as part of the JSON payload

**Workaround**
I do currently have a workaround since I can just select the album I want from the JSON, but I don't want to do this until I know if this is a bug or not, and if it's going to be fixed (since I'll have to make code changes once you fix it).

**System info (please complete the following information):**
 - Lidarr Version: 0.5.0.583
 - Operating System: Docker (LSIO Container)

**Comment by ta264** [comment]
We plan to change this in 0.6 so that if you pass a `foreignAlbumId` you get back a singleton list with the result you'd expect.  If you add the additional parameter `&includeAllArtistAlbums=true` then you'll get the current behaviour which returns a list of all albums by that artist.

**Comment by tidusjar** [comment]
OK, for now I'll wait for 0.6 rather than implementing a workaround.

Thanks.
