### ISSUE TITLE
Constantly selecting torrent with no seeds

### ISSUE THREAD

**Issue by bryangauvin** [lidarr/Lidarr#739]
**Describe the bug**
Constantly selecting torrents with 0 seeds when other copies have multiple seeds

**To Reproduce**
Auto download anything

**Expected behavior**
Select the torrent that has seeds vs the one with 0

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by Qstick** [comment]
Can you post a screenshot of interactive search results of an album where this happens? I assume there are other issues with the seeded release given this is first report of this. Or post debug logs

**Comment by Qstick** [comment]
Whoa just noticed you are mannnnnnny versions behind. Please update Lidarr
