### ISSUE TITLE
Some songs won't get imported, require artist (I cannot give)

### ISSUE THREAD

**Issue by iAmRenzo** [lidarr/Lidarr#744]
<img width="939" alt="Schermafbeelding 2019-04-12 om 08 42 43" src="https://user-images.githubusercontent.com/1183790/56017309-28a79d00-5cff-11e9-9b60-b41fd46efd4e.png">
<img width="453" alt="Schermafbeelding 2019-04-12 om 08 43 24" src="https://user-images.githubusercontent.com/1183790/56017320-2ba28d80-5cff-11e9-82ec-0de1f9b8d133.png">

This situation... song won't get scanned. For manual import I need to select an artist, which I cannot enter. Song won't import at all... :(

/edit: half of my text is cut-off. 
If I select the artist gets a red rectangle, but when I click on it nothing happens. In other cases when the album gets a rectangle, you can choose an album from the popup. It looks like this:
<img width="938" alt="Schermafbeelding 2019-04-12 om 08 50 11" src="https://user-images.githubusercontent.com/1183790/56017585-06624f00-5d00-11e9-87a4-970243515435.png">

Lidarr 0.5.0.583 Mono 5.16.0.179

**Comment by ta264** [comment]
Which version? Why can't you add the artist? We need more details...

**Comment by ta264** [comment]
Ps probably more likely to get helpful responses in the discord support channel.
