### ISSUE TITLE
unstable 0.6.0

### ISSUE THREAD

**Issue by Fish2** [lidarr/Lidarr#745]
**Describe the bug**
lots or resource time outs on web inspection unable to load a lot of pages and unstably 

**To Reproduce**
Update to 0.6.0

**Logs**
nothing in debug issue shown for this issue 

**System info (please complete the following information):**
 - 0.6.0.815

**Comment by ta264** [comment]
The metadata server is currently struggling under the load as everyone upgrades. It should calm down eventually.
