### ISSUE TITLE
API release/push endpoint unable to parse title

### ISSUE THREAD

**Issue by lethargy-navigator** [lidarr/Lidarr#749]
The release/push API endpoint responds with error "Unable to parse" no matter the string sent in the title. Maybe I'm doing this incorrectly but it works this way in sonarr and radarr.

Lidarr version: 0.6.0.815 / Linux
Mono version: 5.18.1.0
Curl version used to POST to API: 7.52.1

`=> Send data, 95 bytes (0x5f)
0000: {"title":"test","downloadUrl":"test","protocol":"torrent","publi
0040: shDate":"2019-04-13 13:49:44Z"}
== Info: upload completely sent off: 95 out of 95 bytes
<= Recv header, 26 bytes (0x1a)
0000: HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
<= Recv header, 33 bytes (0x21)
0000: X-ApplicationVersion: 0.6.0.815
X-ApplicationVersion: 0.6.0.815
<= Recv header, 63 bytes (0x3f)
0000: Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
<= Recv header, 18 bytes (0x12)
0000: Pragma: no-cache
Pragma: no-cache
<= Recv header, 12 bytes (0xc)
0000: Expires: 0
Expires: 0
<= Recv header, 47 bytes (0x2f)
0000: Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
<= Recv header, 26 bytes (0x1a)
0000: Server: Mono-HTTPAPI/1.0
Server: Mono-HTTPAPI/1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Sat, 13 Apr 2019 13:49:44 GMT
Date: Sat, 13 Apr 2019 13:49:44 GMT
<= Recv header, 19 bytes (0x13)
0000: Connection: close
Connection: close
<= Recv header, 28 bytes (0x1c)
0000: Transfer-Encoding: chunked
Transfer-Encoding: chunked

<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 119 bytes (0x77)
0000: 6c
0004: [.  {.    "propertyName": "Title",.    "errorMessage": "Unable t
0044: o parse",.    "attemptedValue": "test".  }.]
0072: 0
0075: 
[
  {
    "propertyName": "Title",
    "errorMessage": "Unable to parse",
    "attemptedValue": "test"
  }`

**Comment by Qstick** [comment]
You need to pass a valid release name. If Lidarr can't parse the release name it will kick back now instead of failing out completely.

The release push endpoint was also recently fixed in Sonarr V3 as we let them know that validation and error handling wasn't working correctly.

Do you have an example of a release title that should be parsed that isn't?

**Comment by lethargy-navigator** [comment]
Here's an album that's monitored in my collection. I'm not sure if the title here is correctly formatted:

  {
    "propertyName": "Title",
    "errorMessage": "Unable to parse",
    "attemptedValue": "The Chemical Brothers - No Geography"
  }

**Comment by Qstick** [comment]
`The Chemical Brothers - No Geography` will fail parse as it has no year.

**Comment by lethargy-navigator** [comment]
Thanks for the clarification, it worked with the following format:
"The Chemical Brothers - No Geography - 2019"
