### ISSUE TITLE
API release/push endpoint - protocol?

### ISSUE THREAD

**Issue by lethargy-navigator** [lidarr/Lidarr#750]
The API documentation for the release/push endpoint says 'downloadProtocol' , but API expects 'protocol'.

Lidarr version: 0.6.0.815 / Linux

`=> Send data, 103 bytes (0x67)
0000: {"title":"test","downloadUrl":"test","downloadProtocol":"torrent
0040: ","publishDate":"2019-04-13 13:57:29Z"}
== Info: upload completely sent off: 103 out of 103 bytes
<= Recv header, 26 bytes (0x1a)
0000: HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
<= Recv header, 33 bytes (0x21)
0000: X-ApplicationVersion: 0.6.0.815
X-ApplicationVersion: 0.6.0.815
<= Recv header, 63 bytes (0x3f)
0000: Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
<= Recv header, 18 bytes (0x12)
0000: Pragma: no-cache
Pragma: no-cache
<= Recv header, 12 bytes (0xc)
0000: Expires: 0
Expires: 0
<= Recv header, 47 bytes (0x2f)
0000: Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
<= Recv header, 26 bytes (0x1a)
0000: Server: Mono-HTTPAPI/1.0
Server: Mono-HTTPAPI/1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Sat, 13 Apr 2019 13:57:29 GMT
Date: Sat, 13 Apr 2019 13:57:29 GMT
<= Recv header, 19 bytes (0x13)
0000: Connection: close
Connection: close
<= Recv header, 28 bytes (0x1c)
0000: Transfer-Encoding: chunked
Transfer-Encoding: chunked

<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 369 bytes (0x171)
0000: 165
0005: [.  {.    "propertyName": "Protocol",.    "errorMessage": "'Prot
0045: ocol' should not be empty.",.    "attemptedValue": "unknown",.  
0085:   "errorCode": "notempty_error",.    "formattedMessageArguments"
00c5: : [],.    "formattedMessagePlaceholderValues": {.      "property
0105: Name": "Protocol",.      "propertyValue": "unknown".    },.    "
0145: resourceName": "notempty_error".  }.]
016c: 0
016f: 
[
  {
    "propertyName": "Protocol",
    "errorMessage": "'Protocol' should not be empty.",
    "attemptedValue": "unknown",
    "errorCode": "notempty_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Protocol",
      "propertyValue": "unknown"
    },
    "resourceName": "notempty_error"
  }`

**Comment by Qstick** [comment]
Thanks, docs fixed
