### ISSUE TITLE
New Update Reset All Artists

### ISSUE THREAD

**Issue by BatchAssassin** [lidarr/Lidarr#751]
Just noticed that artists without pictures now have their name in big white bold letters now. Thought that was pretty cool, but then I realized that wasn't normal, and that most of the bands that have this used to have pictures. I then realized there must have been an update. Then I noticed that every artist was marked complete. My best guess is that this newest update nuked whatever database it had been using previously at some point during the update, but I can't confirm this. I can, however, confirm that I now have to re-scan my entire library, which will take more than 24 hours. Kinda peeved about that, but hey, it's a pre-release for software I didn't have to pay for, so I can't really complain. Figured I'd bring this to the attention of the community so it can be fixed.

EDIT: It did not reset my list of artists or the monitored/unmonitored identifier for each individual album. Thank god, because I use this feature to select which singles I want, and I only download singles that aren't on an album or EP. This would take even longer to re-do, and it would have to be done by hand. *wipes sweat from brow* The only things I can see got reset is artist pictures (seemingly random) and which tracks I have from each album.

**Comment by ta264** [comment]
Yes, there's a big metadata update but the volume of requests resulted in a self inflicted DDOS. This is what caused the "reset".

**Comment by ta264** [comment]
So yes, artist are intact but the track matching will have been lost in the failed metadata update. We disabled art to get the load under control, they'll come back once everything settles down.

**Comment by BatchAssassin** [comment]
Okay, that makes sense. I'm all for nuking the metadata database if it gets a new one. My library is gigantic and will take 24 hours to re-scan. Should I wait a bit to finish the re-scan, or is it not that big an issue?

**Comment by ta264** [comment]
It shouldn't be a big issue. Let it finish, it's mostly hitting our cache now. We'll give it a few days before turning art back on I guess
