### ISSUE TITLE
Allow importing albums of same artist from multiple root folders

### ISSUE THREAD

**Issue by just-Addict** [lidarr/Lidarr#752]
**Is your feature request related to a problem? Please describe.**
I have two root folders, one in which I store archive copies of albums, consisting mostly of single file albums (e.g. FLAC, APE, ISO) with cue files.
The other contains downloaded albums in varying quality.
If I try adding the `archive` root folder, it won't import the artists that also exist in the `dynamic` folder. So in the final artist view, those albums existing in the `archive` folder are still listed as 'missing'

**Describe the solution you'd like**
I would like to be able to import/scan albums where the artists already exists in an earlier added rootfolder.

**Additional context**
Currently even if these artist albums would be allowed to import, it wouldn't work since lidarr can't parse single file albums. see issue  #515)

**Comment by just-Addict** [comment]
**Is your feature request related to a problem? Please describe.**
I have two root folders, one in which I store archive copies of albums, consisting mostly of single file albums (e.g. FLAC, APE, ISO) with cue files.
The other contains downloaded albums in varying quality.
If I try adding the `archive` root folder, it won't import the artists that also exist in the `dynamic` folder. So in the final artist view, those albums existing in the `archive` folder are still listed as 'missing'

**Describe the solution you'd like**
I would like to be able to import/scan albums where the artists already exists in an earlier added rootfolder.

**Additional context**
Currently even if these artist albums would be allowed to import, it wouldn't work since lidarr can't parse single file albums. see issue  #515)

**Comment by ta264** [comment]
This is coming in the next version
