### ISSUE TITLE
Not downloading artwork (Kodi) Metadata for Artists/Albums during scans or import

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lidarr/Lidarr#755]
**Describe the bug**
Lidarr is not adding artist/album artwork during scans

**To Reproduce**
1. Enable Kodi Metadata
2. Enable Create Empty Artist Folder During scan
3. Add artist
4. Folder will be created with NFO file for artist, but no artwork is added

If you import or add albums to the folders they also only get nfo files, no artwork

**Expected behavior**
I expected it to download artwork for the artists/albums

**System info (please complete the following information):**
 - Lidarr Version: 0.6.0.822
 - Operating System Docker (Linuxserver.io)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.18.1.0

**Comment by ta264** [comment]
That hasn't been implemented yet

**Comment by RandomNinjaAtk** [comment]
Strange, I could swear in previous versions before 0.6 that it was working.

**Comment by ta264** [comment]
I take it back, I was thinking about embedding album art. Art is currently disabled until the upgrade rush on our metadata server does down

**Comment by hikaricore** [comment]
While I know asking for exact time frames is an impossible question to answer properly, do you have any indication as to if this rush is nearer to the beginning or the end of its cycle? I was starting to question my own sanity while experiencing this issue myself. Any info is appreciated.  ^_^

**Comment by hikaricore** [comment]
A further thought. Is there anywhere within Lidarr or elsewhere that we can see the status of the metadata server without manually searching logs?  I poked around a bit, but didn't find much on the topic.

**Comment by Qstick** [comment]
https://status.lidarr.audio/, it won’t show that art or overview are done though, only if main service is up
