### ISSUE TITLE
Renamer, MediaInfo.AudioBitsPerSample not working for mp3

### ISSUE THREAD

**Issue by Ing-Med** [lidarr/Lidarr#758]
**Describe the bug**
When adding MediaInfo.AudioBitsPerSample to the renaming, it wouldn't show the correct bitrate for mp3 files (works for FLAC and others as far as i can see) 
It always shows "0bit"

**To Reproduce**
Add MediaInfo.AudioBitsPerSample and rename mp3 files. 

**Expected behavior**
Correct bitrate for mp3 file.

**Smaple**

Track | Title | Duration | Audio Info | Status | Relative Path |  

1 | Iron Man 3 | 00:02:23 | MP3 - 2.0 - 320 kbps | MP3-320 | Iron Man 3 (2013)/Brian.Tyler-Iron.Man.3.(2013)-01-Iron.Man.3-[MP3-0bit].mp3

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.830
 - Operating System Ubuntu 16.04.4 LTS
 - mono (macOS/Linux) Version: 5.8.0.127

**Comment by Qstick** [comment]
First things first, AudioBitsPerSample is not the same as AudioBitrate. Looks like we don't have a token for bitrate so I'll add that as that is likely what you are looking for. 

The bits per sample would be 16bit or 24bit audio, but you are correct, it would appear that info isn't being grabbed for mp3s

**Comment by Ing-Med** [comment]
thanks!

**Comment by Qstick** [comment]
@ta264 assuming this should be moved to our taglib repo?

**Comment by ta264** [comment]
I guess so. Taglib doesn't report it. It may be that it should just always report 16bit for MP3, I don't know enough about the format to know if 24bit MP3 is possible

**Comment by Qstick** [comment]
Reading some about this, it seems MP3 format isn't based on a fixed integer bits per sample. Thus not returning a value for this maybe correct from Taglib. We can probably just have Lidarr make blank when 0 instead of showing 0bit.

**Comment by Qstick** [comment]
Seems this is already done in MediaFormatter
