### ISSUE TITLE
Every Artist Photo / Bio were Removed

### ISSUE THREAD

**Issue by mbxIO** [lidarr/Lidarr#761]
I'm not sure if I'm missing something in the release notes, but I've noticed that, post-update / post-artist scan, all of my artists' photos / bio info are no longer listed. I attempted to update a few of the artists manually to see if they would re-pull information but nothing changed. 

Version: 0.6.1.830
OS: Windows 10

**Comment by ta264** [comment]
Art and bios are temporarily disabled to reduce server load following upgrade to 0.6.  https://status.lidarr.audio/

**Comment by webmosher** [comment]
Any chance that Lidarr could choose to update and cache artist/album photos from the local filesystem? This could be based on the a metadata provider's standard file names.
