### ISSUE TITLE
rateyourmusic import 

### ISSUE THREAD

**Issue by fire4wd** [Lidarr/Lidarr#763]
**Is your feature request related to a problem? Please describe.**
would be great to have the possibility to import the rateyourmusic "export data"

**Additional context**
If can be of any help this is a strip of the export data

"22049","","Annihilator","","","Waking the Fury","2002","0","o","","CD",  ""
"36643","","Banco del Mutuo Soccorso","","","Come in un'ultima cena","1976","8","o","","CD",  ""
"265616","","Candlemass","","","Candlemass","2005","0","o","","CD",  ""
"1631034","Sergio","Caputo","","","A tu per tu","2006","8","o","","MP3",  ""
"1950960","","Carcass","","","Heartwork","1994","8","o","","CD",  ""
"35750","","Coroner","","","R.I.P.","1987","7","o","","CD",  ""

[AB#434](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/434)

**Comment by Qstick** [comment]
No plans for this until they have an API.
