### ISSUE TITLE
Queue Returns "Failed to load Queue"

### ISSUE THREAD

**Issue by agster27** [lidarr/Lidarr#769]
**Describe the bug**
When clicking on "Activity -> Queue" I get an error "Failed to load Queue"

**To Reproduce**
Click on Activity -> Queue

**Expected behavior**
Should show the Queue :)

**Screenshots**
![image](https://user-images.githubusercontent.com/43124684/56472388-f8ad7780-642b-11e9-8f01-eda08de29763.png)

**Logs**
Trace Log at the time it happened:

`19-4-21 15:54:01.5|Trace|Http|Req: 3174 [GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownArtistItems=false
19-4-21 15:54:05.5|Trace|Http|Res: 3174 [GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownArtistItems=false: 200.OK (3959 ms)
19-4-21 15:54:05.5|Debug|Api|[GET] /api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownArtistItems=false: 200.OK (3959 ms)
19-4-21 15:54:05.5|Trace|Http|Req: 3175 [GET] /api/v1/album?albumIds=22277&albumIds=45788&albumIds=45817&albumIds=18414
19-4-21 15:54:05.5|Trace|LidarrErrorPipeline|Handling Exception
19-4-21 15:54:05.5|Fatal|LidarrErrorPipeline|Request Failed. GET /api/v1/album

[v0.6.0.815] System.ApplicationException: Expected query to return 4 rows but returned 0
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Collections.Generic.IEnumerable`1[T] ids) [0x00063] in C:\projects\lidarr\src\NzbDrone.Core\Datastore\BasicRepository.cs:92 
  at NzbDrone.Core.Music.AlbumService.GetAlbums (System.Collections.Generic.IEnumerable`1[T] albumIds) [0x00000] in C:\projects\lidarr\src\NzbDrone.Core\Music\AlbumService.cs:166 
  at Lidarr.Api.V1.Albums.AlbumModule.GetAlbums () [0x00b44] in C:\projects\lidarr\src\Lidarr.Api.V1\Albums\AlbumModule.cs:81 
  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00000] in C:\projects\lidarr\src\Lidarr.Http\REST\RestModule.cs:122 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 

19-4-21 15:54:05.6|Trace|Http|Res: 3175 [GET] /api/v1/album?albumIds=22277&albumIds=45788&albumIds=45817&albumIds=18414: 500.InternalServerError (49 ms)
19-4-21 15:54:05.6|Debug|Api|[GET] /api/v1/album?albumIds=22277&albumIds=45788&albumIds=45817&albumIds=18414: 500.InternalServerError (49 ms)
19-4-21 15:54:05.6|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'
19-4-21 15:54:05.6|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
19-4-21 15:54:05.7|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
19-4-21 15:54:05.7|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
19-4-21 15:54:05.7|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
19-4-21 15:54:05.7|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
19-4-21 15:54:05.7|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'`

**System info (please complete the following information):**
 - Lidarr Version: v0.6.0.815
 - Operating System: Docker Linuxserver/Lidarr:preview 
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono 5.18.1.0

**Comment by Qstick** [comment]
Thanks, same as #766

**Comment by loeschj** [comment]
Hi, sorry to comment on an older issue but I noticed something in the log that was provided that i'm experiencing.
"19-4-21 15:54:05.6|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30'"
How do you change the value of 30? I'm having issues with post processing not working properly because Lidarr isn't seeing everything that is truely in SABNZBD

**Comment by ta264** [comment]
You don't I'm afraid.

**Comment by loeschj** [comment]
so there's no way to see more than the last 30 items in history?

**Comment by ta264** [comment]
Correct. Idea being it should be importing them as it downloads. Why do you need more?

**Comment by loeschj** [comment]
in SAB i do have the option enabled for recursive processing of archives, but what has been happening recently is they are still zipped too far so when the download is done and has moved, the output is a tar file. Since LIDARR can't work with that, once it has hit a max of 30 then no more processing would happen.
So this morning i woke up to 152 items in my SAB history because LIDARR wasn't able to see the entire queue and process the downloads that were proper.
In the meantime I've written a post processing script to extract any .tar files that it may find in the completed download so that should solve that issue.

**Comment by adir6** [comment]
@loeschj Could you please share the script with me? Thanks.
