### ISSUE TITLE
Add Filter on Artist Page

### ISSUE THREAD

**Issue by agster27** [lidarr/Lidarr#776]
**Describe the solution you'd like**
When on an Artist Page ( https://xxx.xxx.xxx.xxx:8686/artist/ ) include a filter to only show records that have existing tracks.

For example some artists like Armin Van Buuren have large number of either albums or broadcasts or live shows and it is overwhelming to see hundreds of listing. Adding a filter would be a really nice user interface addition to narrow it down to only the ones you have.

**Comment by Qstick** [comment]
You can do this with custom filters can't you? Use track progress > 0
