### ISSUE TITLE
Global Manual Import

### ISSUE THREAD

**Issue by bryangauvin** [lidarr/Lidarr#777]
**Is your feature request related to a problem? Please describe.**
Yes, Setting up a new database many tracks don't import. Having to go artist by artist is a pain

**Describe the solution you'd like**
A manual import menu on the left. Displays a list of artists that have unmatched tracks. Next to artist name is a count of unmatched tracks. Click artist name starts the manual import process for the artist

**Describe alternatives you've considered**
Using beets to tag all files then rescanning with Lidarr. But this should not be necessary. Ultimately I want to eliminate Beets completely.  

**Additional context**

**Comment by agster27** [comment]
This is a duplicate or similar of #774 . Hint hint ;)

**Comment by Qstick** [comment]
Closing as Dupe, add discussion to #774
