### ISSUE TITLE
Fingerprinting doesn't work (and some other stuff :)

### ISSUE THREAD

**Issue by achmetinternet** [lidarr/Lidarr#778]
**Describe the bug**
When I followed these install instructions: https://www.ixsystems.com/community/resources/fn11-2-iocage-jails-plex-tautulli-sonarr-radarr-lidarr-jackett-transmission-organizr.58/
I got an error in the settings that told me fpcalc wasn't available / installed so I couldn't do the fingerprinting. 

I then did pkg install chromaprint in a console and all of a sudden fingerprinting was available to me which I thought is great but it still yields an error, see the attached logs.

**Logs**
Info level
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/3110766/Lidarr.txt)
Debug level
[Lidarr.debug.txt](https://github.com/lidarr/Lidarr/files/3110770/Lidarr.debug.txt)

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.830
 - Mono Version: 5.10.1.57
 - Operating System FreeNAS

**Additional context**
It seems that there are some other issues in the log :)

**Comment by ta264** [comment]
The debug log is pretty much empty... Please jump on the discord support channel for support requests, it's easier to help there than on github

**Comment by ta264** [comment]
As discussed on discord, fingerprinting is working and there is a permissions error to resolve
