### ISSUE TITLE
Unknown Release - MusicBrainz

### ISSUE THREAD

**Issue by agster27** [lidarr/Lidarr#781]
**Describe the bug**
If an artist has albums that has unknown Releases, Lidarr does not have a corresponding category.

![image](https://user-images.githubusercontent.com/43124684/56779940-4834d000-67ab-11e9-8e96-1db797713ea1.png)

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.838

**Comment by agster27** [comment]
MusicBrainz ID for the artist c5bb07b6-d402-46a7-9c42-456c9ec1a3d6

**Comment by ta264** [comment]
I would say the solution here is to edit musicbrainz and give the release the appropriate category

**Comment by Qstick** [comment]
Agree, bad data on musicbrainz, should be a quick edit

**Comment by Qstick** [comment]
I submitted an edit for this as well as a artist name edit

**Comment by agster27** [comment]
@Qstick Thanks! You didn't have todo that. I would have. The reason I submitted this is from the lens of an average user would not know to submit a change in MusicBrainz. 

It would be nice for Lidarr to have some way to handle this exception. Possibly even make the submission to MusicBrainz based on user input. Or at least have some corresponding category. 

I am going to reference #774. It would be really nice to have a way to identify issues for easier importing :)

**Comment by biship** [comment]
It would be nice to have this as another metadata category
