### ISSUE TITLE
Can't select root folder

### ISSUE THREAD

**Issue by devolution2409** [lidarr/Lidarr#782]
**Describe the bug**
Can't select root folder when adding new aritst.

**To Reproduce**
1. Go to 'add new artist'
2. Click on 'add a new path'
3. Select a path
4. Path isn't added

**Expected behavior**
Path should be selected

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.830
 - Operating System Ubuntu 18.04.2 LTS
 - Mono Version 5.20.1.19

**Additional context**
I just set up lidarr. (It was setup using a docker, via the linuxserver.io image)

**Comment by Qstick** [comment]
I can’t seem to reproduce this

**Comment by devolution2409** [comment]
Maybe i'm doing something wrong ?
I uploaded a quick video showing what i assume to be the bug here 
https://www.youtube.com/watch?v=i7CKbiYF_Nc

**Comment by Qstick** [comment]
Yea that appears to be a bug, does it get added to the drop down after you select it? Just not selected as default.

**Comment by devolution2409** [comment]
nope, only the option to select a path is there after adding a path

**Comment by mmolitor87** [comment]
Check your logs. I had the same problem and found:

19-4-28 22:00:20.2|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- Folder is not writable by user lidarr

**Comment by devolution2409** [comment]
@mmolitor87 is right, it seems to be fixed after settings the PUID and the PGID to the ID of the owner of the folders. This isn't *strictly* docker related. I feel like it would be a great enhancement if Lidarr told you right away folder permissions are not good instead of having to go in the logs to search this :)


 I guess we can close this !

**Comment by erkexzcx** [comment]
This is not how UI works. UI should tell user what is wrong.

Anyway, issue is solved for me too. Thanks for this GitHub issue. :)
