### ISSUE TITLE
Transmission API misreporting download directory

### ISSUE THREAD

**Issue by ta264** [lidarr/Lidarr#783]
**Describe the bug**
Suspect Extra `.` in path here
https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L123

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by Qstick** [comment]
Fixed in 5d1a5ee
