### ISSUE TITLE
Changing Artistname in Path results in importing loop

### ISSUE THREAD

**Issue by synofan** [lidarr/Lidarr#787]
If you edit the path of an artist for sorting or other reasons it will result in a constant importing of the whole library of already correctly added albums.

for example:
change original path of artist 喜多郎 (Kitaro) from "/volume1/music/Flac/喜多郎/" to "/volume1/music/Flac/Kitaro/" and have all albums moved to the new location, that works fine, until you press button "manual import" all albums are then shown as needing being imported.

you could think well ok logical the albums are on a new location, but it then happens continually.

tried it with another artist:
"/volume1/music/Flac/George Benson/" change to "/volume1/music/Flac/Benson, George/"

Same result.

as soon as the path is reverted to the original one then problem solved.
I suspect artist name is compared to artist name in path in building  string for comparison with a false result  so already imported albums and songs get to be re imported again and again.

Still a ton of compliments for the program

**Comment by Qstick** [comment]
This is expected, Lidarr maps a given artist path to an artist, if you change the path you need to remove and add the artist currently.

**Comment by synofan** [comment]
? if this is expected, why have you added a routine to move all the files to the new directory upon detection of a change. if one deletes the artist and adds the artist again you can only change the path after artist has been added. Sorry to crash your party but answer is a bit shortsighted! may the force be with you. i suspect you did not try this but for a mind experiment. Kudos for Lidarr

**Comment by Qstick** [comment]
How are you editing the path? Manually changing it outside of Lidarr? Are you then fixing the artist path mapping inside of Lidarr as well via the artist edit screen?

Give me some exact steps on what you are doing

**Comment by synofan** [comment]
I added the artist in a standard way inside of Lidarr, added albums via NZBget (automatically imported by Lidarr. then go edit artist form within Lidarr.
![image](https://user-images.githubusercontent.com/1736905/57179650-54422100-6e80-11e9-8a35-c68a77cc37e3.png)
to for example:
![image](https://user-images.githubusercontent.com/1736905/57179686-a1be8e00-6e80-11e9-8ebe-bc3d4f503024.png)
then hit save and get:
![image](https://user-images.githubusercontent.com/1736905/57179702-c9adf180-6e80-11e9-8e25-aa517a4eebf4.png)
after confirming [Yes, Move the files] files are moved correctly, and then the misbehavior as reported in first communication starts ;-)

**Comment by Qstick** [comment]
Lidarr version? Can you also provide a debug log from Lidarr during this? You seem to have deleted everything from our original issue template.

**Comment by synofan** [comment]
![image](https://user-images.githubusercontent.com/1736905/57185343-c68b2380-6ec9-11e9-9d51-bce27aa8c103.png)

Sorry no debug log
