### ISSUE TITLE
Monitor Artist problem

### ISSUE THREAD

**Issue by screwfaze** [lidarr/Lidarr#794]
**Describe the bug**
In Album Studio selecting all names and changing monitor artist to monitored also changed all albums to monitored
**To Reproduce**
1. Go to 'Album Studio'
2. Click on 'Select all artists'
3. Change to 'Monitored'

**Expected behavior**
Should monitor the artists but not change all albums to monitored unless that option is changed
**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.858
 - Operating System Docker

**Additional context**

**Comment by ta264** [comment]
I think this is the desired behaviour. Album studio affects albums, if you want to change monitored status of artists then use mass editor
