### ISSUE TITLE
Cannot add some artists by mbid

### ISSUE THREAD

**Issue by OlegAndreych** [lidarr/Lidarr#795]
Cannot add some artists via "Add new" menu by mbid.
For example:
`lidarr:973d7c4c-11b6-4424-980a-eb9262a08589` (https://musicbrainz.org/artist/973d7c4c-11b6-4424-980a-eb9262a08589)
`lidarr:485111e2-a1e8-4a46-bf3e-a073f005b28a` (https://musicbrainz.org/artist/485111e2-a1e8-4a46-bf3e-a073f005b28a)

1. Go to 'Artist -> Add new'
2. Fill search with `lidarr:973d7c4c-11b6-4424-980a-eb9262a08589`
3. See no results

**Expected behavior**
Artist is found and can be added.
Even better would be if artists can be found by their names.

**Screenshots**
![image](https://user-images.githubusercontent.com/2041351/57012634-f663ce00-6c20-11e9-8400-d38f99523fe5.png)

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.830
 - Operating System: Ubuntu Linux
 - Docker: 18.09.5, build e8ff056
 - mono Version: 5.20.1.19

**Comment by ta264** [comment]
API seems to be down more generally, doesn't seem to be working for any artist

**Comment by jkoopmann** [comment]
Agreed: 19-5-1 13:00:25.6|Warn|HttpClient|HTTP Error - Res: [GET] https://api.lidarr.audio/api/v0.4/search?type=artist&query=lid: 503.ServiceUnavailable
{"error":"Could not connect to redis"}

**Comment by ta264** [comment]
Back up now and those artists work as expected

**Comment by OlegAndreych** [comment]
Thank you for your help )
