### ISSUE TITLE
Folder Mapping Issue

### ISSUE THREAD

**Issue by mccorkled** [lidarr/Lidarr#802]
I am using Docker for all of my programs described below. 

Recently I setup Haugene's Transmission which has OVPN built in. It stores it's downloads to /data/incomplete and data/complete and I mapped this to my downloads/incomplete and downloads/complete within the Docker. When Lidarr adds torrents they are tagged with Music and when completed are in downloads/complete/Music

In Lidarr I mapped /downloads to downloads and with the non-OVPN version of Transmission it knew completed downloads were in the /downloads/complete/Music folder since it was the program that tagged it as such. With this OVPN version of Transmission I am getting this error in Lidarr and it will not post process anything.

`You are using docker; download client Transmission places downloads in /data/complete/.Music but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.`

I have been messing around with this for about a week now and can't figure out what the problem is. Although Lidarr is showing /data/Downloads I have the downloads folder mapped to /downloads in both Transmission and Lidarr. I also do not know why Lidarr is looking for .Music instead of just Music.

Any idea what is causing this?
Thank you.

**Comment by Qstick** [comment]
Fixed in nightly, should be in new release this week
