### ISSUE TITLE
Request: Integrate with Spotify and Noteburner or any other app that can rip from Spotify

### ISSUE THREAD

**Issue by timc6896** [Lidarr/Lidarr#806]
**Feature Request**

This is a new feature request if not already implemented.  Noteburner is an app that can rip music off of Spotify playlists.  It would be awesome if Lidarr can search Spotify for songs/albums and send it to Noteburner to rip, then put them into the correct folders.  This would be an addition to supporting torrents and usenet.  Spotify seems to be the most complete for grabbing missing song titles instead of full album downloads from usenet or torrents.

**Describe how it would work**
Noteburner works by dragging a playlist from Spotify.  What Lidarr can do is to autocreate the playlist in Spotify for each album in question.  Send the playlist to Noteburner.  Delete playlist from Spotify once done.  Move the files from the Saved location to the correct location.

**Describe alternatives you've considered**
Noteburner is just one application that can rip from Spotify.  Pretty much any application to rip from Spotify, iTunes, Amazon music or any provider will work.

[AB#423](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/423)

**Comment by mechanimal82** [comment]
I'm not sure how easy that would be to integrate... a workaround could be to use the feature requests here: https://github.com/lidarr/Lidarr/issues/334 to grab the lists/albums and then couple that with the scripts in the git repo here: https://github.com/ritiek/spotify-downloader to perform the downloading (but from youtube)

**Comment by Gijs735** [comment]
> I'm not sure how easy that would be to integrate... a workaround could be to use the feature requests here: #334 to grab the lists/albums and then couple that with the scripts in the git repo here: https://github.com/ritiek/spotify-downloader to perform the downloading (but from youtube)

I tried this suggestion but Spotify-Downloader seems to sometimes make mistakes or download very inferior versions. Some music that I listen to on Spotify isn't available on youtube as well (remixes, soundtracks, ...).

Because of this I would like a ripping feature as well.

**Comment by liquidthex** [comment]
I love Lidarr but I'm having difficulty using it--I don't have access to any private music trackers, and it looks like they are rather difficult to gain access.
So I'd like some alternatives to usenet or torrents for acquiring older music.
I know some python and would be willing to do some work on this if you could point me in the right direction for how this should be implemented fundamentally speaking (best practice), and where in the code the modifications need to be made (so that I don't miss something I wasn't aware of).
Thanks!

**Comment by ta264** [comment]
I think the first thing to be aware of is it's written in csharp :D

**Comment by Qstick** [comment]
Not planned native, possible with plug-in
