### ISSUE TITLE
Failure to Manual Import

### ISSUE THREAD

**Issue by benzo8** [lidarr/Lidarr#807]
**Describe the bug**
When an artist is selected, Manual Import should give a list of unmapped files to allow manual import. Trying this I get an error:

`Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [https://api.acoustid.org/v2/lookup]`. 

On going to the given URL manually, I get:

`{"status": "error", "error": {"message": "missing required parameter \"client\"", "code": 2}}`

**To Reproduce**
1. Go to any artist
2. Click on Manual Import
3. Wait

**Expected behavior**
A list of unmapped files on the disk should be shown

**System info (please complete the following information):**
 - Lidarr Version: 0.6.1.830
 - Operating System Linux 18.09.03 within linuxserver/lidarr:latest Docker Container
 - Mono Version: 5.20.1.19

**Comment by Qstick** [comment]
Fixed in #808
