### ISSUE TITLE
User Defined Queue Depth

### ISSUE THREAD

**Issue by RandallSG** [lidarr/Lidarr#809]
**Feature Request**

Lidarr appears to be limited to a queue depth of 3, or in other words only three tasks are queued for Lidarr at any given time. 

For those of us with a very large libraries... who may also happen to have  very fast file servers, lots of bandwidth and a powerful server, none of which is helping Lidarr run any faster since tasks are limited to 3 threads.

Some tasks such as running a refresh of artists take a very long time and could be completed much sooner if Lidarr would give the user the option to queue more tasks at the same time.

*User Defined Queue Depth**

Allow the User to choose how many concurrent tasks are run by Lidarr at any given time.  Ideally somewhere between 3-10 concurrent tasks (or more)

**Describe alternatives you've considered**

I am not aware of any other alternative to increase the overall performance of Lidarr on any given server.

**Comment by Qstick** [comment]
We have some other plans in mind that will lead to much better performance for refreshing. Ex. #760 and improved metadata caching. While I'm not closing this I think there are better ways to improve performance currently than just stacking on threads, this can also lead to support nightmares when users don't know what they are doing.
