### ISSUE TITLE
Request: ability to move music files to a new location for imported music

### ISSUE THREAD

**Issue by timc6896** [lidarr/Lidarr#810]
**Feature Request**
A way to move all the music files to a new location.  This will be awesome to clean up your library, especially when adding existing library.  This is will help generate a new clean library.

**Solution**
Option to move the files to a clean location on any part of the network.

**Comment by Qstick** [comment]
Artist Edit Screen allows you to move a path, I believe Artist editor let's to multiple artists at once.

**Comment by timc6896** [comment]
You are correct!  I missed that because I never actually clicked on Save :)  I'll be testing this extensively now to help clean up my library.  This seems to be a much better way than anything I have found out there.

**Comment by Qstick** [comment]
Let us know if you find any issues with it

**Comment by timc6896** [comment]
Definitely!  And thank you for the support.  I just did a quick test of moving one artist and the associated albums.  The artist contains 8 album releases in Lidarr because that's how my metadata is configured.  The folder on my HDD has about 26 albums for the artist.  The move I was expecting was to move just the 8 albums, and not the entire directory.  Is this the intended behavior?

**Comment by Qstick** [comment]
Yea, Lidarr is very focused around the artist path as the base. Currently it will pickup the entire folder and everything in it
