### ISSUE TITLE
Importing fails, invalid handle to path ""

### ISSUE THREAD

**Issue by Ing-Med** [lidarr/Lidarr#812]
**Describe the bug**
Lidarr doesn't import my files, i don't know why. Supposedly because of the filenaming? 

**To Reproduce**
Reproducable for same files. 

**Expected behavior**
Importing the file

**Logs**

> 19-5-14 01:31:51.6|Debug|TrackFileMovingService|Moving track file: complete/music/1999 - Love Songs/04 Almost A Whisper.flac to /Music/Yanni/Love Songs (1999)/Yanni-Love.Songs.(1999)-04-Almost.a.Whisper-[FLAC-16bit].flac
> 19-5-14 01:31:51.6|Debug|DiskTransferService|Move complete/music/1999 - Love Songs/04 Almost A Whisper.flac] > [/Music/Yanni/Love Songs (1999)/Yanni-Love.Songs.(1999)-04-Almost.a.Whisper-[FLAC-16bit].flac]
> 19-5-14 01:31:53.0|Debug|Api|[POST] /api/v1/command: 201.Created (2380 ms)
> 19-5-14 01:31:53.4|Info|RefreshArtistService|Updating Info for Yanni
> 19-5-14 01:31:54.4|Debug|SkyHookProxy|Getting Artist with LidarrAPI.MetadataID of 9a2afb1e-504c-443e-acff-6c40ce75b1a1
> 19-5-14 01:31:55.5|Debug|RefreshArtistService|[9a2afb1e-504c-443e-acff-6c40ce75b1a1][Yanni] Deleting 0, Updating 49, Adding 0 albums
> 19-5-14 01:31:55.5|Info|RefreshAlbumService|Updating Info for My World in Music - The Collection
> 19-5-14 01:31:55.6|Debug|SkyHookProxy|Getting Album with LidarrAPI.MetadataID of 023a86d6-2653-3927-9d02-34e13a40272a
> 19-5-14 01:31:57.4|Debug|Api|[GET] /api/v1/customFilter: 200.OK (2 ms)
> 19-5-14 01:31:57.5|Debug|Api|[GET] /api/v1/tag: 200.OK (2 ms)
> 19-5-14 01:31:57.5|Warn|ImportApprovedTracks|Couldn't import track complete/music/1999 - Love Songs/04 Almost A Whisper.flac
> 
> [v0.6.2.883] System.IO.IOException: Invalid handle to path ""
>   at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00116] in <a6f810169ec746eeb2789b925e2858c0>:0 
>   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal (System.String source, System.String destination) [0x00000] in <661475469d074ecf9c4fa9103b859bad>:0 
>   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal (System.String source, System.String destination) [0x00076] in <a2c4be6d06774f1bbe7e6317175cf464>:0 
>   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e1] in <661475469d074ecf9c4fa9103b859bad>:0 
>   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, System.Int64 originalSize, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0008f] in <661475469d074ecf9c4fa9103b859bad>:0 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x003cc] in <661475469d074ecf9c4fa9103b859bad>:0 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in <661475469d074ecf9c4fa9103b859bad>:0 
>   at NzbDrone.Core.MediaFiles.TrackFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.TrackFile trackFile, NzbDrone.Core.Music.Artist artist, System.Collections.Generic.List`1[T] tracks, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x00129] in <5ef528d97f504a2eb51961f386df9d8b>:0 
>   at NzbDrone.Core.MediaFiles.TrackFileMovingService.MoveTrackFile (NzbDrone.Core.MediaFiles.TrackFile trackFile, NzbDrone.Core.Parser.Model.LocalTrack localTrack) [0x00073] in <5ef528d97f504a2eb51961f386df9d8b>:0 
>   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeTrackFile (NzbDrone.Core.MediaFiles.TrackFile trackFile, NzbDrone.Core.Parser.Model.LocalTrack localTrack, System.Boolean copyOnly) [0x00181] in <5ef528d97f504a2eb51961f386df9d8b>:0 
>   at NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean replaceExisting, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.TrackImport.ImportMode importMode) [0x005bd] in <5ef528d97f504a2eb51961f386df9d8b>:0 

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System Ubuntu 18 LTS
 - mono (macOS/Linux) Version: 5.8.0.127

**Comment by ta264** [comment]
The path looks wrong, starting without a /. Not sure how that has happened. You'll probably have more luck getting support in the discord channel.

**Comment by Ing-Med** [comment]
Path is correct, that's only missing because of my sloppy censoring :) i ll have a look into the discord channel
