### ISSUE TITLE
Lidarr cannot see this directory

### ISSUE THREAD

**Issue by OrganicKobze** [lidarr/Lidarr#813]
**Describe the bug**
Download client Deluge reported files in X - Y but Lidarr cannot see this directory. You may need to adjust the folder's permissions.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by ta264** [comment]
This is a feature telling you that if you lidarr set up incorrectly, not a bug.  Please join the discord support channel if you need help setting it up.
