### ISSUE TITLE
Bug Report: Album in MusicBrainz not found/fetched by Lidarr

### ISSUE THREAD

**Issue by jimbobcraig** [lidarr/Lidarr#814]
Album in MusicBrainz not found/fetched by Lidarr

- Add artist: Bassheads
- Album: C.O.D.E.S. is not fetched by Lidarr, perhaps something to do with periods (.) in album name!?
- Metdadata profile is set to fetch everything.

https://musicbrainz.org/artist/bc288953-2b93-4c3d-8ee0-851c8bbc30f4

Excerpt from logs:
`[Info] RefreshArtistService: Updating Info for Bassheads
[Info] DiskScanService: Scanning Bassheads
[Info] DiskScanService: Completed scanning disk for Bassheads
[Info] ExistingMetadataImporter: Found 0 existing metadata files
[Info] ExistingLyricImporter: Found 0 existing lyric files
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files
[Info] ExistingExtraFileService: Found 0 extra files
[Info] RefreshArtistService: Updating Info for Bassheads
[Info] AddAlbumService: Adding Album Is There Anybody Out There?
[Info] RefreshTrackService: Starting track info refresh for: [46187641-ec1b-3163-a45a-a547b88edab6][Is There Anybody Out There?]
[Info] RefreshTrackService: Finished track refresh for album: [46187641-ec1b-3163-a45a-a547b88edab6][Is There Anybody Out There?].
[Info] AddAlbumService: Adding Album Back to the Old School
[Info] RefreshTrackService: Starting track info refresh for: [a9c4044e-4e8a-342e-b6ef-a26c4bc86c9c][Back to the Old School]
[Info] RefreshTrackService: Finished track refresh for album: [a9c4044e-4e8a-342e-b6ef-a26c4bc86c9c][Back to the Old School].
[Info] DiskScanService: Scanning Bassheads
[Info] DiskScanService: Completed scanning disk for Bassheads`

**System info (please complete the following information):**

Version 0.6.2.883
Mono Version 5.18.1.0
Docker True (linuxserver/lidarr) up-to-date!
DB Migration 29

**Comment by ta264** [comment]
It was missing a release status on Musicbrainz.  I've put in an edit but it'll take a day or two to reflect in our metadata feed.

**Comment by jimbobcraig** [comment]
@ta264 great, thanks. will learn how to contribute to MusicBrainz now!
