### ISSUE TITLE
API gives "Sequence contains more than one element"

### ISSUE THREAD

**Issue by petwri** [lidarr/Lidarr#816]
When doing the API call `api/v1/album?apikey=$myapikey` I get the following message back

`{
  "message": "Sequence contains more than one element",
  "description": "System.InvalidOperationException: Sequence contains more than one element\n  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0007b] in <35ad2ebb203f4577b22a9d30eca3ec1f>:0 \n  at Lidarr.Api.V1.Albums.AlbumResourceMapper.ToResource (NzbDrone.Core.Music.Album model) [0x0003b] in <99b84aff4e774ab7845fd2ccab446c9c>:0 \n  at System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () [0x0002a] in <35ad2ebb203f4577b22a9d30eca3ec1f>:0 \n  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <35ad2ebb203f4577b22a9d30eca3ec1f>:0 \n  at Lidarr.Api.V1.Albums.AlbumResourceMapper.ToResource (System.Collections.Generic.IEnumerable`1[T] models) [0x00017] in <99b84aff4e774ab7845fd2ccab446c9c>:0 \n  at Lidarr.Api.V1.Albums.AlbumModuleWithSignalR.MapToResource (System.Collections.Generic.List`1[T] albums, System.Boolean includeArtist) [0x00000] in <99b84aff4e774ab7845fd2ccab446c9c>:0 \n  at Lidarr.Api.V1.Albums.AlbumModule.GetAlbums () [0x00503] in <99b84aff4e774ab7845fd2ccab446c9c>:0 \n  at Lidarr.Http.REST.RestModule`1[TResource].<set_GetResourceAll>b__33_0 (System.Object options) [0x00006] in <c2222b24c4c34e46bb6c82bdd60b9516>:0 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <bb3027f50b35411088f45475912cc2ff>:0 "
}`

**System info:**
 - Lidarr Version: 0.6.1.830
 - Operating System: Ubuntu Linux 16.04
 - mono Version: 5.20.1.19

**Additional context**
API has been working for quite a while, it suddently stopped.

**Comment by ta264** [comment]
Upgrade to 0.6.2 and it should be fixed

**Comment by petwri** [comment]
Works with 0.6.2, thanks for the fix!

**Comment by ybaumy** [comment]
Sorry but this does not work for me with 0.6.2

> Version
> 0.6.2.883
> Mono Version
> 5.20.1.19

i am having the same problem

**Comment by ta264** [comment]
Try manually refreshing the relevant artist

**Comment by ybaumy** [comment]
happens when adding a new artist as well. refreshing the same or searching for albums. basically lidarr currently does not work for me anymore

**Comment by ta264** [comment]
Jump on the discord channel and we can investigate
