### ISSUE TITLE
Make calendar feed time span configurable

### ISSUE THREAD

**Issue by HerHde** [lidarr/Lidarr#817]
**Is your feature request related to a problem? Please describe.**
Currently the relative start and end date of the iCal feed are hardcoded, which first confused me, then I thought it'd be a bug, then I found this setting hardcoded:
https://github.com/lidarr/Lidarr/blob/cee1b33c60a1a9a17bce390fff3a0f2631f48d70/src/Lidarr.Api.V1/Calendar/CalendarFeedModule.cs#L35-L40

**Describe the solution you'd like**
Please make the number of days (past and future) included in the ics configurable in the iCal modal (and therefore in the GET-parameters).

**Describe alternatives you've considered**
I could hardcode a different interval for myself.

**Additional context**
I've tested it with the latest [linuxserver/lidarr](https://github.com/linuxserver/docker-lidarr) docker image.

**Comment by Qstick** [comment]
Looking at the code, these are not hard-coded, they are just defaults. if you pass the pastDays or futureDays parameter to the feed then Lidarr will use those instead:

https://github.com/lidarr/Lidarr/blob/cee1b33c60a1a9a17bce390fff3a0f2631f48d70/src/Lidarr.Api.V1/Calendar/CalendarFeedModule.cs#L44-L58
