### ISSUE TITLE
 Deezloader Support

### ISSUE THREAD

**Issue by Wdavery** [Lidarr/Lidarr#820]
Deezloader is a great source for music and would be great to integrate into Lidarr. 
https://notabug.org/RemixDevs/DeezloaderRemix

Obviously there would need to be an API on their end before this can happen, so I will [open an issue over there. ](https://notabug.org/RemixDevs/DeezloaderRemix/issues/350)

[AB#426](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/426)

**Comment by Wdavery** [comment]
SMLoadr is another option. 
https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr

This script is all that exists to interface between them so far. https://github.com/Migz93/lidarr_smloadr_script

**Comment by jimsaye** [comment]
https://github.com/Sorrow446/Qo-DL this tool for qobuz

**Comment by Wdavery** [comment]
Deezloader appears to have added a rest API now. See here: https://github.com/RemixDev/DRemixIssues/issues/93

**Comment by mecaz** [comment]
+1

**Comment by Qstick** [comment]
This will come via plug-in, not native
