### ISSUE TITLE
No files found are eligible for import

### ISSUE THREAD

**Issue by mccorkled** [lidarr/Lidarr#821]
I recently got all my programs reset up in Docker after a crash. After a download completes I am getting at error on the completed torrent  `No files found are eligible for import /downloads/complete/Music/artists or album name`

In the container I have tried to map /downloads to /downloads and when that didn't work I mapped /downloads/complete/Music to /downloads and that didn't work. 

I am also getting `You are using docker; download client Transmission places downloads in /downloads/complete/Music but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.`  under the system menu

**Comment by ta264** [comment]
Please join the discord channel for support, there's just a configuration error somewhere.
