### ISSUE TITLE
Lidarr not importing utorrent files

### ISSUE THREAD

**Issue by DavideCampagna** [lidarr/Lidarr#823]
**Describe the bug**
Lidarr not importing files once downloaded from uTorrent

**To Reproduce**
Download any album via utorrent

**Expected behavior**
Once downloaded, move to music folder & index

**Logs**
[Lidarr.1.txt](https://github.com/lidarr/Lidarr/files/3229982/Lidarr.1.txt)
[Lidarr.2.txt](https://github.com/lidarr/Lidarr/files/3229983/Lidarr.2.txt)
[Lidarr.3.txt](https://github.com/lidarr/Lidarr/files/3229984/Lidarr.3.txt)
[Lidarr.4.txt](https://github.com/lidarr/Lidarr/files/3229985/Lidarr.4.txt)
[Lidarr.txt](https://github.com/lidarr/Lidarr/files/3229986/Lidarr.txt)
[Lidarr.0.txt](https://github.com/lidarr/Lidarr/files/3229987/Lidarr.0.txt)

**System info (please complete the following information):**
 - Lidarr Version: [0.6.2.883]
 - Operating System [Windows 10 Pro 64]

**Additional context**
I know that there is an error given by a indexer not working, that's not the problem

**Comment by Qstick** [comment]
Lidarr will tell you in queue why imports are not working. Also feel free to join discord support channel for help on this
