### ISSUE TITLE
Download/monitor single songs?

### ISSUE THREAD

**Issue by Ansem93** [Lidarr/Lidarr#826]
Hi,
I would ask if would be possible to monitor and dowload only selected songs.
To do so this is how I would do it:
1) Add a column with checkbox "Monitor"
2) Add a button "invert selection" in case someone need only few songs
3) If it's not possible to tell at the torrent client which files download, just download the full album, then move the checked songs and delete the others

[AB#427](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/427)

**Comment by Qstick** [comment]
Would you plan on having Lidarr download the entire album and delete the rest of the songs? Seems like a waste

**Comment by Ansem93** [comment]
As I said, I'm not sure if lidarr can tell at the torrent client which songs download. 
If it can select the files to download to every client than is perfect, otherwise download the entire album and then manage the single files can still be a solution.

**Comment by skidaddl3** [comment]
If Lidarr can't find the single song in the torrent library, then it should download the album... Worst case scenario?

**Comment by Ansem93** [comment]
After downloading the entire album it should delete the unwanted songs, since otherwise players like musicbee will add them to the music library even if I don't want to.
This is how it works on my NAS:
- Lidarr download the album in the default folder
- it move the album to the "new songs" folders
- MB scan "new songs" and move it to the music library.

I would like lidarr to move only the selected songs to the "new songs" folder and possibly delete the unwanted one.

**Comment by costaht** [comment]
That would be a great feature. I have some music that I just want to be upgraded to a higher bitrate and for that, I'm willing to download the full album and discard the ones I don't want.

**Comment by FabioDeMiranda** [comment]
+1

I think this is a great idea, it doesn’t matter if it’s a waste downloading the album, it’s much worse having to remove it later or waste disk space with songs I don’t really want...

I love streaming services because I have the option to only add songs that I really want.

**Comment by bakerboy448** [comment]
Please refrain from making useless, spammy comments: including, me too and +1.

If you are in favor of something and do not have anything beneficial or productive to add. Simply +1 the OP

**Comment by FabioDeMiranda** [comment]
> Please refrain from making useless, spammy comments: including, me too and +1.
> 
> If you are in favor of something and do not have anything beneficial or productive to add. Simply +1 the OP

Please be less toxic with people trying to help improve the system, thank you!

**Comment by kernitus** [comment]
On top of wanting to download just a couple of songs out of albums, I also find it incredibly annoying when Lidarr decides to downloads 12 different versions of the same single, including every possible remix by any mediocre DJ you may have never even heard of...

**Comment by taibhse-designs** [comment]
Is there any way to get this working yet? Looking at programs like Mylar that download comics yet let you download specific issues and mark ones to be skipped, it would ideal if Lidarr can do the same for music and albums, often only a few songs from different albums are wanted, while space is cheap, having to then sort through a thousand extra songs you dont want for making playlists gets tedious real quick.

It would be ideal if we could just add artists and then either mark an entire album or just the specific songs we want. Lidarr can still download the entire album and afterwards just delete the not wanted songs.

**Comment by driesvandamme** [comment]
Would be even better if the file renaming could be different for Singles vs. Albums & Multi-disk Albums...
Or if Lidarr would support a syntax like MusicBrainz (with variables, so we can create the logic ourselves for singles)

**Comment by dvd741-a** [comment]
Would be even better if the file renaming could be different for Singles vs. Albums & Multi-disk Albums...
Or if Lidarr would support a renaming syntax like MusicBrainz (with variables, so we can create the logic ourselves for singles)

**Comment by bakerboy448** [comment]
Closing in favor of #3047
