### ISSUE TITLE
Manual import shouldn't remove downloads.

### ISSUE THREAD

**Issue by rubdos** [lidarr/Lidarr#828]
**Is your feature request related to a problem? Please describe.**
I want to permanently seed all music that I snatch. If Lidarr does not like the format of the download for some reason (e.g., different edition than specified in request), I have to resort to manual import. Manual import unconditionally removes the files from the source location. If I'd use e.g. beets for the manual import, the queue stays littered with "unhandled" downloads.

Before I noticed this happened, I've already got a bunch of albums unseeded.

**Describe the solution you'd like**
Manual import should provide an option to copy and link instead of move files.

**Describe alternatives you've considered**
Use beets to import, leave the queue littered.

**Additional context**
n/a

**Comment by ta264** [comment]
There's a drop-down on the bottom left that lets you choose to move Vs copy (and copy will link if that's how you have it set up)

**Comment by fent** [comment]
this happened to me too, took me a while to notice missing files in my torrent client. sonarr and radarr are also like this.

I suggest one of
- putting a warning next to the "move" option that says something like "(this will move the file from your torrent client's location)"
- changing the location of the downloaded file in the torrent client too. the tricky side with this is handling upgrades. the previously downloaded version would have to be moved back or paused or deleted from the client.

additionally, "copy" could say "hard link" if that's what the user has set in the options.
