### ISSUE TITLE
MediaCover API Documentation Needs Updating

### ISSUE THREAD

**Issue by TChilderhose** [lidarr/Lidarr#832]
**Describe the bug**
PR #780 changed the endpoints for artist and album MediaCover apis as outlined [in the wiki](https://github.com/lidarr/Lidarr/wiki/Images). 

Old Example:
```
/api/v1/MediaCover/1/poster-250.jpg
/api/v1/MediaCover/Albums/9/cover-250.jpg
```

New Working Example:
```
/api/v1/MediaCover/Artist/1/poster-250.jpg
/api/v1/MediaCover/Album/9/cover-250.jpg
```

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System: Linux (Docker)
 - Mono Version: 5.20.1.19

**Additional context**
Not sure the protocol for public editing wiki pages, and I'm sort of new to the github project flow (svn guy) so not sure what is all supported for pull requests on something like wikis. Thanks for all the hard work!

**Comment by Qstick** [comment]
We currently have wiki open for public edits, feel free to update the page. We can keep this open until then.

Thanks!!

**Comment by TChilderhose** [comment]
Great! Updated it. Let me know if you need me to change anything in it. Otherwise going to close.

Thanks again!

**Comment by Qstick** [comment]
Think we ditched the 500px cover, so that could be removed from options at bottom
