### ISSUE TITLE
HTTP 400 - Bad Request (Invalid host) if Lidarr listens on localhost with reverse_proxy setup

### ISSUE THREAD

**Issue by sqozz** [Lidarr/Lidarr#837]
**Describe the bug**
Lidarr refuses to serve its content to the connecting browser if its `BindAddress` is set to `localhost` or `127.0.0.1` and the connection is made trough an nginx reverse proxy setup. If I set the `BindAddress` to the specific interface ip or alternatively to `*`, everything works as expected trough the reverse proxy. Therefore I'll not paste my nginx config since it works with the right bind address and the later described workaround.

Here is an `ngrep` capture of the HTTP request between Lidarr and my nginx:
```
T 127.0.0.1:34720 -> 127.0.0.1:8686 [AP]
GET / HTTP/1.0.
Host: lidarr.example.com.
Connection: close.
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0.
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8.
accept-language: de,en-US;q=0.7,en;q=0.3.
accept-encoding: gzip, deflate, br.
upgrade-insecure-requests: 1.
cache-control: max-age=0.
.

##
T 127.0.0.1:8686 -> 127.0.0.1:34720 [AP]
HTTP/1.1 400 Bad Request.
Content-Type: text/html; charset=utf-8.
Server: Mono-HTTPAPI/1.0.
Date: Wed, 19 Jun 2019 21:19:08 GMT.
Content-Length: 35.
Connection: close.
.
<h1>Bad Request (Invalid host)</h1>
```

**To Reproduce**
1. Set BindAddress to 127.0.0.1 in the lidarr config
2. Access the domain for lidarr served by the reverse proxy
3. Observe the http 400 message: "Bad Request (Invalid host)"

**Expected behavior**
I understand that this might be done by the mono web-server to increase security. If this is not relevant, this check should be disabled. Alternatively there could be an additional option to configure the allowed/expected Host-header in lidarr itself.
For the time being the workaround might be added to the documentation.

**Logs**
Unfortunately I was unable to capture any useful information from the lidarr log. All insights came from network traffic and web-server logs.

**System info:**
 - Lidarr Version: 0.6.2.883
 - Operating System: Gentoo Linux
 - mono (macOS/Linux) Version: 5.20.1.19

**Workaround**
I was able to workaround this issue by explicitly cleaning the HTTP `Host` header from the requests before passing them to Lidarr. This can be done like follows in the nginx config:

```
proxy_set_header Host "";
```

Afterwards the backend happily serves requests even though technically speaking an empty `Host` header should be invalid too then. But this might be worth a separate report.

Thanks in advance!

[AB#453](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/453)

**Comment by ta264** [comment]
Does this happen in sonarr v3 also or is this lidarr specific?

**Comment by sqozz** [comment]
Can't tell you if it happens with sonarr but I had the same problem with radarr.

**Comment by ta264** [comment]
I suggest you test sonarr v3 (I imagine it'll have the same issue if Radarr does too) and if so open an issue there. If not we can try to work out what has broken in lidarr specifically. I think you'll get more traction getting the upstream project fixed and we can pull the changes into lidarr and radarr.

**Comment by sqozz** [comment]
I searched their issues a little bit and found that https://github.com/Sonarr/Sonarr/issues/622#issuecomment-146271678 already describes the same behavior and workaround.
