### ISSUE TITLE
Cannot write metadata tags to OPUS files (.opus)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lidarr/Lidarr#841]
**Describe the bug**
OPUS support was recently added, the files are now detected properly and imported properly. However, if you use the retag function you will end up with files with no tags at all.

**To Reproduce**
1. Import/add some OPUS (.opus) music to your library
2. Use the re-tag option to tag the files or have them tagged on import
3. View the file metadata in a tag editor (MP3Tag (windows), Puddletag (Linux))
4. See that files are blank

**Expected behavior**
Expected the file to be tagged

**Screenshots**
![image](https://user-images.githubusercontent.com/8386416/60267400-27c2e800-98b8-11e9-9730-db741f48c022.png)

**System info (please complete the following information):**
 - Lidarr Version: Nightly
 - Operating System: Docker (LinuxServer.io)

**Additional context**
The tags should be VORBIS type, which is what FLAC uses.

**Comment by ta264** [comment]
There are tests built in that verify opus tagging is working (and can write tags and read them back in properly) so this is odd. Can you join the discord channel and we can investigate?

**Comment by ta264** [comment]
As discussed on discord, the tags show up in picard and foobar so looks like a bug in mp3tag

**Comment by ta264** [comment]
Seems there is a legitimate bug in taglib
