### ISSUE TITLE
Mac app damaged

### ISSUE THREAD

**Issue by roontoon** [lidarr/Lidarr#842]
Mac app on Github damage and will not launch. Tried on two different macs.

**Comment by roontoon** [comment]
<img width="573" alt="lidarr" src="https://user-images.githubusercontent.com/874090/60305160-b01da900-9909-11e9-8fac-7d0735ebdc27.png">

**Comment by Qstick** [comment]
What version are you trying to use? I thought this was fixed long ago

**Comment by roontoon** [comment]
The one that downloads from your main github page.

**Comment by Qstick** [comment]
That tells me nothing, there are many releases under the release page, what is the name of the file?

**Comment by roontoon** [comment]
Latest commit 447bf63  yesterday

**Comment by roontoon** [comment]
Lidarr.app

**Comment by Qstick** [comment]
Did you just download the source code and try to run it? Can you screenshot exactly what you clicked and downloaded?

**Comment by roontoon** [comment]
Not doing source code. Just hit the download button on your page and moved the Lidarr.app to my mac.

**Comment by Qstick** [comment]
You downloaded from this page? https://github.com/lidarr/Lidarr/releases

**Comment by roontoon** [comment]
This one.

<img width="1066" alt="lidarr:Lidarr: Looks and smells like Sonarr but made for music  2019-06-27 19-03-23" src="https://user-images.githubusercontent.com/874090/60306480-510e6300-990e-11e9-8df5-26d205c3567a.png">

**Comment by Qstick** [comment]
That's the source code... Go to the releases page

**Comment by Qstick** [comment]
Lidarr.develop.0.6.2.883.osx-app.zip is what you want
