### ISSUE TITLE
XMBC Metadata not writing .nfo

### ISSUE THREAD

**Issue by ic3y808** [lidarr/Lidarr#843]
**Describe the bug**
XMBC Metadata provider is not writing missing data after re scanning an artist. It is also not generating data when new albums are added from local existing media/preview rename.

**To Reproduce**
- Start fresh lidarr
- go to settings -> metadata
- Edit Kodi (XBMC) / Emby Metadata
- Check enabled/all boxes
- Add a new artist which you already have an album for.
- Open root music folder and copy existing data.
- Make sure there is a album which does not have metatdata album.nfo file in the sub folder
- Click refresh artist
- new .nfo files are not generated for existing albums folders

**Expected behavior**
An album.nfo file containing the musicbrainz information is generated for folders which do not have it and are showing as found in lidarr

**Logs**
https://gist.github.com/ic3y808/8268525d9323423cbccdf96a57674344

**System info (please complete the following information):**
 - Current develop brange as of commit /447bf63a4dc390055a3aee03ec5372a58d43b246
 - Operating System: windows 10
 - .windows .net 4.5 

**Additional context**
This used to worked as described but I didnt catch when this broke. The refresh used make sure all .nfo files were present in the artist and album sub folders. I have external software which relies on these files to be present and that lidarr is generating these files during rescans. 
Thanks.

**Comment by ta264** [comment]
Are you saying that lidarr doesn't generate the nfo for the new album that you copied in?  Or that lidarr doesn't add nfo for a second album that is already added to lidarr but is missing the nfo?

**Comment by ta264** [comment]
Looking at your logs more closely this is to be expected.  There have been no changes to music files on disk so lidarr doesn't do any scanning/metadata generation.
```
19-6-28 09:43:18.5|Debug|MediaFileService|Filtering 64 files for unchanged files
19-6-28 09:43:18.5|Debug|ImportDecisionMaker|Analyzing 0/64 files.
```

Metadata will only be added on initial import - if something is deleting them they won't be regenerated.  But we should perhaps make sure they are generated correctly if the metadata settings change.

**Comment by ic3y808** [comment]
Thanks for the input ta264. 

**_Are you saying that lidarr doesn't generate the nfo for the new album that you copied in?_** 

Correct, an album which has no existing data (0 red track count in ui). 
If you add the data to the artist folder and then refresh the artist to find the new album. it does not generate album.nfo The album is added (green tracks in UI) but no file is generated. 

Here is a quick video of the problem: https://gfycat.com/elatedabsolutefalcon
You can see at the very end, lidarr signals Complete for the scan and found the files, but no .nfo files were added to the album folder. 

This happens in both cases of already having the correct naming/folder structure or just adding the loose files to the artist folder/rescan/preview rename. No album.nfo is ever generated. 

**_Looking at your logs more closely this is to be expected. There have been no changes to music files on disk so lidarr doesn't do any scanning/metadata generation._**

What should constitute a change? Lidarr did not have the files under the root folder when I added the artist, I then added them and re scanned which it found the new files. 

**_Metadata will only be added on initial import - if something is deleting them they won't be regenerated. But we should perhaps make sure they are generated correctly if the metadata settings change._**

Nothing is being removed externally, the file is just not being generated at all during any import scenario. 

Having the metadata feature enabled to me means that lidarr is keeping track of all folders it manages. I would like to see that if I have this feature enabled, it always enforces metadata to be present for the managed files/folders. 

Thanks for the fast reply!

**Comment by ta264** [comment]
Can you jump on the discord channel and we can investigate a little?
https://discord.gg/QfVFHr7

**Comment by ta264** [comment]
Testing this on latest nightly this works fine so I'm going to close this.  Feel free to ask again in discord if you're still having problems.
