### ISSUE TITLE
You have an old version of fpcalc. Please upgrade to 1.4.3.

### ISSUE THREAD

**Issue by fana13** [lidarr/Lidarr#846]
**Lidarr Version:**
    0.6.2.883

**Operating System:**
Debian Jessie

**.net Framework (Windows) or mono (macOS/Linux) Version:**
    5.18.1.0

**Browser (for UI bugs):**
Firefox

### Description of request and what problem are you looking to solve?

System > Status > You have an old version of fpcalc. Please upgrade to 1.4.3.

The last version of libchromaprint-tools is installed, no more upgrade possible
But i've got this message
And since the post processing doesn't work.

**Comment by ta264** [comment]
This message doesn't indicate a problem that would break post processing. Check you logs for the actual cause. Jessie doesn't provide up to date packages for chromaprint print, you can either ignore the warning or download binaries from the chromaprint website.
