### ISSUE TITLE
Mixtape being marked as .ape

### ISSUE THREAD

**Issue by lostandlost** [lidarr/Lidarr#847]
I have noticed that if a release that has the word "mixtape" in it Lidarr will marking it as .ape.  Since I don't have ape allowed in my profile it means that mixtapes are not getting downloaded unless I force it.  If there is no good way to fix this, is there a set of rules I can use that will not download .ape files, but allow mixtapes?  Thanks!

**Comment by Qstick** [comment]
Regex needs to be adjusted, likely.

**Comment by Qstick** [comment]
@lostandlost do you have a release name that fails?

**Comment by lostandlost** [comment]
> 
> 
> do you have a release name that fails?

I started looking at some of the Logic mixtapes and they are no longer being marked as APE after the latest update.  If you still need examples let me know.  Thank you for the update.

**Comment by Qstick** [comment]
Yea I was able to reproduce... Thanks
