### ISSUE TITLE
Artist is missing album

### ISSUE THREAD

**Issue by Ackis** [lidarr/Lidarr#849]
3 Door's Down first self-titled album is missing.  The 2008 release shows up, but the 1997 release does not.

Note that both albums have the same name.

**Comment by ta264** [comment]
This isn't a lidarr issue, it's a musicbrainz issue (the underlying data source). You can edit it yourself if you want.

https://beta.musicbrainz.org/artist/2386cd66-e923-4e8e-bf14-2eebe2e9b973

**Comment by Ackis** [comment]
Ah okay - my apologies. I thought since it was a duplicate album name, something might be going on.
