### ISSUE TITLE
redownloading /mediacover/albums files during artist refresh

### ISSUE THREAD

**Issue by hfunder** [lidarr/Lidarr#850]
when the task "refresh artist" runs once a day lidarr seems to redownload random files each day in the directory /mediacover/albums using the mediacoverservice

on a limited internet connection this takes up all bandwidth daily for 1-2 hours.

I have attached debug log files from when the "refresh artist" task runs to the end of this task - at this point the mediacoverservice is still downloading files.
[logs.zip](https://github.com/lidarr/Lidarr/files/3364292/logs.zip)

**Comment by thoppa** [comment]
I noticed this too.  My backup logs are filled with re-downloaded album art.

**Comment by Qstick** [comment]
I'll look at this, caa may have different headers and thus our existing checks are not working correctly and we redownload on every refresh... Or it could just be new art
