### ISSUE TITLE
Trigger `On Release Import` connection event on Manual Import

### ISSUE THREAD

**Issue by TChilderhose** [lidarr/Lidarr#853]
**Is your feature request related to a problem? Please describe.**
I have a `Connection - Custom Script` that I trigger on `On Release Import`, but `Manual Import` doesn't seem to trigger it.

**Describe the solution you'd like**
I would like `Manual Import` to trigger the `On Release Import` connection event

**Describe alternatives you've considered**
I might be misunderstanding when the `On Release Import` event should be triggered, if there is a better event to use for downloaded and manual import of an album please let me know.

Thanks!

**Comment by ta264** [comment]
Have you confirmed your script is triggered on automatic import? It should be triggered on manual too.

**Comment by TChilderhose** [comment]
It does run on automatic import. I have it spitting out some logs so I can see it. And sorry, I also forgot to mention that I have a pushover connection set up as well for  Release Import and it does trigger on automatic and it doesn't trigger on manual.

**Comment by ta264** [comment]
What version of lidarr?

**Comment by ta264** [comment]
Just double checked the code and it only runs the notification if it's a new file. If you've pressed manual import from the artist age it won't fire, it will from the queue or wanted pages.

**Comment by TChilderhose** [comment]
I'm using linuxserver/lidarr:latest

Version:  0.6.2.883
Mono Version: 5.20.1.19
Docker: True
DB Migration: 29

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)

**Comment by TChilderhose** [comment]
Interesting. Im pretty sure I was going through wanted/manual import as that's what I'm use to in sonarr. I'll see if I can try another one.

**Comment by ta264** [comment]
It's actually a little more subtle, I had forgotten that I'd changed it so that if you have replace existing files selected it counts a a new download and should fire the event. If you have combine with existing then I think it won't.

**Comment by TChilderhose** [comment]
Ah that fixed it. Switched to 'Replace Existing Files' in the dropdown and it triggered. Thanks!
