### ISSUE TITLE
/Content/Fonts/fonts.css does not use the 'URL Base' value if set

### ISSUE THREAD

**Issue by x-radeon** [lidarr/Lidarr#854]
**Describe the bug**
/Content/Fonts/fonts.css does not use the 'URL Base' value if set

**To Reproduce**
1. Set the "URL Base" value, e.g. 'lidarr'
2. Restart lidarr
3. Open F12 dev tools and refresh the page
4. See request to /Content/Fonts/fonts.css instead of /lidarr/Content/Fonts/fonts.css

**Expected behavior**
fonts.css should be loaded from "URL Base" + /Content/Fonts, e.g. /lidarr/Content/Fonts/fonts.css

**Screenshots**
n/a

**Logs**
n/a

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System Docker/Unraid
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.19

**Additional context**
n/a

**Comment by ta264** [comment]
Looks like I have this issue too

**Comment by Qstick** [comment]
I think this was fixed on Sonarr side, may just be a cherry pick

**Comment by ta264** [comment]
See https://github.com/Sonarr/Sonarr/commit/2b4519a4ad08eecf02b75d778588e389744afcfc
