### ISSUE TITLE
Rename "Root Folder" to "Library Folder"

### ISSUE THREAD

**Issue by tommyalatalo** [lidarr/Lidarr#856]
# What problem are you looking to solve?
The naming of folders in Lidarr is confusing, the name "Root Folder" doesn't explain what folder is referred to. Is it the download clients' root folder? The system root folder? Or the library root folder? Of course this is stated on the "Import" page, that it is in fact what everyone else calls the "Library Folder" which is intended.

Pretty much all other media solutions such as Plex, Kodi, Emby etc use the term "library" since it clearly explains what's intended. Lidarr should do the same for consistency and to minimize confusion on this topic (confusing download folder with "root folder") which is commonly seen in the support chat on Discord.

Add to this the fact that the Lidarr UI actually refers to "the library" in other circumstances, such as when adding an existing artist to Lidarr, the user gets the response "Already in your library".

# What is the proposed solution?
Rename "Root Folder" to "Library Folder". This is a small thing, but it will make is easier for new users to understand what Lidarr is expecting as input, will be consistent with other media software, and makes the UI terminology more internally consistent.

**Comment by Qstick** [comment]
Likely not going to happen, given its recognized as Root Folder by most users already as well as anyone familiar with the arr programs
