### ISSUE TITLE
Trying to search for a certain artist fails and crashes the search job

### ISSUE THREAD

**Issue by nonamethanks** [lidarr/Lidarr#858]
**Describe the bug**
Trying to search for the artist Батюшка (https://musicbrainz.org/artist/26822e77-5be2-47c7-9a95-6dd389d7b83c) makes the worker crash. Lidarr also cannot find the artist in the Musicbrainz library. Subsequently, the Lidarr worker fails to fetch any other artist search after it fails with that artist. This problem does not manifest if I restart Lidarr and don't search for that artist.

**To Reproduce**
1. Search for "Батюшка" in the search bar.
2. Check the logs.

**Expected behavior**
Lidarr should find and add the artist.

**Logs**
https://pastebin.com/raw/Y0XGRXqc

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883 (latest at the time of the opening of this issue)
 - Operating System: Debian Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: mono 5.20.1.19

**Additional context**
I should add that despite the fact that cloudflare errors appear in the log, I am perfectly capable to search for other artists. It's just that specific artist that lidarr doesn't seem to be able to process.

This problem happens with the UUID search too.

Seems related to issue #266 because I get the same error messages in the webpages.

**Comment by ta264** [comment]
The API was down for maintenaince (hence the cloudflare errors).  All working now.
