### ISSUE TITLE
Issue starting Lidarr.exe on Ubuntu 16.04 with mono 4.2.3

### ISSUE THREAD

**Issue by kormic911** [lidarr/Lidarr#86]
> [Fatal] ConsoleApp: EPIC FAIL!
> 
> [v10.0.0.6776] System.MissingMethodException: Method 'Array.Empty' not found.
>   at NzbDrone.Common.Disk.DiskProviderBase.EnsureFolder (System.String path) <0x417ff610 + 0x00017> in <filename unknown>:0
>   at NzbDrone.Common.EnvironmentInfo.AppFolderFactory.Register () <0x417ff5c0 + 0x0003d> in <filename unknown>:0
>   at NzbDrone.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, IUserAlert userAlert, System.Action`1 startCallback) <0x417c8e70 + 0x00137> in <filename unknown>:0
>   at NzbDrone.Console.ConsoleApp.Main (System.String[] args) <0x4177c470 + 0x00083> in <filename unknown>:0

Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

Also looks like 4.2.4 doesn't work either but is resolved with 4.4

**Comment by danielunderwood** [comment]
May be related to https://bugzilla.xamarin.com/show_bug.cgi?id=36942, where a 4.6+ build environment uses `Array.Empty` that 4.2 doesn't have.

**Comment by danielunderwood** [comment]
Due to the transition to 4.6.1 and appearing in 3cb463e4.

**Comment by Qstick** [comment]
Min mono version raised to 4.6 in c8ed468 due to this and other issues
