### ISSUE TITLE
Error refreshing artist

### ISSUE THREAD

**Issue by jscottdouglas** [lidarr/Lidarr#87]
> Error occurred while executing task RefreshArtist: constraint failed
> UNIQUE constraint failed: Albums.ForeignAlbumId

> System.Data.SQLite.SQLiteException (0x80004005): constraint failed
> UNIQUE constraint failed: Albums.ForeignAlbumId
>   at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0016b] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.ExecuteScalar (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.ExecuteScalar () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at Marr.Data.QGen.InsertQueryBuilder`1[T].Execute () [0x00046] in C:\projects\lidarr\src\Marr.Data\QGen\InsertQueryBuilder.cs:140 
>   at Marr.Data.DataMapper.Insert[T] (T entity) [0x0005d] in C:\projects\lidarr\src\Marr.Data\DataMapper.cs:728 
>   at NzbDrone.Core.Datastore.BasicRepository`1[TModel].InsertMany (System.Collections.Generic.IList`1[T] models) [0x0002d] in C:\projects\lidarr\src\NzbDrone.Core\Datastore\BasicRepository.cs:145 
>   at NzbDrone.Core.Music.AlbumService.InsertMany (System.Collections.Generic.List`1[T] albums) [0x00000] in C:\projects\lidarr\src\NzbDrone.Core\Music\AlbumService.cs:139 
>   at NzbDrone.Core.Music.RefreshAlbumService.RefreshAlbumInfo (NzbDrone.Core.Music.Artist artist, System.Collections.Generic.IEnumerable`1[T] remoteAlbums) [0x00251] in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshAlbumService.cs:108 
>   at NzbDrone.Core.Music.RefreshArtistService.RefreshArtistInfo (NzbDrone.Core.Music.Artist artist) [0x0019e] in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:100 
>   at NzbDrone.Core.Music.RefreshArtistService.Execute (NzbDrone.Core.Music.Commands.RefreshArtistCommand message) [0x00043] in C:\projects\lidarr\src\NzbDrone.Core\Music\RefreshArtistService.cs:148 
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000f6] in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:91 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
>   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <f25192448d514c6cbd6f6f1a76ee036e>:0 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\projects\lidarr\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

Deleted an artist without deleting folder, then went to re add it got this error when it tried to download album info

**Comment by Qstick** [comment]
Should be fixed with 5b641c2 on metadata
