### ISSUE TITLE
fpcalc during manual import

### ISSUE THREAD

**Issue by Joleun** [lidarr/Lidarr#873]
**Is your feature request related to a problem? Please describe.**
I understand that fpcalc runs during a manual import to identify tracks.  However, what is extremely frustrating is that runiing under Windows it opens a window presumably for each track.  As a manual import works at the artist rather than album level, I would also take it that every track by the artist is scanned even when trying to add only one album.  In many cases, this means that hundreds of tracks have to be scanned, and consequently the same number of windows open in succession.  This pretty much makes it impossible to use the computer for anything else while the files are being scanned. 

**Describe the solution you'd like**
For the process to be kept in the background, or at least for the windows to be kept minimised.

**Describe alternatives you've considered**
I've tried looking for a way I can force the windows to run minimised, but couldn't find a solution.  If there is one that I can apply myself that would be great.

**Comment by Qstick** [comment]
This is already fixed in nightly, will be in next release
