### ISSUE TITLE
When download completes, only the first track is moved to the correct directory

### ISSUE THREAD

**Issue by smidley** [lidarr/Lidarr#89]
When download completes, only the first track is moved to the correct directory.  There is also no update in the webui that says that track is now visible to lidarr.

**Comment by danielunderwood** [comment]
Are the files uniformly named? Do they show as tracks for the album? Any errors in the log?

**Comment by smidley** [comment]
The files are named like this: "01 - track title.flac"

I don't see any errors in the log.

**Comment by Qstick** [comment]
What do the tags look like?

**Comment by smidley** [comment]
What tags?

**Comment by danielunderwood** [comment]
The metadata tags of the audio file. You could probably grab them with mp3tag on windows or the flac/flactag utility on linux.

**Comment by Qstick** [comment]
We need more info on this on (id3 tags on files, logs).
