### ISSUE TITLE
Memory usage jumps after ~24h

### ISSUE THREAD

**Issue by tehniemer** [lidarr/Lidarr#904]
**Describe the bug**
Lidarr is holding onto a large amount of memory after about 24 hours. It seems to coincide with some event that happens as seen by a spike in CPU usage. The CPU usage is temporary, but the memory use never drops down to pre-event levels until lidarr is restarted.

**To Reproduce**
1. Start Lidarr
2. Wait
3. See error

**Expected behavior**
The memory should be released back to the system when it is no longer needed.

**Screenshots**
![Image 1565351676](https://user-images.githubusercontent.com/11021632/62787764-05adaf80-ba8b-11e9-9b7c-36745bc2b498.png)

![Image 1565351710](https://user-images.githubusercontent.com/11021632/62787780-0e05ea80-ba8b-11e9-9ce4-01d4ffdf573b.png)

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Lidarr Version: 0.6.2.883
 - Operating System: Docker

**Comment by ta264** [comment]
What's the underlying OS? Which docker imag are you using?

**Comment by tehniemer** [comment]
It's running on Debian 9 and the Linuxserver latest image.

**Comment by Wesselinator** [comment]
Boosting this.
Brought my server to it's knees (not a lot of free RAM).

**Version:** 0.6.2.883
**Mono Version:** 6.0.0.313
**OS:** Docker on QTS 4.3
**Flavor:** Latest linuxserver.io

**Comment by ta264** [comment]
@tehniemer can you try manually running the refresh artist task in system / tasks and see if that triggers the increased memory usage?

**Comment by tehniemer** [comment]
@ta264 Yes, that triggered the increased memory usage.

**Comment by ta264** [comment]
Ok, first step to a fix is being able to replicate... Please could you check if the same thing happens on nightly? Note that you can't switch back from nightly to stable so you might want to backup your database first.

**Comment by tehniemer** [comment]
It does seem to happen on the nightly also, but not nearly as severe, 750Mb vs 2Gb on stable. Normal "idle" usage is about 250Mb. Another odd thing is that whenever Lidarr does its scan the PLEX container CPU use jumps up at the same time and for the same duration. 
![Image 1565577159](https://user-images.githubusercontent.com/11021632/62843465-9a78fe80-bc7f-11e9-89f5-16d584c89145.png)

**Comment by tehniemer** [comment]
It jumped again from 750Mb to 1.2Gb after another artist refresh.

**Comment by ta264** [comment]
Good to know.  How big is your library? How many artists and how many files?

**Comment by tehniemer** [comment]
361 artists, 19155 tracks
