### ISSUE TITLE
Issue: Auto Wanting All Albums

### ISSUE THREAD

**Issue by mccorkled** [lidarr/Lidarr#92]
I am not sure if this is an issue or a feature but...

MusicBrainz lists wayyy too many albums for artists when adding them rather than just the main releases. When I searched Neil Young there were 7038 albums and Led Zeppelin is showing 1167. Even less known bands such as In Flames are showing over 500.

**Comment by danielunderwood** [comment]
Lidarr isn't showing that many albums, it is? I believe you're referring to releases and we're using release groups (with a default release) for albums.

**Comment by mccorkled** [comment]
You are correct. I didn't mean to use "albums" to describe this. Even still, using the release groups it pulling over 300 albums for Neil Young, and this is the case with many other artists.

![1](https://user-images.githubusercontent.com/13697804/31197398-f82a552c-a91e-11e7-9038-d60361507c07.png)

**Comment by danielunderwood** [comment]
Ahh we are indeed working on filtering based on the primary/secondary types from musicbrainz. There's still work do be done, but I believe it should be able to exclude things such as live albums.

**Comment by mccorkled** [comment]
Ok, no problem. Just trying to help. :) I never know where you guys are at.

**Comment by Qstick** [comment]
All backend work for this is now in place, currently defaults to studio albums only. Just UI remains
