### ISSUE TITLE
Artist/Album/Track CleanName still contain non-clean characters in filenames...

### ISSUE THREAD

**Issue by RandomNinjaAtk** [lidarr/Lidarr#942]
**Describe the bug**
Artists such as A$AP Rocky still have the $ in the file/folder names

**To Reproduce**
1. Set filename/album/artist to use Clean Names
2. Add A$AP Rocky artist
3. Check reported file path, still contains $

**Expected behavior**
Replace unclean character "$" with "S"

**System info (please complete the following information):**
 - Lidarr Version: Nightly
 - Operating System: Docker Linuxserver.io

**Additional context**
Trying to use scripts to process files, and cannot easily do so because the file/folder names appear to have a variable in them... This breaks bash scripting...

**Comment by ta264** [comment]
Clean is only designed to remove illegal characters, not characters that are "difficult". There's nothing wrong with a `$` in a filename so it allows it.

I think you need to add some escaping to your scripts!
