### ISSUE TITLE
0.7.0.1347 requires mono 5.16+ Latest on FreeBSD is 5.10.1.57

### ISSUE THREAD

**Issue by ChaosBlades** [lidarr/Lidarr#971]
**Describe the bug**
After a minute or so, Lidarr WebUI will crash with "Failed to load system status from API". The WebUI then 404s after this. Everything was fine until the update yesterday. Both my upgraded install and a fresh install I did crash.

**To Reproduce**
Did a fresh install via Lidarr Wiki. Everything seems to go well until it starts scanning my music. Just added/tested Indexers and downloader. Then added my root directory and started the scan. My upgraded install also crashes while scanning. I discovered if I pull my WAN cable it won't crash but as soon as it gets internet again it will crash. Probably something to do with outdated mono on FreeBSD would be my guess.

**Expected behavior**
Not fall on its face.

**Logs**
regular / debug / trace
https://mega.nz/#F!WVlA3YQY!FHjZzBtT7Pb5TWJd6NCgPQ

**System info (please complete the following information):**
 - Lidarr Version: 0.7.0.1347
 - Operating System FreeNAS-11.2-U5 (Jail: 11.2-RELEASE-p12)
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.10.1.57 (This is the latest availible for FreeNAS Jails)

**Additional context**
This version of Lidarr has a fresh warning to upgrade to mono 5.20. From what I can find this is not possible on FreeBSD currently.

**Comment by ChaosBlades** [comment]
While figuring out the below I may have discovered that the package version of mono on FreeNAS is causing the issue and removing that and installing the port version fixes the issue but that is going to have to wait until I get off work to test.

-------

Using https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238089 to upgrade mono to 5.20 on a FreeNAS 11.2 Jail isn't straightforward

FreeNAS Jails when for example you do 'pkg install mono' you are not installing from ports you are installing from pre configured packages. So in order to apply a patch to a port which the above is we need to remove the mono package and install the port version to patch it. Or at least that is how I am understanding it.

Stop all services running mono

`service lidarr stop`

`pkg remove mono`

`portsnap fetch extract`

`pkg update`

`pkg upgrade`

`nano /tmp/mono-patch-5.20.1.34`

Copy everything from https://bz-attachments.freebsd.org/attachment.cgi?id=205999 into that file, save and close

`cd /usr/ports/lang/mono`

`pkg install mono`

`patch -E < /tmp/mono-patch-5.20.1.34`

`nano Makefile`

We need to change the 'PORTVERSION=' from 5.10.1.57 to 5.20.1.34 then save and exit

If you try 'make install clean' here you get "libepoxy-1.5.2 needs Python 3.3 at least, but 2.7 was specified." When you follow that rabbit hole you find bug https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233723 so we need to compile that from scratch first. But if you try to 'make install clean' for libepoxy you get a similar error for llvm80. So we need to compile llvm80 first then libepoxy, then finally mono.

`cd /usr/ports/devel/llvm80`

I have an E5-2680V2 and the following still took a good long while to compile. Get some popcorn and watch a movie maybe.

`make -DBATCH install clean`

`cd /usr/ports/graphics/libepoxy`

`make -DBATCH install clean`

`cd /usr/ports/lang/mono`

`make -DBATCH install clean`

`make deinstall reinstall`

Restart all services running mono

`service lidarr start`

Lidarr is now working for me under mono version 5.20.1.34. This should also work for Sonarr, Radarr, and Jackett.

**Comment by ChaosBlades** [comment]
Installing the port version does not resolve the issue. Maybe I just didn't give it enough time to crash or maybe I was just logged into the wrong jail. Older versions are indeed broken but manually compiling 5.20 from source works as mentioned in the previous comment. I made a resource on the FreeNAS forums for changing over Sonarr, Radarr, Lidarr, and Jackett to 5.20 as preventative maintenance to prevent these applications from breaking once support is dropped outright for those stalking this issue.

https://www.ixsystems.com/community/resources/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.126/

**Comment by Qstick** [comment]
This should be resolved with 0.7.1.1381 that was just pushed. Can you confirm

**Comment by ChaosBlades** [comment]
Fesh jail using normal install routine and It has been scanning my music for a few minutes now. It has always crashed by this point. Also not seeing any warnings or errors in default log level. Calling this resolved with 0.7.1.1381 and closing issue.

**Comment by Qstick** [comment]
Thanks
