### ISSUE TITLE
Manual import from downloads fails due to read only source

### ISSUE THREAD

**Issue by i418c** [Lidarr/Lidarr#978]
**Describe the bug**
Trying to manually import downloaded music will fail because Lidarr wrongfully attempts to delete the source file after copying, causing the whole transaction to be rolled back.

**To Reproduce**
1. Create read only download location
2. Put something in there that Lidarr doesn't automatically import
3. Go to Queue > Activity
4. Manually import a file
5. Watch your file get copied to the library
6. Watch your file get deleted from the library

**Expected behavior**
Copy the file to the library.  Don't do anything else.
Even if subsequent actions were to fail, I don't see why Lidarr should remove a successful copy from the library.

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1381
 - Operating System FreeBSD (FreeNAS plugin)
 - Mono Version: 5.10.1.57

**Additional context**
I've seen #828 but the dropdown in the lower left only sets track information.  There is no ability to choose whether to copy or move.
![lidar_manual_import](https://user-images.githubusercontent.com/7959508/64911138-8c395a80-d6e3-11e9-9c34-c90c5dc88c08.png)

[AB#292](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/292)

**Comment by ta264** [comment]
Are you trying to manually import an nzb download that's shows in the queue but fails to download automatically?

**Comment by i418c** [comment]
Yes, but the source of the content is a torrent.

**Comment by ta264** [comment]
If the source is a torrent it should be copying anyway and not trying to move or delete old. Can you jump on the discord channel and we can try to figure it out?

**Comment by i418c** [comment]
Here's the relevant trace.
[lidarr.trace.log](https://github.com/lidarr/Lidarr/files/3613065/lidarr.trace.log)

**Comment by mazzma12** [comment]
Any idea how to trigger moving and renaming from download folder to library, once you have fixed the RO problem ?

**Comment by bakerboy448** [comment]
Is this still an issue in recent builds?

**Comment by bakerboy448** [comment]
Closing; abandoned, no other recent reports.
