### ISSUE TITLE
docker-rexray s3 mount issues

### ISSUE THREAD

**Issue by jwhostet** [lidarr/Lidarr#984]
**Describe the bug**
Using docker and rexray s3 volume plugin lidarr does not show my volume mount as an option when adding a root folder.

**To Reproduce**
1. Create Docker Volume with rexray s3 plugin as the driver: `s3testvol`
2. start lidarr container with volume mount just created: `-v s3testvol:/music`
3. Go to Settings > Media Management > add a root folder
4. /music is not an option

**Expected behavior**
The rexray plugin mounts the bucket inside of the container as a directory. If you run something like `if [[ -d /music ]]; then echo "real dir"; fi` it prints real dir meaning the shell detects it as a directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/36669652/65046240-399fae80-d92e-11e9-8be8-9abeefb71551.png)

![image](https://user-images.githubusercontent.com/36669652/65046570-e11ce100-d92e-11e9-8f96-f34292f1daac.png)

**Logs**
 -- Path does not exist ,
[Warn] LidarrErrorPipeline: Invalid request Validation failed: 

I wasn't able to find debug/trace logs even though they are enabled.

Response from rootFolder API call.
`[
  {
    "propertyName": "Path",
    "errorMessage": "Path does not exist",
    "attemptedValue": "/music/",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Path",
      "propertyValue": "/music/"
    }
  }
]`

**System info (please complete the following information):**
Version 0.7.1.1381
Mono Version 5.20.1.34
Docker True
DB Migration 35
Linuxserver.io version:- 0.7.1.1381-ls33 Build-date:- 2019-09-15T02:24:59+01:00

**Additional context**
I'm not super familiar with the code but doing a few minutes of digging I was wondering if it's not part of the `isPathValid` code that is returning back false or something that doesn't allow the directory to be added?

**Comment by ta264** [comment]
If it's mounted as a folder it should be supported, in pretty sure this will just be a configuration problem. Please use the discord channel for support.
