### ISSUE TITLE
Pseudo_Release Profile

### ISSUE THREAD

**Issue by Joleun** [lidarr/Lidarr#987]
**Describe the bug**
I'm unsure if this is a problem, or I'm misunderstanding things.  If I create a profile: Album/Studio/Soundtrack/Pseudo, and assign that to an artist, I would expect Lidarr to display onlly the matching albums for which a pseudo-release exists on Musicbrainz.  Doing so would help considerably in showing the albums as I'd want to see them.  However, when I do this I invariably get zero album results.  If I change the profile to official, then all abums are discovered, and I can add the albums I want selecting the pseudo-releases.  I've also discovered that if I then change it back to the profile for pseudo-releases only I retain only the albums I've added which suits my needs in one way, bt whether it causes any future issues I don't know.

**To Reproduce**
It's worked this way this way with a few artists now so it seems consistent.

**Expected behavior**
It might just be my misunderstanding of how it should work, but as I said above, I would expect a profile with a release status of pseudo only to find and display those releases.

*Screenshots**
I forgot to take any.  If necessary I could easily recreate it with a different artist, and provide them.  For reference the artist I was just working on was: 梶浦由記

**System info (please complete the following information):**
 - Version    0.7.1.1381
 - Operating System Windows 10 Home 64
 - .net Framework (Windows) 4.8

**Comment by Qstick** [comment]
Ex Release Group: https://beta.musicbrainz.org/release-group/c5124ab7-d153-32ba-a215-e02aa67f804b

Should be added with a psuedo only profile but is not
